### DISCUSSION TITLE
How can  attach  environment  attribute (tag) in opentelemerty .

### DISCUSSION THREAD

**Discussion by nikhil-ht** [open-telemetry/opentelemetry-collector#10124] [General]
I want to attach the env  attribute   so that I can filter the traces on the Grafana
Here is my sample opentelemetry config.yaml file  
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:5555

exporters:
  logging:
    loglevel: warn
  otlphttp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    auth:
      authenticator: basicauth/client

extensions:
  basicauth/client:
    client_auth: 
      username: ${TEMPO_USERNAME}
      password: ${TEMPO_PASSWORD}

service:
  extensions: [basicauth/client]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp, logging]
  telemetry:
    logs:
      encoding: json
```

like below 

![image](https://github.com/open-telemetry/opentelemetry-collector/assets/92708869/a3b10e52-da8e-4f8c-a6a1-77a06c064d8e)
