### DISCUSSION TITLE
OTEL-SDK-Java: Connection failed to OTEL-Collector in Docker

### DISCUSSION THREAD

**Discussion by mkarg** [open-telemetry/opentelemetry-collector#10458] [Q&A] [answered]
I am running two docker containers, interconnected via a Docker network. Container1 contains OTEL-SDK-Java-instrumented app, Container2 contains OTEL-Collector.

OTEL-SDK-Java says:  `SEVERE: Failed to export metrics. The request could not be executed. Full error message: Failed to connect to container2/192.168.80.2:4318`

Config:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    root_path: /
    scrapers:
      cpu:
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true

processors:
  batch:

exporters:
  otlphttp:
    endpoint: https://...

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp]
```

Indeed `curl` on the host tells me it can connect to port 8888 (which is shown in the log of OTEL-COLLECTOR) but not on ports 4317 nor 4318!

**What am I doing wrong? How to *actually* enable ports 4317 and 4318 in the OTEL-COLLECTOR?**
