### DISCUSSION TITLE
Use Docker Secrets for Configuration Values

### DISCUSSION THREAD

**Discussion by JaronrH** [open-telemetry/opentelemetry-collector#10706] [Q&A]
I currently use Docker Swarm with Docker Secrets to store configuration information.  I would like to load information from Secrets into my configuration.  For example:

```
receivers:
  rabbitmq:
    endpoint: http://rabbitmq_rabbitmq:15672
    username: ${file:/run/secrets/RABBITMQ_USER}
    password: ${file:/run/secrets/RABBITMQ_PASSWORD}
    collection_interval: 10s
```

Docker Secrets are exposed as files in /run/secrets.  The problem (as far as I can tell - I'm not a Go dev) is that the ${file:} processor is trying to load those secrets as yaml files instead of values!  So, I'm getting errors like this as a result:

```
Error: failed to get config: cannot resolve the configuration: yaml: did not find expected node content
2024/07/23 16:08:53 collector server run finished with error: failed to get config: cannot resolve the configuration: yaml: did not find expected node content
```

Is there a better way to do this? Maybe some way to tell opentelemetry-collector-contrib to load everything in /run/secrets into env variables so I can use ${env:*}?

Thanks!
