### DISCUSSION TITLE
How to extract container metdata from simple filelog tailing

### DISCUSSION THREAD

**Discussion by mikkelam** [open-telemetry/opentelemetry-collector#11545] [General]
```yaml
receivers:
  filelog/containers:
    include: ["/var/lib/docker/containers/*/*.log"]
```

I'm trying to extract metadata such as `container_name` from docker and enrich this as the otel resource attribute `service.name`.

However, i cannot figure out how to get this data. I am not using kubernetes, just plain docker.  It seems to me that the container operator is not useful if not running on kube (please correct me if im wrong!)

Help or referral to documentation will be really appreciated 🙏
