### DISCUSSION TITLE
0.123 Contrib Collector internal metrics publishing exemplars causing Prometheus "Error on ingesting out-of-order exemplars"

### DISCUSSION THREAD

**Discussion by swapdonkey** [open-telemetry/opentelemetry-collector#12885] [Q&A] [answered]
Hi, 
I've turned on the internal metrics and logging in the otel contrib collector as per below. 
Tracing isn't configured. 
However I'm now getting loads of "out of order exemplar" errors for the internal metrics in Prometheus. 
As I'm not interested in the exemplars can I just turn them off in the config? 

Current config
```
telemetry:
   metrics:
    readers:
       - periodic:
             interval: 10000
             exporter:
                 otlp:
                     protocol: http/protobuf
                    endpoint: .... 

    logs:
       processors:
          - batch:
                exporter:
                    otlp:
                        protocol: http:/protobuf
                        endpoint:.....  
```
