### DISCUSSION TITLE
Relation between batch_size and kafka topic partition

### DISCUSSION THREAD

**Discussion by dittakaviram** [open-telemetry/opentelemetry-collector#4144] [Q&A]
My question is on how to interpret the value of the parameter **batch_size** in https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/batchprocessor in correlation with https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/kafkaexporter. 

Below is an excerpt from my config file:

```
processors:
  batch:
    batch_size: 20

exporters:
  kafka:
    protocol_version: 2.4.0
    brokers:
      - <broker endpoint>
    topic: test_topic
    encoding: otlp_proto
    auth:
      sasl:
        username: <user>
        password: <password>
        mechanism: PLAIN
```

Assuming my **test_topic** has multiple partitions, does the above config mean that a single batch of 20 metric data points (I work on metrics) are sent to a single partition of the topic?
