### DISCUSSION TITLE
Can i use OTEL collector as a receiver for logs over HTTP

### DISCUSSION THREAD

**Discussion by kushal-ti** [open-telemetry/opentelemetry-collector#5536] [Q&A]
I'm trying to send application logs to the otel collector over HTTP, 

this is how i'm setting up by log ransport with winston 

```javascript
const logger = winston.createLogger({
  level: 'info',
  transports: [
    new winston.transports.Http({
      host: 'localhost',
      port: 4318,
      path: '/v1/logs',
      batch: true,
      batchCount: 1,
    }),
  ],
});
```

I have an otel collector running locally with the following configuration

```yaml
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://localhost:3000
            - http://localhost:3001

  # Collect own metrics
  # prometheus:
  #   config:
  #     scrape_configs:
  #       - job_name: "otel-collector"
  #         scrape_interval: 10s
  #         static_configs:
  #           - targets: ["0.0.0.0:8888"]

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "localhost:14250"
    tls:
      insecure: true
  file:
    path: /home/kushal/traces.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]

    # metrics:
    #   receivers: [otlp, prometheus]
    #   processors: [batch]
    #   exporters: [logging]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]

```
but when i run this with my application, and check the traces in jaeger, i see that wherever i'm trying to send the logs, i get an error 
![Screenshot from 2022-06-14 21-26-47](https://user-images.githubusercontent.com/88190553/173622497-c53e6bda-4cb9-46dd-b74c-6f67b89cb927.png)

My server which is trying to send the logs is running on 3001. Can any one tell me what i'm doing wrong ?
