### DISCUSSION TITLE
Is it possible to disable metrics port for the collector ?

### DISCUSSION THREAD

**Discussion by santoshkashyap** [open-telemetry/opentelemetry-collector#6547] [Q&A]
Hi,

I have following configuration for the otel collector:
## otel-config.yaml
```
extensions:
  health_check: 
    endpoint: localhost:13133

receivers:
  otlp:
    protocols:
      http: 
        endpoint: localhost:4318

processors:
  memory_limiter:
    # Maximum amount of memory, in MiB, targeted to be allocated by the process heap.
    # Typically the total memory usage of process will be about 50MiB higher
    # than this value.
    limit_mib: 100
    # maximum spike, in MiB, expected between the measurements of memory usage.
    # recommended value of 20% of the limit_mb
    spike_limit_mib: 20
    # time between measurements of memory usage for the
    # purposes of avoiding going over the limits. Defaults to zero, so no
    # checks will be performed. Values below 1 second are not recommended since
    # it can result in unnecessary CPU consumption.
    check_interval: 1s
  batch:
    send_batch_size: 10000
    timeout: 5s
   

exporters:
  otlp:
    endpoint: ${OTLP_ENDPOINT}
    headers:
      Authorization: "${OTLP_BASIC_AUTH_HEADER}"
    retry_on_failure:
      enabled: false
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
  extensions: [health_check]

```

My focus currently is on traces ONLY. But, when the collector binary is run with the above config, prometheus port (8888) is also enabled .

> 2022-11-15T12:14:19.532+0530    info    service/telemetry.go:159        Serving Prometheus metrics      {"address": ":8888", "level": "basic"}

![image](https://user-images.githubusercontent.com/16810482/201849019-302a5eda-2778-4d6e-95ab-e47934705ca4.png)

Is there a way to disable exposure of metrics port ?  The [receiver config documentation](https://opentelemetry.io/docs/collector/configuration/#receivers) doesn't have much information. Thanks in advance!

**Best,**
Santosh

**Comment by chennin** [comment]
Set the metrics level to none. You should then see the log line "Skipping telemetry setup." after restart.

```
service:
  telemetry:
    metrics:
      level: none
```

Reference: https://github.com/open-telemetry/opentelemetry-collector/blob/f2a0133bf677b9fe2e18b7c02eb1b6bf5e849999/service/telemetry.go#L83-85
