### DISCUSSION TITLE
To change a port

### DISCUSSION THREAD

**Discussion by Donadominic** [open-telemetry/opentelemetry-collector#6941] [Q&A]
I installed opentelemetry collector otelcol_0.69.0_linux_amd64.rpm on centos7 .
But I am not able to start it because "Asynchronous error received, terminating process {"error": "listen tcp :8888: bind: address already in use"}
I want to change the port number. How can I do that?
I am new to this.
Anyone please provide the steps to edit the rpm package and please specify which file specifies the port 8888.

**Comment by jpkrohling** [comment]
You can find more information here: https://opentelemetry.io/docs/collector/configuration/#service

You'll need to override the metrics default endpoint in the service configuration, like this:

```
service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
```

**Comment by ddibiasi** [comment]
The answer from @jpkrohling is outdated as of 2025.  According to the [documentation](https://opentelemetry.io/docs/collector/internal-telemetry/#configure-internal-metrics), the currently correct config would be:
```yaml
  service:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
```
