### DISCUSSION TITLE
how to enable otelcol metrics receiver feature

### DISCUSSION THREAD

**Discussion by sixwaaaay** [open-telemetry/opentelemetry-collector#7364] [Q&A]
config.yaml
```yaml
receivers:
  otlp:
    protocols:
      grpc:
```
log when started:
```
2023-03-14T14:49:20.518+0800    info    otlpreceiver@v0.73.0/otlp.go:94 Starting GRPC server    {"kind": "receiver", "name": "otlp", "data_type": "traces", "endpoint": "0.0.0.0:4317"}
```

how to make it support metrics data_type
