### DISCUSSION TITLE
How to enable mTLS between Application and Otel Collector receiver?

### DISCUSSION THREAD

**Discussion by amitgoyal02** [open-telemetry/opentelemetry-collector#7564] [Q&A]
I am trying to enable the mTLS between Spring boot Application and Otel Collector, one way SSL is working fine but when I am setting client_ca_file I am started seeing a bad_certificate error.
Here is what I have done so far.
- I have created a Self-signed cert using Keytool command and extracted the private key and public cert.
- added the key and cert in Otel collector receive section to enable the SSL

 ```
receivers:
   otlp:
     protocols:
       grpc:
         tls:
           cert_file: /etc/client-cert.pem
           key_file: /etc/client-key.pem
           client_ca_file: /etc/client-cert-app.pem
       http:
         tls:
           cert_file: /etc/client-cert.pem
           key_file: /etc/client-key.pem
           client_ca_file: /etc/client-cert-app.pem
```

- I exported the Otel cert and imported it into my application's truststore file.
- I created another keystore to enable the SSL for my application. 
- I exported the Application cert and added the cert in Otel collector under receivers > otlp > protocols > grpc > tls > client_ca_file. 
- I started both Application and Otel Collector
But I am getting a bad_certificate error. I am not sure if I need to set anything else here.
