### DISCUSSION TITLE
[processor/memorylimiter] limit_percentage question

### DISCUSSION THREAD

**Discussion by ajsaclayan** [open-telemetry/opentelemetry-collector#7958] [Q&A]
Hi OpenTelemetry community,

I have a question with the `memory_limiter` processor in regards to how it relates to container/pod resources. My team has a collector configured and deployed in k8s. 

Say I have the following resources configured for a collector container:
```
resources:
      limits:
        memory: 1Gi
        cpu: 500m
      requests:
        memory: 500Mi
        cpu: 100m
```
and the following `memory_limiter` configured:
```
memory_limiter:
  check_interval: 2s
  limit_percentage: 90
  spike_limit_percentage: 20
```

The doc states `limit_percentage` is based on the following:
> Maximum amount of total memory targeted to be allocated by the process heap.

How does this pertain to the requests/limits defined in this simple example?
