### DISCUSSION TITLE
Relationship between hpa scaling and memorylimiter

### DISCUSSION THREAD

**Discussion by ajsaclayan** [open-telemetry/opentelemetry-collector#7959] [Q&A]
Hi OpenTelemetry community,

Does anyone have experience with collector configuration as it relates to scaling? 

For example, I have a collector configured with the following scaling rules. For simplicity sake we can say the collector is the only container running in the pod.
```
targetCPUUtilizationPercentage: 70
targetMemoryUtilizationPercentage: 70
```
with the following resources defined:
```
resources:
  limits:
    memory: 1Gi
    cpu: 500m
  requests:
    memory: 500Mi
    cpu: 200m
```
with the following memory limiter configured:
```
memory_limiter:
      check_interval: 2s
      limit_percentage: 90
      spike_limit_percentage: 20
```
I believe it makes sense to have scaling kick in before the memory limiter hits its soft limit. In other words, the collector should not refuse data due to memory constraints until it has appropriately scaled to handle the traffic. Because the soft limit here is 70% (`limit_percentage - spike_limit_percentage`), and the target memory utilization percentage is also 70%, should we rethink this to be less than 70%?

My question somewhat relates to https://github.com/open-telemetry/opentelemetry-collector/discussions/7958 but wanted to open a separate discussion because the advice is less concrete.
