### DISCUSSION TITLE
Do we need a batch processor for the usecase where exporter is only prometheus

### DISCUSSION THREAD

**Discussion by rohitprg** [open-telemetry/opentelemetry-collector#7963] [Q&A]
I want to know if a batch processor is required for the usecase where exporter is only prometheus and receiver is otlp. I am not sure if batch processor has any advantage if the pipeline only has pull based(promethues) exporter. Any help appreciated.
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
```
