### DISCUSSION TITLE
Environment variable

### DISCUSSION THREAD

**Discussion by couragecowardlydog** [open-telemetry/opentelemetry-collector#8081] [General]
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  jaeger:
    endpoint: jaeger-service:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ jaeger ]     
```

What are the equivalent environment variable for this config 
https://opentelemetry.io/docs/specs/otel/configuration/sdk-environment-variables/#otlp-exporter

I couldn't find any env except OTEL_EXPORTER_JAEGER_ENDPOINT
