### DISCUSSION TITLE
How do I get the routing to work

### DISCUSSION THREAD

**Discussion by trajano** [open-telemetry/opentelemetry-collector#8801] [Q&A] [answered]
I'm trying to route some spans so they won't get to the OTLP endpoint
```
processors:
  routing/drop_actuator:
    # attribute_source: resource
    from_attribute: http.route
    default_exporters:
      - otlp
    table:
      - value: /actuator/health
        exporters: [debug]
      - value: /actuator/prometheus
        exporters: [debug]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [routing/drop_actuator]
      exporters: [otlp,spanmetrics,debug]
```

But it does not appear to work and the spans still appear on jaeger also the debug dump of the trace does not appear

**Comment by trajano** [comment, marked as answer]
Ok took a bit of research but here's my otel-config.yaml which drops the healthchecks

```
exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
  filter/drop_actuator:
    traces:
      span:
        - attributes["http.route"] == "/actuator/prometheus"
        - attributes["http.route"] == "/actuator/health"
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/drop_actuator,batch]
      exporters: [otlp]
```
