### DISCUSSION TITLE
How to change logging of the opentelemetry-collector pod?

### DISCUSSION THREAD

**Discussion by dmitry-mightydevops** [open-telemetry/opentelemetry-collector#8845] [General]
![image](https://github.com/open-telemetry/opentelemetry-collector/assets/70822710/a3ec8aae-9051-47ef-b29e-f09f60eeaa0b)

I'd like to change "info" to "warn".

my config:

```yaml
opentelemetry-collector:
  enabled: false
  mode: statefulset
  presets:
    logsCollection:
      enabled: false
    hostMetrics:
      enabled: false
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: true
      extractAllPodAnnotations: true
    kubeletMetrics:
      enabled: false
    kubernetesEvents:
      enabled: false
    clusterMetrics:
      enabled: false
  config:
    exporters:
      otlp:
        endpoint: tempo.opentelemetry.svc:4317
        tls:
          insecure: true
      logging: {}
    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check: {}
      memory_ballast: {}
    processors:
      batch: {}
      # If set to null, will be overridden with values based on k8s resource limits
      memory_limiter: null
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
    service:
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888
      extensions:
        - health_check
        - memory_ballast
      pipelines:
        logs:
          exporters:
            - logging
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
        metrics:
          exporters:
            - logging
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces:
          exporters:
            - logging
            - otlp
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp

```
