### DISCUSSION TITLE
Update opentelemetry-collector from 0.84.0 up to 0.90.0

### DISCUSSION THREAD

**Discussion by FaraSys** [open-telemetry/opentelemetry-collector#9036] [Q&A]
Hi everyone!
After update opentelemetry-collector from 0.84.0 up to 0.90.0 metrics stopped coming.
I try version 0.85.0 the same situation.
Up to version 0.84 everything works.
My env:
K8s 1.27.5
Ubuntu 22.04 LTS
My deployment:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      telemetry:
        metrics:
          level: none
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: prometheus-metrics # Default endpoint for querying metrics.
    port: 8889
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
        image: otel/opentelemetry-collector:0.84.0
        name: otel-collector
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 4317  # Default endpoint for OpenTelemetry receiver.
        - containerPort: 8889  # Default endpoint for querying metrics.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf

      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
```
Help pls. Thanks
