### DISCUSSION TITLE
Getting an error in open telemetry collector as 415 unsupported media type

### DISCUSSION THREAD

**Discussion by iliyas86** [open-telemetry/opentelemetry-collector#9269] [Q&A]
I am trying to query oen telemetry collector through below mentiorn API, but getting an error as

Request: Request: http://127.0.0.1:4318/v1/metrics

Browser: 
405 method not allowed, supported: [POST]

Prometheus:
Even tried to connect to Prometheus, but the connection is getting refused.

Postman:
          "415 unsupported media type, supported: [application/json, application/x-protobuf]"
          In case, if I pass Content-Type "application/json", getting some junk data:

              {
                           "code": 3,
                            "message":"ReadObjectCB: expect { or n, but found 
               }

Setup Info:
Using Docker desktop where All pods are hosted and running.

**Configuration:**

_**docker compose:**_

otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"  # Expose OTLP HTTP endpoint
    networks:
      - HACK
  prometheus:
    image: quay.io/prometheus/prometheus:v2.42.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - HACK
    depends_on:
      - otel-collector

**_prometheus.yml_**

global:
  scrape_interval: 100s
  scrape_timeout: 90s
scrape_configs:
  - job_name: 'otel-collector'
    metrics_path: /metrics
    static_configs:
    - targets:
        - '172.27.83.69:4318'

**_otel-collector-config.yaml_**

receivers:
  otlp:
    protocols:
     grpc:
        endpoint: "localhost:4319"
      http:
        endpoint: "localhost:4317"

exporters:
  prometheus:
    endpoint: "localhost:4318"
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

**Comment by lextas** [comment]
According to the [readme](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/README.md#server-configuration) you should be able to configure CORS origins on the `receiver` configuration (in your `tempo.yaml`). You should also be able to use a wildcard `- "*"` but that doesn't work for me. Make sure you remove and restart your containers to ensure the new configuration is loaded.

```
receivers:
  otlp:
    protocols:
      http:
        include_metadata: true
        auth:
          authenticator: some-authenticator-extension
        cors:
          allowed_origins:
            - https://foo.bar.com
            - https://*.test.com
          allowed_headers:
            - Example-Header
          max_age: 7200
        endpoint: 0.0.0.0:55690
```
