### DISCUSSION TITLE
How to override config with env var on Windows?

### DISCUSSION THREAD

**Discussion by cocowalla** [open-telemetry/opentelemetry-collector#9373] [Q&A] [answered]
I'm trying to setup the otel collector as a Windows Service. As part of that, I want to load part of the config using an `OTEL_AUTH` environment variable:

```yaml
exporters:
  logging:
    verbosity: detailed
  otlp/openobserve:
      endpoint: apm.example.com:5081
      headers:
        Authorization: Basic ${env:OTEL_AUTH}
```

I tried putting this in a `.env` file alongside the otel exe, but it doesn't seem to use this file. I also don't want to set this as a system-wide env var, since it contains credentials.

How can I get the otel collector to read this env var from another file? Or can I somehow pass it on the command line?
