### DISCUSSION TITLE
receiver config

### DISCUSSION THREAD

**Discussion by Samyu09** [open-telemetry/opentelemetry-collector#9737] [Q&A]
i have my receiver config and service pipeline defined this way. code is below
So my question is if i have to push my metrics to open telemetry, do i have to push directly to an  endpoint of it?? or to the port **8888**???
once pushed ,metrics where can i view the metrics if my exporter is not configured yet??? can we view it at the endpoint???

**for suppose if my endpoint is https://otmcollector.abc.def.net/
should i use some post request and send metrics??
or  use endpoint/metrics to post the data????**

```
 receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
    prometheus: # To scrape the Collector
      config:
        scrape_configs:
          - job_name: "otelcol"
            scrape_interval: 10s
            static_configs:
              - targets: ["0.0.0.0:8888"]
            metric_relabel_configs: # Labels to ignore
              - source_labels: [__name__]
                regex: ".*grpc_io.*"
                action: drop

  service:
    extensions: [health_check, zpages]
    telemetry:
      # logs:
      #   level: "debug"
      metrics:
        level: detailed
        address: 0.0.0.0:8888
```
