### ISSUE TITLE
received message after decompression larger than max (4331797 vs. 4194304)

### ISSUE THREAD

**Issue by zhulei-pacvue** [open-telemetry/opentelemetry-collector#10025]
### Describe the issue you're reporting

**During the operation of otelcol, errors are often reported, and the specific error content is as follows:**
2024-04-22T07:17:12.488Z	error	exporterhelper/queue_sender.go:101	Exporting failed. Dropping data.	{"kind": "exporter", "data_type": "traces", "nameermanent error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4430579 vs. 4194304)", "dropped_items": 441}
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.97.0/exporterhelper/queue_s

**Otelcol version：** 0.97.0

**CPU usage and memory usage：**
![memory](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/151591728/c78dfd72-77a6-4d69-ba75-9f71617db1c4)
![cpu](https://github.com/open-telemetry/opentelemetry-collector-contrib/assets/151591728/5dd5145e-2112-4cff-96d6-1bb4e37eacb3)

**Main configurations：**

    connectors:
      spanmetrics:
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.route
        exemplars:
          enabled: false
        events:
          enabled: false
          dimensions:
            - name: exception.type
            - name: exception.message
    exporters:
      otlp:
        endpoint: 'jaeger-collector:4317'
        tls:
          insecure: true 
        compression: "gzip"
        timeout: 1s
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 10000
      prometheus:
        endpoint: ${env:MY_POD_IP}:8889
        namespace:
        send_timestamps: false
        metric_expiration: 10m
        add_metric_suffixes: false   
    extensions:
      zpages:
        endpoint: ${env:MY_POD_IP}:55679
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      pprof:
        endpoint: ${env:MY_POD_IP}:1777
    processors:
      batch:
        timeout: 1s
        send_batch_size : 100
      filter/ottl:
        error_mode: ignore
        metrics:
          metric:
          - name == "rpc.server.duration"
          - name == "duration"

**Meanwhile, how to modify the limitations of GRPC ` s 4M**

**Comment by timur-ND** [comment]
I also faced the same error, can't configure "exporter" configuration, since **max_recv_msg_size_mib** is only applicable in the "receiver" configuration block:

`2024-09-18T07:33:08.073Z	error	exporterhelper/queue_sender.go:92	Exporting failed. Dropping data.	{"kind": "exporter", "data_type": "traces", "name": "otlp/jaeger", "error": "not retryable error: Permanent error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4194305 vs. 4194304)", "dropped_items": 70}`

Configuration:

```
receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 100
      http:
        endpoint: 0.0.0.0:4318
  otlp/secure:
    protocols:
      http:
        endpoint: 0.0.0.0:4344
        tls:
          ...
      grpc:
        endpoint: 0.0.0.0:4343
        tls:
          ...
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"
processors:
  batch:
connectors:
  spanmetrics:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/jaeger:
    endpoint: "localhost:4322"
    tls:
      insecure: true
```

Adding parameter to the exporter section causes an error:
`error decoding 'exporters': error reading configuration for "otlp/jaeger": decoding failed due to the following error(s):
'' has invalid keys: max_recv_msg_size_mib`

Otel collector version - otel/opentelemetry-collector-contrib:0.108.0

**Comment by surajEE** [comment]
I am also facing same issue. Can someone please update here?

**Comment by bulmust** [comment]
In addition to increse `max_recv_msg_size_mib` in collector's config, you should increase `grpc_server_max_recv_msg_size`, `grpc_server_max_send_msg_size` for the Grafana Tempo endpoint, [REF](https://grafana.com/docs/tempo/latest/troubleshooting/response-too-large/).

**Comment by hiepqdinh** [comment]
+1 on this one, is there any fix coming soon. Or any workaround in the meantime? Our exporter is sending to oltp/jaeger, would switching to use different protocol (from grpc) help?

**Comment by ErezWeiss** [comment]
+1

**Comment by timur-ND** [comment]
For my case, I fixed this error by increasing these variables on `jaeger-collector` side:
```
COLLECTOR_OTLP_GRPC_MAX_MESSAGE_SIZE=10485760
COLLECTOR_GRPC_SERVER_MAX_MESSAGE_SIZE=10485760
KAFKA_PRODUCER_MAX_MESSAGE_BYTES=10485760
```
and on kafka side:
```
KAFKA_PRODUCER_MAX_MESSAGE_BYTES=10485760
```
Also reduced batch size:
```
processors:
  batch:
    send_batch_size: 1000
    send_batch_max_size: 4000
    timeout: 200ms
```

I am using this scheme:
`opentelemetry-collector` -> `jaeger-collector` -> `Kafka` -> `Elasticsearch`

Versions:
otel/opentelemetry-collector-contrib:0.132.0
jaegertracing/jaeger-collector:1.72.0
