### ISSUE TITLE
error decoding 'receivers': unknown type: "mongodbatlas"

### ISSUE THREAD

**Issue by ashishstationcasinos** [open-telemetry/opentelemetry-collector#10034]
I did installed OpenTelemetry Collector on Centos 7 using the rpm -i otelcol_0.98.0_linux_amd64.rpm

I did Update the /etc/otelcol/config.yaml as below

```
receivers:
  mongodbatlas:
    public_key: xxxxxxx
    private_key: xxxxx

exporters:
  prometheus:
    endpoint: '0.0.0.0:9092'

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      exporters: [prometheus]
```

I did Restart the otelcol  sudo systemctl restart otelcol

When I tail otelcol I see the Below Issue      journalctl -f --unit otelcol

	  
Apr 25 11:54:01 <hostname> otelcol[1540966]: * error decoding 'receivers': unknown type: "mongodbatlas" for id: "mongodbatlas" (valid values: [zipkin nop otlp hostmetrics jaeger kafka opencensus prometheus])
Apr 25 11:54:01 <hostname> systemd[1]: otelcol.service: main process exited, code=exited, status=1/FAILURE
Apr 25 11:54:01 <hostname> systemd[1]: Unit otelcol.service entered failed state.
Apr 25 11:54:01 <hostname> systemd[1]: otelcol.service failed.
Apr 25 11:54:01 <hostname> systemd[1]: otelcol.service holdoff time over, scheduling restart.
Apr 25 11:54:01 <hostname> systemd[1]: Stopped OpenTelemetry Collector.
Apr 25 11:54:01 <hostname> systemd[1]: start request repeated too quickly for otelcol.service
Apr 25 11:54:01 <hostname> systemd[1]: Failed to start OpenTelemetry Collector.
Apr 25 11:54:01 <hostname> systemd[1]: Unit otelcol.service entered failed state.
Apr 25 11:54:01 <hostname> systemd[1]: otelcol.service failed.

**Comment by ashishstationcasinos** [comment]
Sorry My config file as Below

```
receivers:
  mongodbatlas:
    public_key: ddwcvgjw
    private_key: 6eb02978-ec7c-4d51-a5c8-1cfb4d1bdca1


processors:
  batch:


exporters:
  prometheus:
    endpoint: '0.0.0.0:9092'

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      processors: [batch]
      exporters: [prometheus]

```

**Comment by ashishstationcasinos** [comment]
The Above Config file is Updated as Below. Still got the Same Error
```
receivers:
  mongodbatlas:
    public_key: xxxxxxx
    private_key: xxxxx


processors:
  batch:


exporters:
  prometheus:
    endpoint: '0.0.0.0:9092'

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      processors: [batch]
      exporters: [prometheus]
```
