### ISSUE TITLE
ctx propagation in otlp/http vs otlp/grpc

### ISSUE THREAD

**Issue by grandwizard28** [open-telemetry/opentelemetry-collector#10093]
**Context**
I have written a custom auth extension which derives a key called consumer. I want to batch requests based on consumer by using the batch processor and use the same in a custom exporter.
Issue 1: Batch processor uses the incoming metadata keys to batch. I can set the client.Metadata in my custom auth extension but the otlp/grpc receiver overrides client.Metadata.
Issue 2: For the exporter, I tried setting client.Auth as well in my custom auth extension but the batch processor does not respect it. It creates a new context with only metadata, discarding the Auth (if set) by any authenticators.

**Describe the bug**
I have created a custom server authenticator extension. At the end I am calling the following: 
```
return client.NewContext(ctx, client.Info{
		Metadata: client.NewMetadata(map[string][]string{
		      MetadataKeyId:      {key},
	        }),
	}), nil
```
Basically, I am trying to set some information in the metadata.

Now in one of my subsequent processors, I am trying to access this key. It works fine for http requests but the key is not present for grpc requests.

**Steps to reproduce**

**What did you expect to see?**
Context should be preserved for both otlp/http and otlp/grpc

**What did you see instead?**

**What version did you use?**
v0.99.0

**What config did you use?**
```
extensions:
  customauthextension:
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        include_metadata: true
        max_recv_msg_size_mib: 16
        auth:
          authenticator: customauthextension
      http:
        cors:
          allowed_origins:
            - '*'
        endpoint: 0.0.0.0:4318
        include_metadata: true
        auth:
          authenticator: customauthextension
exporters:
  logging:
processors:
  customprocessor:
service:
  extensions:
    - customauthextension
  pipelines:
    logs:
      receivers: [otlp]
      processors: [customprocessor, batch]
      exporters: [logging]
```

*** Additional Context ***
I have been trying for a way to propagate context data from my custom authenticator to all processors and exporters for some time now. Here is a related PR regarding the same: https://github.com/open-telemetry/opentelemetry-collector/pull/10002
