### ISSUE TITLE
Trace transformer (processor)

### ISSUE THREAD

**Issue by william-tran** [open-telemetry/opentelemetry-collector#1012]
**Is your feature request related to a problem? Please describe.**
- In synchronous / RPC architectures, a single span can be used to determine the end to end duration of a transaction that spans multiple services, and trace instrumentation on the ingress service does this for you. In async / messaging architectures, you need to do some funny business to express end to end duration with a single span, e.g. propagate the start_timestamp downstream, and the end, start a new span with that timestamp, and then finish it immediately.
- Traces can get big and noisy, especially when relying on auto-instrumentation to generate spans and propagate span context. All the details might be relevant to some audiences, but not others.
- In general, given a trace, I want to pick out parts of it and transform it into something that is more meaningful and less noisy. This can make traces more useful and make them cost less in the backend. 

**Describe the solution you'd like**
Some of the dependencies for this to work are the same as the tail sampler. We need a trace ID aware load balancer. We need an ID batcher that batches spans by trace ID. Given those two things, have an config based API that can be used to specify a transformation. E.g. for measuring end to end duration:

```yaml
- match:
    service: pizza-order
    operation: confirm-order
    withDescendent:
    - service: pizza-delivery
      operation: delivery-completed
  add:
  - service: e2e
    operation: order-confirmed-to-delivery-completed
    childOf:
      service: pizza-delivery
      operation: delivery-completed
    followsFrom:
      service: pizza-order
      operation: confirm-order
    startOn: # span starts when the below span starts, vs startAfter
      service: pizza-order
      operation: confirm-order
    finishAfter: # span finishes when the below span finishes vs finishOn
      service: pizza-delivery
      operation: delivery-completed
```

**Describe alternatives you've considered**
- waiting for tracing backends to implement this functionality
- manually instrumenting the start and end services to facilitate the creation of the e2e duration span
