### ISSUE TITLE
When deploying in K8s, release the connection limit

### ISSUE THREAD

**Issue by chenzhiguo** [open-telemetry/opentelemetry-collector#10168]
**Describe the bug**
I tried to deploy the relevant components of otel in my k8s cluster using `examples/k8s/otel-config.yaml`, but I realized that the default IP for service startup is bound to its own POD. I think the configurations in these two ConfigMaps: `otel-collector-conf` and `otel-agent-conf` are as follows:
```yaml
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
```
Is it more appropriate to change it to `0.0.0.0`?
```yaml
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
```

**Steps to reproduce**
Up

**What version did you use?**
v0.100.0

**What config did you use?**
`examples/k8s/otel-config.yaml`

**Environment**
K8s v1.19.9

**Additional context**
None
