### ISSUE TITLE
Otelcol drop metrics instead label when targetAllocator with prometheusCR  enabled

### ISSUE THREAD

**Issue by VtG242** [open-telemetry/opentelemetry-collector#10198]
**Issue description**
Instance of otelcol created via crd OpenTelemetryCollector with targetAllocator:
``` 
kind: OpenTelemetryCollector
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
```
and following servicemonitor with  metricRelabelings and labeldrop action:
```
serviceMonitor:
  enabled: true
  metricRelabelings:
    - action: labeldrop
      regex: (instance)
```
**What did you expect to see?**
Specified label will be dropped.

**What did you see instead?**
All metrics dropped.

**What version did you use?**
Otelcol: 0.100.0
Otelcol-operator: 0.98.0

**Environment**
Kubernetes

**Additional context**
The same serviceMonitor definition works with prometheus-operator.
