### ISSUE TITLE
[confighttp] Make the compression level configurable

### ISSUE THREAD

**Issue by rnishtala-sumo** [open-telemetry/opentelemetry-collector#10467]
Current compression algorithms seem to support multiple compression levels. These levels determine the speed and efficiency of the compression algorithm.

Lower compression levels provide faster speed but larger file sizes. Compression levels could be 3, 5, 7 or 11. Level 3 seems to be the default across multiple compression algorithms. It could benefit a user to give them the option to save on AWS egress costs by configuring a higher compression level with a tradeoff on processing speed.

Example configuration could looks like below:

```
exporter:
  otlphttp:
    endpoint: otelcol2:55690
    auth:
      authenticator: some-authenticator-extension
    tls:
      ca_file: ca.pem
      cert_file: cert.pem
      key_file: key.pem
    headers:
      test1: "value1"
      "test 2": "value 2"
    compression
       type: zstd
       level: 7
    cookies:
      enabled: true
```

**Comment by rnishtala-sumo** [comment]
I like the idea of configuring this as a single string

```
exporter:
  otlphttp:
    endpoint: otelcol2:55690
    auth:
      authenticator: some-authenticator-extension
    tls:
      ca_file: ca.pem
      cert_file: cert.pem
      key_file: key.pem
    headers:
      test1: "value1"
      "test 2": "value 2"
    compression: zstd/7
    cookies:
      enabled: true
```

**Comment by wasim-nihal** [comment]
Hi @mx-psi /@rnishtala-sumo , is this open for contribution?

**Comment by rnishtala-sumo** [comment]
@wasim-nihal yes, please proceed if this issue is of interest to you. I can assist with the PR review.

**Comment by rnishtala-sumo** [comment]
@mx-psi if there's no one working on this, could this issue be assigned to me?

**Comment by mx-psi** [comment]
Assigned!

**Comment by rnishtala-sumo** [comment]
@dmitryax @mx-psi I've raised a PR for this issue. Would appreciate your review.

**Comment by rnishtala-sumo** [comment]
The latest approach to configuring this is as follows

```
exporter:
  otlphttp:
    endpoint: otelcol2:55690
    auth:
      authenticator: some-authenticator-extension
    tls:
      ca_file: ca.pem
      cert_file: cert.pem
      key_file: key.pem
    headers:
      test1: "value1"
      "test 2": "value 2"
    compression
       type: zstd
    compression_params:
       level: 10
    cookies:
      enabled: true
```
