### ISSUE TITLE
Logger config

### ISSUE THREAD

**Issue by ckanner** [open-telemetry/opentelemetry-collector#1048]
Otelcol use `zap` to logger something. But now, I can only config my looger by set `log-level` and `log-profile`. 

How can I config my logger custom? I want to set something like `Encoding`, `OutputPaths`, `logrotate` and so on.

**Comment by bogdandrutu** [comment]
Can you provide details how others do this? Also what are the configs you want to offer?

**Comment by jrcamp** [comment]
@bogdandrutu I think we could use Zap's config struct as-is (it has yaml and json tags)

https://github.com/uber-go/zap/blob/master/config.go#L58

This would allow the user to completely configure Zap to their liking.

**Comment by bogdandrutu** [comment]
Sounds good, it should probably be part of the "service" configuration :)

**Comment by pavankrish123** [comment]
Hello @bogdandrutu, now that we have log level configuration property exposed via "service"  configuration (#4009), is it ok if we exposed other zap configuration in similar ones.

#4009 only exposes level, but important ones are ["outputPaths"](https://github.com/uber-go/zap/blob/master/config.go#L84)  ["encoding"](https://github.com/uber-go/zap/blob/master/config.go#L91),   ["errorOutputPaths"](https://github.com/uber-go/zap/blob/master/config.go#L78). I was thinking in the lines of 

```yaml

    logs:
      level: "DEBUG"
      development: true
      encoding: "console"
      outputPaths: ["/var/log/somefile.log"]
      errorOutputPaths: ["/var/log/someOutput.log"]
``` 

Let me know WDYT? We can work on implementation - cc: @jpkrohling
