### ISSUE TITLE
Deadlock on startup when exporting is not possible

### ISSUE THREAD

**Issue by martinsson** [open-telemetry/opentelemetry-collector#10518]
**Describe the bug**
The collector starts but does nothing on any of the pipelines
All connection attempts are immediately aborted (http receiver)

From what I gather, this happens when an exporter (otlphttp) is unable to post data. 

Perhaps this is not a bug, but I'm surprised that
- There are no logs about the failed push
- The problem affects all pipelines, even pipelines that don't have the failing exporter
- I don't find any explanation of this kind of behaviour in the trouble-shooting section

**Steps to reproduce**
Exceed metrics quota on grafana cloud,
Include otlphttp exporter in one pipeline
try to connect to post a log or connect to the http port `telnet localhost 4317`. 

The connection is immediately closed

**What did you expect to see?**
A log about the problem

That other pipelines work properly

**What did you see instead?**
The whole app seems deadlocked

**What version did you use?**
v1.1.0

**What config did you use?**
approximately
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]

    traces:
      receivers: [otlp]
      processors: [ batch]
      exporters: [debug, otlp]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, logging, loki]

```
