### ISSUE TITLE
wrong status code set in tracing spans

### ISSUE THREAD

**Issue by rafaeljesus** [open-telemetry/opentelemetry-collector#10538]
**Describe the bug**

I have a `logs.exporters.otlphttp` that is not properly converting the status code being returned from the logging backend, the problem is that the logging backend (in this case logmixer-ingest) is returning 400 status code but the collector server span (in this case logingest) is setting 500 instead, this is causing my SLOs to incorrectly burn

**Steps to reproduce**

**What did you expect to see?**

I expect the server span status code attribute to correctly match what is being returned by the logging service, which in this case, the logging service returns 400 but the server span sets 500 instead

**What did you see instead?**

here we see that the http client is correctly setting 400 to the span

<img width="1610" alt="Screenshot 2024-07-04 at 14 53 16" src="https://github.com/open-telemetry/opentelemetry-collector/assets/1216425/5be19769-c203-422b-92d6-420f0124a453">

in the span above, we see that the permanent error message contains the 400

<img width="1673" alt="Screenshot 2024-07-04 at 14 48 34" src="https://github.com/open-telemetry/opentelemetry-collector/assets/1216425/15a6cfc0-fb07-4d07-8a80-90e79ab97d43">

but in the server span we see that it is 500 instead

<img width="1606" alt="Screenshot 2024-07-04 at 14 50 10" src="https://github.com/open-telemetry/opentelemetry-collector/assets/1216425/d090dc57-9217-4996-b55f-f3e70b6d0aa9">

**What version did you use?**

v0.95.0

**What config did you use?**

this is the configMap managed by https://github.com/open-telemetry/opentelemetry-operator

```yaml
apiVersion: v1
data:
  collector.yaml: |
    receivers:
      otelarrow:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            include_metadata: true
            keepalive:
              server_parameters:
                max_connection_age: 180s
                max_connection_age_grace: 240s
            max_recv_msg_size_mib: 20
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
            include_metadata: true
    exporters:
      logging:
        verbosity: detailed
      otlphttp:
        auth:
          authenticator: headers_setter
        logs_endpoint: http://logmixer-ingest:9201/v1/otlp
        retry_on_failure:
          enabled: false
        sending_queue:
          enabled: false
        timeout: 5s
    extensions:
      headers_setter:
        headers:
          - from_context: lightstep-org-id
            key: lightstep-org-id
          - from_context: lightstep-org-name
            key: lightstep-org-name
          - from_context: lightstep-project-id
            key: lightstep-project-id
          - from_context: lightstep-project-name
            key: lightstep-project-name
          - from_context: log-database-id
            key: log-database-id
      health_check:
        check_collector_pipeline:
          enabled: false
          exporter_failure_threshold: 5
          interval: 5m
        endpoint: 0.0.0.0:13133
        path: /
      lightsteptelemetry:
        lightstep:
          lightstep:
            access_token: ${LS_TOKEN}
            collector:
              address: kube-otel-stack-internal-collector:4317
              plaintext: true
          metrics:
            opentelemetry:
              access_token: ${LS_TOKEN}
              enable_otlp: true
              grpc:
                endpoint:
                  address: kube-otel-stack-internal-collector:4317
                  plaintext: true
              tags_from_request_headers:
                log_database_id: log-database-id
                org_name: lightstep-org-name
                organization_id: lightstep-org-id
                project_id: lightstep-project-id
                project_name: lightstep-project-name
      pprof: null
    service:
      extensions:
        - lightsteptelemetry
        - health_check
        - pprof
        - headers_setter
      telemetry:
        metrics:
          level: detailed
        resource:
          service.name: null
      pipelines:
        logs:
          exporters:
            - otlphttp
          processors: []
          receivers:
            - otelarrow
            - otlp
```

**Environment**

GKE

**Additional context**
