### ISSUE TITLE
Duplicate field `"level"` in json logs

### ISSUE THREAD

**Issue by jo-goro** [open-telemetry/opentelemetry-collector#10537]
**Describe the bug**

Enabling json logging with internal metrics enabled will produce a log line which contains the field `"level"` twice.

```json
{
  "level": "info",
  "ts": 1720086435.41712,
  "caller": "service@v0.104.0/telemetry.go:96",
  "msg": "Serving metrics",
  "address": "10.0.0.41:8888",
  "level": "Detailed"
}
```

**Steps to reproduce**
Enable json logging and internal metrics. Look for a log with `"msg": "Serving metrics"`. Should be among the first few lines after startup.

**What version did you use?**
Version: `v0.104.0`

**What config did you use?**
```yaml
service:
  telemetry:
    logs:
      encoding: json
      level: INFO
      disable_stacktrace: true
      sampling:
        enabled: false
    metrics:
      level: detailed
```
