### ISSUE TITLE
Error in OpenTelemetry With Istio - OcAgent trace exporter: Export() failed: UNKNOWN: sending queue is full

### ISSUE THREAD

**Issue by MikeWang0731** [open-telemetry/opentelemetry-collector#10566]
**Describe the bug**
I'm using OpenTelemetry as a tracing collector in istio, but after running OpenTelemetry Collector for a while, the logs for istio-ingressgateway and the logs for Sidecar (istio-proxy) in the Pod keep printing `OcAgent trace exporter: Export() failed: UNKNOWN: sending queue is full`. I also tried to change the `queue_size` field in the OpenTelemetry Config, but it didn't fix the problem.

**What did you expect to see?**
Normal ingressgateway logs with various information about traffic, etc.

**What did you see instead?**
<img width="996" alt="SCR-20240709-mveo" src="https://github.com/open-telemetry/opentelemetry-collector/assets/35026879/763179ce-ac65-4972-9b83-d8ef1da05353">

**What version did you use?**
Istio 1.15.7
OpenTelemetry Collector 0.91 or 0.92

**What config did you use?**
otel config
```
receivers:
  opencensus:
    max_recv_msg_size_mib: 10
    endpoint: 0.0.0.0:55678
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
processors:
  memory_limiter:
    limit_mib: 32000
    spike_limit_mib: 1000
    check_interval: 2s
exporters:
  zipkin/nontls:
    sending_queue:
      queue_size: 10000
    endpoint: <A Jaeger Backend>
  kafka:
    sending_queue:
      queue_size: 10000
      ......
  logging:
    loglevel: debug
service:
  pipelines:
    ....
```

Istio operator yaml
```
meshConfig:
    accessLogEncoding: JSON
    accessLogFile: /dev/stdout
    accessLogFormat: ...
    defaultConfig:
      holdApplicationUntilProxyStarts: true
      proxyMetadata:
        EXIT_ON_ZERO_ACTIVE_CONNECTIONS: 'true'
        ISTIO_META_DNS_AUTO_ALLOCATE: 'true'
        ISTIO_META_DNS_CAPTURE: 'true'
      tracing:
        max_path_tag_length: 256
        openCensusAgent:
          address: dns:opentelemetry-collector.istio-system.svc.cluster.local:55678
          context:
            - B3
        sampling: 100
    defaultProviders:
      tracing:
        - opencensus
    enableTracing: true
    extensionProviders:
      - name: opencensus
        opencensus:
          context:
            - B3
          port: 55678
          service: opentelemetry-collector.istio-system.svc.cluster.local
      - envoyExtAuthzGrpc:
          port: '9898'
          service: local-opa-grpc.local
        name: opa.local
  profile: default
  tag: 1.15.0
  values:
      .....
      tracer:
        zipkin:
          address: jaeger-collector-headless.jaeger-system.svc.cluster.local:9411
```

**Environment**
Ubuntu 20.04
