### ISSUE TITLE
Logging sampler configuration not working properly (?)

### ISSUE THREAD

**Issue by je-al** [open-telemetry/opentelemetry-collector#1061]
**Describe the bug**
Logging sampling configuration seems to not be applied

**What did you expect to see?**
A constant logging rate

**What did you see instead?**
Logging sampling isn't working as intended, we get approximatelly 1k loglines per second

**What version did you use?**
otel/opentelemetry-collector-contrib:0.3.0

**What config did you use?**
```
exporters:
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 1000
...

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [sapm]
      processors: [memory_limiter, batch, attributes/newenvironment, queued_retry]
      exporters: [logging, sapm]
```

**Additional context**
I'm not sure whether this is a problem with our configuration, but dropped traces from the queued_retry processor are flooding our logs.
