### ISSUE TITLE
Issue enforcing quoted values in config

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector#10659]
**Describe the bug**

When providing a configuration that uses the `env` provider, it does not preserve the quotes around the `"${env:...}"`.

This means when a complaint time RFC string is supplied, it gets converted into a `time.Time` value instead of the expected string, which then stops the config from being valid.

**Steps to reproduce**

1. Set an env var with a timestamp value
  a. `export BUILT_TS="2006-01-02T15:04:05Z07:00"`
1. Reference var in configuration.
  a. `value : "${env:BUILT_TS}"`
1. Have collector run with configuration using reference variable.

**What did you expect to see?**
Considering the provider is in quotes, it should not strip those values

**What did you see instead?**
Upon running the collector with the provider configuration, the error is show as:
```
Error: failed to get config: cannot resolve the configuration: unsupported type=time.Time for retrieved config, ensure that values are wrapped in quotes
```

**What version did you use?**
v0.105.0

**What config did you use?**

```yaml
processors:
  resource/static:
    attributes:
    - key: build.version
      action: insert
      value: "${BUILD_VERSION}"
```

**Environment**
Linux, go v1.23.4

**Additional context**
I've tried a few different combinations, but this currently works in `v0.103.0` but upgrading to `v0.105.0` surfaced this. 

I've also tried:
```yaml
\"${env:var}\" # Didn't work with error: retrieved value does not have unambiguous string representation: <nil>
"${env:var}"  # moved to calling the env provider directly, same error as reported
```

**Comment by mx-psi** [comment]
I believe #10618 would fix this, I will add a test on this specific case.

**Comment by TylerHelmuth** [comment]
@MovieStoreGuy I was not able to reproduce this on `v0.105.0` in a binary or the confmap e2e test.

```
export BUILT_TS="2006-01-02T15:04:05Z07:00"
```

```yaml
receivers:
  nop:

processors:
  resource:
    attributes:
      - key: build.version
        value: "${env:BUILT_TS}"
        action: insert

exporters:
  nop:

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers:
        - nop
      processors:
        - resource
      exporters:
        - nop
```

And in the confmap e2e tests the following tests pass:

```
{
	value:       "2006-01-02T15:04:05Z07:00",
	targetField: TargetFieldString,
	expected:    "2006-01-02T15:04:05Z07:00",
},
{
	value:       "2006-01-02T15:04:05Z07:00",
	targetField: TargetFieldInlineString,
	expected:    "inline field with 2006-01-02T15:04:05Z07:00 expansion",
},
```
