### ISSUE TITLE
Connection Refused while trying to send traces to honeycomb refinery

### ISSUE THREAD

**Issue by manojnc** [open-telemetry/opentelemetry-collector#10660]
**Describe the bug**
I configured the otlp exporter to send traces to honeycomb refinery residing in the same k8 cluster in the same namespace. However, the call is failing with connection refused error

**Steps to reproduce**
My Exporter configuration

exporters:
      otlp:
        endpoint: "honeycomb-refinery.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
          insecure_skip_verify: true
        headers:
          "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
          "x-honeycomb-dataset": "apps"
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlp]
      telemetry:
          logs:
            level: "DEBUG"
            development: true
            encoding: "json"

**What did you expect to see?**
Traces should have been submitted to the refinery app over grpc

**What did you see instead?**
{"level":"info","ts":1721273275.352986,"caller":"zapgrpc/zapgrpc.go:176","msg":"[core] [Channel #1 SubChannel #4]Subchannel Connectivity change to TRANSIENT_FAILURE, last error: connection error: desc = \"transport: Error while dialing: dial tcp X.X.X.X:4317: connect: connection refused\"","grpc_log":true}

**What version did you use?**
Main 0.105.0

**What config did you use?**
Already shared above

**Environment**
AWS EKS

**Additional context**
honeycomb service is running and port 4317 is exposed. A get service command will report 4317 is exposed and it is mapped to container port 4317. Honeycomb agent is sending the data over http to honeycomb refinery. So, I do not think there is any issue with the refinery app.

**Comment by manojnc** [comment]
If I change the exporter to otlphttp and point it to http port then I see the log entry that says "preparing to make http request for traces to the specified endpoint" but nothing after that. Don't see a post call going out.

{"level":"debug","ts":1721409906.8589747,"caller":"otlphttpexporter@v0.105.0/otlp.go:153","msg":"Preparing to make HTTP request","kind":"exporter","data_type":"traces","name":"otlphttp","url":"http://refinery.monitoring.svc.cluster.local:80/v1/traces"}

**Comment by codeboten** [comment]
Thanks for opening the issue @manojnc, can you confirm the configuration you have? The one in the description only includes the `otlp` exporter, not the `otlphttp` exporter shown in the log line. Additionally the url for the config provided doesn't match the url in the log:

```
honeycomb-refinery.monitoring.svc.cluster.local:4317
refinery.monitoring.svc.cluster.local:80/v1/traces
```

**Comment by manojnc** [comment]
Thanks for taking a look at this @codeboten 

Here is my latest exporter configuration for otlphttp. I have verified the network connectivity on this service and port combination. It would be helpful if we can add a debug log that logs the actual request and response from the server hosting the endpoint.

   exporters:
      otlphttp:
        endpoint: "http://refinery.monitoring.svc.cluster.local:6000/"
        tls:
          insecure: true
          insecure_skip_verify: true
        headers:
          "x-honeycomb-team": "${HONEYCOMB_API_KEY}"
          "x-honeycomb-dataset": "apps"
          
Refinery is another service in the namespace and I have configured it to listen to port 6000 over http protocol. If I do a simple curl the refinery service responds with hello message back. So, I just want to understand what is happening to calls from otel to refinery.

**Comment by yujianweilai** [comment]
When I use otel, I also encountered a similar problem, just prompting "Preparing to make HTTP request", and then there is no follow-up, backend apm (I use deepflow) can not receive any trace information generated by the application
![image](https://github.com/user-attachments/assets/147c3ca4-6d2f-4506-af80-ffc07f72c3fe)
my otel-collector config:

![image](https://github.com/user-attachments/assets/9170f64f-e791-4512-9c47-946f42e335a9)

otel-version: 0.85.0

Is the configuration file wrong?

**Comment by JGoebel-WIS** [comment]
Hello together, it's February 2025 and I have the same problem.

I'm encountering an issue with the otlphttp exporter in my OpenTelemetry Collector configuration. Here is the relevant part of my configuration:

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed 
  otlphttp:
    endpoint: "${env:ELASTIC_APM_SERVER_ENDPOINT}"  
    tls:
      insecure: false
      insecure_skip_verify: false
      ca_file: "/etc/certificates/cert.pem"
      min_version: "1.1"
      include_system_ca_certs_pool: true
    headers:
      Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlphttp]
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp]
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
Despite this configuration, I'm getting the following error:

2025-02-20 09:53:36 {"level":"debug","ts":"2025-02-20T08:53:36.013Z","caller":"otlphttpexporter@v0.117.0/otlp.go:177","msg":"Preparing to make HTTP request","kind":"exporter","data_type":"traces","name":"otlphttp","url":"https://SERVER:8200/v1/traces"}

Has anyone encountered a similar issue or have any suggestions on how to resolve this?

**Comment by klesh** [comment]
Same here


```
otel-importer-1  | 2025-07-09T09:42:41.251Z     info    internal/retry_sender.go:133    Exporting failed. Will retry the request after interval.        {"resource": {"service.instance.id": "716c3e4b-2224-46be-b769-32093c22df59", "service.name": "otelcol-contrib", "service.version": "0.128.0"}, "otelcol.component.id": "otlphttp", "otelcol.component.kind": "exporter", "otelcol.signal": "traces", "error": "failed to make an HTTP request: Post \"http://langfuse-web:3000/api/public/otel/v1/traces\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)", "interval": "6.442312843s"}
```

`http://langfuse-proxy:8888/api/public/otel/v1/traces` can be accessed from other containers in the same `docker-compose.yaml` file without problem.

I am trying to import some JSON data into an OLTP backend.

docker-compose:
```
  langfuse-web:
    image: langfuse/langfuse:3
    #restart: always
    depends_on: *langfuse-depends-on
    ports:
      - 3000:3000
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: mysecret # CHANGEME
      LANGFUSE_INIT_ORG_ID: ${LANGFUSE_INIT_ORG_ID:-}
      LANGFUSE_INIT_ORG_NAME: ${LANGFUSE_INIT_ORG_NAME:-}
      LANGFUSE_INIT_PROJECT_ID: ${LANGFUSE_INIT_PROJECT_ID:-}
      LANGFUSE_INIT_PROJECT_NAME: ${LANGFUSE_INIT_PROJECT_NAME:-}
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-}
      LANGFUSE_INIT_PROJECT_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY:-}
      LANGFUSE_INIT_USER_EMAIL: ${LANGFUSE_INIT_USER_EMAIL:-}
      LANGFUSE_INIT_USER_NAME: ${LANGFUSE_INIT_USER_NAME:-}
      LANGFUSE_INIT_USER_PASSWORD: ${LANGFUSE_INIT_USER_PASSWORD:-}

  otel-importer:
    image: otel/opentelemetry-collector-contrib:0.128.0
    volumes:
      - ./importer-conf.yaml:/etc/otelcol-contrib/config.yaml
      - ./collected-data:/data
    depends_on:
      - langfuse-proxy
```

importer-conf.yaml
```
receivers:
  otlpjsonfile:
    include: [ /data/data.json ]

exporters:
  otlphttp:
    # traces_endpoint: http://localhost:3000/api/public/otel/v1/traces
    endpoint: http://langfuse-web:3000/api/public/otel
    tls:
      insecure: true
      insecure_skip_verify: true
    headers:
      x_langfuse_public_key: xxx
    auth:
      authenticator: basicauth/client
    timeout: 10

extensions:
  basicauth/client:
    client_auth: 
      username: pk-lf-a6xxx
      password: sk-lf-984xxx
service:
  extensions: [basicauth/client]
  pipelines:
    traces:
      receivers: [otlpjsonfile]
      # processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlpjsonfile]
      # processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlpjsonfile]
      # processors: [batch]
      exporters: [otlphttp]
```


Does `otel/opentelemetry-collector-contrib:0.128.0` have any shell that can be attached to verify if the endpoint can be accessed in the container?
