### ISSUE TITLE
not able to upload logs from Fluentbit to OTelcollector

### ISSUE THREAD

**Issue by RitikaLaddha** [open-telemetry/opentelemetry-collector#10687]
### Discussed in https://github.com/open-telemetry/opentelemetry-collector/discussions/10635

<div type='discussions-op-text'>

<sup>Originally posted by **RitikaLaddha** July 17, 2024</sup>
Hi,
I want to upload logs from fluent bit to open telemetry collector on AKS cluster

So, I have installed otel collector as deployment [from here](https://artifacthub.io/packages/helm/opentelemetry-helm/opentelemetry-collector)
and fluentbit [from here](https://docs.fluentbit.io/manual/installation/kubernetes#installing-with-helm-chart)

This is my fluentbit configration for output to OTel

   ```
 [OUTPUT]
        Name                 opentelemetry
        Match                *
        Host                 http://my-opentelemetry-collector.namespace.svc.cluster.local
        Port                 4318
        Metrics_uri          /v1/metrics
        Logs_uri             /v1/logs
        Traces_uri           /v1/traces
        Log_response_payload True
        Tls                  On
        Tls.verify           Off
```

I have also added environment variable in fluentbit Daemonset
`env:
  - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
    value: http://my-opentelemetry-collector.namespace.svc.cluster.local:4318`

**But I am getting below error, in my fluentbit logs**

```
[error] [tls] error: unexpected EOF
[2024/07/17 13:51:23] [error] [output:opentelemetry:opentelemetry.1] no upstream connections available to my-opentelemetry-collector.namespace.svc.cluster.local:4317
[2024/07/17 13:51:23] [ warn] [engine] failed to flush chunk '1-1721224282.439304987.flb', retry in 7 seconds: task_id=8, input=tail.0 > output=opentelemetry.1 (out_id=1)
[2024/07/17 13:51:23] [ warn] [engine] failed to flush chunk '1-1721224282.536490801.flb', retry in 9 seconds: task_id=9, input=tail.0 > output=opentelemetry.1 (out_id=1)
```

Do I need to make any configuration change in Otel configmap?
</div>

**Comment by atoulme** [comment]
This says your TLS connection failed. You are trying to connect over TLS to a http endpoint.

You should check your configuration.

**Comment by RitikaLaddha** [comment]
Hi @atoulme 
Thanks for replying 

After I turned off TLS. I am getting below error in logs. I have added fluentbit and otel configmap, can you please have a look and guide me please 🥺

```
[2024/07/21 17:13:15] [ warn] [net] getaddrinfo(host='http://my-opentelemetry-collector.dis.svc.cluster.local', err=15): Out of memory
[2024/07/21 17:13:15] [error] [output:opentelemetry:opentelemetry.1] no upstream connections available to http://my-opentelemetry-collector.dis.svc.cluster.local:4318
[2024/07/21 17:13:15] [ warn] [engine] failed to flush chunk '1-1721581994.699105145.flb', retry in 7 seconds: task_id=4, input=tail.0 > output=opentelemetry.1 (out_id=1)
```


Fluentbit Configmap
```
apiVersion: v1
items:
- apiVersion: v1
  data:
    custom_parsers.conf: |
      [PARSER]
          Name docker_no_time
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
    fluent-bit.conf: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On

      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

      [OUTPUT]
          Name                 opentelemetry
          Match                *
          Host                 http://my-opentelemetry-collector.dis.svc.cluster.local
          Port                 4318
          Metrics_uri          /v1/metrics
          Logs_uri             /v1/logs
          Traces_uri           /v1/traces
          Log_response_payload True
          Tls                  Off
          Tls.verify           Off
          logs_body_key $message
          logs_span_id_message_key span_id
          logs_trace_id_message_key trace_id
          logs_severity_text_message_key loglevel
          logs_severity_number_message_key lognum
          # add user-defined labels
          add_label            app fluent-bit
          add_label            color blue
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: fluent-bit
      meta.helm.sh/release-namespace: dis
    labels:
      app.kubernetes.io/instance: fluent-bit
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/version: 3.1.3
      helm.sh/chart: fluent-bit-0.47.3
    name: fluent-bit
    namespace: dis
```

OTEL Configmap
```
- apiVersion: v1
  data:
    relay: |
      exporters:
        otlp/uptrace:
          endpoint: otlp.uptrace.dev:4317
          headers:
            uptrace-dsn: 'https://mOMzBlbLofrg@api.uptrace.dev?grpc=4317'
      extensions:
        health_check:
          endpoint: ${env:MY_POD_IP}:13133
      processors:
        batch: {}
        memory_limiter:
          check_interval: 5s
          limit_percentage: 80
          spike_limit_percentage: 25
      receivers:
        otlp:
          protocols:
            http:
              endpoint: ${env:MY_POD_IP}:4318
      service:
        extensions:
        - health_check
        pipelines:
          logs:
            exporters:
            - otlp/uptrace
            processors:
            - memory_limiter
            - batch
            receivers:
            - otlp
          metrics:
            exporters:
            - otlp/uptrace
            processors:
            - memory_limiter
            - batch
            receivers:
            - otlp
          traces:
            exporters:
            - otlp/uptrace
            processors:
            - memory_limiter
            - batch
            receivers:
            - otlp
        telemetry:
          metrics:
            address: ${env:MY_POD_IP}:8888
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: my-opentelemetry-collector
      meta.helm.sh/release-namespace: dis
    labels:
      app.kubernetes.io/instance: my-opentelemetry-collector
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: opentelemetry-collector
      app.kubernetes.io/version: 0.104.0
      helm.sh/chart: opentelemetry-collector-0.97.2
    name: my-opentelemetry-collector
    namespace: dis
```
