### ISSUE TITLE
Simple processor metrics

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector#10708]
**Is your feature request related to a problem? Please describe.**

We currently [define a set of metrics for processors](https://github.com/open-telemetry/opentelemetry-collector/blob/21c3f3643dc895d6b7a721fb2a86d41eedf53562/processor/processorhelper/obsreport.go#L63-L121) which cannot be automatically recorded by the collector framework, and as far as I can tell are not _actually_ recorded by any processors in core or contrib. In short, the metrics describe the number of items accepted, dropped, inserted, and refused. (I believe these metrics are loosely inspired by proposals such as https://github.com/open-telemetry/oteps/pull/259, but no such design has actually landed.)

We also have proposals such as https://github.com/open-telemetry/opentelemetry-collector/issues/10355 which would measure size of data according to the same categories, but again, it is not clear that there is any path to automatically recording these values. In the case of size metrics, it would additionally be very difficult for processor developers to accurately capture such measurements because it's unclear how to attribute inserted, dropped, or refused _sizes_ as a portion of an overall payload.

**Describe the solution you'd like**

Looking at this from a collector implementation perspective, what we clearly _can_ observe automatically, is the data being passed in and out of each processor. It would be difficult to determine precisely which parts of that data were inserted or deleted, but we can certainly count the number of items and measure the size of the payload (according to a standard such as [`ProtoMarshaler.Sizer()`](https://github.com/open-telemetry/opentelemetry-collector/blob/9907ba50df0d5853c34d2962cf21da42e15a560d/pdata/ptrace/pb.go#L11)).

Therefore, I propose that we should define new metrics in `processorhelper` which are _automatically_ recorded. If another more nuanced proposal eventually lands, we can add those later.

Importantly, in order to handle error propagation consistently, these metrics would be recorded _after the processor successfully passes data to the next consumer_. This can be accomplished within `processorhelper` by looking at data before and after the processing function, and taking into consideration the result of passing the data along to the next consumer.

Specifically, I propose the following metrics per data type. I'm showing only logs but assume there would be equivalents for metrics and traces.

Incoming and outgoing counts. 
```yaml
    otelcol_processor_incoming_log_records: # or processor_consumed_log_records
      enabled: true
      description: Number of log records passed to the processor.
      unit: "{records}"
      sum:
        value_type: int
        monotonic: true
    otelcol_processor_outgoing_log_records: # or processor_emitted_log_records
      enabled: true
      description: Number of log records emitted from the processor.
      unit: "{records}"
      sum:
        value_type: int
        monotonic: true
```

Incoming and outgoing sizes. These would be measured only if enabled.
```yaml
    otelcol_processor_incoming_log_size: # or processor_consumed_log_size
      enabled: false # by default
      description: Total size of log records passed to the processor.
      unit: "By"
      sum:
        value_type: int
        monotonic: true
    otelcol_processor_outgoing_log_size: # or processor_emitted_log_size
      enabled: false # by default
      description: Total size of log records emitted from the processor.
      unit: "By"
      sum:
        value_type: int
        monotonic: true
```
