### ISSUE TITLE
Unable to kafka receiver username config value to "$ConnectionString" with confmap.unifyEnvVarExpansion feature gate enabled

### ISSUE THREAD

**Issue by ben-childs-docusign** [open-telemetry/opentelemetry-collector#10713]
**Describe the bug**

We have some config to connect to azure event hubs using the kafka receiver this requires us to set the user name to "$ConnectionString" per azure documentation:
https://learn.microsoft.com/en-us/azure/event-hubs/azure-event-hubs-kafka-overview#shared-access-signature-sas

Prior to this feature gate enabled we were able to do this by configuring the receiver as follows:

```
  config:
    receivers:
      kafka:
        auth:
          sasl:
            mechanism: PLAIN
            username: "$$ConnectionString"
          tls:
            insecure: false
        protocol_version: 1.0.0
        topic: metricstopic
```

With version 105 of the collector we get this error:
```
Error: failed to get config: cannot resolve the configuration: cannot convert the confmap.Conf: variable substitution using $VAR has been deprecated in favor of ${VAR} and ${env:VAR} - please update $ConnectionString or temporarily disable the confmap.unifyEnvVarExpansion feature gate
2024/07/23 21:58:26 collector server run finished with error: failed to get config: cannot resolve the configuration: cannot convert the confmap.Conf: variable substitution using $VAR has been deprecated in favor of ${VAR} and ${env:VAR} - please update $ConnectionString or temporarily disable the confmap.unifyEnvVarExpansion feature gate
```

**Steps to reproduce**

Configure kafka receiver as shown above (no need to even add it to a pipeline)

**What did you expect to see?**

The config is loaded successfully

**What did you see instead?**

The collector crashes on boot

**What version did you use?**

v0.105.0

**What config did you use?**

```
  config:
    receivers:
      kafka:
        auth:
          sasl:
            mechanism: PLAIN
            username: "$$ConnectionString"
          tls:
            insecure: false
        protocol_version: 1.0.0
        topic: metricstopic
```

**Environment**

Ubuntu 20.04 - go 1.21

**Additional context**

Does this regex need to be updated to allow for "$$" prefixed strings to be excluded? Or is there some other fix missing?
https://github.com/open-telemetry/opentelemetry-collector/blob/c239e73bbb83aec650866e15dcae3792d9b7279d/confmap/converter/expandconverter/expand.go#L94

Note that this PR proposes to fix this problem but I should have that fix since I'm using version 105:
https://github.com/open-telemetry/opentelemetry-collector/pull/10560
