### ISSUE TITLE
The headers_setter extension supports values from attributes

### ISSUE THREAD

**Issue by danielnegreiros** [open-telemetry/opentelemetry-collector#10727]
**Is your feature request related to a problem? Please describe.**

No, it's not a technical issue, more of a business value.

**Describe the solution you'd like**

It involves the Headers Setter extension providing the capability to fetch data not only from HTTP headers but also from attributes. We have two options to set the content, value or from_context.

```yaml
extensions:
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        from_context: tenant_id
```

According to the documentation:
from_context: The header value is looked up from the request metadata, such as HTTP headers.

But when using fluentforward as a receiver we will not have HTTP headers, only logs attributes.

```yaml
    receivers:
      fluentforward:
          endpoint: 0.0.0.0:8006
```

It would be great to have an option like this to get the value from attributes.

```yaml
extensions:
  headers_setter:
    headers:
      - action: insert
        key: X-Scope-OrgID
        from_attribute: tenant_id
```

Otherwise, It's not possible to use fluentforward or another non-HTTP receiver as multi-tenancy.

**Describe alternatives you've considered**

I have considered using otlp/http header configuration, it works with hardcoded values, but also cannot get values from attributes.

```yaml
otlphttp:
  endpoint: "https://1.2.3.4:1234"
  headers:
    X-Scope-OrgID: "somevalue"
```
