### ISSUE TITLE
Use Docker Secrets for Configuration Values

### ISSUE THREAD

**Issue by JaronrH** [open-telemetry/opentelemetry-collector#10759]
### Discussed in https://github.com/open-telemetry/opentelemetry-collector/discussions/10706

<div type='discussions-op-text'>

<sup>Originally posted by **JaronrH** July 23, 2024</sup>
I currently use Docker Swarm with Docker Secrets to store configuration information.  I would like to load information from Secrets into my configuration.  For example:

```
receivers:
  rabbitmq:
    endpoint: http://rabbitmq_rabbitmq:15672
    username: ${file:/run/secrets/RABBITMQ_USER}
    password: ${file:/run/secrets/RABBITMQ_PASSWORD}
    collection_interval: 10s
```

Docker Secrets are exposed as files in /run/secrets.  The problem (as far as I can tell - I'm not a Go dev) is that the ${file:} processor is trying to load those secrets as yaml files instead of values!  So, I'm getting errors like this as a result:

```
Error: failed to get config: cannot resolve the configuration: yaml: did not find expected node content
2024/07/23 16:08:53 collector server run finished with error: failed to get config: cannot resolve the configuration: yaml: did not find expected node content
```

Is there a better way to do this? Maybe some way to tell opentelemetry-collector-contrib to load everything in /run/secrets into env variables so I can use ${env:*}?

Thanks!</div>

**Comment by TylerHelmuth** [comment]
@JaronrH what version of the collector are you using?

**Comment by JaronrH** [comment]
> @JaronrH what version of the collector are you using?

I'm using otelcol-contrib 0.105.0

**Comment by mx-psi** [comment]
@JaronrH could you try with 0.106.0?

**Comment by JaronrH** [comment]
> @JaronrH could you try with 0.106.0?

I upgraded to 0.106.0 and tried it again.  Here are my findings:
-  Adding the _RabbitMq_ config allowed the process to startup in Docker.
- Adding config for _Postgres_ (see below) caused the same error to appear.
- RabbitMq receiver was getting 401/Unauthorized errors back from RabbitMq so I do not believe the credentials were actually being loaded from the Docker Secrets mount point.

```
  postgresql:
    endpoint: database_postgres:5432
    transport: tcp
    tls:
      insecure: true
    username: ${file:/run/secrets/dbUser}
    password: ${file:/run/secrets/dbPassword}
```

**Comment by mx-psi** [comment]
@JaronrH Thanks!!

> Adding the RabbitMq config allowed the process to startup in Docker.

So to be clear about this, the following config works for you in v0.106.0 but does not work in v0.105.0?

```
receivers:
  rabbitmq:
    endpoint: http://rabbitmq_rabbitmq:15672
    username: ${file:/run/secrets/RABBITMQ_USER}
    password: ${file:/run/secrets/RABBITMQ_PASSWORD}
    collection_interval: 10s
```

> Adding config for Postgres (see below) caused the same error to appear.

With this you mean the `yaml: did not find expected node content` error?

> RabbitMq receiver was getting 401/Unauthorized errors back from RabbitMq so I do not believe the credentials were actually being loaded from the Docker Secrets mount point.

:thinking: I think this part is likely not an issue of the Collector itself but some misconfiguration in the `/run/secrets` files.

**Comment by JaronrH** [comment]
> So to be clear about this, the following config works for you in v0.106.0 but does not work in v0.105.0?

It "works" in that I did not get an error starting up.  It does not seem to load the value from Docker Secrets as I'm getting the 401 error.

> > Adding config for Postgres (see below) caused the same error to appear.
> 
> With this you mean the `yaml: did not find expected node content` error?

That is correct!

> > RabbitMq receiver was getting 401/Unauthorized errors back from RabbitMq so I do not believe the credentials were actually being loaded from the Docker Secrets mount point.
> 
> 🤔 I think this part is likely not an issue of the Collector itself but some misconfiguration in the `/run/secrets` files.

 It very well could be!  In the example from your documentation, which is loading a file for Exports, you're loading a yaml file that is used for the exports.  In this case, the Docker Secrets file contains JUST the username (Ex: User) or JUST the password (Ex: Password123) and not a [partial] yaml file.

This is why I was wondering if there was a better way for me to be handling this in Docker OR if Docker Secrets support could be added?

For Example:
```
receivers:
  rabbitmq:
    endpoint: http://rabbitmq_rabbitmq:15672
    username: ${dockersecret:RABBITMQ_USER}
    password: ${dockersecret:RABBITMQ_PASSWORD}
    collection_interval: 10s
```
dockersecret: handler looks for a file in  /run/secrets/ named RABBITMQ_USER and loads the files contents as the value to be inserted.
