### ISSUE TITLE
Own-telemetry: Ability to enabled/disable individual metrics

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector#10769]
**Is your feature request related to a problem? Please describe.**

Our notion of basic/normal/detailed telemetry levels is a quick and convenient way for users to tune the volume of the collector's own telemetry, but it is quite crude compared to what we provide to control telemetry not generated by the collector. For example, out `mdatagen` library provides the ability to enable or disable any individual metric. _Not_ having this ability for the collector's own telemetry means that users may not be able to get the metrics they need without enabling all metrics.

**Describe the solution you'd like**

In the telemetry configuration, we should offer the ability to enable or disable individual metrics, regardless of telemetry level.

The telemetry level should be used as the starting point for which metrics are enabled or disabled, but then individual metric settings can override.

**Comment by codeboten** [comment]
Thanks for opening the issue. One question I have is how this works w/ views, because configuration of views would allow this same functionality. I'd rather not have multiple ways of doing the same thing if possible

**Comment by djaglowski** [comment]
I'm not familiar enough with views to give a good answer here. Are they exposed to our users via the collector config? Or are they an implementation detail? For that matter, is there a reason we don't use views instead of in-code checks against metric level?

**Comment by codeboten** [comment]
@djaglowski views will be configurable in the same way as they are for SDK via config, see https://github.com/open-telemetry/opentelemetry-configuration/blob/cc7cd375d893e440afdc294a00f98038ebaa4eab/examples/kitchen-sink.yaml#L221 as an example

The main reason I can see wanting to keep a telemetry level configuration option is for convenience to end users. It would be easier to configure one setting than to have to configure views for all metrics. But then, if we have multiple ways to configured things, we get into the issue of precedence.

**Comment by djaglowski** [comment]
> The main reason I can see wanting to keep a telemetry level configuration option is for convenience to end users.

I agree but couldn't these be implemented as views? (Then for example component developers don't have to check `if telemetrySettings.Level == Detailed`, etc.)

If we did that, does that normalize configuration in a way where users could add or subtract from our predefined views by adding their own?

**Comment by codeboten** [comment]
> I agree but couldn't these be implemented as views? (Then for example component developers don't have to check if telemetrySettings.Level == Detailed, etc.)

There's no concept of levels built into views. I considered adding a `level` in mdatagen block for each metric configured via `telemetry::metrics` to allow the code to be automatically generated and remove the need to check in the components themselves. Otherwise we'd need to provide a mechanism for components to return views based on different levels.

An alternative proposed was to have a [different MeterProvider](https://github.com/open-telemetry/opentelemetry-collector/issues/9510#issuecomment-2039370186) for everything level which would again remove the need to check a level before recording telemetry. This would mean that the component developer would have to make a decision on what they consider appropriate for the different levels.

> If we did that, does that normalize configuration in a way where users could add or subtract from our predefined views by adding their own?

We could definitely publish a configuration for each level that users could modify as they see fit. This would be somewhat easy to generate via mdatagen in the documentation as well

**Comment by crobert-1** [comment]
I hope I'm not getting sidetracked from the original purpose of this issue, but is [this line in the `mdatagen` metadata schema](https://github.com/open-telemetry/opentelemetry-collector/blob/297135886b88c7372a650227d99ab99410c2c4bb/cmd/mdatagen/metadata-schema.yaml#L138) the same thing as what Dan's proposing here? I'm pretty new to this area of the collector so I may be missing something obvious, but the schema appears to state that this should be supported.

_Please let me know if I'm missing something._

**Comment by ptodev** [comment]
Hello! 👋  I could take a look into implementing this, but I'm still not yet sure what a good solution would look like. 

One solution is to use views to disable (but not enable) metrics using views. The user defined views would override the settings configured by the `level` config argument so that the Collector emits less metrics than it normally would:

```yaml
service:
  telemetry:
    metrics:
      level: basic
      views:
      - selector:
          instrument_name: otelcol_exporter_send_failed_spans
        stream:
          aggregation:
            drop:
```

Another solution could be to make the `service/telemetry/metrics/level` and `service/telemetry/metrics/views` config arguments mutually exclusive, and to let users create a view which drops specific metrics. I suppose this is similar to @codeboten's suggestion above:

> We could definitely publish a configuration for each level that users could modify as they see fit. 

However, I'm not sure how ergonomic both of these approaches are. I suppose most users want to specify the metrics they are interested in, not the ones they are not interested in. That's because if you have a dashboard which uses a particular metric, you want to make sure the metric is always present.

**Comment by mx-psi** [comment]
I feel like the [`disabled` parameter in the in-development `MeterConfig`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#meterconfig) would be the solution for this. 

This is not consistent with the rest of our configuration so I filed open-telemetry/opentelemetry-specification/issues/4344

**Comment by djaglowski** [comment]
> I feel like the [`disabled` parameter in the in-development `MeterConfig`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#meterconfig) would be the solution for this.

If I'm understanding correctly, the `disabled` parameter would give us a mechanism for controlling individual metrics. However, I think we still need to agree on the mechanism for configuring the value of the flag.

> Re-reading this I am not sure what the decision if any was. Do we want to have a separate mechanism for configuring inidividual metrics different from views or `service::telemetry::metrics`?

I don't think we have consensus. Admittedly, I am not familiar enough with views to understand what has been suggested.

Perhaps we could continue this conversation starting from what the actual configuration would look like:

Let's just say we have two metrics `otelcol.foo.enabledbydefault` and `otelcol.foo.disabledbydefault` which I'd like to flip to non-default settings. What I intended with this issue is that we'd have something like the following:

```yaml
service:
  telemetry:
    metrics:
      otelcol.foo.enabledbydefault: false
      otelcol.foo.disabledbydefault: true
```

Can someone please show me how the collector configuration would look if we used views to change _only_ these two metrics to non-default settings?

**Comment by mx-psi** [comment]
@djaglowski So here is my proposal with some examples. The issue I linked above about `MeterConfig.disabled` could simplify this, but I am sticking with views config for all examples.

My pitch is that we should conceptualize this as having two incompatible modes for configuring telemetry: a *basic*, level-based configuration and an *advanced*, views/meter config based configuration for advanced users that really want to configure things with a lot of detail. The basic mode would be equivalent to the advanced mode with a concrete set of views. Users would be able to get this concrete list of views for a particular level through some sort of mechanism (initially docs, in the longer term it could be a subcommand, this doesn't need to be ready for 1.0), so they can have a starting template.

To make this concrete, let's say we have `otelcol.foo.basic` available on `level: basic` or above, and `otelcol.foo.detailed` available on `level: detailed`. Some examples:

- *No levels, no views*:You don't configure any views or any level (but, maybe, you configure the `readers`). The defaults apply.
```yaml
service:
  telemetry:
     metrics:
       readers:
         - periodic:
            exporter:
              otlp_http:
                endpoint: http://localhost:4318/v1/metrics
```
- *detailed level, no views*: You configure levels but don't configure views. In this case both `otelcol.foo.basic` and `otelcol.foo.detailed` would be available
```yaml
service:
  telemetry:
    metrics:
      level: detailed
```
- *drop view, no level*: You drop a metric based on a view. The levels are ignored, the views from `level` do not apply, so in this case you would have `otelcol.foo.detailed` but not `otelcol.foo.basic`. You also get an info-level log that says something like *"Views-based configuration, ignoring levels to report metrics. If you want to get the default views for a level, run `otelcol get-views <level>`"*
```yaml
service:
  telemetry:
     metrics:
       views:
          - selector:
               instrument_name: otelcol.foo.basic
            stream:
               aggregation:
                   drop:
```
- *Yes levels, yes views*: This would result in an error telling you to pick one or the other, something like: *error: `service::telemetry::metrics::level` is incompatible with `service::telemetry::metrics:views`. See <link to documentation that explains the two possibilities>"*
```yaml
service:
  telemetry:
     metrics:
       level: detailed
       views:
          - selector:
               instrument_name: otelcol.foo.basic
            stream:
               aggregation:
                   drop:
```


Summary table:

| Release                  | `otelcol.foo.basic` reported? | `otelcol.foo.detailed` reported? |
|--------------------------|-------------------------------|----------------------------------|
| none set (default)       | Yes                           | No                               |
| detailed level, no views | Yes                           | Yes                              |
| drop view, no level      | No  (log explains why)                          | Yes                              |
| level AND views          | :bangbang: invalid config                   | :bangbang:    invalid config                   |

**Comment by jade-guiton-dd** [comment]
@mx-psi This proposal is probably the simplest to implement (either use the specified views or the list corresponding to a level), but I fear this may be a big pain point for users.

Users who just want to drop one metric from the defaults will probably just add a drop view for it. If they didn't have a level configured, they'll suddenly see the amount of exported telemetry explode (everything except the one they dropped), and will need to notice the warning to understand why. And then they'll have to write a gigantic config file just to get back to the previous behavior.

And once views _are_ set up, they would no longer be able to quickly enable more telemetry for debugging purposes, and would have to remove views for specifically the metrics they want.

I think the ideal solution from a user's perspective would be:
- `level` for setting default views;
- a `map[key]bool` object like `metrics` in Dan's example to customize the views on an emit/drop basis;
- the `views` object for more advanced customization.
The only question is the feasibility of "merging" explicit views with the default ones.

**Comment by mx-psi** [comment]
> Users who just want to drop one metric from the defaults will probably try to simply add a drop view for it. If they didn't have a level configured, they'll suddenly see the amount of exported telemetry explode (everything except the one they dropped), and will need to notice the warning to understand why.

IMO _any_ system that has multiple ways of configuring the same thing runs into this risk of confusion. If needed we could have a (name to be bikeshedded) `level_based_config::enabled: false` flag that you need to disable to be able to use views, if we want to make it super explicit.

> Then, they'll have to write a gigantic config file just to get back to the previous behavior.

Our config system is flexible enough to make this a nonissue, if we get merge rules right they could just include a file and merge it with their config. They would just generate the views config into a `genbasic_level_views.yaml` file and do something like:

```
otelcorecol --config genbasic_level_views.yaml --config my_config.yaml  --merge=append
```

> And once views are set up, they would no longer be able to quickly enable more telemetry for debugging purposes and would have to remove views for specifically the metrics they want.

Following the above, they would just have to change the file they include

```
otelcorecol --config gendetailed_level_views.yaml --config my_config.yaml  --merge=append
```

> Even with views being a thing, I think an intermediate option would be good, because it would allow easy toggling of the default metrics without having to understand or think about how views work and interact with one another.

I agree that views can be complex. This however feels like a problem we should solve at the specification level, if it's complex for our users it would be complex for users of any other application.

> So adding the default views after the list of explicit ones may be enough to give the latter priority, with the only caveat being potential warning logs about conflicts.

It would be interesting to understand the exact semantics of having overlapping views. I am not categorically opposed to this option, but my initial gut feeling is that this could be as confusing as the solution I am proposing.

**Comment by jade-guiton-dd** [comment]
> IMO any system that has multiple ways of configuring the same thing runs into this risk of confusion. If needed we could have a (name to be bikeshedded) level_based_config::enabled: false flag that you need to disable to be able to use views, if we want to make it super explicit.

I half-agree; I think a system with a "broad" configuration and a "detailed" configuration that customizes it is relatively intuitive in comparison with a system where setting the latter essentially changes the former to "everything on".

If we go with your proposal, I'm in support of something like `level_based_config::enabled` (or maybe something like `level: custom`?), it would make it harder to accidentally switch everything on.

> Our config system is flexible enough to make this a nonissue, if we get merge rules right they could just include a file and merge it with their config.

> It would be interesting to understand the exact semantics of having overlapping views. I am not categorically opposed to this option, but my initial gut feeling is that this could be as confusing as the solution I am proposing.

Concatenating the default list of views with a custom one by applying two configuration files will have the same confusing semantics as doing it automatically in the code, it just requires more work on the user's part.

> This however feels like a problem we should solve at the specification level, if it's complex for our users it would be complex for users of any other application.

Definitely agree with that part. I think the way that conflicting Views interact is surprising and confusing in the spec, and I think the inclusion of MetricConfig is a sign that others agree that using Views to enable/disable metrics is too complicated. I'm not sure if the interaction between the two is specified? If the spec goes with a "Views take priority over MetricConfig.enabled" solution and adds a YAML-based way to specify MetricConfig, my proposal could be implemented by simply setting a default value for the MetricConfigs based on the level.

**Comment by mx-psi** [comment]
> Concatenating the default list of views with a custom one by applying two configuration files will have the same confusing semantics as doing it automatically in the code, it just requires more work on the user's part.

Hm, I think the important difference between the concatenate-views solution and the basic-and-advanced-modes solution is that users are not _required_ to use the default config in the basic-and-advanced-modes solution; they can just write their own thing if they want to.

**Comment by mx-psi** [comment]
@jade-guiton-dd This is how the `MeterConfig` would work (pending approval by the Configuration WG): https://github.com/open-telemetry/opentelemetry-configuration/pull/140. Could you make your proposal more concrete with some examples like I did on https://github.com/open-telemetry/opentelemetry-collector/issues/10769#issuecomment-2624984772 ?

**Comment by jade-guiton-dd** [comment]
To recap, the SDK spec has an experimental spec for a `MeterConfig` struct:
> ### MeterConfig
> A `MeterConfig` defines various configurable aspects of a `Meter`'s behavior. It consists of the following parameters:
> * `disabled`: A boolean indication of whether the Meter is enabled.

and a `MeterConfigurator` parameter for the `MeterProvider`:
> #### MeterConfigurator
> A `MeterConfigurator` is a function which computes the MeterConfig for a Meter.
> The function MUST accept the following parameter:
> * `meter_scope`: The `InstrumentationScope` of the `Meter`.
>
> `MeterConfigurator` is modeled as a **function** to maximize flexibility. However, implementations MAY provide shorthand or helper functions to accommodate common use cases:
> * Select one or more Meters by name, with exact match or pattern matching.
> * Disable one or more specific Meters.
> * Disable all Meters, and selectively enable one or more specific Meters.

The PR linked above proposes the following example YAML config to customize the `MeterConfigurator`:
```yaml
meter_provider: # This corresponds to `service::telemetry::metrics` in the OTelCol config
  meter_configurator:
    default_config: # Configure the default meter config used there is no matching entry in .meter_configurator.meters.
      disabled: true
    meters:
      - name: io.opentelemetry.contrib.* # Meter names to match, which can include '?' and '*' placeholders.
        config:
          disabled: false
```

This hasn't been implemented in the SDK yet, but presumably this implies that when the `meter_configurator` key is set, a `MeterConfigurator` function is set on the provider by the SDK, which returns a `MeterConfig` corresponding to the first matching rule in `meters`, or the one in `default_config` if there are no matches.

With this PR in my mind, my updated proposal would be to allow specifying both `level` and `meter_configurator`. The `level` would provide a default `meter_configurator`, which would be customized by the one explicitly provided, allowing easy toggling of metrics on top of the defaults. This could be done by setting the `MeterConfigurator` ourselves to a function implementing this fallback to `level`-based defaults, no concatenating of lists required.

However, there is a big issue with this proposal in the form of `default_config`. That key conflicts with my intended use of `level` as a "default config". No matter what merge policy we choose, I think it would be confusing for users. Therefore, I think we will need to make `level` and `default_config` mutually exclusive, similar to Pablo's proposal.

I think the best way to do that would be to require setting `level` to `custom` before making use of `default_config`. This way users are still clearly aware that they are disabling our `level`-based defaults. Users who want to customize the `level`-based defaults will leave `default_config` unset, and users who want everything except specific metrics or nothing but specific metrics will set `level: custom` and define `default_config` to what they want.

Here are some examples of what this would look like, assuming we have the same example `otelcol.foo.basic` and `otelcol.foo.detailed` metrics as above:

**Example 1: Oops, All Defaults**
```yaml
service:
  telemetry:
    metrics:
      readers: [...]
```
→ `level` defaults to `normal`. We define a `MeterConfigurator` which enables `normal` and up metrics.
→ Only `otelcol.foo.basic` is emitted.

**Example 2: Level up**
```yaml
service:
  telemetry:
    metrics:
      readers: [...]
      level: detailed
```
→ `level: detailed` is applied. We define a `MeterConfigurator` which enables `detailed` and up metrics.
→ Both example metrics are emitted.

**Example 3: Customized defaults**
```yaml
service:
  telemetry:
    metrics:
      readers: [...]
      meter_configurator:
        meters:
          - name: otelcol.foo.basic
            config:
              disabled: true
```
→ `level` defaults to `normal`. Since `meter_configurator` is set without `default_config`, we define a `MeterConfigurator` which applies the first matching `MeterConfig` in `meters`, or, if no matches are found, enables `normal` and up metrics.
→ Neither metric is emitted (`basic` is explicitly disabled, `detailed` is disabled by the default `level`).

**Example 4: Customized defaults 2: Electric Boogaloo**
```yaml
service:
  telemetry:
    metrics:
      readers: [...]
      meter_configurator:
        meters:
          - name: otelcol.foo.detailed
            config:
              disabled: false
```
→ Same as above.
→ Both metrics are emitted (`basic` is enabled by the default `level`, `detailed` is explicitly enabled).

**Example 5: I am altering the defaults, pray I do not alter them any further**
```yaml
service:
  telemetry:
    metrics:
      readers: [...]
      level: custom
      meter_configurator:
        default_config:
          disabled: false
```
→ Because `level` is set to `custom`, level-based config is entirely disabled, and the `meter_configurator` is passed as-is to the SDK.
→ Both metrics are emitted (the default is `disabled: false` and no further rules are set).

**Example 6: Conflicting directives**
```yaml
service:
  telemetry:
    metrics:
      readers: [...]
      level: normal
      meter_configurator:
        default_config:
          disabled: false
```
→ `meter_configurator::default_config` is set, but `level` is not set to custom. Return an error explaining that `meters` can customize either the `level` defaults or the `default_config`, but both cannot be used at the same time.

**Important note:** If the SDK team decides to make the `default_config` key required rather than optional, then my proposal is to fall back on Pablo's proposal entirely, and make `level` and `meter_configurator` as a whole mutually exclusive. I would recommend using the same `level: custom` approach as above.
