### ISSUE TITLE
Percentage settings for memory limiter processor and ballast size

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1078]
**Is your feature request related to a problem? Please describe.**

Flag `--mem-ballast-size-mib` and memory linter processor configuration accept absolute settings. This makes it hard to enable and configure these components in a default/hardcoded configuration. The percentage settings could be applied to a wide range of deployments and default values could be used.

`--mem-ballast-size-mib=2000`
```yaml
processors:
  memory_limiter:
    ballast_size_mib: 2000
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500
```

**Describe the solution you'd like**

Use percentages to set `--mem-ballast-size-mib`, `ballast_size_mib`, `limit_mib` and `spike_limit_mib`. The `check_interval` could be set some optimal default value.

**Describe alternatives you've considered**

Wrap the memory linter and dynamically calculate absolute values. However, it would be better to get this implemented directly in the core.

**Additional context**

Jaeger binaries would like to enable memory linter in the default configuration.
