### ISSUE TITLE
Variables in comments in config files that are included are interpolated

### ISSUE THREAD

**Issue by antonio** [open-telemetry/opentelemetry-collector#10787]
**Describe the bug**
String interpolation is being applied to comments in config files that are included from another config file, which can cause errors and prevent the collector from starting.

**Steps to reproduce**
Start the collector with the following config:

***config.yaml***
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:

exporters:
  ${file:logging.yaml}

service:
  telemetry:
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
```

***logging.yaml***
```yaml
# ${hello.world}
logging:
  verbosity: detailed
```

**What did you expect to see?**
The collector should ignore the comment and carry on.

**What did you see instead?**
The collector tried to replace the variable in the comment with an environment variable that does not exist and exited with an error.

```sh
❯ ./otelcol validate --config=config.yaml
Error: failed to get config: cannot resolve the configuration: environment variable "hello.world" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
2024/08/01 20:06:33 collector server run finished with error: failed to get config: cannot resolve the configuration: environment variable "hello.world" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
```

**What version did you use?**
v0.106.1

**What config did you use?**
See above

**Environment**
I've manually replicated this on MacOS, go 1.22.5, but I've also seen it fail in CI (Ubuntu, different go versions) 

**Additional context**
Versions prior to v0.106.0 did not have this issue.

```sh
~/Code/opentelemetry-collector-contrib
❯ ./otelcol validate --config=config.yaml

~/Code/opentelemetry-collector-contrib
❯ echo $?
0

~/Code/opentelemetry-collector-contrib
❯ ./otelcol --version
otelcol version 0.105.0
```
