### ISSUE TITLE
Collector's Internal Metrics Not Disabled When Specifying service:telemetry:metrics:level:none

### ISSUE THREAD

**Issue by RaginiDhatric** [open-telemetry/opentelemetry-collector#10780]
**Describe the bug**

The setting of  **service: telemetry: metrics: level: none** successfully disables basic and normal-level metrics in the OpenTelemetry Collector; however, detailed-level metrics continue to be exported to Stackdriver, Prometheus and managed Prometheus metrics exporters.

**Steps to reproduce**

1. Set service:telemetry:metrics:level:none in the OpenTelemetry Collector configuration.
2. Deploy the Collector with this configuration.
3. Observe the metrics exported to Google Stackdriver, managed Prometheus and Prometheus noting that detailed-level internal metrics are still being collected and exported.

**What did you expect to see?**

All internal metrics, including detailed-level metrics, should not be collected or exported

**What did you see instead?**

Detailed-level metrics are still being collected and exported. Example below
![image](https://github.com/user-attachments/assets/f3388d27-e5f0-4107-9096-1952b3d872b6)

**What version did you use?**

v0.99.0

**What config did you use?**

exporters:
googlecloud:
  metric:
    service_resource_labels: false
    instrumentation_library_labels: false
  prometheus:
    endpoint: 0.0.0.0:9090
    metric_expiration: 1m
    add_metric_suffixes: false
  googlemanagedprometheus:
    metric:
      add_metric_suffixes: false
      extra_metrics_config:
        enable_scope_info: false
        enable_target_info: false
    project: test
  logging: {}
processors:
  batch:
    send_batch_size: 200
    timeout: 0s
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection:
    detectors:
    - gcp
    timeout: 10s
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ***:4317
      http:
        endpoint: ***:4318
service:
  pipelines:
    logs:
      exporters:
      - logging
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
    metrics:
      exporters:
      - googlecloud
      - googlemanagedprometheus
      - prometheus
      processors:
      - resourcedetection
      - memory_limiter
      - batch
      receivers:
      - otlp
  telemetry:
    metrics:
      level: none
    logs:
      encoding: json

**Environment**

**Additional context**

Initially by setting metrics:level:none option disabled basic level and normal level metrics [listed here](https://opentelemetry.io/docs/collector/internal-telemetry/#lists-of-internal-metrics:~:text=by%20instrumentation%20type.-,basic%2Dlevel%20metrics,-Metric%20name) but i still continue to see detailed level metrics.
Supported logs: 
![image](https://github.com/user-attachments/assets/cdb28f5d-44fc-4a07-ae60-a3d8367845e4)

**Comment by mx-psi** [comment]
@RaginiDhatric Can you try with the latest version (v0.106.0)?

**Comment by dashpole** [comment]
I suspect these are opencensus metrics.  Is the OC bridge still used when metrics level is set to none?

**Comment by RaginiDhatric** [comment]
@mx-psi okay, let me try and get back!!

@codeboten I see these metrics from all the exporters i configured i.e googlecloud , googlemanagedprometheus and prometheus. 

@dashpole I dont think so, because googlecloud exporter exports it as custom.googleapis.com/opentelemetry/rpc.client.duration and googlemanagedprometheus exports as prometheus.googleapis.com/rpc_client_duration/histogram

**Comment by dashpole** [comment]
nevermind.  OC grpc metrics have a different name: https://github.com/census-instrumentation/opencensus-go/blob/01e6da5fc01c42aca1e0ce315f41744876e9fcbb/plugin/ocgrpc/server_metrics.go#L16

**Comment by RaginiDhatric** [comment]
@mx-psi On upgrading to latest version(v0.106.0), i see the following message with continuous restarts of the collector pod.

"{"caller":"localhostgate/featuregate.go:63", "feature gate ID":"component.UseLocalHostAsDefaultHost", "level":"info", "msg":"The default endpoints for all servers in components have changed to use localhost instead of 0.0.0.0. Disable the feature gate to temporarily revert to the previous default."}"
What is the configuration to disable the feature gate? Can you help here?

**Comment by RaginiDhatric** [comment]
@mx-psi Upgrading to the latest version(v0.106.1) helped in disabling internal metrics for googlecloud and googlemanagedprometheus but not for prometheus exporter. I still see the following metrics when API calls are made i.e
rpc_client_duration, rpc_client_request_size, rpc_client_requests_per_rpc, rpc_client_response_size, rpc_client_responses_per_rpc.  Is there something more to configure?

**Comment by RaginiDhatric** [comment]
@mx-psi I upgraded to the latest version (v0.106.1) but it did not help in disabling internal metrics for any of the exporters. I still see the following metrics when API calls are made i.e
rpc_client_duration, rpc_client_request_size, rpc_client_requests_per_rpc, rpc_client_response_size, rpc_client_responses_per_rpc.

**Comment by atib92** [comment]
I am also observing the same issue. Irrespective of the 'level' value set via config, it seems the collector is configured with level=Normal
```
2024-08-05T16:36:15.305Z  info  service@v0.106.1/telemetry.go:96  Serving metrics {"address": ":8888", "metrics level": "Normal"}
```

**Comment by mx-psi** [comment]
@RaginiDhatric @atib92 It would be helpful if you can test which of the components is generating the metrics. To do this you can replace the different components and check if the metrics are still seen.

**Comment by atib92** [comment]
Mine turned out to be a false positive. The otel configs were not correctly mounted in the container which was causing the default configs to get loaded which probably enables debug metrics.

**Comment by RaginiDhatric** [comment]
@mx-psi I tested the setup by simplifying the OpenTelemetry Collector configuration to primarily include only the metrics exporter component. I still observed that internal telemetry metrics were being generated and exported. Below, I have detailed the testing configuration and my findings:

```yaml
exporters:
  googlemanagedprometheus:
    metric:
      add_metric_suffixes: false
      extra_metrics_config:
        enable_scope_info: false
        enable_target_info: false
    project: gcp-project-name
  prometheus:
    add_metric_suffixes: false
    endpoint: 0.0.0.0:9090
    metric_expiration: 1m
extensions:
  health_check:
    endpoint: ${env:MY_POD_IP}:13133
processors:
  batch: {}
  k8sattributes: null
  k8sattributes/2:
    extract:
      labels:
      - from: pod
        key: app
        tag_name: container_name
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection:
    detectors:
    - gcp
    timeout: 10s
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4317
      http:
        endpoint: ${env:MY_POD_IP}:4318
service:
  extensions:
  - health_check
  pipelines:
    metrics:
      exporters:
      - prometheus
      - googlemanagedprometheus
      processors:
      - resourcedetection
      - k8sattributes
      - memory_limiter
      - batch
      receivers:
      - otlp
  telemetry:
    logs:
      encoding: json
    metrics:
      level: none
```
Since I excluded the Google Cloud exporter from my configuration, I observed that the internal telemetry metrics were no longer exported through that particular exporter. However, these metrics were still visible for both the Google Managed Prometheus and Prometheus exporters.

Metrics i observed:
TYPE rpc_client_duration histogram
TYPE rpc_client_request_size histogram
TYPE rpc_client_requests_per_rpc histogram
TYPE rpc_client_response_size histogram
TYPE rpc_client_responses_per_rpc histogram

Detailed logs:
![image](https://github.com/user-attachments/assets/86b5f574-9616-4460-975f-75f932ba314e)

**Comment by adriangb** [comment]
I also have not been able to get any config to disable internal telemetry. This should be documented (and work).

**Comment by codeboten** [comment]
@adriangb can you share the configuration you've used? I just tested the following:

```yaml
service:
  telemetry:
    metrics:
      level: detailed
```

```bash
curl localhost:8888/metrics
# HELP otelcol_process_cpu_seconds Total CPU user and system time in seconds [alpha]
# TYPE otelcol_process_cpu_seconds counter
otelcol_process_cpu_seconds{service_instance_id="582f2176-3448-4bdb-8032-616baabfc003",service_name="otelcontribcol",service_version="0.120.1-dev"} 0.15523283333333332
# HELP otelcol_process_memory_rss Total physical memory (resident set size) [alpha]
# TYPE otelcol_process_memory_rss gauge
...
```

then changed it to:

```yaml
service:
  telemetry:
    metrics:
      level: none
```

```bash
curl localhost:8888/metrics
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Couldn't connect to server
```

The internal metrics are no longer collected.

**Comment by adriangb** [comment]
I'm still seeing:

```
StartTimestamp: 2025-03-04 16:24:01.754 +0000 UTC
Timestamp: 2025-03-04 16:24:01.754 +0000 UTC
Value: 0.000000
Metric #18
Descriptor:
     -> Name: scrape_duration_seconds
     -> Description: Duration of the scrape
     -> Unit: s
     -> DataType: Gauge
NumberDataPoints #0
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2025-03-04 16:24:01.754 +0000 UTC
Value: 0.001777
        {"otelcol.component.id": "debug", "otelcol.component.kind": "Exporter", "otelcol.signal": "metrics"}
```

With that in my config:

```yaml
receivers:
  otlp:
    protocols:
      http:
exporters:
  otlp/jaeger:
    endpoint: "https://jaeger-all-in-one:4317"
debug:
  verbose: basic
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug]
  telemetry:
    metrics:
      level: none
```

**Comment by iblancasa** [comment]
@adriangb remove the `debug` exporter.

**Comment by codeboten** [comment]
@adriangb the debug exporter would be emitting data received by the `otlp` receiver configured in the `traces` pipeline, is something else sending metrics over otlp to your collector? i've used the configuration you provided and i'm not seeing data emitted. 

note: the `debug` configuration needs to be updated from `verbose` to `verbosity`

**Comment by adriangb** [comment]
I think those logs are coming from internal telemetry given I see metrics with names like `otelcol_process_runtime_heap_alloc_bytes`.

I shouldn't have anything else sending metrics, but even if I add:

```yaml
    service:
      pipelines:
        metrics:
          receivers: []
          exporters: []
```

I still see stuff in stdoud logs.

Here's my full config by the way, I'm trying to get it working for a demo and just happened to notice the stdout log pollution making it hard to debug why my traces weren't making it to Jaeger:

<details>
  <summary>Example</summary>

  ```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-deploy
data:
  main.py: |
    # /// script
    # requires-python = ">=3.12"
    # dependencies = [
    #   "logfire==3.7.0",
    # ]
    # ///

    import time

    import logfire

    logfire.configure(send_to_logfire=False)

    x = 0
    while True:
        logfire.info(f'counter: {x}')
        x += 1
        time.sleep(1)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
        - name: test-deploy
          image: ghcr.io/astral-sh/uv:debian-slim
          command: ["uv"]
          args: ["run", "/test-deploy/main.py"]
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://otel-collector:4318/v1/traces"
            - name: LOGFIRE_SERVICE_NAME
              value: "test-deploy"
          volumeMounts:
            - name: test-deploy
              mountPath: /test-deploy
      volumes:
        - name: test-deploy
          configMap:
            name: test-deploy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
    exporters:
      otlp/jaeger:
        endpoint: jaeger-all-in-one:4317
        tls:
          insecure: true
    debug:
      verbosity: basic
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp/jaeger, debug]
        metrics:
          receivers: []
          exporters: []
      telemetry:
        metrics:
          level: none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:0.121.0
          volumeMounts:
            - name: otel-collector-config
              mountPath: /etc/otel-collector
      volumes:
        - name: otel-collector-config
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      name: otlp-http
      port: 4318
      targetPort: 4318
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-all-in-one
  template:
    metadata:
      labels:
        app: jaeger-all-in-one
    spec:
      containers:
        - name: jaeger-all-in-one
          image: jaegertracing/jaeger:2.3.0
          ports:
            - containerPort: 16686  # UI
            - containerPort: 4317   # OTLP gRPC
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-all-in-one
spec:
  selector:
    app: jaeger-all-in-one
  ports:
    - protocol: TCP
      name: otlp
      port: 4317
      targetPort: 4317
    - protocol: TCP
      name: ui
      port: 16686
      targetPort: 16686
  ```
</details>
