### ISSUE TITLE
Issue using environment variable for pipelines

### ISSUE THREAD

**Issue by kago-dk** [open-telemetry/opentelemetry-collector#10799]
**Describe the bug**
Environment variables used for pipelines are not processed correctly in 0.106.1, while they worked in 0.105.0. I have tried to put the value in double quotes and disable the confmap.strictlyTypedInput feature gate without success.

I a receiving an error instead.

When using confmap.strictlyTypedInput
failed to get config: cannot resolve the configuration: expanding ${env:OTEL_LOGS_RECEIVER}: retrieved value does not have unambiguous string representation: [filelog windowseventlog/application]

When using -confmap.strictlyTypedInput
failed to get config: cannot resolve the configuration: expanding ${env:OTEL_LOGS_RECEIVER}: expected convertable to string value type, got ["filelog" "windowseventlog/application"]([]interface {})

**What version did you use?**
0.106.1

**What config did you use?**
```
    logs:
      receivers: ${env:OTEL_LOGS_RECEIVER}
      processors: [memory_limiter,resourcedetection/system,resource/environment,transform,filter,batch]
      exporters: ${env:OTEL_LOGS_EXPORTER}
```

With [filelog,windowseventlog/application]  as the environment value for OTEL_LOGS_RECEIVER as an example.

**Environment**
Windows 2022 Server
