### ISSUE TITLE
[mdatagen] validateAttributes func should alos consider check attributes used in telemetry section

### ISSUE THREAD

**Issue by Frapschen** [open-telemetry/opentelemetry-collector#10925]
**Describe the bug**

The below metadata.yaml will encounter an error `unused attributes: [unused_attr used_attr]`:
```yaml
type: metricreceiver

sem_conv_version: 1.9.0

status:
  class: receiver
  stability:
    development: [logs]
    beta: [traces]
    stable: [metrics]

attributes:
  used_attr:
    description: Used attribute.
    type: string

  unused_attr:
    name_override: state
    description: Unused attribute.
    type: string

telemetry:
  metrics:
    test:
      enabled: true
      description: Metric.
      unit: "1"
      gauge:
        value_type: double
      attributes: [used_attr]
```

I believe the `used_attr` is already used in the telemetry section.
