### ISSUE TITLE
Logging Exporter doesn't log metrics details at 'debug' level

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#1107]
**Describe the bug**
The `loglevel: debug` config parameter currently doesn't have any effect on metric logging.

**Steps to reproduce**
Configure collector with any metric receiver (e.g. self-observability Prometheus endpoint) and a logging exporter, e.g.:
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: "test"
        scrape_interval: 60s
        static_configs:
        - targets: ["localhost:8888"]
exporters:
  logging:
    loglevel: debug
service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [logging]
```

**What did you expect to see?**
Detailed log messages with metric descriptor

**What did you see instead?**
Only information at the "info" level with a number of data points
```
2020-06-11T14:10:08.693+1000	INFO	loggingexporter/logging_exporter.go:169	MetricsExporter	{"#metrics": 4}
2020-06-11T14:11:08.693+1000	INFO	loggingexporter/logging_exporter.go:169	MetricsExporter	{"#metrics": 4}
```
