### ISSUE TITLE
Javascript: Collector Error: 14 UNAVAILABLE: DNS resolution failed 

### ISSUE THREAD

**Issue by davidwitten** [open-telemetry/opentelemetry-collector#1110]
If this issue would be more relevant in the opentelemetry-js repo, I would be happy to move it, but I don't think it's related to a Javascript-specific code issue. 

**Describe the bug**
When the [Node collector exporter](https://github.com/tinylox/opentelemetry-js/tree/master/packages/opentelemetry-exporter-collector/src/platform/node) attempts to export my traces from Node to the collector, I get this error:
```
[1] { Error: 14 UNAVAILABLE: DNS resolution failed
[1]     at Object.exports.createStatusError (/home/davidwitten_google_com/opentelemetry-testing/Supplier/node_modules/grpc/src/common.js:91:15)
[1]     at Object.onReceiveStatus (/home/davidwitten_google_com/opentelemetry-testing/Supplier/node_modules/grpc/src/client_interceptors.js:1209:28)
[1]     at InterceptingListener._callNext (/home/davidwitten_google_com/opentelemetry-testing/Supplier/node_modules/grpc/src/client_interceptors.js:568:42)
[1]     at InterceptingListener.onReceiveStatus (/home/davidwitten_google_com/opentelemetry-testing/Supplier/node_modules/grpc/src/client_interceptors.js:618:8)
[1]     at callback (/home/davidwitten_google_com/opentelemetry-testing/Supplier/node_modules/grpc/src/client_interceptors.js:847:24)
[1]   code: 14,
[1]   metadata: Metadata { _internal_repr: {}, flags: 0 },
[1]   details: 'DNS resolution failed' }
```

This only occurs in the Node version of the collector exporter ([code pointer of the error](https://github.com/open-telemetry/opentelemetry-js/blob/master/packages/opentelemetry-exporter-collector/src/platform/node/CollectorExporter.ts#L114)). The Node version uses gRPC, whereas the browser version (which I was able to successful set up) uses XHR. Do I need to make any changes in my config.yaml file to allow for gRPC?

**Steps to reproduce**
I essentially reused the JS code at the bottom of this [page](https://github.com/open-telemetry/opentelemetry-js/tree/master/packages/opentelemetry-exporter-collector). 

Additionally, I downloaded the collector with this command
`wget "https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/download/v0.3.0/otelcontribcol_linux_amd64"` and ran the collector using this command:
`./otelcontribcol_linux_amd64 --config config.yaml --new-metrics --legacy-metrics=false`

I have been running this on a Google Cloud VM Instance, so I think that may be relevant. 

**What did you expect to see?**
I expected the traces to appear on Google Cloud.

**What did you see instead?**
Every time the JS collector exporter attempted to export my traces, it returned that error.  

**What version did you use?**
I am using v0.3.0 of the OpenTelemetry Contrib Collector, because the Stackdriver exporter is only in the contrib not the main collector. 

**What config did you use?**
Here is a copy-paste of my config.yaml file:
```
receivers:
  otlp:
    endpoint: 0.0.0.0:55678
    cors_allowed_origins:
      - http://33.58.232.124:*
      - http://localhost:*

  opencensus:
    endpoint: 0.0.0.0:55671
    cors_allowed_origins:
      - http://33.58.232.124:*
      - http://localhost:*
exporters:
  stackdriver:
    project: "opentel-davidwitten-starter" 
service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp, opencensus]
      exporters: [stackdriver]
    metrics:
      receivers: [otlp, opencensus]
      exporters: [stackdriver]
```

**Environment**
OS: Debian GNU/Linux 9
I'm running this on a Google Cloud Virtual Machine.

**What I have tried so far**
- I tried sending an empty object
- I tried using valid credentials and insecure credentials
