### ISSUE TITLE
[announcement] logging exporter has been replaced with debug exporter

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#11337]
On v0.111.0, the [`logging` exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/v0.110.0/exporter/loggingexporter) has been removed in favor of the [`debug` exporter](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/debugexporter). The `logging` exporter last version will be v0.110.0 and it will be removed in all officially released distros.

Starting on v0.111.0, you need to replace all your instances of the `logging` exporter by the `debug` exporter. For example, if not using any specific settings you can switch as follows:

<table>
<tr>
<td> Before </td> <td> After </td>
</tr>
<tr>
<td valign="top">

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
```

</td><td valign="top">

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
```
</tr></table>

You may also need to update your OpenTelemetry Collector Builder manifest to include the debug exporter instead of the logging exporter when bumping the version of components.

Both exporters support the `verbosity` option and have the same behavior. The `debug` exporter does not support the `logging` exporter's `loglevel` option. The following table summarizes how to translate from one to the other:

| **`loglevel` value** | **Equivalent `verbosity` level** |
|----------------------|----------------------------------|
| `debug`              | `detailed`                       |
| `info`               | `normal`                         |
| `warn`               | `basic`                          |
| `error`              | `basic`                          |
| `dpanic`             | `basic`                          |
| `panic`              | `basic`                          |
| `fatal`              | `basic`                          |

The `debug` exporter is available since v0.86.0 and you can migrate to it before upgrading to v0.111.0. If you find any trouble with the migration, please comment below!
