### ISSUE TITLE
Auto-instrumented pipeline components

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector#11343]
**Is your feature request related to a problem? Please describe.**

The collector's components should be observable. Intuitively, to some extent there must be some instrumentation which can be applied to components in a universal and uniform way.

Goals of this proposal:
1. Articulate a mechanism which enables us to _automatically_ capture signals from _all pipeline components_.
2. Define attributes that are (a) specific enough to describe individual component [_instances_](https://github.com/open-telemetry/opentelemetry-collector/issues/10534) and (b) consistent enough for correlation across signals.
3. Define specific metrics for each kind of pipeline component.
4. Define specific logs for each kind of pipeline component.
5. Define specific spans for processors and connectors.

**Describe the solution you'd like**

### Mechanism

The mechanism of telemetry capture should be _external_ to components. Specifically, we should inject instrumentation at each point where a component passes data to another component, and, at each point where a component consumes data from another component. In terms of the component graph, this means that every _edge_ in the graph will have two layers of instrumentation - one for the producing component and one for the consuming component. Generally these layers will act independently (e.g. record a metric about the data coming out of a receiver), but in the case of processors and connectors, their adjacent layers can act in concert (e.g. record the start and end of a span).

###

Attributes are discussed in detail in https://github.com/open-telemetry/opentelemetry-collector/issues/11179, though only in the context of metrics. To restate the consensus from that issue, all signals should use the following attributes:

#### Receivers

- `receiver`: The component ID
- `otel.signal`: `logs`, `metrics`, `traces`, **OR `ALL`**

#### Processors

- `processor`: The component ID
- `otel.signal`: `logs`, `metrics`, `traces`, **OR `ALL`**
- `pipeline`: The pipeline ID, **OR `ALL`**

#### Exporters

- `exporter`: The component ID
- `otel.signal`: `logs`, `metrics` `traces`, **OR `ALL`**

#### Connectors

- `connector`: The component ID
- `otel.signal`: `logs->logs`, `logs->metrics`, `logs->traces`, `metrics->logs`, `metrics->metrics`, etc, **OR `ALL`**

Notes: The use of `ALL` is based on the assumption that components are instanced either in the default way, or as a single instance per configuration (e.g. otlp receiver).

### Metrics

There are two straightforward measurements that can be made on any pdata:
1. A count of "items" (spans, data points, or log records). These are low cost but broadly useful, so they should be enabled by default.
2. A measure of size, based on [ProtoMarshaler.Sizer()](https://github.com/open-telemetry/opentelemetry-collector/blob/9907ba50df0d5853c34d2962cf21da42e15a560d/pdata/ptrace/pb.go#L11). These are high cost to compute, so by default they should be disabled (and not calculated).

The location of these measurements can be described in terms of whether the data is "incoming" or "outgoing". 
1. Incoming measurements are attributed to the component which is _consuming_ the data.
2. Outgoing measurements are attributed to the component which is _producing_ the data.

An `outcome` attribute with possible values `success` and `failure` should be automatically recorded, corresponding to whether or not the function call returned an error.

Finally, the kind of component being described should be captured _as an attribute_, since other aspects of the metrics are generally the same (except instance-specific attributes).

With all of the above in mind, the following metrics should be captured:

```yaml
    otelcol_component_incoming_items:
      enabled: true
      description: Number of items passed to the component.
      unit: "{items}"
      sum:
        value_type: int
        monotonic: true
    otelcol_component_outgoing_items:
      enabled: true
      description: Number of items emitted from the component.
      unit: "{items}"
      sum:
        value_type: int
        monotonic: true

    otelcol_component_incoming_size:
      enabled: false
      description: Size of items passed to the component.
      unit: "By"
      sum:
        value_type: int
        monotonic: true
    otelcol_component_outgoing_size:
      enabled: false
      description: Size of items emitted from the component.
      unit: "By"
      sum:
        value_type: int
        monotonic: true
```

### Spans

When adding instrumentation layers to processors and connectors, we should be able to record the start and end of a span.

### Logs

Metrics and spans add a lot of observability, but there are some gaps which logs can fill. For example, we can record spans for processors and connectors but logs are sufficient for capturing precise timing as it relates to data produced by receivers and consumed by exporters. Additionally, although metrics would describe the overall item counts, it may be helpful to record more granular events. e.g. If an outgoing batch of 10,000 spans results in an error, but 100 batches of 100 spans do not, this may be a matter of batch size that can be detected by analyzing logs, while the corresponding metric reports only that a 50% success rate is observed. 

For security and performance reasons, I do not believe in any case it would be appropriate to log the contents of telemetry. 

We should also consider that it's very easy for logs to become too noisy. Even if errors are occurring frequently, they may only be of interest to many users if they are not handled automatically.

With the above considerations, I propose only that we add a DEBUG log for each individual outcome. This should be sufficient for detailed troubleshooting but does not impact users otherwise.

In the future, it may be helpful to define triggers for reporting repeated failures at a higher severity level. e.g. N number of failures in a row, or a moving average success %. For now, the criteria and necessary configurability is unclear to me so I mention this only as an example of future possibilities.

**Additional context**

This proposal pulls from a number of smaller scoped issues and PRs:
- https://github.com/open-telemetry/opentelemetry-collector/pull/11311
- https://github.com/open-telemetry/opentelemetry-collector/issues/11179
- https://github.com/open-telemetry/opentelemetry-collector/issues/10708
