### ISSUE TITLE
Help: How can I hide/disable some INFO logs? The custom collector.yaml config didn't work

### ISSUE THREAD

**Issue by thiagosanches** [open-telemetry/opentelemetry-collector#11471]
Hi everyone, I'm trying to suppress or disable certain OpenTelemetry logs, or ideally all of them if possible. While I understand their usefulness, they're currently generating excessive noise that's not beneficial to us at the moment.

I've been experimenting locally and was able to configure the opentelemetry-demo Docker sample to only log errors. As shown below, I'm now only seeing error-level logs.

![image](https://github.com/user-attachments/assets/6c166795-8a10-4692-8e7b-7ab324786563)

I've used the following config:

![image](https://github.com/user-attachments/assets/37f408c6-8961-49cf-a973-d2f2c3d79da0)

However, I'm looking to replicate this behavior on AWS Lambdas using the Node.js runtime. To achieve this, I've made the following changes to my application:

- Added a `collector.yaml` file to the root folder of the application, copying the official default configuration and modifying it to set `telemetry.log.level` to `error`.

```yaml
# collector.yaml in the root directory
# Set an environment variable 'OPENTELEMETRY_COLLECTOR_CONFIG_FILE' to '/var/task/collector.yaml'
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"
exporters:
  logging:
  awsxray:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [awsxray]
    metrics:
      receivers: [otlp]
      exporters: [logging]
  telemetry:
    logs:
      level: error
    metrics:
      address: localhost:8888
      level: error
```

- Added the following environment variables to my lambda:

```
AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
OPENTELEMETRY_COLLECTOR_CONFIG_FILE: /var/task/collector.yaml
```

I can see that the file was successfully picked up by OTEL:
![image](https://github.com/user-attachments/assets/94d8c260-8d12-4fb6-a2f8-8298e9e86c07)

However, the info logs are still being generated.

![image](https://github.com/user-attachments/assets/753f074d-f8fd-4ba9-8be8-cf8af62b106f)

I'm using the following lambda layer:
![image](https://github.com/user-attachments/assets/b5cfeed3-a0c2-4319-b3e2-ab4854813298)
`arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-arm64-ver-1-18-1:4`.

Do we have any way to hide them? Or am I missing something that I over looked at the documentation?
