### ISSUE TITLE
Metric otelcol_receiver_accepted_log_records does not show the full load

### ISSUE THREAD

**Issue by makrushin-evgenii** [open-telemetry/opentelemetry-collector#11526]
**Describe the bug**
Metric `otelcol_receiver_accepted_log_records` does not show the full load. With actual load 100k/1m log records per second show only 70k

**Steps to reproduce**
I added linearly increasing load up to 100k logs records per second. Then constant 1m records per second. In both cases rate on the panel did not exceed 70k

_I used internal tool for testing with loads over 10k log records per second, so there is no point in sharing the code_

<img width="2139" alt="image" src="https://github.com/user-attachments/assets/853a2639-efe5-43c4-8d92-f224af090426">

I tried to load collector with constant 5k and 10k RPS. Load code:
```csharp
// <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.9.0" />
// <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
// <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />

using Microsoft.Extensions.Logging;
using OpenTelemetry.Exporter;
using OpenTelemetry.Logs;


using var loggerFactory = LoggerFactory.Create(builder => builder
    .AddOpenTelemetry(options => options
        .AddOtlpExporter(exporterOptions =>
        {
            exporterOptions.HttpClientFactory = () => new HttpClientDecorator();
            exporterOptions.Endpoint = new Uri("https://.../v1/logs");
            exporterOptions.Protocol = OtlpExportProtocol.HttpProtobuf;
        })
    )
);

var logger = loggerFactory.CreateLogger<Program>();

long index = 0;
for (var i = 0; i < 2 * 60; i++)
{
    const int rps = 10_000;
    for (var j = 0; j < rps; j++)
        logger.LogInformation(string.Format("test: {0}", index++));
    Console.WriteLine($"{DateTime.Now:T} sent {rps} log messages");
    Thread.Sleep(1 * 1000);
}

internal class HttpClientDecorator: HttpClient
{
    public override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        Console.WriteLine(request);
        var response = base.Send(request, cancellationToken);
        Console.WriteLine($"{DateTime.Now:T} Response: {response.StatusCode}");
        return response;
    }
}
```
I was convinced by the logs of this script that it generates the specified load (`rps` variable). The `HttpClientDecorator` received only successfull codes (`200 OK`). Also, I used `debugexporter` to make sure that all sent records have been processed. And in this cases rate on the panel did not exceed 2.5k:
![image](https://github.com/user-attachments/assets/ad8776a1-2010-4b58-b1f8-5c3b19bd7d9f)

**What did you expect to see?**

I expect `otelcol_receiver_accepted_log_records` metric counts the number of records processed: `0` on start, `X` after processed `X` records

**What did you see instead?**

The metric increases less than the number of records processed

**What version did you use?**

Chart `open-telemetry/opentelemetry-collector:0.107.0`, image `otel/opentelemetry-collector-contrib:0.110.0`

**What config did you use?**

```yaml
mode: deployment

image:
  repository: "otel/opentelemetry-collector-contrib"
command:
  name: "otelcol-contrib"

serviceAccount:
  create: false
  name: ...

service:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8888'

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

resources:
  requests:
    cpu: 300m
    memory: 300Mi
  limits:
    cpu: 300m
    memory: 300Mi
replicaCount: 1


config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
  exporters:
    debug:
      verbosity: normal # basic - normal - detailed
    kafka:
      protocol_version: '2.8.0'
      brokers:
        - vm-hercules01:9092
        - vm-hercules02:9092
        - vm-hercules03:9092
      topic: 0_otlp_logs_test
      encoding: otlp_proto
      producer:
        compression: zstd
  service:
    pipelines:
      logs:
        receivers:
          - otlp
        exporters:
          - kafka
          - debug
      metrics: null
      traces: null
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
        level: detailed

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/enable-opentelemetry: 'false'
  hosts:
    - host: ...
      paths:
        - path: /
          pathType: Prefix
          port: 4317
  additionalIngresses:
   - name: http
     hosts:
       - host: ...
         paths:
           - path: /
             pathType: Prefix
             port: 4318
```

**Environment**

Kubernetes 1.27

**Additional context**

1. When running the load code locally (code I shared) and in one cluster zone with a collector (code I didnt share), the boundaries of metric are different: 2.4k and 70k
2. With small loads (<2.5k records per second) metric show correct values
3. [I use this dashboard for monitoring](https://grafana.com/grafana/dashboards/15983-opentelemetry-collector/)
