### ISSUE TITLE
use otlp push metric message to collector,  message is that grpc: error unmarshalling request: proto: wrong wireType = 2 for field Temporality

### ISSUE THREAD

**Issue by gunsluo** [open-telemetry/opentelemetry-collector#1154]
**Describe the bug**
I use the following example to send metric messages to opentelemetry collector server. 
https://github.com/open-telemetry/opentelemetry-go/blob/master/example/otlp/main.go

and then get some error message

```
Metrics Accumulator error: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field Temporality
```

**Steps to reproduce**
https://github.com/open-telemetry/opentelemetry-go/tree/master/example/otlp#otlp-example

Follow the above document to configure and run the program.

**What did you expect to see?**

**What did you see instead?**
error message is `Metrics Accumulator error: rpc error: code = Internal desc = grpc: error unmarshalling request: proto: wrong wireType = 2 for field Temporality`

**What version did you use?**
version: v0.4.0
docker image I used is `otel/opentelemetry-collector-contrib:0.4.0`

**What config did you use?**
```
extensions:
  health_check:

receivers:
  otlp:
    endpoint: 0.0.0.0:55680

processors:
  batch:
  queued_retry:

exporters:
  logging:
      loglevel: debug

  jaeger:
      endpoint: jaeger-all-in-one:14250
      insecure: true

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger]

    metrics:
      receivers: [otlp]
      exporters: [logging]

  extensions: [health_check]
```

**Environment**
OS:  macos 10.15.4

**Additional context**

The reason for the problem is that the client and server use different `pb.go` generation files.

grpc server of the collector(v0.4.0)  use this file  `https://github.com/open-telemetry/opentelemetry-collector/blob/v0.4.0/internal/data/opentelemetry-proto-gen/collector/metrics/v1/metrics_service.pb.go`

grpc client() use the file `https://github.com/open-telemetry/opentelemetry-proto/blob/v0.3.0/gen/go/collector/metrics/v1/metrics_service.pb.go`

**Incompatible pb files are the cause of the problem.**
