### ISSUE TITLE
jaeger exporter missing critical data

### ISSUE THREAD

**Issue by nicks** [open-telemetry/opentelemetry-collector#1160]
**Describe the bug**
I'm playing around with setting up opentelemetry with Jaeger for the first time, and Jaeger is spewing errors. They look like this:

> {"level":"error","ts":1592618224.399752,"caller":"app/span_processor.go:138","msg":"process is empty for the span","stacktrace":"github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:138\ngithub.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:35\ngithub.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:175\ngithub.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1\n\tgithub.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:75\ngithub.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1\n\tgithub.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:77"}

**Steps to reproduce**

I'm using:
- opentelemetry-go with the otlp exporter
- an opentelemetry-collector server that receives otlp and exports to jaeger
- a jaeger server

I have a pretty good isolated repro that I can create a repo for, if that would be helpful. It basically just uses the off-the-shelf docker containers for opentelemetry-collector and jaeger, plus the sample code for opentelemetry-go

**What did you expect to see?**
No error

**What did you see instead?**
The error above

**What version did you use?**

> docker run --rm --env JAEGER_REPORTER_LOG_SPANS=true  --network=host -v "${PWD}/otel-config.yaml":/otel-config.yaml --name otelcol otel/opentelemetry-collector --config otel-config.yaml

**What config did you use?**

```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    endpoint: "0.0.0.0:55680"
    
processors:
  batch:
  queued_retry:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: "localhost:14250"
    insecure: true

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [jaeger, logging]
```

**Environment**
docker

**Additional context**
I also filed this bug upstream against Jaeger
https://github.com/jaegertracing/jaeger/issues/2300
They believe that opentelemetry is missing critical data here
