### ISSUE TITLE
Limit the log.level in OTel to only error, debug, or information

### ISSUE THREAD

**Issue by divyap15** [open-telemetry/opentelemetry-collector#11614]
I need to configure my OTel YAML file to send only error logs to Datadog. I've tried all the available options but haven't had success. Could someone help me set it up correctly?

**Comment by dmathieu** [comment]
The filter processor would be what you're looking for.
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor

This is untested, but the following should allow you to do what you're looking for:

```yaml
processors:
  filter/ottl:
    error_mode: ignore
    logs:
      log_record:
        - 'severity_number < 17'
```

I'm closing this issue, as this is not a bug report.
