### ISSUE TITLE
Collector not working over https with receiver http endpoint set to localhost:4318 and tls enabled - works well with 0.0.0.0:4318

### ISSUE THREAD

**Issue by alxivanov** [open-telemetry/opentelemetry-collector#11757]
The collector is set up with tls configuration. Agent call results in tls handshake failure.

**/var/lib/opentelemetry/.config/containers/systemd/opentelemetry.container**
```
[Unit]
Description=opentelemetry container
After=network-online.target
Wants=network-online.target

[Install]
WantedBy=default.target

[Container]
Image=otel/opentelemetry-collector:latest
ContainerName=opentelemetry
Network=slirp4netns:port_handler=slirp4netns
PublishPort=127.0.0.1:4317:4317/tcp
PublishPort=127.0.0.1:4318:4318/tcp
User=501
Volume=/var/lib/opentelemetry/otel-collector-config.yaml:/etc/otelcol/config.yaml:U,Z
Volume=/var/lib/opentelemetry/certs/mycert.crt:/etc/otelcol/server.pem:U,Z
Volume=/var/lib/opentelemetry/certs/mykey.key:/etc/otelcol/server-key.pem:U,Z
Volume=/var/lib/opentelemetry/certs/ca-bundle.pem:/etc/otelcol/ca-bundle.pem:U,Z
[Service]
Restart=always
TimeoutStartSec=900
```

**netstat -tulpen**
```
tcp        0      0 127.0.0.1:4317            0.0.0.0:*               LISTEN      501        1683366    124508/slirp4netns
tcp        0      0 127.0.0.1:4318            0.0.0.0:*               LISTEN      501        1683369    124508/slirp4netns
```

**/var/lib/opentelemetry/otel-collector-config.yaml** (receivers part only)
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
        tls:
          ca_file: /etc/otelcol/ca-bundle.pem
          cert_file: /etc/otelcol/server.pem
          key_file: /etc/otelcol/server-key.pem
      http:
        endpoint: localhost:4318
        tls:
          ca_file: /etc/otelcol/ca-bundle.pem
          cert_file: /etc/otelcol/server.pem
          key_file: /etc/otelcol/server-key.pem
```

**/etc/hosts**
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
...
```

This setup is working fine if `endpoint: localhost:4318` is changed to `endpoint: 0.0.0.0:4318` and `PublishPort` set to `4318:4318/tcp`
