### ISSUE TITLE
[mdatagen] `telemetry` codegen outputs illegal Go files

### ISSUE THREAD

**Issue by diurnalist** [open-telemetry/opentelemetry-collector#11761]
**Describe the bug**

When using the `telemetry` config section, mdatagen outputs code that does not compile due to missing or extra imports.

**Steps to reproduce**

Run `mdatagen` on any module that defines an internal telemetry config section.

**What version did you use?**

0.114.0

**What config did you use?**
```yaml
telemetry:
  metrics:
    batch_size_trigger_send:
      enabled: true
      stability:
        level: deprecated
        from: v0.110.0
      description: Number of times the batch was sent due to a size trigger
      unit: "{times}"
      sum:
        value_type: int
        monotonic: true
    request_duration:
      enabled: true
      stability:
        level: alpha
      description: Duration of request
      unit: s
      histogram:
        value_type: double
        bucket_boundaries: [1, 10, 100]
    process_runtime_total_alloc_bytes:
      enabled: true
      stability:
        level: stable
      description: Cumulative bytes allocated for heap objects (see 'go doc runtime.MemStats.TotalAlloc')
      unit: By
      sum:
        async: true
        value_type: int
        monotonic: true
    queue_length:
      enabled: true
      description: This metric is optional and therefore not initialized in NewTelemetryBuilder.
      extended_documentation: For example this metric only exists if feature A is enabled.
      unit: "{items}"
      optional: true
      gauge:
        async: true
        value_type: int
```
