### ISSUE TITLE
Authentication handshake failed: credentials: cannot check peer: missing selected ALPN property       {"grpc_log": true}

### ISSUE THREAD

**Issue by MugenTwo** [open-telemetry/opentelemetry-collector#11838]
**Describe the bug**
I am getting the following message when I start OTEL with Grafana cloud.

Grafana gave me a link:
https://otlp-gateway-prod-REGION.grafana.net/otlp

**Steps to reproduce**

My config.yaml is:

```
receivers:
  otlp:
    protocols:
      http: {}

exporters:
  otlp:
    endpoint: otlp-gateway-prod-<REGION>.grafana.net:443
    headers:
      Authorization: "Bearer <TOKEN>"
    compression: "gzip"
    tls:
      insecure: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
```

And I run with the docker container:
```
docker run \                
  -p 127.0.0.1:4317:4317 \
  -p 127.0.0.1:4318:4318 \
  -p 127.0.0.1:55679:55679 \
  -v /Users/<ME>/Documents/project/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml \
  otel/opentelemetry-collector-contrib:0.115.1 \
  2>&1 | tee collector-output.txt
```

**What did you expect to see?**
No, errors from the logs in the docker container

**What did you see instead?**
I saw a lot of 
Err: connection error: desc = "transport: authentication handshake failed: credentials: cannot check peer: missing selected ALPN property"       {"grpc_log": true}

**What version did you use?**
0.115.1

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      http: {}

exporters:
  otlp:
    endpoint: otlp-gateway-prod-<REGION>.grafana.net:443
    headers:
      Authorization: "Bearer <TOKEN>"
    compression: "gzip"
    tls:
      insecure: false

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
```

**Environment**
Docker

**Additional context**
N/A
