### ISSUE TITLE
Using Unix socket for internal telemetry metrics

### ISSUE THREAD

**Issue by avinovarov** [open-telemetry/opentelemetry-collector#11941]
**Describe the bug**
When OTel Collector is run We use Unix socket

**Steps to reproduce**
In internal telemetry config, try to use `unix:otlp.sock` instead of URI in `config.service.telemetry.metrics.readers[periodic].exporters.otlp.endpoint`

**What did you expect to see?**
Unix socket recognized properly as internal telemetry endpoint, internal telemetry metrics are being sent to Unix socket in the same way app container in the same pod does.

**What did you see instead?**
Pod fails to start, sidecar OTel Collector container logs error:
```
2024/12/17 09:29:01 collector server run finished with error: failed to create metric provider: parse "http://unix:otlp.sock": invalid port ":otlp.sock" after host
```

**What version did you use?**
We run OTel Collectors in our k8s clusters, installed as Helm charts.
Chart version: `opentelemetry-operator:0.74.3`
OTel image version override: `0.115.1` (tried on `0.114.0` too)

**What config did you use?**
```
  config:
    service:
      telemetry:
        metrics:
          level: detailed
          readers:
            - periodic:
                interval: 10000
                exporter:
                  otlp:
                    protocol: grpc/protobuf
                    endpoint: unix:otlp.sock # <- only network URI is being accepted due to address:port validation
```

**Environment**
 All workloads are run in Azure k8s/AKS v1.30

**Additional context**
It looks like the error hints on what's happening:
```
2024/12/17 09:29:01 collector server run finished with error: failed to create metric provider: parse "http://unix:otlp.sock": invalid port ":otlp.sock" after host
```
Instead of accepting the connection string the way it is, the validation adds `http://` to the beginning of the string, and considers everything after colon as the port, like `:<port_expected>`.

OTel Collector [OTLP exporter documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md#getting-started) refers to the [gRPC name resolution specification](https://github.com/grpc/grpc/blob/master/doc/naming.md) which should allow unix sockets in `unix:socket` syntax, so this extra connection string validation looks excessive and actually breaks the usage of unix sockets.
