### ISSUE TITLE
Mismatch in resource attributes between metrics and everything else

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector#12021]
**Describe the bug**
When setting up the collector's self-telemetry, I found that metrics emit different resource attributes than the other signals.

**Steps to reproduce**
1. download a collector v0.116.0 binary
2. run the config provided
3. grep for `service.instance.id` in the outputs to discover differing IDs

**What did you expect to see?**
A single and consistent service.instance.id in self-telemetry

**What did you see instead?**

logs service.instance.id: ca53d844-128d-4358-8978-8702c6bf3aad
traces service.instance.id: ca53d844-128d-4358-8978-8702c6bf3aad
opamp service.instance.id: ca53d844-128d-4358-8978-8702c6bf3aad
metrics service.instance.id: d768bfb1-6707-4b57-a96a-c89da7255388

**What version did you use?**
v0.116.0

**What config did you use?**

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://localhost:4318/
    # push own metrics to the internal_metrics receiver
    traces:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: grpc/protobuf
                endpoint: http://localhost:4317/
    metrics:
      level: detailed
      readers:
        - periodic:
            interval: 30000
            exporter:
              otlp:
                protocol: grpc/protobuf
                endpoint: localhost:4317
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```

**Environment**
Mac OS 15.1

**Additional context**
