### ISSUE TITLE
How to add resource attributes to internal telemetry

### ISSUE THREAD

**Issue by nityanandagohain** [open-telemetry/opentelemetry-collector#12040]
I want to add resource attributes like `k8s.pod.name` etc to the internal telemetry, what is the best way to do it ?

```yaml
service:
  telemetry:
    metrics:
      level: detailed
      readers:
        - periodic:
            interval: 30000
            exporter:
              otlp:
                protocol: grpc/protobuf
                endpoint: host:4317
 ```
