### ISSUE TITLE
Otel stops scrapping or doesn't scrap a few of the metrics

### ISSUE THREAD

**Issue by gaur-piyush** [open-telemetry/opentelemetry-collector#12123]
Hi Team,

We're using google cloud exporter with our Otel configuration. However, we have seen that Otel collector doesn't scrape all the metrics. Can you help us identify the problem? From the configuration endpoint, I couldn't find an issue.

Attached is the configuration currently in use.

Regards,
Piyush Gaur

[values.txt](https://github.com/user-attachments/files/18473180/values.txt)

**Comment by mattsains** [comment]
I would recommend trying to pare this config down to a minimal working example - remove all the unnecessary components and config and try to reproduce the problem that way.

For example, I noticed that you have a filter like this:

```
        filter/cv:
            metrics:
                include:
                    match_type: strict
                    metric_names:
                        - LIST_OF_METRICS
```

Do you think that could be the cause of the missing metrics?
