### ISSUE TITLE
[OCB] Ensure unique aliases for packages with same suffix

### ISSUE THREAD

**Issue by mackjmr** [open-telemetry/opentelemetry-collector#12162]
**Describe the bug**
When two packages have the same suffix, this leads to OCB using the same alias, which breaks the build.

**Steps to reproduce**
`builder-config.yaml`
```
extensions:
- gomod: extension01/impl v0.61.0
  path: ../extension01/impl
- gomod: extension02/impl v0.61.0
  path: ../extension02/impl
```

Resulting `components.go`:
```
package main

import (
	impl "extension01/impl "
	impl "extension02/impl"
)

...

func components() (otelcol.Factories, error) {
	factories.Extensions, err = extension.MakeFactoryMap(
		impl.NewFactory(),
		impl.NewFactory(),
	)
...
	factories.ExtensionModules[impl.NewFactory().Type()] = "extension01/impl v0.61.0"
	factories.ExtensionModules[impl.NewFactory().Type()] = "extension02/impl v0.61.0"
...
}
```

**What did you expect to see?**
Unique aliases
