### ISSUE TITLE
Fix README of Zipkin exporter 

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector#1220]
**Describe the bug**
Zipkin exporter's [README](https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/zipkinexporter/README.md) still refers to `url` as the setting key instead of `endpoint`. Think that is what is being used per sample configurations example presented [here](https://github.com/open-telemetry/opentelemetry-collector/blob/master/exporter/zipkinexporter/testdata/config.yaml)

**Steps to reproduce**
using this configuration with latest opentelemetry-collector will throw an error 

```
receivers:
  otlp:

exporters:
  zipkin:
    url: "http://zipkin:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
```

```
otel-collector    | {"level":"info","ts":1593243690.1561713,"caller":"service/service.go:293","msg":"Loading configuration..."}
otel-collector    | Error: cannot load configuration: error reading settings for exporter type "zipkin": 1 error(s) decoding:
otel-collector    | 
otel-collector    | * '' has invalid keys: url
otel-collector    | 2020/06/27 07:41:30 application run finished with error: %v: cannot load configuration: error reading settings for exporter type "zipkin": 1 error(s) decoding:
otel-collector    | 
otel-collector    | * '' has invalid keys: url
```
using `endpoint` instead of `url` works fine.

**What did you expect to see?**
README.md should have proper key updated 

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**Environment**
OS: alpine linux (docker container)
Compiler(if manually compiled): (e.g., "go 14.2")
