### ISSUE TITLE
Otlp exporter - received message after decompression larger than max (4194305 vs. 4194304)

### ISSUE THREAD

**Issue by teyyubismayil** [open-telemetry/opentelemetry-collector#12219]
**Describe the bug**
We are sending traces from opentelemetry collector to tempo. We are getting randomly following error logs. What is suspicious is that failing size is always 4194305 (which is default grpc limit + 1). `dropped_items` count varies from about 2000 to 8196 (which is max batch size set in batch processor).

`error	internal/queue_sender.go:92	Exporting failed. Dropping data.	{"kind": "exporter", "data_type": "traces", "name": "otlp/tempo", "error": "not retryable error: Permanent error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max (4194305 vs. 4194304)", "dropped_items": 3847}`

**What version did you use?**
0.113.0

**What config did you use?**
```
exporters:
  otlp/tempo:
    endpoint: "tempo-distributor.tempo:4317"
    headers:
      X-Scope-OrgID: "..."
    tls:
      insecure: true
processors:
  tail_sampling:
    num_traces: 500000
    policies:
      [
....
      ]
  batch:
    send_batch_size: 4096
    timeout: 200ms
    send_batch_max_size: 8196
  memory_limiter:
    check_interval: 1s
    limit_mib: 3800
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - tail_sampling
        - batch
      exporters:
        - otlp/tempo
```

**Environment**
Kubernetes

**Comment by codeboten** [comment]
The destination is rejecting the data because of the payload size. I'm not sure what is being reported as a bug here.

**Comment by sfc-gh-akrishnan** [comment]
> Can try add some info on this since we are facing similar issue. What is strange here is that we have hundreds failed attempts and all them have the same 1 byte difference (4194305 vs. 4194304). What we observed before, that the size of failed send data would always differer in logs across time and cluster and usually somewhat higher than +1. In this case we have 2 different clusters and the only and the same "send vs limit" 4194305 vs. 4194304 all the time in logs, which looks bit suspicious. Could also be that some of our agents that sends data is misconfigured by sending +1 byte more, but we use the defaults autoinstrumentation for our applications. So this might be not the issue of opentelemetry-collector, but some OTEL Instrumentation default setups.

We are hitting the same issue as well. Were you able to debug this issue any further?

**Comment by sfc-gh-sili** [comment]
Hi Teyyub, thanks for putting this together.

```
batch:
    send_batch_size: 4096
    timeout: 200ms
    send_batch_max_size: 8196
```

This configuration ensures that each batch contains no more than 8,196 log records, but it does not enforce an upper limit on the total serialized byte size of a batch.

We are actively working on supporting byte-size-based batching, and you can find more details and ongoing discussions in [opentelemetry-collector#3262](https://github.com/open-telemetry/opentelemetry-collector/issues/3262).

**Comment by athifsha** [comment]
otelcol.processor.batch "default" {
  send_batch_size = 2000      
  send_batch_max_size = 6000   
  timeout = "200ms"    

  output {
    traces = [otelcol.exporter.otlp.grafana_cloud_traces.input]
  }
}


send_batch_max_size: Set to 6000 to enforce a maximum batch size that aligns with the  server limit 

send_batch_size: Reduced to 2000 to trigger more frequent flushing before reaching the maximum limit

timeout: Kept at default 200ms to ensure timely flushing even if batch doesn't reach size limits

**Comment by athifsha** [comment]
If u face this issue in grafana alloy collector use the config below 

otelcol.processor.batch "default" {
	send_batch_size     = 4000
	send_batch_max_size = 8196
	timeout             = "200ms"

	output {
		traces = [otelcol.exporter.otlp.grafana_cloud_traces.input]
	}
}

refer for more info : https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.processor.batch/#arguments

**Comment by Sithembiso-Mashinini** [comment]
Configure the tempo distributor receiver with the following configuration:
```yaml
distributor:
  receivers:
    otlp:
      grpc:
        max_recv_msg_size_mib: <size>
```
-  https://grafana.com/docs/tempo/latest/troubleshooting/querying/response-too-large/#ingestion
