### ISSUE TITLE
regression in service telemetry metrics configuration

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#12254]
The following configuration causes errors in the current version in main:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:5317
      http:
        endpoint: localhost:5318

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    metrics:
      level: detailed
      readers:
        - periodic:
            interval: 10000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: localhost:4318
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug]
```

With this config, if I wait a few seconds, I get this error message (no need to send any telemetry):

```
2025/02/03 10:13:45 failed to upload metrics: Post "https:///v1/metrics": http: no Host in request URL
```

_Originally posted by @mx-psi in https://github.com/open-telemetry/opentelemetry-collector/issues/12252#issuecomment-2630401591_
