### ISSUE TITLE
Getting {"partialSuccess":{}} for OpenTelemetry Collector when cURL POST HTTP payload for metrics endpoint

### ISSUE THREAD

**Issue by developer1622** [open-telemetry/opentelemetry-collector#12325]
### Component(s)

receiver/otlp

### What happened?

**Describe the bug**
I have installed OpenTelemetry Collector binary for my WSL2 Ubuntu and it is installed properly, with the below provided configuration, I tried posting  the JSON payload using cURL request, however cURL throwing : **{"partialSuccess":{}}**

**Steps to reproduce**
I have attached OTel configuration I have used below fields, and just running binary with it.

**What did you expect to see?**
Although I have got 200, I was expecting success message.

**What did you see instead?**
Got **{"partialSuccess":{}}**

### Collector version

0.119.0

## Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.5 LTS"

Linux LAPTOP-XXXXXX 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 G

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: debug
      development: true
      sampling:
        initial: 10
        thereafter: 5
      output_paths:
        - stdout
      error_output_paths:
        - stderr
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```

### Log output

```shell
{"partialSuccess":{}}
```

### Additional context

Hi Team,

I am unsure if this is bug or not, I can see the posted metric as log where I am running this binary, just wanted to confirm if this expected output. Thank you.
