### ISSUE TITLE
Breaking change: periodic exporter otlp.protocol

### ISSUE THREAD

**Issue by joschi** [open-telemetry/opentelemetry-collector#12332]
### Component(s)

service

### What happened?

**Describe the bug**

The upgrade to [`go.opentelemetry.io/contrib/config/v0.3.0`](https://pkg.go.dev/go.opentelemetry.io/contrib/config@v0.14.0/v0.3.0) in https://github.com/open-telemetry/opentelemetry-collector/pull/11611 broke backward-compatibility for the `protocol` field in the [`OTLP` type](https://pkg.go.dev/go.opentelemetry.io/contrib/config@v0.14.0/v0.3.0#OTLP).

Using OpenTelemetry Collector 0.118.0, this was a valid configuration but breaks with OpenTelemetry Collector 0.119.0:
```yaml
service:
  telemetry:
    metrics:
      readers:
      - periodic:
          exporter:
            otlp:
              protocol: grpc/protobuf
```

The breaking change was introduced in [opentelemetry-go-contrib v1.33.0](https://github.com/open-telemetry/opentelemetry-go-contrib/releases/tag/v1.33.0) with https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6338.

**What did you expect to see?**

Successful startup of OpenTelemetry Collector with the configuration which was working with OpenTelemetry Collector 0.118.0.

**What did you see instead?**

```
opentelemetry-collector 2025/02/10 16:11:23 collector server run finished with error: failed to create SDK: unsupported protocol "grpc/protobuf"
```

### Collector version

v0.119.0

## Environment
OS: Linux

### OpenTelemetry Collector configuration

```yaml
service:
  telemetry:
    metrics:
      readers:
      - periodic:
          exporter:
            otlp:
              protocol: grpc/protobuf
```

### Log output

```shell
opentelemetry-collector 2025/02/10 16:11:23 collector server run finished with error: failed to create SDK: unsupported protocol "grpc/protobuf"
```
