### ISSUE TITLE
mTLS issue with OTLP

### ISSUE THREAD

**Issue by vipinvkmenon** [open-telemetry/opentelemetry-collector#12396]
### Component(s)

receiver/otlp

### What happened?

**Describe the bug**
I am trying to connect 2 OTEL collectors via mTLS, however, I get the error (otlp exporter):
```
2025-02-15T16:06:24.066Z        info    internal/retry_sender.go:126    Exporting failed. Will retry the request after interval.     {"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match abc.xyz.com\"", "interval": "30.981901146s"}
```

No Logs Reciever side. so not sure what the issue there

**Steps to reproduce**
The following are the configurations in place:

I) **Istio is enabled, however TLS I believe is disabled with the following configuration**
```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "ba-ot-peer-authentication"
  namespace: tls-ot
spec:
  mtls:
    mode: DISABLE
```
2) **OTEL Collector (receiver) within the kubernetes cluster:**

```
# Reciever OTEL Collector
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: basic-auth-otel-collector
  namespace: tls-ot
  annotations:
    sidecar.istio.io/logLevel: "debug"
spec:
  mode: deployment
  volumeMounts:
  - name: server-certificates-volume
    mountPath: /etc/pki/ca-trust/source/server-ca
    readOnly: true
  - name: client-certificates-volume
    mountPath: /etc/pki/ca-trust/source/client-ca
    readOnly: true
  volumes:
  - name: server-certificates-volume
    secret:
      secretName: otelserver-creds-new
  - name: client-certificates-volume
    secret:
      secretName: otelclient-creds-new
  image: otel/opentelemetry-collector-contrib:0.119.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            tls:
              cert_file: /etc/pki/ca-trust/source/server-ca/tls.crt
              key_file: /etc/pki/ca-trust/source/server-ca/tls.key
              client_ca_file: /etc/pki/ca-trust/source/client-ca/tls.crt
    exporters:
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [debug]
      telemetry:
        metrics:
          level: detailed
        logs:
          level: DEBUG
          output_paths: ["stdout"]
---
apiVersion: v1
kind: Service
metadata:
  name: basic-auth-otel-collector-grpc
  namespace: tls-ot 
spec:
  selector:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: tls-ot.basic-auth-otel-collector
    app.kubernetes.io/name: basic-auth-otel-collector-collector
  type: ClusterIP
  ports:
  - name: grpc # important!
    protocol: TCP
    port: 4317
```
_A note on the certificates created:_
1) Root CA certificates created
```
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -subj '/O=PMT/CN=root.pmt.com' -keyout root.key -out root.crt
```
2) Create signed Server Certificate
```
openssl req -out server.csr -newkey rsa:2048 -nodes -keyout server.key -subj "/CN=abc.xyz.com/O=PM" -config san_server.cnf -extensions req_ext

openssl x509 -req -sha256 -days 365 -CA root.crt -CAkey root.key -set_serial 0 -in server.csr -out server.crt -extensions req_ext -extfile san_server.cnf
```
extfile: san_server.cnf
```
[req]
default_bits = 4096
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn
[ dn ]
CN = abc.xyz.com
[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = abc.xyz.com
```
3) Client signed certificates:
```
openssl req -out client.csr -newkey rsa:2048 -nodes -keyout client.key -subj "/CN=client.local/O=client" -extensions req_ext -config san_client.cnf

openssl x509 -req -sha256 -days 365 -CA root.crt -CAkey root.key -set_serial 1 -in client.csr -out client.crt -extensions req_ext -extfile san_client.cnf
```
Extfile
```
[req]
default_bits = 4096
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn
[ dn ]
CN = client.local
[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = client.local
```
Finally uploaded the certificates as secrets:
```
# CA File used was root.crt
k create secret generic otelserver-creds -n tls-ot  --from-file=tls.crt=server.crt --from-file=tls.key=server.key --from-file=ca.crt=root.crt

k create secret generic otelclient-creds -n tls-ot  --from-file=tls.crt=client.crt --from-file=tls.key=client.key --from-file=ca.crt=root.crt
```
**Create the Gateway and Route:**

Gateway Config:

```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-ot-gateway
  namespace: tls-ot 
spec:
  gatewayClassName: istio
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    hostname: abc.xyz.com
    name: otel
    port: 4317
    protocol: TLS
    tls:
      mode: Passthrough
```
Route Config:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: tls-ot-route
  namespace: tls-ot 
spec:
  hostnames:
    - abc.xyz.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: tls-ot-gateway
    sectionName: otel
  rules:
    - backendRefs:
      - name: basic-auth-otel-collector-grpc
        weight: 1
        port: 4317
```
**I configured sample external otel collector as follows:**
```
# EXPORTER OTEL Collector
receivers:
  # Data sources: metrics
  hostmetrics:
    scrapers:
      cpu:
      disk:
processors:
  # Data sources: traces
  attributes:
    actions:
      - key: environment
        value: production
        action: insert
  # Data sources: traces, metrics, logs
exporters:
  otlp:
    endpoint: "External-Loadbalancer-host:4317"
    tls:
     server_name_override: "abc.xyz.com"
     ca_file: /etc/cert/ca.crt
     cert_file: /etc/cert/client.crt
     key_file: /etc/cert/client.key
     #insecure_skip_verify: true
  debug:
service:
 pipelines:
   metrics:
     receivers: [hostmetrics]
     processors: [attributes]
     exporters: [otlp,debug]
```

But the setup does not work. As an alternative I also tried to replace the `root.crt` with `ca_file: /etc/cert/server.crt` (in the exporter) and `client_ca_file: /etc/pki/ca-trust/source/client-ca/client.crt` (in the receiver). However it keeps throwing error at the exporter as mentioned above.

**P.S** With the following configuration below, the setup works of course:
- `tls` configuration from the RECIEVER OTEL removed
- Remove certificate settings (only keeping `server_name_override`) in the EXPORTER OTEL
- Configure an `HTTPS` Gateway with `certificateRefs` and `mode: Terminate`
- `PeerAuthentication` set to `strict` it worked with any setting here btw...

**What did you expect to see?**
- mTLS works, or proper documentation with example for a successful mTLS setup
- Proper logs from the `telemetry` service from the RECIEVER OTEL.

**What did you see instead?**
mTLS doesn't work and the exporter throws the error:
```
2025-02-15T16:14:17.964Z        info    internal/retry_sender.go:126    Exporting failed. Will retry the request after interval.     {"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match abc.xyz.com\"", "interval": "15.741533215s"}
```
- Also, no examples or documentation are showing a successful mTLS setup.

### Collector version

0.118.0

## Environment
Kubernetes

### OpenTelemetry Collector configuration

```yaml
receivers:
  # Data sources: metrics
  hostmetrics:
    scrapers:
      cpu:
      disk:
processors:
  # Data sources: traces
  attributes:
    actions:
      - key: environment
        value: production
        action: insert
  # Data sources: traces, metrics, logs
exporters:
  otlp:
    endpoint: "External-Loadbalancer-host:4317"
    tls:
     server_name_override: "abc.xyz.com"
     ca_file: /etc/cert/ca.crt
     cert_file: /etc/cert/client.crt
     key_file: /etc/cert/client.key
     #insecure_skip_verify: true
  debug:
service:
 pipelines:
   metrics:
     receivers: [hostmetrics]
     processors: [attributes]
     exporters: [otlp,debug]
```

### Log output

```shell
2025-02-15T16:14:17.964Z        info    internal/retry_sender.go:126    Exporting failed. Will retry the request after interval.     {"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match abc.xyz.com\"", "interval": "15.741533215s"}
```
