### ISSUE TITLE
telemetry: parsing v0.2.0 configuration causes loss of default settings

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#12436]
### Component(s)

service

### What happened?

**Describe the bug**

A bug was introduced in https://github.com/open-telemetry/opentelemetry-collector/commit/4edaacddf92c43b932221a736163b04227d2157c which causes default values to be ignored. 

**Steps to reproduce**
Update collector to v0.119.0+ and use a configuration that triggers the codepath to parse the config using the old config schema (headers using a map instead of a list of key/value pairs, see collector config)

**What did you expect to see?**
Collector start as before

**What did you see instead?**
The following error:

```
2025/02/19 14:06:59 collector server run finished with error: failed to create logger: no encoder name specified
```

### Collector version

v0.119.0+

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
service:
  telemetry:
    logs:
      level: debug
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: collector:4318
                headers:
                  key1: value1
```

### Log output

```shell
2025/02/19 14:06:59 collector server run finished with error: failed to create logger: no encoder name specified
```

**Comment by codeboten** [comment]
A workaround is to update the configuration to the following:

```yaml
service:
  telemetry:
    logs:
      level: debug
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: collector:4318
                headers:
                  - name: key1
                    value: value1
```
