### ISSUE TITLE
[service] Internal counter metrics now have a .filtered suffix instead _filtered for Prometheus

### ISSUE THREAD

**Issue by marcinsiennicki95** [open-telemetry/opentelemetry-collector#12524]
### Component(s)

service Telemetry

### What happened?

**Describe the bug**

Hi after upgrade from version 0.118 to version 0.120 we found out that name of metrics has changed  

**Steps to reproduce**

Upgrade from 0.118 to 0.120

**What did you expect to see?**

Names should be the same after the upgrade

**What did you see instead?**

It looks like all metrics with suffix `filtered ` has been modified. Last separator changed from `_` to `.`
`
![Image](https://github.com/user-attachments/assets/9802a028-03ea-4781-826d-864e1f34cbe2)

The metric names for version 0.120 can be found at this [link](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/536cb72a69cdc37004605b2262cbd154e3539d76/processor/filterprocessor/documentation.md). It is unclear why they are currently displayed with underscores (_) and what the correct naming convention should be

Also we don't see these metrics in official metrics 
https://opentelemetry.io/docs/collector/internal-telemetry/

### Collector version

0.120

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
telemetry:
  logs:
    level: {{ $.Values.global.logLevel }}
    encoding: json
  metrics:
    level: {{ $.Values.global.metricLevel }}
    readers:
      - pull:
          exporter:
            prometheus:
              host: 0.0.0.0
              port: 8888
              without_type_suffix: true
              without_units: true
              without_scope_info: true
{{- end }}
```

### Log output

```shell

```
