### ISSUE TITLE
[exporter/otlp] port is not recognized correctly

### ISSUE THREAD

**Issue by JPeer264** [open-telemetry/opentelemetry-collector#12536]
### Component(s)

exporter/otlp

### What happened?

**Describe the bug**

When using the config from below it wouldn't see the port in the correct place. Adding or removing the port would result in either `port is missing` or `invalid port`.  The collector can't start since the port is expected to be at the very end of the URL.

**Steps to reproduce**

1. Create a file `config.yaml` in any directory
2. Copy/Paste the collector config from below
3. Execute `docker run --rm -v $(pwd)/config.yaml:/etc/otel/config.yaml otel/opentelemetry-collector:0.120.0 --config /etc/otel/config.yaml`

**What did you expect to see?**
I actually expected that it would recognize the port correctly (without the pathname). The example with `otel/tempo` is actually working, since there is no pathname needed.

**What did you see instead?**

Following error was seen instead:
 
```sh
invalid port "443/api/prom/push"
```

(maybe related #10488)

### Collector version

v0.120.0 (asuming docker has the same version)

## Environment
OS: MacOS 15.3.1 (not sure if needed if it is running within Docker)

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  otlp/tempo:
    # URL ending with :443
    endpoint: https://tempo-prod-xxx.grafana.net:443
  otlp/loki:
    # URL without port
    endpoint: https://logs-prod-xxx.grafana.net/loki/api/v1/push
  otlp/metrics:
    # URL with port directly after domain
    endpoint: https://prometheus-prod-xxx.grafana.net:443/api/prom/push
  otlp/withouthttps:
    # URL with port directly after domain
    endpoint: otlp-gateway-prod-xxx.grafana.net:443/otlp
service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters:
        - otlp/loki
    metrics:
      receivers: [otlp]
      exporters:
        - otlp/metrics
        - otlp/withouthttps
    traces:
      receivers: [otlp]
      exporters:
        - otlp/tempo
```

### Log output

Explicit log output:

```shell
Error: invalid configuration: exporters::otlp/loki: address logs-prod-xxx.grafana.net/loki/api/v1/push: missing port in address
exporters::otlp/metrics: invalid port "443/api/prom/push"
exporters::otlp/withouthttps: invalid port "443/otlp"
2025/03/03 19:03:35 collector server run finished with error: invalid configuration: exporters::otlp/loki: address logs-prod-xxx.grafana.net/loki/api/v1/push: missing port in address
exporters::otlp/metrics: invalid port "443/api/prom/push"
exporters::otlp/withouthttps: invalid port "443/otlp"
```
