### ISSUE TITLE
Add Logs support to mdatagen

### ISSUE THREAD

**Issue by cyrusjk** [open-telemetry/opentelemetry-collector#12571]
### Describe the issue you're reporting

mdatagen supports metrics and telemetry, but not logs, even though the collector supports log collection. Having wrappers generated that support all of the Open Telemetry types would be nice thing.

**Comment by bogdandrutu** [comment]
How would you use it? And what for?

**Comment by cyrusjk** [comment]
In the context of RDBMS receivers, I would like to be able to update the receiver to support the exporting of SQL query and query plan text data to the Logs pipeline along with some attributes such as timestamp, db/schema, user, etc. While Logs scraping can be added to a Receiver, the support is inconsistent and having mdatagen support would help set a standard for how this kind of integration can be done.

**Comment by sincejune** [comment]
While working on the SQL Server receiver, I encountered similar use cases. I believe there are several benefits, particularly for scraper-based receivers, from supporting logs in `mdatagen`:

#### Automatic Generation of Scope Name and Version
Currently, we manually attach the scope name and version when constructing plog. Although this approach works, many scope versions may become outdated over time.

#### Template-Based Documentation
Documentation can become inconsistent across different scraper-based receivers. Using templates can help maintain consistency and uniformity.

#### Avoiding Field Type Conflicts
There might be multiple scrapers calling databases and sending different log records for various use cases (e.g., sample query and top query). Field types may unexpectedly differ among these log records, potentially causing issues for subsequent consumers. Having a defined schema will help avoid such conflicts.

### Implementation Plan
I plan to add the following specification to the schema for supporting logs in the initial version:
```
logs:
  sample_log:
    enabled: true
    description: <description>
    extended_documentation: <extended_documentation>
    attributes: [attribute1, attribute2] # reuse the attributes section
```
We can consider adding configurations as well in the next iteration:
```
logs:
  sample_log:
    enabled: true
    description: <description>
    extended_documentation: <extended_documentation>
    attributes: [attribute1, attribute2] # reuse the attributes section
    configs:
      lookback_window:
        type: int
        unit: s
      ...
```

@bogdandrutu I'm willing to implement this if we agree with this proposal.

cc @open-telemetry/collector-approvers

**Comment by sincejune** [comment]
While working on the SQL Server receiver, I encountered similar use cases. I believe there are several benefits, particularly for scraper-based receivers, from supporting logs in `mdatagen`:

#### Automatic Generation of Scope Name and Version
Currently, we manually attach the scope name and version when constructing plog. Although this approach works, many scope versions may become outdated over time.

#### Template-Based Documentation
Documentation can become inconsistent across different scraper-based receivers. Using templates can help maintain consistency and uniformity.

#### Avoiding Field Type Conflicts
There might be multiple scrapers calling databases and sending different log records for various use cases (e.g., sample query and top query). Field types may unexpectedly differ among these log records, potentially causing issues for subsequent consumers. Having a defined schema will help avoid such conflicts.

### Implementation Plan
I plan to add the following specification to the schema for supporting logs in the initial version:
```
logs:
  sample_log:
    enabled: true
    description: <description>
    extended_documentation: <extended_documentation>
    attributes: [attribute1, attribute2] # reuse the attributes section
```
We can consider adding configurations as well in the next iteration:
```
logs:
  sample_log:
    enabled: true
    description: <description>
    extended_documentation: <extended_documentation>
    attributes: [attribute1, attribute2] # reuse the attributes section
    configs:
      lookback_window:
        type: int
        unit: s
      ...
```

@bogdandrutu I'm willing to implement this if the team agrees with this proposal. cc @open-telemetry/collector-approvers
