### ISSUE TITLE
Resource attributes from telemetry.resource are missing for internal logs

### ISSUE THREAD

**Issue by iblancasa** [open-telemetry/opentelemetry-collector#12582]
When the `telemetry.resource` field is populated like this:
```yaml
service:
  telemetry:
    resource:
      service.name: "your-service-name"
      service.version: "your-version"
    logs:
      level: "debug"
```

Those resource attributes appear in the metrics and traces but not in the logs. This issue is to fix this and add those to the logs.

*Update 27Mar2025:*
this happens only on the logs printed via console
