### ISSUE TITLE
Feature request: add support for multi-tenancy

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#1260]
In the Jaeger project, we've received numerous requests for adding multi-tenancy support. The way that OpenTelemetry Collector is designed, encouraging multi-hop collectors, makes it suitable for multi-tenant scenarios, even though it currently requires at least one OpenTelemetry Collector instance per tenant.

Right now, each agent/local collector would need to talk to a tenant-specific remote-collector, which is then configured to write to a tenant-specific backend/storage. This would require at least one instance of the remote-collector to be available all times, even if the tenant has low-traffic. Some common concerns, such as authentication and authorization would have to be replicated to all collectors as well, with the risk of individual configurations drifting apart.

```
+-----------------------------------------------------------+
|                                                           |
|                   Application cluster                     |
|                                                           |
|  +---------------------+    +-------------------------+   |
|  |                     |    |                         |   |
|  |   tenant: acme      |    | OpenTelemetry Collector +-+ |
|  | workload: myservice +----> Agent for Acme          | | |
|  |                     |    |                         | | |
|  +---------------------+    +-------------------------+ | |
|                                                         | |
|                                                         | |
|  +---------------------+    +-------------------------+ | |
|  |                     |    |                         | | |
|  |   tenant: ecorp     |    | OpenTelemetry Collector | | |
|  | workload: myservice +----> Agent for Ecorp         | | |
|  |                     |    |                         | | |
|  +---------------------+    +---------------+---------+ | |
|                                             |           | |
+-----------------------------------------------------------+
                                              |           |
+-----------------------------------------------------------+
|                       Firewall              |           | |
+-----------------------------------------------------------+
|                                             |           | |
|                   Monitoring cluster        |           | |
|                                             |           | |
|               +-------------------------+   |           | |
|               |                         |   |           | |
|               | OpenTelemetry Collector |   |           | |
|          +----+ for Ecorp w/ authz      <---+           | |
|          |    |                         |               | |
|          |    +-------------------------+               | |
|          |    +-------------------------+               | |
|          |    |                         |               | |
|          |    | OpenTelemetry Collector |               | |
|          |    | for Acme w/ authz       <---------------+ |
|          |    |                         |                 |
|          |    +---------------------+---+                 |
|          |                          |                     |
|     +----v-------------+          +-v---------------+     |
|     |                  |          |                 |     |
|     | Jaeger for Ecorp |          | Jaeger for Acme |     |
|     |                  |          |                 |     |
|     +------------------+          +-----------------+     |
+-----------------------------------------------------------+
```

Ideally, only one remote collector would be required, taking care of concerns like authentication and authorization (and perhaps sampling,  throttling, ...). This would be one example of a desired architecture:

```
+-----------------------------------------------------------+
|                                                           |
|                   Application cluster                     |
|                                                           |
|  +---------------------+    +-------------------------+   |
|  |                     |    |                         |   |
|  |   tenant: acme      |    | OpenTelemetry Collector +-+ |
|  | workload: myservice +----> Agent for Acme          | | |
|  |                     |    |                         | | |
|  +---------------------+    +-------------------------+ | |
|                                                         | |
|                                                         | |
|  +---------------------+    +-------------------------+ | |
|  |                     |    |                         | | |
|  |   tenant: ecorp     |    | OpenTelemetry Collector | | |
|  | workload: myservice +----> Agent for Ecorp         | | |
|  |                     |    |                         | | |
|  +---------------------+    +---------------+---------+ | |
|                                             |           | |
+-----------------------------------------------------------+
                                              |           |
+---------------------------------------------v-----------v-+
|                 Firewall, Auth/z, ...                     |
+--------------------------------------------------+--------+
|                                                  |        |
|                   Monitoring cluster             |        |
|                                                  |        |
|     +--------------------------------------------v---+    |
|     |                                                |    |
|     |        OpenTelemetry Collector Cluster         |    |
|     |                                                |    |
|     +----------------------+-------------------------+    |
|                            |                              |
|     +-----------------+    |      +------------------+    |
|     |                 |    |      |                  |    |
|     | Jaeger for Acme +<---+----->+ Jaeger for Ecorp |    |
|     |                 |           |                  |    |
|     +-----------------+           +------------------+    |
|                                                           |
+-----------------------------------------------------------+

```

**Describe the solution you'd like**
I'm not quite sure what's the best solution for this at this point, and I would like to start a discussion around this. I can think of a few possible solutions, but they either require quite a good amount of work, or don't feel quite right. 

Here are a couple of ideas, to start a discussion:

1. multi-tenancy as first-class citizen, probably requires quite some work in the pipeline processing:

```yaml
receivers:
  examplereceiver:

processors:
  exampleprocessor:

exporters:
  logging:
  jaeger/globex:
    endpoint: "https://jaeger.globex.example.com:14250"
  jaeger/ecorp:
    endpoint: "https://jaeger.ecorp.example.com:14250"
  saas/globex:
    endpoint: "https://saas.globex.example.com:8443"
    license: xyz
  otlp:
    endpoint: "https://otlp.catch-all.example.com:55680"

service:
  pipelines:
    traces:
      receivers: [examplereceiver]
      processors: [exampleprocessor]
      routing:
        default_exporters: [otlp]
        from_attribute: __tenant
        table:
        - value: acme
          exporters: [logging]
        - value: globex
          exporters: [jaeger/globex, saas/globex]
        - value: ecorp
          exporters: [jaeger/ecorp]
```

2. multi-tenancy in a processor. This would require the processor to have access to the instantiated exporters, currently private to the pipeline. When a span doesn't match a specific route, it falls through and reaches the exporter specified in the pipeline. Not very intuitive at first, but documentation can solve that. This doesn't feel like a proper solution, but would probably work and is a low-impact change, as most of the changes would be inside a new processor.

```yaml
receivers:
  examplereceiver:

processors:
  routing:
    from_attribute: __tenant
    table:
    - value: acme
      exporters: [logging]
    - value: globex
      exporters: [jaeger/globex, saas/globex]
    - value: ecorp
      exporters: [jaeger/ecorp]

exporters:
  logging:
  jaeger/globex:
    endpoint: "https://jaeger.globex.example.com:14250"
  jaeger/ecorp:
    endpoint: "https://jaeger.ecorp.example.com:14250"
  saas/globex:
    endpoint: "https://saas.globex.example.com:8443"
    license: xyz
  otlp:
    endpoint: "https://otlp.catch-all.example.com:55680"

service:
  pipelines:
    traces:
      receivers: [examplereceiver]
      processors: [routing]
      exporters: [logging, otlp]
```

Questions:

1. how about dynamic configurations? When new tenants are added, the configuration would need to be changed, causing a restart of the running collectors. Perhaps a "pattern" value for the endpoint would make sense?

```yaml
exporters:
  jaeger/common-tenants:
    pattern: "https://jaeger.%s.example.com:14250"
```

**Comment by kbrockhoff** [comment]
Based on feature requests for load balancing, sharding and multi-tenency that periodically come up, Map and MapReduce capabilities will eventually need to be added to pipeline processing. My concern is the amount of work-in-progress we already have. The focus needs to be getting WIP items to GA. Any of these feature requirements can be met in an inefficient manner by chaining more clusters of collectors together and applying simple filtering. Doing this as a first step would increase knowledge on how to design it correctly once WIP is reduced.

**Comment by jpkrohling** [comment]
True, but perhaps we can come up with the design for what we want in the future. Otherwise, we'll need a major new version to introduce a feature that introduces breaking changes to the configuration.

**Comment by tigrannajaryan** [comment]
(2) can be done today with no changes to the core codebase. Processors do have access to instantiated exporters. The Host exposes GetExporters() function for that. This seems like a good enough approach to me, do we really need to do better?

There is a third, slightly different way that is perhaps more intuitive like approach (1) and does not require introducing new pipeline concepts. We can implement an exporter named "routing" that can be chained to other exporters:
```yaml
receivers:
  examplereceiver:

processors:
  exampleprocessor:

exporters:
  logging:
  jaeger/globex:
    endpoint: "https://jaeger.globex.example.com:14250"
  jaeger/ecorp:
    endpoint: "https://jaeger.ecorp.example.com:14250"
  saas/globex:
    endpoint: "https://saas.globex.example.com:8443"
    license: xyz
  otlp:
    endpoint: "https://otlp.catch-all.example.com:55680"
  routing:
    default_exporters: [otlp]
    from_attribute: __tenant
    table:
    - value: acme
      exporters: [logging]
    - value: globex
      exporters: [jaeger/globex, saas/globex]
    - value: ecorp
      exporters: [jaeger/ecorp]    

service:
  pipelines:
    traces:
      receivers: [examplereceiver]
      processors: [exampleprocessor]
      exporters: [routing]
```
The "routering" exporter will start the second-stage exporters it references. There will be some minimal changes necessary to ensure the exporters that are not directly attached to pipelines can still be started (does not happen today).

An open question is how we ensure that second-stage exporters created by "routing" exporter are the same instances used directly in pipelines (if they are). Today we guarantee this for exporters attached to multiple pipelines, which ensures that e.g. a single "fileexporter" instance writes to the file and concurrent export requests are correctly handled. This will likely require a shared registry of created exporters to be available during pipeline building. Should be doable.

**Comment by jrcamp** [comment]
@tigrannajaryan I like your routing exporter idea.

Maybe it should allow passing through processors  as well before being passed to exporters, similar to pipeline? Building on your example:

```yaml
receivers:
  examplereceiver:

processors:
  filter/globex:
    metrics:
      exclude:
      match_type: regexp
      metric_names:
      - host\.cpu.*

  filter/ecorp:
    metrics:
      exclude:
      match_type: regexp
      metric_names:
      - host\.mem.*

exporters:
  logging:
  jaeger/globex:
    endpoint: "https://jaeger.globex.example.com:14250"
  jaeger/ecorp:
    endpoint: "https://jaeger.ecorp.example.com:14250"
  saas/globex:
    endpoint: "https://saas.globex.example.com:8443"
    license: xyz
  otlp:
    endpoint: "https://otlp.catch-all.example.com:55680"
  routing:
    default_exporters: [otlp]
    from_attribute: __tenant
    table:
    - value: acme
      exporters: [logging]
    - value: globex
      processors: [filter/globex]
      exporters: [jaeger/globex, saas/globex]
    - value: ecorp
      processors: [filter/ecorp]
      exporters: [jaeger/ecorp]    

service:
  pipelines:
    traces:
      receivers: [examplereceiver]
      processors: [exampleprocessor]
      exporters: [routing]
```
