### ISSUE TITLE
[Metric builder] Add external system states to be used in metric constraints

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#12620]
_Originally suggested by @djaglowski in https://github.com/open-telemetry/opentelemetry-collector/pull/6358#discussion_r1000609067_

Add ability to provide optional states of the monitored system that can be used in metric constraints like the following:

```yaml
some.metric.with_min:
  ...
  constraints:
    min_version: 5.0
some.metric.with_max:
  ...
  constraints:
    max_version: 99.9
some.metric.with_minmax:
  ...
  constraints:
    min_version: 0.1
    max_version: 0.9
some.metric.requires_config:
  ...
  constraints:
    config_settings:
      - replication: enabled
some.metric.with_unusual_constraint:
  ...
  constraints:
    text: Only returned when...
```
