### ISSUE TITLE
Traffic loss during shutdown

### ISSUE THREAD

**Issue by manojsm51** [open-telemetry/opentelemetry-collector#12647]
### What happened?

Hi team,

I'm trying to shutdown the otel process gracefully and I could see traffic loss during this.

> otelcol_receiver_accepted_log_records{receiver="otlp",service_instance_id="95e3c7f2-7f51-45df-8c99-4129d41e7300",service_name="otelcol-custom",service_version="",transport="grpc"} 1826
 
> otelcol_processor_accepted_log_records{processor="memory_limiter",service_instance_id="95e3c7f2-7f51-45df-8c99-4129d41e7300",service_name="otelcol-custom",service_version=""} 1826
 
> otelcol_processor_batch_batch_send_size_sum{processor="batch",service_instance_id="95e3c7f2-7f51-45df-8c99-4129d41e7300",service_name="otelcol-custom",service_version=""} 1777
 
> otelcol_exporter_sent_log_records{exporter="opensearch",service_instance_id="95e3c7f2-7f51-45df-8c99-4129d41e7300",service_name="otelcol-custom",service_version=""} 1777

Is graceful shutdown implemented in otel collector?

### Collector version

0.119.0

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by atoulme** [comment]
Please post your configuration and explain how you shut down the collector.

**Comment by manojsm51** [comment]
Here is the config I used.

```
service:
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8888
  extensions:
    - health_check
    - file_storage/opensearch
  pipelines:
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - opensearch
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  file_storage/opensearch:
    directory: /tmp/otel/queue/opensearch
    create_directory: true
    timeout: 10s
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
exporters:
  opensearch:
    http:
      endpoint: http://opensearch:9200
    logs_index: log_index
    dataset: test_ds
    namespace: test_ns
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000
      storage: file_storage/opensearch
    retry_on_failure:
      enabled: true
      max_elapsed_time: 0
```

I used `kill -15` command to stop the otel process.
