### ISSUE TITLE
service: configuration example for telemetry causes startup issue

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#12661]
### Component(s)

service

### What happened?

the basic config for emitting internal metrics through OTLP from [the docs](https://opentelemetry.io/docs/collector/internal-telemetry/#configure-internal-metrics), which worked in 0.121.0, crashes the 0.122.0 Collector 
with the message:

`2025/03/18 19:10:19 collector server run finished with error: failed to create SDK: must not specify multiple metric reader type`

### Collector version

v0.122.0

### OpenTelemetry Collector configuration

```yaml
receivers:
  nop:
exporters:
  nop:
service:
  pipelines:
    logs:
      receivers: [nop]
      processors: []
      exporters: [nop]
  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: https://backend:4318
```

### Log output

```shell

```

**Comment by TylerHelmuth** [comment]
I am investigating

**Comment by codeboten** [comment]
Further investigation by @TylerHelmuth, @evan-bradley and @dehaansa indicate this is related to https://github.com/open-telemetry/opentelemetry-collector/commit/b8830dd7c6346ac558569d887ee0da079fb8a0d4

**Comment by codeboten** [comment]
a potential workaround, it seems configuring a pull reader as well as a periodic reader allows the collector to start:

```
service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: localhost
                port: 8889
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: https://backend:4318
```
