### ISSUE TITLE
[exporterhelper persistent-queue] Not working as expected

### ISSUE THREAD

**Issue by julianocosta89** [open-telemetry/opentelemetry-collector#12711]
### Component(s)

extension/storage/filestorage

## Description

I've been trying to use the storage extension and I'm having some trouble understanding it. The README is a bit confusing and the example is super basic.

When using the storage extension with `sending_queue.storage.file_storage` I can see that my traces, metrics and logs are being saved in the files `exporter_otlp_<signal>`, but that just happens when the data is exported.

Imagine the following scenario:

- Collector receives the data.
- The Batch processor is configured to wait for 30s to send the data.
- The Collector dies for some reason before exporting the data.

In that case, the data would be lost, and even when the Collector is restarted it wouldn't be aware of the missing data.

## Steps to Reproduce

I'll paste a simple app I'm using below, but this can be reproduced by using the Collector Config in here: https://github.com/julianocosta89/otel-lab/blob/main/q-and-a/otel-collector/otelcol-config.yaml

If you would like to test in the app, here it is:

```
git clone https://github.com/julianocosta89/otel-lab
cd otel-lab/q-and-a

docker compose up -d
```

After everything is up and running you can run the script `./requests.sh` to send 100 requests to the weather service.

Once the script is finished, you can kill the Collector and when starting it again nothing happens.

```
docker kill q-and-a-otel-collector-1

docker compose up -d
```

## Expected Result

I'd expect the received Traces, Metrics and Logs to be stored in the filesystem as soon as the Collector receives it, and if something happens before the data is exported, I'd expect the Collector to retry to send the data till it succeed.

I have this expectation due to this diagram here: https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/exporterhelper#persistent-queue

## Actual Result

If the Collector dies for some reason before exporting the data, the data is lost, and even when the Collector is restarted it isn't aware of the missing data.

### Collector version

Contrib 0.119.0

### Environment information

OS: MacOS Sequoia 15.3 (24D60)

But I'm running everything with Docker.

### OpenTelemetry Collector configuration

```yaml
extensions:
  file_storage: {}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}
  postgresql:
    endpoint: ${env:POSTGRES_HOST}:${env:POSTGRES_PORT}
    username: ${env:POSTGRES_USER}
    password: ${env:POSTGRES_PWD}
    databases:
      - ${env:POSTGRES_DB}
    tls:
      insecure: true

processors:
  batch:
    timeout: 30s
  transform:
    error_mode: ignore
    metric_statements:
      - context: scope
        conditions:
          - name == "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/postgresqlreceiver"
        statements:
          - set(resource.attributes["service.name"], "${env:POSTGRES_DB}")

connectors:
  spanmetrics: {}

exporters:
  debug: {}
  otlp:
    endpoint: "aspire-dashboard:18889"
    tls:
      insecure: true
    sending_queue:
      storage: file_storage
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
    sending_queue:
      storage: file_storage

service:
  extensions: [file_storage]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp, otlp/jaeger, spanmetrics]
    metrics:
      receivers: [otlp, postgresql, spanmetrics]
      processors: [transform, batch]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
```

### Additional context

It would be great if we could have a more detailed documentation on how to use the components. In the main docs (opentelemetry.io) we only mention what are extensions, but there is not a single example there.
In the READMEs we have examples, but without data being actually sent anywhere, or even worse, with `nop` components.
