### ISSUE TITLE
[confmap] is not preserving the original type when a slice of a map is unmarshalled

### ISSUE THREAD

**Issue by dloucasfx** [open-telemetry/opentelemetry-collector#12793]
### Component(s)

confmap

### What happened?

**Describe the bug**
When using an env variable with numerical values, example: `SPLUNK_ACCESS_TOKEN=12345`

````
extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-SF-TOKEN
        from_context: X-SF-TOKEN
        default_value: "${SPLUNK_ACCESS_TOKEN}"

````
the collector fails to start with the below error:

````
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'extensions': error reading configuration for "headers_setter": decoding failed due to the following error(s):

'headers[0].default_value' expected type 'string', got unconvertible type 'int', value: '12345'
````

**Steps to reproduce**
Set the env variable to `SPLUNK_ACCESS_TOKEN=12345` and run contrib using a config like this:

````
extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-SF-TOKEN
        from_context: X-SF-TOKEN
        default_value: "${SPLUNK_ACCESS_TOKEN}"

receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      filesystem:
      memory:

processors:
  batch:
  batch/out:
    metadata_keys:
      - X-SF-Token

exporters:
  otlphttp:
    metrics_endpoint: https://ingest.us1.signalfx.com/v2/datapoint/otlp
    headers:
      X-SF-Token: "${SPLUNK_ACCESS_TOKEN}"
    auth:
      authenticator: headers_setter


service:
  telemetry:
    logs:
      level: "info"
  pipelines:
    metrics/internal:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp]

  extensions: [headers_setter]
````

**What did you expect to see?**
No error

**What did you see instead?**
Below error
````
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'extensions': error reading configuration for "headers_setter": decoding failed due to the following error(s):

'headers[0].default_value' expected type 'string', got unconvertible type 'int', value: '12345'
````

What I believe is happening is that the confmap correctly handles maps and run each entry of the map into the `isStringyStructure`, however, when a config is made out of a slice of maps is used (like the case here), the decoder hooks do not run each entry of the slice into `isStringyStructure` . 

<img width="392" alt="Image" src="https://github.com/user-attachments/assets/4e8f24db-f622-4a94-a5f7-2132a103c907" />

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-SF-TOKEN
        from_context: X-SF-TOKEN
        default_value: "${SPLUNK_ACCESS_TOKEN}"

receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      filesystem:
      memory:

processors:
  batch:
  batch/out:
    metadata_keys:
      - X-SF-Token

exporters:
  otlphttp:
    metrics_endpoint: https://ingest.us1.signalfx.com/v2/datapoint/otlp
    headers:
      X-SF-Token: "${SPLUNK_ACCESS_TOKEN}"
    auth:
      authenticator: headers_setter


service:
  telemetry:
    logs:
      level: "info"
  pipelines:
    metrics/internal:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp]

  extensions: [headers_setter]
```

### Log output

```shell

```
