### ISSUE TITLE
Batch processor performance issues

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#1279]
**Describe the bug**
When running the testbed with the SignalFx receiver/exporter and using batch the performance is reduced by ~20%. 

pprof output shows batch is taking 25% of total execution time:

```
Showing nodes accounting for 2650ms, 25.36% of 10450ms total
      flat  flat%   sum%        cum   cum%
    2530ms 24.21% 24.21%     2530ms 24.21%  go.opentelemetry.io/collector/processor/batchprocessor.(*batchMetricProcessor).sendItems
```

**Steps to reproduce**
Run testbed and compare throughput of batch enabled vs not.

**What did you expect to see?**
Batch improving performance.

**What did you see instead?**
Batch hampering performance.

**What version did you use?**
79d14c4 (core)
7b9163a (contrib)

**What config did you use?**
```yaml
receivers:
  signalfx:
    endpoint: "localhost:35000"
exporters:
    signalfx:
      ingest_url: "http://localhost:25000/v2/datapoint"
      api_url: "http://localhost/"
      access_token: "access_token"
processors:
  batch: {send_batch_size: 8192}


extensions:
  pprof:
    save_to_file: /Users/jaycamp/src/opentelemetry-collector-contrib/testbed/tests/results/TestMetric10kItems/SignalFx_Collector/cpu.prof

service:
  extensions: [pprof]
  pipelines:
    metrics:
      receivers: [signalfx]
      processors: [batch]
      exporters: [signalfx]
```

**Environment**
go version go1.14.4 darwin/amd64

**Additional context**
