### ISSUE TITLE
Http status: 400 Bad Request when sending from Vector to OTEL - No warning in Otel

### ISSUE THREAD

**Issue by seilerre** [open-telemetry/opentelemetry-collector#12818]
### What happened?

**Describe the bug**

I get "Http status: 400 Bad Request" when sending from Vector to Otel. Lots of logs go through, but for some I get this error. I can't find a way to properly get Otel to log what produces these bad requests. As you can see below, Otel is in debug mode but not complaining at all.

**Steps to reproduce**

Error

```sh
2025-04-09T15:12:25.367398Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25487}: vector::sinks::util::retries: Not retriable; dropping the request. reason="Http status: 400 Bad Request" internal_log_rate_limit=true
2025-04-09T15:12:25.367414Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25487}: vector_common::internal_event::service: Internal log [Service call failed. No retries or retries exhausted.] has been suppressed 499 times.
2025-04-09T15:12:25.367419Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25487}: vector_common::internal_event::service: Service call failed. No retries or retries exhausted. error=None request_id=25487 error_type="request_failed" stage="sending" internal_log_rate_limit=true
2025-04-09T15:12:25.367432Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25487}: vector_common::internal_event::component_events_dropped: Internal log [Events dropped] has been suppressed 499 times.
2025-04-09T15:12:25.367435Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25487}: vector_common::internal_event::component_events_dropped: Events dropped intentional=false count=1 reason="Service call failed. No retries or retries exhausted." internal_log_rate_limit=true
2025-04-09T15:12:25.367654Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25489}: vector::sinks::util::retries: Internal log [Not retriable; dropping the request.] is being suppressed to avoid flooding.
2025-04-09T15:12:25.367667Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25489}: vector_common::internal_event::service: Internal log [Service call failed. No retries or retries exhausted.] is being suppressed to avoid flooding.
2025-04-09T15:12:25.367675Z ERROR sink{component_kind="sink" component_id=otel component_type=opentelemetry}:request{request_id=25489}: vector_common::internal_event::component_events_dropped: Internal log [Events dropped] is being suppressed to avoid flooding.
```

Open Telemetry is happily receiving "some" logs and not logging ANY errors. I tried multiple configurations to get better logs, like setting OTEL_LOG_LEVEL=debug, using the debug exporter, setting service.telemetry.logs. No info.

```sh
{"level":"info","ts":"2025-04-09T15:09:40.702Z","msg":"Logs","kind":"exporter","data_type":"logs","name":"debug","resource logs":51,"log records":51}
{"level":"info","ts":"2025-04-09T15:09:50.702Z","msg":"Logs","kind":"exporter","data_type":"logs","name":"debug","resource logs":100,"log records":100}
{"level":"info","ts":"2025-04-09T15:10:10.704Z","msg":"Logs","kind":"exporter","data_type":"logs","name":"debug","resource logs":51,"log records":51}
{"level":"info","ts":"2025-04-09T15:10:20.704Z","msg":"Logs","kind":"exporter","data_type":"logs","name":"debug","resource logs":100,"log records":100}
{"level":"info","ts":"2025-04-09T15:10:30.705Z","msg":"Logs","kind":"exporter","data_type":"logs","name":"debug","resource logs":1,"log records":1}
```

My vector config:

```yaml
sources:
  docker:
    # Reads logs from Docker containers via the Docker socket
    type: docker_logs
    # endpoint: "unix:///var/run/docker.sock"
    # include_containers:
    #   - "my_container_name"
    exclude_containers:
      - otel-otel-collector
transforms:
  enrich:
      type: remap
      inputs: ["docker"]
      source: |
        # Log ID
        .logId = uuid_v4()

        # Severity
        .severity = "UNKNOWN"
        if contains(string!(.message), "info", case_sensitive: false) {
          .severity = "INFO"
          .severityNumber = 9
        } else if contains(string!(.message), "trace", case_sensitive: false) {
          .severity = "TRACE"
          .severityNumber = 1
        } else if contains(string!(.message), "debug", case_sensitive: false) {
          .severity = "DEBUG"
          .severityNumber = 5
        } else if contains(string!(.message), "warn", case_sensitive: false) {
          .severity = "WARN"
          .severityNumber = 13
        } else if contains(string!(.message), "error", case_sensitive: false) {
          .severity = "ERROR"
          .severityNumber = 17
        } else if contains(string!(.message), "fatal", case_sensitive: false) {
          .severity = "FATAL"
          .severityNumber = 21
        }
  otel_remap:
    # https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md
    # https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/file-exporter.md#examples
    inputs: ["enrich"]
    type: "remap"
    source: |
      .resourceLogs = [
        {
          "resource": {
            "attributes": [
              { "key": "host.hostname", "value": { "stringValue": .host.hostname } },
              { "key": "service.name", "value": { "stringValue": .container_name} },
              { "key": "source_type", "value": { "stringValue": .source_type } }
            ]
          },
          "scopeLogs": [
            {
              "scope": {},
              "logRecords": [
                {
                  "timeUnixNano": to_unix_timestamp!(.timestamp, unit: "nanoseconds"),
                  "body": { "stringValue": .message },
                  "severityText": .severity,
                  "severityNumber": .severityNumber,
                  "attributes": [
                    { "key": "container_created_at", "value": { "stringValue": to_string!(.container_created_at) } },
                    { "key": "log_id", "value": { "stringValue": .logId } },
                    { "key": "container_id", "value": { "stringValue": .container_id } },
                    { "key": "container_name", "value": { "stringValue": .container_name } },
                    { "key": "host", "value": { "stringValue": "${HOST_HOSTNAME}" } },
                    { "key": "image", "value": { "stringValue": .image } },
                    # Optionally include other fields like .stream, .message, etc.
                    { "key": "stream", "value": { "stringValue": .stream } }
                  ]
                }
              ]
            }
          ]
        }
      ]
      .
sinks:
  # console:
  #   inputs:
  #     - otel_remap
  #   target: stdout
  #   type: console
  #   encoding:
  #     codec: json
  otel:
    type: opentelemetry
    inputs:
      - otel_remap
    protocol:
      type: http
      uri: "http://otel-collector:4318/v1/logs"
      method: post
      batch:
        # TODO: Change this to more after https://github.com/vectordotdev/vector/issues/22188
        max_events: 1
      encoding:
        codec: json
      framing:
        method: newline_delimited
      request:
        headers:
          content-type: application/json
```

My Compose:

```yaml
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.123.0
    restart: always
    user: "0"
    env_file:
      - .env
    environment:
      - OTEL_LOG_LEVEL=debug
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    deploy:
      resources:
        limits:
          cpus: '1.00'      # maximum 50% of a single CPU
          memory: 500M      # maximum 500 MB memory usage
        reservations:
          cpus: '0.30'      # reserve 25% of a single CPU
          memory: 300M      # reserve 250 MB memory
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vector:
    depends_on:
      - otel-collector
    image: timberio/vector:0.46.0-alpine
    restart: always
    user: "0"
    environment:
      - VECTOR_LOG=info
      - HOST_HOSTNAME=CHANGE
    volumes:
      # Mount Docker socket read-only so Vector can read logs directly
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount your Vector config file
      - ./vector.yaml:/etc/vector/vector.yaml:ro
    command: ["--config", "/etc/vector/vector.yaml"]
    # Optionally expose or publish ports for Vector's own internal metrics
    # ports:
    #   - 8686:8686
    deploy:
      resources:
        limits:
          cpus: '1.00'      # maximum 50% of a single CPU
          memory: 300M      # maximum 500 MB memory usage
        reservations:
          cpus: '0.30'      # reserve 25% of a single CPU
          memory: 300M      # reserve 250 MB memory
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
```

My OTEL Config:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    timeout: 5s
    send_batch_size: 100
exporters:
  debug:
    verbosity: detailed
  kafka:
    brokers: ["redacted"] # Replace with your Kafka broker(s)
    topic: redacted
    encoding: otlp_proto
    protocol_version: "3.8.0" # Adjust according to your Kafka setup
    retry_on_failure:
      enabled: true
    sending_queue:
      queue_size: 200
    producer:
      compression: lz4
    auth:
      sasl:
        mechanism: "SCRAM-SHA-512"  # Choose "PLAIN", "SCRAM-SHA-256", or "SCRAM-SHA-512" depending on your Kafka setup
        username: "${OTEL_KAFKA_USERNAME}"
        password: "${OTEL_KAFKA_PASSWORD}"
      tls:
        insecure: false
        insecure_skip_verify: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
```

**What did you expect to see?**
All logs get ingested or at least I receive a WARN/ERROR about this bad request in OTEL

**What did you see instead?**
Nothing, some logs get ingested, some produce a 400

### Collector version

0.123.0

### Environment information

Newest Otel Docker Image running on Ubuntu

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    timeout: 5s
    send_batch_size: 100
exporters:
  debug:
    verbosity: detailed
  kafka:
    brokers: ["redacted"] # Replace with your Kafka broker(s)
    topic: redacted
    encoding: otlp_proto
    protocol_version: "3.8.0" # Adjust according to your Kafka setup
    retry_on_failure:
      enabled: true
    sending_queue:
      queue_size: 200
    producer:
      compression: lz4
    auth:
      sasl:
        mechanism: "SCRAM-SHA-512"  # Choose "PLAIN", "SCRAM-SHA-256", or "SCRAM-SHA-512" depending on your Kafka setup
        username: "${OTEL_KAFKA_USERNAME}"
        password: "${OTEL_KAFKA_PASSWORD}"
      tls:
        insecure: false
        insecure_skip_verify: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
```

### Log output

```shell

```
