### ISSUE TITLE
Collector internal metrics causing "Out of order exemplar"  in Prometheus 3.0.1 when using OTLP

### ISSUE THREAD

**Issue by swapdonkey** [open-telemetry/opentelemetry-collector#12923]
## Description
When the collector internal metrics are turned on and configured to publish directly to Prometheus 3 via OTLP, Prometheus is  logging "Out of order exemplar" errors.
 
As internal traces are experimental the tracing wasn't configured but the exemplar errors still occur. 
So it would also be beneficial if internal exemplars can be disabled by default and turned on either when the tracing is configured or a flag in the internal tracing sets exemplars to true.  

## Steps to Reproduce
Stripping down the collector config to the bare minimum still triggers the exception in Prometheus. 
Note the ```interval: 10000``` makes it occur significantly more frequently so it could be something to do with the batching?

## Expected Result
No errors in Prometheus logs 
 
## Actual Result
Errors logged in Prometheus

### Collector version

contrib collector 0.23.1

## Environment
OS: Redhat

### OpenTelemetry Collector configuration

```yaml
receivers:
   otlp:
     protocols:
       grpc:
         endpoint: localhost: xxxx
  
  exporters:
     otlphttp/prom:
        endpoint: ...../api/v1/otlp
   
 service:
   pipelines:
     metrics
       receivers: [otlp, otlp/internal_metrics]
       exporters: [ otlphttp/prom]
   
 telemetry:
   metrics:
     readers:
       - periodic:
           interval: 10000
           exporter:
             otlp:
               protocol: http/protobuf
               endpoint: <remote Prometheus 3.1.0>/api/v1/otlp/v1
```

### Log output

```shell
{"time:"2025-04-24T08:41:17.38853321Z", "level": "DEBUG", "source":"write_handler.go:263", "msg":"Out of order exemplar", "component":"web","series":"{__name__=\"otelcol_exporter_sent_metric_points_total\", deployment_environment_name=\"qa", exporter=\"otlphttp\", instance=\"...\",job=\"…\", "exemplar":"{Labels:{span_id=\"....\", trace_id\"...\"}} Value:0 Ts:1745484064027Z HasTs:true"}
```

### Additional context

Not sure if this is also related https://github.com/prometheus/prometheus/issues/13577 in which case it could be a Prometheus issue rather then a collector issue?
