### ISSUE TITLE
Use Header from Incoming Requests

### ISSUE THREAD

**Issue by safaci2000** [open-telemetry/opentelemetry-collector#12947]
### Component(s)

exporter/otlphttp

### Describe the issue you're reporting

I believe this is not currently supported but if someone can tell me either how this can be done I'd love to know. Otherwise consider this a feature request.

My collector config can be seen below. Basically every request that is incoming to the http endpoint has an Authorization Header. I would like to extract that header and pass it along to the exporter. It seemed like a pretty straightforward feature to me but there's likely some complexities around batching and such which could potentially collect one or multiple keys. Any thoughts on how this can be done would be great. 

Collector config:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318
        include_metadata: true

processors:
  attributes:
    actions:
      - key: auth_header
        from_context: Authorization
        action: upsert


exporters:
  otlp/elastic:
    endpoint: localhost:8200
    tls:
      insecure: true
    headers:
      Authorization: attributes["auth_header"]


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [otlp/elastic]                      
```

The routing connector https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/routingconnector/README.md was also proposed as an option but I think that would only work for static config, It doesn't seem to have the option to say group by Key and I think the issue of pulling out the Auth Token would still exists.

**Comment by safaci2000** [comment]
I've got this working, here is my working configuration:

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: localhost:4318
        include_metadata: true

extensions:
  headers_setter:
    headers:
      - action: insert
        key: Authorization
        from_context: Authorization

exporters:
  otlp/elastic:
    endpoint: localhost:8200
    tls:
      insecure: true
    auth:
      authenticator: headers_setter



service:
  extensions: [headers_setter]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic, zipkin]
    metrics:
      receivers: [otlp]
      exporters: [otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [otlp/elastic]    
```

Sorry for the noise.
