### ISSUE TITLE
Kafka exporter doesn't work with SASL_SSL

### ISSUE THREAD

**Issue by jovezhong** [open-telemetry/opentelemetry-collector#12957]
### What happened?

**Describe the bug**

It seems that kafkaexport only work with unauthorized kafka. I am sure on my VM I can connect to either Aiven Kafka or the GCP managed Kafka, but when I configure the same access in `/etc/otelcol-contrib/config.yaml` I failed to start the collector.

`sudo /usr/bin/otelcol-contrib --config=/etc/otelcol-contrib/config.yaml`

> Error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF
> 2025/05/02 05:44:13 collector server run finished with error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF

**Steps to reproduce**

```yaml
exporters:
  kafka/metrics:
    brokers: ["mybroker:9092"]
    sasl:
         username: avnadmin
         password: ..
         mechanism: SCRAM-SHA-256
    tls:
         insecure: true
    metrics:
         encoding: otlp_json
```

**What did you expect to see?**

write data to kafka
**What did you see instead?**

fail to start the collector
> Error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF
> 2025/05/02 05:44:13 collector server run finished with error: cannot start pipelines: failed to start "kafka/metrics" exporter: kafka: client has run out of available brokers to talk to: unexpected EOF

### Collector version

0.125.0

## Environment
OS: (e.g., "Ubuntu 20.04") Debian
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
exporters:
  kafka/metrics:
    brokers: ["mybroker:9092"]
    sasl:
         username: avnadmin
         password: ..
         mechanism: SCRAM-SHA-256
    tls:
         insecure: true
    metrics:
         encoding: otlp_json
```

### Log output

```shell

```
