### ISSUE TITLE
OTLP receiver buffers incoming requests for 25 s+

### ISSUE THREAD

**Issue by verejoel** [open-telemetry/opentelemetry-collector#13050]
### What happened?

**Describe the bug**
We have observed that requests are getting buffered in the OTLP receiver for an unreasonably long-time, before even being processed by the pipeline steps. This is associated with a drop in accepted logs across our fleet of collectors, an increase in memory consumption (until OOMkilled) and a spike in CPU usage due to garbage collection. Once the pods get into this state, it is impossible to get them out without rebooting them and losing data.

We also see a lot of other weird behaviour that is very hard to explain. 

A typical failure looks like this:
1. steady state: all is well. queue is usually no larger than a few MiB. Items are quickly enqueued and dequeued to Kafka backend.
2. queue starts to increase linearly. This happens at the same time as the memory starts to grow. Note that the rate the queue grows is not the same as the amount that the RSS memory is growing. This implies requests are being buffered (as we see from traces) before they even hit the queue.
3. accepted logs go to 0. But some Istio requests are still arriving, but at a much reduced rate\
4. at some point the memory limiter kicks in and rejects some items (but what is being rejected here, there are no logs being accepted)
5. pod is OOMkilled, at which point it gets rebooted and works as expected.

![Image](https://github.com/user-attachments/assets/2a01e47c-7ccd-443d-892e-5cb2e5544e3a)

![Image](https://github.com/user-attachments/assets/d4e58e88-a095-4212-871c-c917bdafd24b)

Weirdest thing is that this seems to affect multiple pods at the same time.

![Image](https://github.com/user-attachments/assets/e4cb88d1-3991-43b5-93a9-bb0c2143c076)

**Steps to reproduce**
We are running an OTLP receiver, which is responsible for writing data to our Kafka cluster. The pipeline config is as below.

**What did you expect to see?**

Requests should be processed in a timely fashion and pods should not be OOMkilled.

**What did you see instead?**
Pods are falling over at 5k logs/sec. This setup is not stable enough to use this in production.

### Collector version

0.124.1

## Environment
K8s v1.31.7

### OpenTelemetry Collector configuration

```yaml
config:
    exporters:
      debug:
        verbosity: basic
      kafka/logs:
        auth:
          tls:
            ca_file: /etc/certs/client/ca.crt
            cert_file: /etc/certs/client/tls.crt
            insecure: false
            key_file: /etc/certs/client/tls.key
            reload_interval: 2h
        brokers:
        - ${env:KAFKA_BROKER}
        encoding: otlp_proto
        partition_logs_by_resource_attributes: true
        producer:
          compression: lz4
          required_acks: 1
        protocol_version: 3.0.0
        sending_queue:
          batch:
            flush_timeout: 200ms
            max_size: ${env:KAFKA_EXPORTER_BATCH_SIZE}
          block_on_overflow: true
          num_consumers: ${env:KAFKA_EXPORTER_QUEUE_CONSUMERS}
          queue_size: ${env:KAFKA_EXPORTER_QUEUE_SIZE}
          sizer: bytes
          wait_for_result: true
        topic: ${env:KAFKA_TOPIC_LOGS}
      kafka/metrics:
        auth:
          tls:
            ca_file: /etc/certs/client/ca.crt
            cert_file: /etc/certs/client/tls.crt
            insecure: false
            key_file: /etc/certs/client/tls.key
            reload_interval: 2h
        brokers:
        - ${env:KAFKA_BROKER}
        encoding: otlp_proto
        partition_metrics_by_resource_attributes: true
        producer:
          compression: lz4
          required_acks: 1
        protocol_version: 3.0.0
        sending_queue:
          batch:
            flush_timeout: 200ms
            max_size: ${env:KAFKA_EXPORTER_BATCH_SIZE}
          block_on_overflow: true
          num_consumers: ${env:KAFKA_EXPORTER_QUEUE_CONSUMERS}
          queue_size: ${env:KAFKA_EXPORTER_QUEUE_SIZE}
          sizer: bytes
          wait_for_result: true
        topic: ${env:KAFKA_TOPIC_METRICS}
      kafka/traces:
        auth:
          tls:
            ca_file: /etc/certs/client/ca.crt
            cert_file: /etc/certs/client/tls.crt
            insecure: false
            key_file: /etc/certs/client/tls.key
            reload_interval: 2h
        brokers:
        - ${env:KAFKA_BROKER}
        encoding: otlp_proto
        partition_traces_by_id: true
        producer:
          compression: lz4
          required_acks: 1
        protocol_version: 3.0.0
        sending_queue:
          batch:
            flush_timeout: 200ms
            max_size: ${env:KAFKA_EXPORTER_BATCH_SIZE}
          block_on_overflow: true
          num_consumers: ${env:KAFKA_EXPORTER_QUEUE_CONSUMERS}
          queue_size: ${env:KAFKA_EXPORTER_QUEUE_SIZE}
          sizer: bytes
          wait_for_result: true
        topic: ${env:KAFKA_TOPIC_TRACES}
      nop: {}
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
    processors:
      attributes/promtail:
        actions:
        - action: delete
          key: filename
        - action: insert
          from_attribute: node_name
          key: k8s.node.name
        - action: delete
          key: node_name
        - action: insert
          from_attribute: pod
          key: k8s.pod.name
        - action: delete
          key: pod
        - action: insert
          from_attribute: pod_ip
          key: k8s.pod.ip
        - action: delete
          key: pod_ip
        - action: insert
          from_attribute: stream
          key: log.iostream
        - action: delete
          key: stream
        - action: insert
          from_attribute: app
          key: k8s.pod.labels.app
        - action: delete
          key: app
        - action: insert
          from_attribute: instance
          key: k8s.pod.labels.instance
        - action: delete
          key: instance
        - action: insert
          from_attribute: component
          key: k8s.pod.labels.component
        - action: delete
          key: component
        - action: insert
          from_attribute: container
          key: k8s.container.name
        - action: delete
          key: container
        - action: insert
          from_attribute: namespace
          key: k8s.namespace.name
        - action: delete
          key: namespace
      batch:
        send_batch_max_size: 11000
        send_batch_size: 10000
        timeout: 1s
      filter/logs:
        error_mode: ignore
        logs:
          log_record:
          - Len(body) > 262144
      groupbyattrs/promtail:
        keys:
        - job
        - k8s.container.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.ip
        - k8s.pod.labels.app
        - k8s.pod.labels.component
        - k8s.pod.labels.instance
        - k8s.pod.name
        - log.iostream
      k8sattributes/promtail:
        auth_type: serviceAccount
        extract:
          labels:
          - from: namespace
            key: service_component
            tag_name: osdp.service_component
          metadata:
          - container.image.name
          - container.image.tag
          - k8s.cronjob.name
          - k8s.daemonset.name
          - k8s.deployment.name
          - k8s.job.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.name
          - k8s.pod.start_time
          - k8s.pod.uid
          - k8s.statefulset.name
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name
      memory_limiter:
        check_interval: 2s
        limit_percentage: 80
        spike_limit_percentage: 15
      resource/cluster:
        attributes:
        - action: insert
          key: k8s.cluster.name
          value: osdp-prod-azu-switzerlandnorth-2
      resource/service_component:
        attributes:
        - action: insert
          key: service_component
          value: centralinfrastructure
        - action: update
          from_attribute: osdp.service_component
          key: service_component
        - action: delete
          key: osdp.service_component
    receivers:
      jaeger:
        protocols:
          thrift_compact:
            endpoint: 0.0.0.0:6831
      loki/promtail:
        protocols:
          http:
            endpoint: 0.0.0.0:3500
        use_incoming_timestamp: true
      nop: {}
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            max_recv_msg_size_mib: 32
          http:
            endpoint: 0.0.0.0:4318
      zipkin:
        endpoint: 0.0.0.0:9411
    service:
      extensions:
      - health_check
      - pprof
      pipelines:
        logs/otlp:
          exporters:
          - kafka/logs
          processors:
          - memory_limiter
          - filter/logs
          receivers:
          - otlp
        logs/promtail:
          exporters:
          - kafka/logs
          processors:
          - memory_limiter
          - attributes/promtail
          - groupbyattrs/promtail
          - k8sattributes/promtail
          - resource/service_component
          - resource/cluster
          receivers:
          - loki/promtail
        metrics/incoming:
          exporters:
          - kafka/metrics
          processors:
          - memory_limiter
          receivers:
          - otlp
        traces/tempo:
          exporters:
          - kafka/traces
          processors:
          - memory_limiter
          receivers:
          - jaeger
          - otlp
          - zipkin
      telemetry:
        logs:
          disable_caller: false
          disable_stacktrace: true
          encoding: json
          level: info
          processors:
          - batch:
              exporter:
                otlp:
                  endpoint: http://internal-telemetry-collector.otel.svc:4318
                  protocol: http/protobuf
        metrics:
          address: 0.0.0.0:8888
          level: detailed
          readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888
        resource:
          component: otel-collector
          k8s.cluster.name: osdp-prod-azu-switzerlandnorth-2
          k8s.namespace.name: ${env:POD_NAMESPACE}
          k8s.node.name: ${env:NODE_NAME}
          k8s.pod.ip: ${env:POD_IP}
          k8s.pod.name: ${env:POD_NAME}
          service.name: experimental-otel-ingress-kafka
        traces:
          processors:
          - batch:
              exporter:
                otlp:
                  endpoint: http://internal-telemetry-collector.otel.svc:4318
                  protocol: http/protobuf
          propagators:
          - tracecontext
```

### Log output

```shell

```

### Additional context

We have Istio service mesh in place, and the traffic towards these collectors is mirrored using a virtual service.
