### ISSUE TITLE
temporality_preference is ignore when using v0.2.0 of the configuration

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#13080]
### Component(s)

service

### What happened?

The configuration `temporality_preference` is ignored if the `service::telemetry::metrics` configuration is parsed by the v0.2.0 schema. This is because the fix to support temporality preference only exists in the v0.3.0 package

### Collector version

main

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by codeboten** [comment]
A workaround for this is to update the config to parse correctly w/ v0.3.0

```
          - periodic:
              exporter:
                otlp:
                  endpoint: https://${MY_BACKEND}
                  headers:
                    - name: key
                       value: value
                  protocol: http/protobuf
                  temporality_preference: delta
              interval: 10000
              timeout: 5000
```
