### ISSUE TITLE
add telemetry in bytes

### ISSUE THREAD

**Issue by povilasv** [open-telemetry/opentelemetry-collector#13105]
### Component(s)

processor/processorhelper, receiver/receiverhelper

### Describe the issue you're reporting

Add a metric that shows the amount of data received / processed in bytes.

Example:

```
    receiver_accepted_span_bytes:
      enabled: true
      stability:
        level: alpha
      description: Number of bytes of spans successfully pushed into the pipeline.
      unit: "byte"
      sum:
        value_type: int
        monotonic: true
```

My use case this, when trying to use bytes based in exporter, its hard to estimate the queue size and batch size from telemetry.

Both receivers report data in units, not in bytes. And items might have different sizes. One huge span can make my queue size large, but also 100 small spans can have no effect to my queue size. How do I know?

It would be easier if receivers and processors would also report bytes.
