### ISSUE TITLE
Not possible to set an attribute to `foo: bar` via an environment variable

### ISSUE THREAD

**Issue by graywolf-s1** [open-telemetry/opentelemetry-collector#13171]
### Component(s)

confmap, confmap/provider/envprovider

### What happened?

**Describe the bug**
I am trying to set a resource attribute to a string `foo: bar` via environment variable, but it does not seem to be possible.

**Steps to reproduce**
Given the following snippet in configuration file:
```
  resource:
    attributes:
      - key: app.version
        action: upsert
        value: ${env:_version}
```

I did not find a value I could use for the `_version` variable to get the attribute added with value `foo: bar`.

Directly using `foo: bar` leads to `     -> app.version: Map({"foo":"bar"})`.  Notice the `Map` type there.

Trying `'foo: bar'` (since it seems to be parsing YAML) leads to `     -> app.version: Str('foo: bar')`.  Notice the `'` which should not be there.

I have tried few other variants, but none is working.

**What did you expect to see?**
The attribute to be set to `Str(foo: bar)`.

**What did you see instead?**
The attribute is either `Str('foo: bar')` or `Map({"foo":"bar"})`.

### Collector version

0.126.0

### OpenTelemetry Collector configuration

```yaml

```

### Log output

```shell

```

**Comment by mx-psi** [comment]
@graywolf-s1 I don't mean this as a definitive solution but just so that you have some workarounds documented:

1. If there is a fixed part of your string, (say, for example, you always have a `v` prefix), you can work around this by forcing the configuration loading system to use `v${env:_version}`
2. You can load the whole item from the `attributes` list from a list:

```yaml
# Content of environment variable named _version_action
key: app.version
action: upsert
value: "foo: bar"
```

and then load it as `- ${env:_version_action}`.
3. If you are using a custom distribution, you can build a custom provider named `strenv` that returns the raw string you pass to it without any YAML parsing and include it in your distribution


Ultimately I think we should provide (3) from our end but until that happens I hope these can serve as workarounds
