### ISSUE TITLE
Collector cannot start when internal telemetry with periodic reader is enabled

### ISSUE THREAD

**Issue by nickytd** [open-telemetry/opentelemetry-collector#13195]
### Component(s)

service

### What happened?

**Describe the bug**
`otel-collector` cannot parse following configuration and fails to start.

```
...
  telemetry:
    metrics:
      level: detailed
      readers:
        - periodic:
            exporter:
              otlp_http:
                endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
                temporality_preference: delta
...
```

The configuration is obtained following: [kitchen-sink.yaml]( https://github.com/open-telemetry/opentelemetry-configuration/blob/main/examples/kitchen-sink.yaml)

**Steps to reproduce**
Here is a docker compose illustrating the problem

```
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:9090'
      - '--web.enable-otlp-receiver'
    networks:
    - opentelemetry

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel
    volumes:
      - ./otel-config.yml:/etc/otel/otel-config.yml
    command:
      - '--config=/etc/otel/otel-config.yml'
    networks:
      - opentelemetry
    depends_on:
      - prometheus

networks:
  opentelemetry:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
```

**What did you expect to see?**
collector emitting internal metrics to OTLP enabled backend

**What did you see instead?**
collector fails to start

### Collector version

v0.128.0

## Environment
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

### OpenTelemetry Collector configuration

```yaml
receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

exporters:
  otlphttp/metrics:
    metrics_endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics

processors:
  batch:
    timeout: 5s
    send_batch_size: 1000

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics]

  telemetry:
    logs:
      level: debug
      encoding: console
      output_paths: [stdout]
      error_output_paths: [stderr]

    metrics:
      level: detailed
      readers:
        - periodic:
            exporter:
              otlp_http:
                endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
                temporality_preference: delta
```

### Log output

```shell
otel        | panic: reflect: Key of non-map type interface {}
otel        |
otel        | goroutine 1 [running]:
otel        | reflect.(*rtype).Key(0x10?)
otel        | 	reflect/map_swiss.go:24 +0x80
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeMap(0x400132e180, {0x4000125920, 0x1c}, {0x95d49e0, 0x40011db1d0}, {0x8fa3b20?, 0x40011db1b0?, 0x14790c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:867 +0x88
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStructFromMap(0x400132e180, {0x4000125920, 0x1c}, {0x95d51e0?, 0x40011daf60?, 0x9ddd140?}, {0x9ddd140?, 0x40011db1a0?, 0x40010d5ad8?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1504 +0x1350
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStruct(0x400132e180, {0x4000125920, 0x1c}, {0x95d51e0?, 0x40011daf60?}, {0x9ddd140?, 0x40011db1a0?, 0x2746c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1305 +0x3f8
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x400132e180, {0x4000125920, 0x1c}, {0x95d51e0, 0x40011daf60}, {0x9ddd140?, 0x40011db1a0?, 0x0?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:532 +0x71c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStructFromMap(0x400132e180, {0x4000f2aa50, 0x13}, {0x95d51e0?, 0x40011dae40?, 0x9ddd200?}, {0x9ddd200?, 0x40011db1a0?, 0x40010d65c8?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1489 +0x730
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStruct(0x400132e180, {0x4000f2aa50, 0x13}, {0x95d51e0?, 0x40011dae40?}, {0x9ddd200?, 0x40011db1a0?, 0xfc100?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1305 +0x3f8
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x400132e180, {0x4000f2aa50, 0x13}, {0x95d51e0, 0x40011dae40}, {0x9ddd200?, 0x40011db1a0?, 0x95d51e0?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:532 +0x71c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodePtr(0x400132e180, {0x4000f2aa50, 0x13}, {0x95d51e0, 0x40011dae40}, {0x9142720?, 0x40011db110?, 0x2746c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1131 +0x3a4
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x400132e180, {0x4000f2aa50, 0x13}, {0x95d51e0, 0x40011dae40}, {0x9142720?, 0x40011db110?, 0x400132f090?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:536 +0x68c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStructFromMap(0x400132e180, {0x4000d7cf40, 0xa}, {0x95d51e0?, 0x40011dacf0?, 0x9ddd2c0?}, {0x9ddd2c0?, 0x40011db110?, 0x40010d7278?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1489 +0x730
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStruct(0x400132e180, {0x4000d7cf40, 0xa}, {0x95d51e0?, 0x40011dacf0?}, {0x9ddd2c0?, 0x40011db110?, 0x6f168?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1305 +0x3f8
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x400132e180, {0x4000d7cf40, 0xa}, {0x95d51e0, 0x40011dacf0}, {0x9ddd2c0?, 0x40011db110?, 0xbdb0a08?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:532 +0x71c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeSlice(0x400132e180, {0x924f6a8, 0x7}, {0x8917380, 0x40013344c8}, {0x890afe0?, 0x4000e4f368?, 0x2746c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1220 +0x83c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x400132e180, {0x924f6a8, 0x7}, {0x8917380, 0x4001231e60}, {0x890afe0?, 0x4000e4f368?, 0x1c0000001c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:538 +0x6c4
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStructFromMap(0x400132e180, {0x0, 0x0}, {0x95d51e0?, 0x40011dac90?, 0x9b37aa0?}, {0x9b37aa0?, 0x4000e4f360?, 0x40010d8038?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1489 +0x730
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStruct(0x400132e180, {0x0, 0x0}, {0x95d51e0?, 0x40011dac90?}, {0x9b37aa0?, 0x4000e4f360?, 0x7a67d8?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1305 +0x3f8
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x400132e180, {0x0, 0x0}, {0x95d51e0, 0x40011dac90}, {0x9b37aa0?, 0x4000e4f360?, 0x8?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:532 +0x71c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).Decode(0x400132e180, {0x95d51e0, 0x40011dac90})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:434 +0xb4
otel        | go.opentelemetry.io/collector/confmap.decodeConfig(0x400123bb90, {0x9143200, 0x4000e4f360}, 0x1, 0x1)
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/confmap.go:300 +0x2e0
otel        | go.opentelemetry.io/collector/confmap.(*Conf).Unmarshal(0x400123bb90, {0x9143200, 0x4000e4f360}, {0x0, 0x0, 0x7e9dfc?})
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/confmap.go:103 +0xa0
otel        | go.opentelemetry.io/collector/service/telemetry/internal/migration.(*MetricsConfigV030).Unmarshal(0x4000e4f360, 0x400123bb90)
otel        | 	go.opentelemetry.io/collector/service@v0.128.0/telemetry/internal/migration/v0.3.0.go:75 +0x68
otel        | go.opentelemetry.io/collector/confmap.decodeConfig.unmarshalerHookFunc.func7({0x95d51e0?, 0x4001074fc0?, 0x40010d8588?}, {0x9b37aa0?, 0x4000e4f360?, 0x95d51e0?})
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/confmap.go:558 +0x240
otel        | go.opentelemetry.io/collector/confmap.decodeConfig.unmarshalerHookFunc.safeWrapDecodeHookFunc.func11({0x95d51e0?, 0x4001074fc0?, 0x4000e4f2e8?}, {0x9b37aa0?, 0x4000e4f360?, 0x4001074fc0?})
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/confmap.go:367 +0x74
otel        | go.opentelemetry.io/collector/confmap/internal/third_party/composehook.cachedDecodeHook.func3({0x95d51e0?, 0x4001074fc0?, 0x40010d8678?}, {0x9b37aa0?, 0x4000e4f360?, 0x866d8?})
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/internal/third_party/composehook/compose_hook.go:61 +0x34
otel        | go.opentelemetry.io/collector/confmap/internal/third_party/composehook.ComposeDecodeHookFunc.func1({0x95d51e0?, 0x4001074fc0?, 0x40010d8668?}, {0x9b37aa0?, 0x4000e4f360?, 0x4001074fc0?})
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/internal/third_party/composehook/compose_hook.go:94 +0xec
otel        | github.com/go-viper/mapstructure/v2.cachedDecodeHook.func3({0x95d51e0?, 0x4001074fc0?, 0x40010d86b8?}, {0x9b37aa0?, 0x4000e4f360?, 0x0?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/decode_hooks.go:55 +0x34
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x4001204ed0, {0x4000125320, 0x19}, {0x95d51e0, 0x4001074fc0}, {0x9b37aa0?, 0x4000e4f360?, 0x40011593e0?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:505 +0x498
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStructFromMap(0x4001204ed0, {0x4000f2aa08, 0x11}, {0x95d51e0?, 0x4001074f60?, 0xa001440?}, {0xa001440?, 0x4000e4f2e8?, 0x40010d9118?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1489 +0x730
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStruct(0x4001204ed0, {0x4000f2aa08, 0x11}, {0x95d51e0?, 0x4001074f60?}, {0xa001440?, 0x4000e4f2e8?, 0x2746c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1305 +0x3f8
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x4001204ed0, {0x4000f2aa08, 0x11}, {0x95d51e0, 0x4001074f60}, {0xa001440?, 0x4000e4f2e8?, 0x400123ab10?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:532 +0x71c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStructFromMap(0x4001204ed0, {0x8488596, 0x7}, {0x95d51e0?, 0x4001074f30?, 0xa000fc0?}, {0xa000fc0?, 0x4000e4f2e8?, 0x40010d9c08?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1489 +0x730
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStruct(0x4001204ed0, {0x8488596, 0x7}, {0x95d51e0?, 0x4001074f30?}, {0xa000fc0?, 0x4000e4f2e8?, 0x2746c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1305 +0x3f8
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x4001204ed0, {0x8488596, 0x7}, {0x95d51e0, 0x4001074f30}, {0xa000fc0?, 0x4000e4f2e8?, 0xf704c?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:532 +0x71c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStructFromMap(0x4001204ed0, {0x0, 0x0}, {0x95d51e0?, 0x4001074f00?, 0xa32b3c0?}, {0xa32b3c0?, 0x4000e4f2c0?, 0x40010da6f8?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1489 +0x730
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodeStruct(0x4001204ed0, {0x0, 0x0}, {0x95d51e0?, 0x4001074f00?}, {0xa32b3c0?, 0x4000e4f2c0?, 0x87a06e0?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1305 +0x3f8
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x4001204ed0, {0x0, 0x0}, {0x95d51e0, 0x4001074f00}, {0xa32b3c0?, 0x4000e4f2c0?, 0x95d51e0?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:532 +0x71c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decodePtr(0x4001204ed0, {0x0, 0x0}, {0x95d51e0, 0x4001074f00}, {0x87a06e0?, 0x4000e04fd0?, 0x7a67d8?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:1131 +0x3a4
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).decode(0x4001204ed0, {0x0, 0x0}, {0x95d51e0, 0x4001074f00}, {0x87a06e0?, 0x4000e04fd0?, 0x0?})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:536 +0x68c
otel        | github.com/go-viper/mapstructure/v2.(*Decoder).Decode(0x4001204ed0, {0x95d51e0, 0x4001074f00})
otel        | 	github.com/go-viper/mapstructure/v2@v2.2.1/mapstructure.go:434 +0xb4
otel        | go.opentelemetry.io/collector/confmap.decodeConfig(0x4001204260, {0x88d7380, 0x4000e04fd0}, 0x1, 0x0)
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/confmap.go:300 +0x2e0
otel        | go.opentelemetry.io/collector/confmap.(*Conf).Unmarshal(0x4001204260, {0x88d7380, 0x4000e04fd0}, {0x0, 0x0, 0x4001074630?})
otel        | 	go.opentelemetry.io/collector/confmap@v1.34.0/confmap.go:103 +0xa0
otel        | go.opentelemetry.io/collector/otelcol.unmarshal(0x4001204260, {0x4000ee82a0, 0x4000ee88d0, 0x4000ee85a0, 0x4000ee80c0, 0x4000ee8b10, 0x4000ee82d0, 0x4000ee8900, 0x4000ee85d0, 0x4000ee80f0, ...})
otel        | 	go.opentelemetry.io/collector/otelcol@v0.128.0/unmarshaler.go:46 +0x2ac
otel        | go.opentelemetry.io/collector/otelcol.(*ConfigProvider).Get(0x10?, {0xbeccd40?, 0x134659e0?}, {0x4000ee82a0, 0x4000ee88d0, 0x4000ee85a0, 0x4000ee80c0, 0x4000ee8b10, 0x4000ee82d0, 0x4000ee8900, ...})
otel        | 	go.opentelemetry.io/collector/otelcol@v0.128.0/configprovider.go:62 +0xcc
otel        | go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0x400171ec60, {0xbeccd40, 0x134659e0})
otel        | 	go.opentelemetry.io/collector/otelcol@v0.128.0/collector.go:180 +0x10c
otel        | go.opentelemetry.io/collector/otelcol.(*Collector).Run(0x400171ec60, {0xbeccd40, 0x134659e0})
otel        | 	go.opentelemetry.io/collector/otelcol@v0.128.0/collector.go:312 +0x3c
otel        | go.opentelemetry.io/collector/otelcol.NewCommand.func1(0x4000643208, {0xaacba14?, 0x7?, 0xaabf6bb?})
otel        | 	go.opentelemetry.io/collector/otelcol@v0.128.0/command.go:39 +0x80
otel        | github.com/spf13/cobra.(*Command).execute(0x4000643208, {0x40001a4330, 0x1, 0x1})
otel        | 	github.com/spf13/cobra@v1.9.1/command.go:1015 +0x844
otel        | github.com/spf13/cobra.(*Command).ExecuteC(0x4000643208)
otel        | 	github.com/spf13/cobra@v1.9.1/command.go:1148 +0x384
otel        | github.com/spf13/cobra.(*Command).Execute(0xaf66be8?)
otel        | 	github.com/spf13/cobra@v1.9.1/command.go:1071 +0x1c
otel        | main.runInteractive({0xaf66be8, {{0xab10b34, 0xf}, {0xabe74ae, 0x1f}, {0xaacb85b, 0x7}, {}}, 0x0, {{{0x0, ...}, ...}, ...}, ...})
otel        | 	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:70 +0x44
otel        | main.run(...)
otel        | 	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main_others.go:10
otel        | main.main()
otel        | 	github.com/open-telemetry/opentelemetry-collector-releases/contrib/main.go:63 +0x544
```

### Additional context

Here is a [gist link](https://gist.github.com/nickytd/49fe7c8492b01325925901be424e480a) containing configuration files.

**Comment by nickytd** [comment]
My fault, was looking in the wrong example. the proper configuration is
```
metrics:
    level: detailed
    readers:
    - # push metrics to Prometheus backend
      periodic:
        interval: 30000
        timeout: 10000
        exporter:
          otlp:
            protocol: http/protobuf
            endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
```
