### ISSUE TITLE
OTLP/HTTP receiver does not respond with google.rpc.Status on 400

### ISSUE THREAD

**Issue by fbogsany** [open-telemetry/opentelemetry-collector#1357]
**Describe the bug**
The OTLP/HTTP OTEP states:
> Response body for all `HTTP 4xx` and `HTTP 5xx` responses MUST be a ProtoBuf-encoded [Status](https://godoc.org/google.golang.org/genproto/googleapis/rpc/status#Status) message that describes the problem.

The collector's HTTP 400 response does not appear to contain a Protobuf-encoded google.rpc.Status message. The response body *is* Protobuf-encoded, but I can't tell what type it is.

**Steps to reproduce**
This was discovered while debugging #1344, so these steps only work with that bug present:

1. Setup Collector with otlp receiver.
2. Send OTLP/HTTP request with “Content-Encoding: gzip” request header and gzipped content.

**What did you expect to see?**
HTTP 400 response with a Protobuf-encoded google.rpc.Status message. This is specified as:
```protobuf
message Status {
  int32 code = 1;
  string message = 2;
  repeated google.protobuf.Any details = 3;
}
```

**What did you see instead?**
Debugging in Ruby, I saw:
```ruby
(byebug) Google::Rpc::Status.decode(response.body)
*** Google::Protobuf::ParseError Exception: Error occurred during parsing: Invalid wire type
(byebug) response
#<Net::HTTPBadRequest 400 Bad Request readbody=true>
(byebug) response.body.b
"\n\x19proto: illegal wireType 7\x10\x03\x1A\x19proto: illegal wireType 7"
```

Picking this apart manually as a Protobuf message, we have:
```
0b1010 => field_number = 1, wire_type = 2 (length-encoded)
0x19 => length = 25
"proto: illegal wireType 7"
0b10000 => field_number = 2, wire_type = 0 (varint)
0x3
0b1110 => field_number = 3, wire_type = 2 (length-encoded)
0x19 => length = 25
"proto: illegal wireType 7"
```
which looks like a message type:
```protobuf
message Foo {
  string bar = 1;
  int32 baz = 2;
  string quux = 3;
}
```

**What version did you use?**
`v0.5.0`

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      http:
exporters:
  jaeger:
    insecure: true
    endpoint: shopify-tracing.railgun:14250
extensions:
  zpages:
service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
```

**Environment**
OS: macOS Catalina 10.15.5 (19F101)
Compiler(if manually compiled): go version go1.13.3 darwin/amd64

**Additional context**
N/A
