### ISSUE TITLE
Support "propagating" metric labels to resource attributes via processor config

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-collector#1358]
**Is your feature request related to a problem? Please describe.**
I have a concrete use case where I need to do the following:
1. Prometheus receiver is configured to inject Pod's namespace and name into collected metrics:
```yaml
relabel_configs:
- source_labels: [__meta_kubernetes_namespace]
  action: replace
  target_label: kubernetes_namespace
- source_labels: [__meta_kubernetes_pod_name]
  action: replace
  target_label: kubernetes_pod_name
```
2. I need to transform these two labels into resource attributes as defined in https://github.com/open-telemetry/opentelemetry-collector/blob/2ba9cdcc2b3c7f45288c1152b97e9ec64b9d6706/translator/conventions/opentelemetry.go#L35-L36

**Describe the solution you'd like**
It may make sense to support this in **Resource Processor**, **Attributes Processor** or some other core component, since it seems like a generic functionality.

**Describe alternatives you've considered**
Currently I have to write a custom processor to perform this custom transformation.
