### ISSUE TITLE
AnyValue

### ISSUE THREAD

**Issue by obecny** [open-telemetry/opentelemetry-collector#1363]
**Steps to reproduce**
1. Get latest version for example `71392e5d543eca6e895d852c9bad122b18ae7b23`
2. Try to send span with attributes converted to latest proto format using AnyValue for example
```
{ key: 'service.name', value: { stringValue: 'basic-service' } }
```

**What did you expect to see?**
I expect to see the span in zipkin

**What did you see instead?**
1. For grpc it works fine
2. For json over http it doesn't
3. For proto over http it doesn't

**What version did you use?**
https://hub.docker.com/r/otel/opentelemetry-collector-dev/tags
`71392e5d543eca6e895d852c9bad122b18ae7b23`

**What config did you use?**
```
version: "3"
services:
  # Collector
  collector:
#    image: otel/opentelemetry-collector-dev:2ba9cdcc2b3c7f45288c1152b97e9ec64b9d6706
    image: otel/opentelemetry-collector-dev:71392e5d543eca6e895d852c9bad122b18ae7b23
#    image: otel/opentelemetry-collector-dev:latest
#    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    networks:
      - otelcol
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "55680:55680"
    depends_on:
      - zipkin-all-in-one

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    networks:
      - otelcol
    ports:
      - "9411:9411"

networks:
  otelcol:
```
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch, queued_retry]
```

**Environment**
Docker container, osx

**Additional context**

I'm getting error
code: HPE_INVALID_CONSTANT
reason: Expected HTTP/

1. For Json over http
'Content-Type': 'application/json'

2. For Proto over http
'Content-Type': 'application/x-protobuf'

Collector url: `http://localhost:55680/v1/trace`
