### ISSUE TITLE
Span Attributes are Null

### ISSUE THREAD

**Issue by stevencl1013** [open-telemetry/opentelemetry-collector#1385]
**Describe the bug**
Span attributes are null

**Steps to reproduce**
Send spans with attributes. I used an example similar to the [http example](https://github.com/open-telemetry/opentelemetry-go/tree/master/example/http) in the `opentelemetry-go` repo, except I'm using the `otlp` exporter pointing at my collector.

**What did you expect to see?**
I expect to see values for each of my span attributes, as shown below:
![image](https://user-images.githubusercontent.com/17007125/87726288-b852bb80-c78c-11ea-95ed-d6026ffb03fa.png)

**What did you see instead?**
Attribute values were null. (`g.co/agent` label was added by the exporter after the fact)
![image](https://user-images.githubusercontent.com/17007125/87727182-775ba680-c78e-11ea-9e74-ef93ca0e586e.png)

**What version did you use?**
Docker image: [otel/opentelemetry-collector-contrib:0.6.0](https://hub.docker.com/layers/otel/opentelemetry-collector-contrib/0.6.0/images/sha256-fc7320d879ffc132096db60abd668154555a7e1a771c3374d1303af412ee7f1d?context=explore)
Also experienced this issue in `0.5.0`, but not in `0.4.0`.

**What config did you use?**
Config: 
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55678
exporters:
  stackdriver:
    project: "my-gcp-project-id"
processors:
  batch:
  queued_retry:
extensions:
  pprof:
    endpoint: :1888
service:
  extensions: [pprof]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [stackdriver]
      processors: [batch, queued_retry]
    metrics:
      receivers: [otlp]
      exporters: [stackdriver]
```

**Environment**
Running in GKE. Also experienced this issue using `otlp` exporter

**Comment by stevencl1013** [comment]
@tigrannajaryan

**Comment by jufab** [comment]
To add more information in this issue, i have the same problem with Jaeger or Zipkin exporter. 
And,  the service name is missing.
(Works fine with the 0.4.0 collector)
**my config**
```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:55680"
        cors_allowed_origins:
        - http://*
        - https://*
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
processors:
  batch:
    send_batch_size: 1
extensions:
  zpages:
    endpoint: "0.0.0.0:55679"
service:
  extensions : [zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger,zipkin]
```

**Payload send to otlp**

```bash
curl 'http://localhost:55680/v1/trace' \
  --data-binary '{"resourceSpans":[{"resource":{"attributes":[{"key":"service.name","type":0,"stringValue":"example-app"},{"key":"telemetry.sdk.language","type":0,"stringValue":"webjs"},{"key":"telemetry.sdk.name","type":0,"stringValue":"opentelemetry"},{"key":"telemetry.sdk.version","type":0,"stringValue":"0.9.0"}],"droppedAttributesCount":0},"instrumentationLibrarySpans":[{"spans":[{"traceId":"yizf+YkMQrkekwbM0ipIgg==","spanId":"mrAdWyQZC2E=","name":"http://localhost:4200/api/","kind":1,"startTimeUnixNano":1595018191682410000,"endTimeUnixNano":1595018191791799800,"attributes":[{"key":"http.method","type":0,"stringValue":"GET"},{"key":"http.url","type":0,"stringValue":"http://localhost:4200/api/"},{"key":"http.status_code","type":2,"doubleValue":200}],"droppedAttributesCount":0,"events":[{"timeUnixNano":1595018191791530000,"name":"response","attributes":[{"key":"body","type":0,"stringValue":"{\"result\":\"ok\"}"}],"droppedAttributesCount":0}],"droppedEventsCount":0,"status":{"code":0},"links":[],"droppedLinksCount":0}],"instrumentationLibrary":{"name":"opentelemetry - webjs","version":"0.9.0"}}]}]}'
```

**Zipkin result**
<img width="1630" alt="zipkin-error" src="https://user-images.githubusercontent.com/25395032/87829241-eadce100-c87e-11ea-9c96-c63254fa3609.png">

**Jaeger result**
<img width="1675" alt="jaeger-error" src="https://user-images.githubusercontent.com/25395032/87829267-fa5c2a00-c87e-11ea-93f5-962a352a441f.png">
