### ISSUE TITLE
Add default collection interval setting

### ISSUE THREAD

**Issue by jrcamp** [open-telemetry/opentelemetry-collector#1406]
**Is your feature request related to a problem? Please describe.**
Currently collection intervals are set on each receiver. A user should be able to configure the default collection interval globally then override that value per-receiver.

Example:

```yaml
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:

  redis:
     # would get 10s default

service:
  collection_interval: 10s
  pipelines:
    metrics:
      receivers: [hostmetrics, redis]
```
