### ISSUE TITLE
tail_sampling "always_sample" policy is not passing any spans

### ISSUE THREAD

**Issue by awwx** [open-telemetry/opentelemetry-collector#1467]
Adding a tail_sampling processor with the "always_sample" policy results in no spans being exported.

Running without the tail_sampling processor causes spans to be exported (in my config, to logging and to file).

Adding the tail_sampling processor with the "always_sample" policy causes no spans to be exported.

```
{"level":"info","ts":1596209369.7920508,"caller":"service/service.go:268","msg":"Everything is ready. Begin running and processing data."}
{"level":"info","ts":1596209374.9770184,"caller":"tailsamplingprocessor/processor.go:218","msg":"First trace data arrived, starting tail_sampling timers","component_kind":"processor","component_type":"tail_sampling","component_name":"tail_sampling"}
{"level":"debug","ts":1596209375.977212,"caller":"tailsamplingprocessor/processor.go:144","msg":"Sampling Policy Evaluation ticked","component_kind":"processor","component_type":"tail_sampling","component_name":"tail_sampling"}
{"level":"debug","ts":1596209375.9772725,"caller":"tailsamplingprocessor/processor.go:206","msg":"Sampling policy evaluation completed","component_kind":"processor","component_type":"tail_sampling","component_name":"tail_sampling","batch.len":0,"sampled":0,"notSampled":0,"droppedPriorToEvaluation":0,"policyEvaluationErrors":0}
{"level":"debug","ts":1596209376.9772344,"caller":"tailsamplingprocessor/processor.go:144","msg":"Sampling Policy Evaluation ticked","component_kind":"processor","component_type":"tail_sampling","component_name":"tail_sampling"}
{"level":"debug","ts":1596209376.9772794,"caller":"tailsamplingprocessor/processor.go:206","msg":"Sampling policy evaluation completed","component_kind":"processor","component_type":"tail_sampling","component_name":"tail_sampling","batch.len":0,"sampled":0,"notSampled":0,"droppedPriorToEvaluation":0,"policyEvaluationErrors":0}
```

**What version did you use?**

f95486 (master branch head) and v0.7.0

**What config did you use?**

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint:

processors:
  tail_sampling:
    policies:
      [
        {
          name: always,
          type: always_sample
        }
      ]

exporters:
  logging:
    loglevel: debug

  file:
    path: ./log.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [logging, file]
```

**Environment**

OS: Ubuntu 18.04.4 LTS

Compiler: go 1.14.6
