### ISSUE TITLE
GRPC MaxRecvMsgSizeMiB default value

### ISSUE THREAD

**Issue by morigs** [open-telemetry/opentelemetry-collector#1494]
[OTLP receiver docs](https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver/otlpreceiver) says that `MaxRecvMsgSizeMiB` (`max_recv_msg_size_mib`) is `Infinity` by default. But when I'm doing a benchmark I see a lot of error messages from trace exporter like this:

```
8 RESOURCE_EXHAUSTED: grpc: received message larger than max (4679564 vs. 4194304)
```

**Steps to reproduce**
Just send huge batch when using OTLP trace exporter

**What did you expect to see?**
I expect no errors

**What did you see instead?**
A lot of huge error messages

**What version did you use?**
Version: 0.7.0

**What config did you use?**
Agent:
```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: otel-collector:55680
    insecure: true

processors:
  memory_limiter:
    check_interval: 5s
    limit_mib: 2000
    spike_limit_mib: 500
    ballast_size_mib: 1000
  batch:
    timeout: 1s
  batch/2:
    send_batch_size: 2048
    timeout: 500ms
  queued_retry:
    backoff_delay: 2s
    queue_size: 100

extensions:
  zpages:
  health_check:

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, queued_retry]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch/2]
      exporters: [otlp]
```

Exporter:
```js
{
    url: 'localhost:55680',
    serviceName: 'some-service',
}
```

**Environment**
OS: Docker

**Additional context**
As we can see [here](https://github.com/open-telemetry/opentelemetry-collector/blob/63b1d77267d2f27bcdcb2c6af335960382d5b8d3/config/configgrpc/configgrpc.go#L246) `MaxRecvMsgSizeMiB ` is set only when config value is set (greater that zero). So when value provided in config default value from GRPC lib is used. And according to [GRPC lib docs](https://godoc.org/google.golang.org/grpc#MaxRecvMsgSize) the default value is 4MB.
