### ISSUE TITLE
Prometheus receiver doesn't work with https scheme

### ISSUE THREAD

**Issue by djjayeeta** [open-telemetry/opentelemetry-collector#1526]
**Describe the bug**
I have a Prometheus config file(the config file is correct as I have verified it with a prometheus server) which I am trying to use with prometheus receiver. I have copied the same config file but the metrics are not scraped by the receiver.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
Deployed the opentelemetry daemonset https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/master/examples/k8s.yaml with custom config.

receivers : prometheus exporter: logging (loglevel:debug)
**What did you expect to see?**
A clear and concise description of what you expected to see.
metrics in the logs 
**What did you see instead?**
A clear and concise description of what you saw instead.
No error in logs 
```
"level":"info","ts":1597130324.8573291,"caller":"service/service.go:268","msg":"Everything is ready. Begin running and processing data."
```
**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

otel/opentelemetry-collector-dev:latest@sha256:ceebae71600ece5b280f7b4f74e7dfde8670761cf84b5c2a5f17089e8db31be0

**What config did you use?**
Config: (e.g. the yaml config file)

```
      receivers:
        prometheus:
          use_start_time_metric: true
          config:
            scrape_configs:
            - job_name: dummy
              scrape_timeout: 10s
              scrape_interval: 15s
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - source_labels: [ __address__ ]
                regex: ([^:]+)(?::\d+)?
                replacement: "${ARG1}:9443"
                target_label: __address__
              - action: keep
                regex: dummy-pod
                source_labels:
                - __meta_kubernetes_pod_label_k8s_app
              scheme: https
              tls_config:
                cert_file: CERT_FILE
                insecure_skip_verify: true
                key_file: KEY_FILE
      exporters:
        logging:
          loglevel: debug
          sampling_initial: 5
          sampling_thereafter: 5
      service:
        pipelines:
          metrics/prom:
            receivers:
              - prometheus
            exporters:
              - logging
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")
n/a
**Additional context**
The same prometheus config seems to work with a separate Prometheus server.

Please guide me, where am I going wrong
