### ISSUE TITLE
Queued retry is too verbose and, yet, not informative enough

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#1604]
**Describe the bug**
When debugging a connectivity issue between the OpenTelemetry Collector and Jaeger Collector, I see the following repeatedly in the logs:

```
2020-08-20T13:15:37.320Z	INFO	loggingexporter/logging_exporter.go:247	TraceExporter	{"#spans": 1}
{"level":"warn","ts":1597929337.3209565,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"info","ts":1597929337.3229399,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"info","ts":1597929337.3229878,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"warn","ts":1597929337.32304,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"warn","ts":1597929337.3231988,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"info","ts":1597929337.324733,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"warn","ts":1597929337.3248084,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"info","ts":1597929337.3249671,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"warn","ts":1597929337.3250358,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"info","ts":1597929337.3251545,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"warn","ts":1597929337.3252296,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"info","ts":1597929337.325253,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"warn","ts":1597929337.3254435,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"info","ts":1597929337.3254714,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"warn","ts":1597929337.3256483,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
{"level":"info","ts":1597929337.3304687,"caller":"queuedprocessor/queued_processor.go:339","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
{"level":"warn","ts":1597929337.3305159,"caller":"queuedprocessor/queued_processor.go:333","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
```

This is too verbose, and yet, not very informative: as an operator, I don't need to know about each and every attempt. What I would need to know is the cause of the failure, which is not mentioned in the log statement.

**What did you expect to see?**
The exporter's error message.

**What did you see instead?**
Queued retry messages about backing off and resuming processing.

**What version did you use?**
`v0.8.0`

**What config did you use?**
Config: 
```yaml
    receivers:
      jaeger:
        protocols: 
          grpc:

    processors:
      queued_retry:

    exporters:
      logging:
      jaeger:
        endpoint: "simplest-collector-headless.default.svc:14250"
        ca_file: "/etc/pki/ca-trust/source/service-ca/service-ca.crt"
        server_name_override: "simplest-collector-headless.default.svc.cluster.local"

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: [queued_retry]
          exporters: [logging, jaeger]
```
