### ISSUE TITLE
Prometheus receiver does not scrape some Summary type metrics

### ISSUE THREAD

**Issue by djjayeeta** [open-telemetry/opentelemetry-collector#1638]
**Describe the bug**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
I have a Prometheus receiver + file exporter + logging exporter config. I expect to see all gauge, histogram and summary metric in the json file from file exporter.

**What did you see instead?**
I can only see Gauge metrics, some of histogram and summary in the json file from fileexporter and logging exporter.

Specifically _sum, _count for summary metrics are not available

The Prometheus receiver translates counter, histogram, and summary metrics into OTLP metrics with non-cumulative temporality. 

Is this the expected behavior with Promethues receiver? If so do I need modify/add a new fileexporter or the receiver to handle this scenario?

**What version did you use?**

otel/opentelemetry-collector-dev:latest@sha256:ceebae71600ece5b280f7b4f74e7dfde8670761cf84b5c2a5f17089e8db31be0

**What config did you use?**
```
receivers:
        prometheus:
          use_start_time_metric: false
          config:
            global:
              scrape_interval: 1m
            scrape_configs:
            - bearer_token_file:TOKEN
              job_name: kube-apiserver
              kubernetes_sd_configs:
              - role: pod
                selectors:
                - role: pod
                  field: "spec.nodeName=$NODE_NAME"
              params:
                component:
                - kube-apiserver
              metric_relabel_configs:
              - action: keep
                regex: (apiserver_admission_step_admission_duration_seconds_summary_sum)
                source_labels:
                - __name__
              relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                regex: ([^:]+)(?::\d+)?
                replacement: "${ARG1}:9443"
                source_labels:
                - __address__
                target_label: __address__
              - action: keep
                regex: kube-apiserver
                source_labels:
                - __meta_kubernetes_pod_label_component
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              scheme: https
              tls_config:
                cert_file: CERT_FILE
                insecure_skip_verify: true
                key_file: KEY_FILE
      exporters:
        file:
          path: /data/exporter/metrics-data.json
        logging:
          loglevel: debug
          sampling_initial: 5
          sampling_thereafter: 5
      service:
        pipelines:
          metrics/prom:
            receivers:
              - prometheus
            exporters:
              - logging
              - file
```

**Environment**
NA

**Additional context**
 My metrics are exposed in prometheus format, so I am left with the choice of using prometheus receiver. The above config works for a prometheus server. So the metric is available.

cc @huyan0 @alolita @jmacd @bogdandrutu

**Comment by huyan0** [comment]
I think this issue, #1541 and #1255 are all about the same problem. I don't think this will be fixed until OTLP settles, is that correct? @jmacd ?

**Comment by bogdandrutu** [comment]
This is a bug in the prometheus receiver, see https://github.com/open-telemetry/opentelemetry-collector/issues/1255

**Comment by bogdandrutu** [comment]
I don't think the file exporter does not work, it exports the entire data as json, are you sure you receive the data?

**Comment by djjayeeta** [comment]
Yes, the logging exporter shows the histogram and summary metrics but I see them as DoubleDataPoints https://github.com/open-telemetry/opentelemetry-collector/blob/8422992a20c343b3a95df57ad15f38bc8862c1d4/exporter/loggingexporter/logging_exporter.go#L135

**Comment by bogdandrutu** [comment]
That is not a histogram or summary it is a double data point.

**Comment by bogdandrutu** [comment]
Please add the logs.

**Comment by djjayeeta** [comment]
@bogdandrutu Sorry for the late response, it took me some time to debug. Both the logging exporter and file exporter is not able to export some summary type metrics, specially the _sum type

My config file

```
receivers:
        prometheus:
          use_start_time_metric: false
          config:
            global:
              scrape_interval: 1m
            scrape_configs:
            - bearer_token_file: /var/run/secrets/kubernetes.io/stackdriver-prometheus-scrape/token
              job_name: kube-apiserver
              kubernetes_sd_configs:
              - role: pod
                selectors:
                - role: pod
                  field: "spec.nodeName=$NODE_NAME"
              params:
                component:
                - kube-apiserver
              metric_relabel_configs:
              - action: keep
                regex: (apiserver_admission_step_admission_duration_seconds_summary_sum)
                source_labels:
                - __name__
              relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                regex: ([^:]+)(?::\d+)?
                replacement: "${ARG1}:9443"
                source_labels:
                - __address__
                target_label: __address__
              - action: keep
                regex: kube-apiserver
                source_labels:
                - __meta_kubernetes_pod_label_component
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              scheme: https
              tls_config:
                cert_file: /var/run/secrets/istio.io/prometheus-scrape/cert-chain.pem
                insecure_skip_verify: true
                key_file: /var/run/secrets/istio.io/prometheus-scrape/key.pem
      exporters:
        file:
          path: /data/exporter/metrics-data.json
        logging:
          loglevel: debug
          sampling_initial: 5
          sampling_thereafter: 5
      service:
        pipelines:
          metrics/prom:
            receivers:
              - prometheus
            exporters:
              - logging
              - file
```

With the same config I launched a prometheus server which is able to scrape the metric. I think this is issue of promethues receiver then which is not able to scrape apiserver_admission_step_admission_duration_seconds_summary_sum, 

This is specially interesting as apiserver_admission_step_admission_duration_seconds_summary is scrapped by the receiver and exported properly. Am I missing something?
