### ISSUE TITLE
Prometheus file-based service discovery failed

### ISSUE THREAD

**Issue by ckanner** [open-telemetry/opentelemetry-collector#1693]
I use prometheus as a metrics receiver, and use file-based service discovery. But it scrape failed. The error message is
`2020-08-31T17:06:34.178+0800    INFO    scrape/scrape.go:972            {"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "level": "debug", "scrape_pool": "dummy", "target": "http://192.168.100.162:8079/metrics", "msg": "Append failed", "err": "unable to find a target group with job=logic.cmdb_service"}
`
The reason may be a job label added to the json file.

The collector config file is

```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "dummy"
          scrape_interval: 10s
          file_sd_configs:
            - refresh_interval: 1m
              files:
                - "/data/conf/targets.json"
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: "(service_request_duration_seconds_total|service_requests_total)"
              action: keep

exporters:
  logging:
    loglevel: debug

processors:
  batch:
    send_batch_size: 10000
    timeout: 1000ms
  queued_retry:

service:
  pipelines:
    metrics:
      receivers:
        - prometheus
      processors:
        - batch
        - queued_retry
      exporters:
        - logging
```

The `targets.json` is 

```
[
  {
    "labels": {
      "job": "logic.cmdb_service"
    },
    "targets": [
      "192.168.100.152:8079"
    ]
  }
]
```

I want to use the `job` key to rewrite the scrape job name.

How can I resolve it?
