### ISSUE TITLE
 opentelemetry-collector service name issue with Prometheus

### ISSUE THREAD

**Issue by Hongbo-Miao** [open-telemetry/opentelemetry-collector#1752]
Moved from https://github.com/open-telemetry/opentelemetry-js/issues/1464

---

### What version of OpenTelemetry are you using?

```json
"@opentelemetry/api": "0.10.2",
"@opentelemetry/exporter-collector": "0.10.2",
"@opentelemetry/metrics": "0.10.2",
```

### What version of Node are you using?
Node 14

### What did you do?

To reproduce, use the demo at https://github.com/open-telemetry/opentelemetry-js/tree/master/examples/collector-exporter-node

### What did you expect to see?

To send metric successfully to Prometheus, OpenTelemetry collector in docker-compose.yaml has to use name "collector" currently, and cannot use other names such as "opentelemetry-collector".

If you use "opentelemetry-collector" for service name, you won't be able to get any metric data.

```yml
version: "3"
services:
  collector: # <- cannot use other service names
    image: otel/opentelemetry-collector:latest
    # ...
```

**Comment by Hongbo-Miao** [comment]
Sorry I was new to those docker-compose settings, I need change the targets in **prometheus.yaml** to same `container_name` in **docker-compose.yml**. Then I can use any name.

**docker-compose.yml**

```
  opentelemetry-collector:
    container_name: my_opentelemetry_collector
    image: otel/opentelemetry-collector:latest
    command: [
      "--config=/conf/otel-collector.config.yaml",
      "--log-level=DEBUG"
    ]
    volumes:
      - ./otel-collector.config.yaml:/conf/otel-collector.config.yaml
    ports:
      - "9464:9464"
      - "55680:55680"
      - "55681:55681"
```

**prometheus.yaml**

```
global:
  scrape_interval: 15s # Default is every 1 minute.

scrape_configs:
  - job_name: 'collector'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['my_opentelemetry_collector:9464'] # <- here needs to change to container_name
```
