### ISSUE TITLE
performance issue with otelcollector http receiver endpoint

### ISSUE THREAD

**Issue by tannaga** [open-telemetry/opentelemetry-collector#1770]
**Describe the bug**
This is related to performance of opentelemetry-collector. I have deployed opentelemtry-collector in k8s. In my pipeline, I have otlp http receiver, attribute processor (adding one tag) and logging exporter with sampling. I have allotted 1cpu and 4gb memory.
With this setup, at around 1250 request per second (1 span in each request), cpu utilization is well over 80%. With 3 spans in each request, cpu utilization was almost 100%. Each span has 10 attributes.
Number seems far too less compared to the numbers mentioned in [performance doc](https://github.com/open-telemetry/opentelemetry-collector/blob/master/docs/performance.md) (12K)

**Steps to reproduce**
Use the below Otel Configuration
```
service:
  extensions:
    - "health_check"
    - "pprof"
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - attributes
      exporters:
        - logging
extensions:
  health_check:
    port: 13133
  pprof:
    endpoint:  localhost:1777
    block_profile_fraction: 3
    mutex_profile_fraction: 5
processors:
  attributes:
    actions:
      - key: foo
        action: insert
        value: boo
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:8080
        tls_settings:
          cert_file: cert.pem
          key_file: key.pem
exporters:
  logging:
    sampling_initial: 1
    sampling_thereafter: 5000
```

**What did you expect to see?**
I was expecting that a pod will be able to support close to ~12k as mentioned in the Performance Section

**What did you see instead?**
Around 1250 spans, cpu utilization was close to 80%. Around 1500-1600 it was well over 100% and I started receiving error response

**What version did you use?**
Version: 0.6.0

**Environment**
OS: Linux amd64
Compiler: go 1.14
