### ISSUE TITLE
Print final configuration

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-collector#1791]
**Is your feature request related to a problem? Please describe.**

When running the collector I don't know what configuration is being used. For instance when the collector is run with the following config I don't know what is the batching, qretry or OTLP receiver configuration. To find out these details I have to read the docs.

```yaml
receivers:
    otlp:
        protocols:
            grpc:

exporters:
    logging:
        logLevel: debug

processors:
    batch:
    queued_retry:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging]
```

**Describe the solution you'd like**

I can think of two possible solutions:

1. Print each component config when the component is starting
2. Add a flag that prints full configuration to stdout

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/jaegertracing/jaeger/issues/2253
