### ISSUE TITLE
Jaeger exporter causes Jaeger to throw "received bogus greeting"

### ISSUE THREAD

**Issue by CarwynNelson** [open-telemetry/opentelemetry-collector#1861]
**Describe the bug**
If the opentelemetry jaeger exporter is talking to an insecure jaeger server without `insecure: true` set then the jaeger server logs the following error message:

```
{"level":"warn","ts":1601037362.4612963,"caller":"grpc@v1.29.1/server.go:732","msg":"grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x06\\\\x01\\\\x00\\\\x01\\\\x02\\\\x03\\\\x03\\\\r8zD\\\\xd8Ap\\\\xace\\\\v\\\\xe8,\\\\xef\\\"\"","system":"grpc","grpc_log":true}
```

The key part being:
```
received bogus greeting from client
```

**What did you expect to see?**
I expected the jaeger exporter to send data to jaeger without issues.

**What did you see instead?**
No data being sent to jaeger, and the following error in the jaeger server logs

```
{"level":"warn","ts":1601037362.4612963,"caller":"grpc@v1.29.1/server.go:732","msg":"grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams received bogus greeting from client: \\\"\\\\x16\\\\x03\\\\x01\\\\x01\\\\x06\\\\x01\\\\x00\\\\x01\\\\x02\\\\x03\\\\x03\\\\r8zD\\\\xd8Ap\\\\xace\\\\v\\\\xe8,\\\\xef\\\"\"","system":"grpc","grpc_log":true}
```

**What config did you use?**
```
receivers:
  zipkin:

exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true # without this it breaks

service:
  pipelines:
    traces:
      receivers: [zipkin]
      exporters: [jaeger]
```

**Environment**
OS: `otel/opentelemetry-collector-contrib` docker image at rev `c793e62be9a7`

**Additional context**
I was asked to raise this by @jpkrohling in gitter
