### ISSUE TITLE
Prometheus Receiver: kubernetes_sd_configs tag cannot be Unmarshalled

### ISSUE THREAD

**Issue by JasonXZLiu** [open-telemetry/opentelemetry-collector#1867]
**Describe the bug**

When using the Prometheus Receiver with the `kubernetes_sd_configs` tag, the OpenTelemetry Collector cannot unmarshal the Prometheus config yaml file.

**Steps to reproduce**

* Build the collector through `make otelcol`
* Using the config file provided below, run `./otelcol --config=config.yaml` (where otelcol is the binary produced in the bin directory)

**What did you expect to see?**

* Expecting the OTel Collector to create a Prometheus receiver with the correct configurations

**What did you see instead?**

```
2020/09/25 22:09:33 application run finished with error: cannot load configuration: error reading receivers configuration for prometheus: prometheus receiver failed to unmarshal yaml to prometheus config: yaml: unmarshal errors:
  line 8: field kubernetes_sd_configs not found in type config.ScrapeConfig
```

**What version did you use?**
Version:  master branch

**What config did you use?**
Config:

```
receivers:
    prometheus:
    config:
        scrape_configs:
        - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: ['localhost:8888']
        - job_name: 'kubernetes-apiservers'
            kubernetes_sd_configs:
            - role: endpoint

exporters:
    file:
    path: test.json
    logging:
    loglevel: debug
    prometheus:
    endpoint: ":9091"

extensions:
    health_check:
    pprof:
    endpoint: :1888
    zpages:
    endpoint: :55679

service:
    extensions: [pprof, zpages, health_check]
    pipelines:
    metrics:
        receivers: [prometheus]
        exporters: [logging, file]

```

**Environment**
OS: Mac 10.15.6 and Linux Alpine:3.12  
Compiler: Go 1.15.2

cc - @alolita @bogdandrutu
