### ISSUE TITLE
Empty objects as component config doesn't work anymore

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#1897]
**Describe the bug**
The collector is failing to start if an empty object provided as a config for any of the components. For example
```
extensions:
  health_check: {}
```

The collector fails to start with the following message:
```
2020-10-02T23:05:49.275-0700	INFO	service/service.go:298	Loading configuration...
Error: cannot load configuration: Service references extension "health_check" which does not exist
2020/10/02 23:05:49 application run finished with error: cannot load configuration: Service references extension "health_check" which does not exist
```

Empty values still work as expected:
```
extensions:
  health_check:
```

**Steps to reproduce**
Set an empty object as a config for any of the components. For example
```
extensions:
  health_check: {}
```

**What did you expect to see?**
Support empty objects the same way as empty values.

**What did you see instead?**
Collector failing to start.

**What version did you use?**
Version: `035aa5cf6c92678c3f8362d6916e18444a8250fb`

**Additional context**
Empty objects are pretty common in k8s world https://github.com/open-telemetry/opentelemetry-collector/blob/master/examples/k8s/otel-config.yaml#L35.

Also currently [helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts) has to use [empty objects](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/master/charts/opentelemetry-collector/templates/config/_base.tpl#L6) in order to have config overrides working. In Helm empty/null value in object overrides removes the key from an object.

**Comment by bogdandrutu** [comment]
Unfortunately I cannot reproduce this in tests, can you post a full config? One other thing that is important is the name of the config file.

**Comment by dmitryax** [comment]
here is the config example I used (just added `{}` to `health_check`):
```
extensions:
  health_check: {}
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

processors:
  batch:

exporters:
  logging:
    logLevel: debug

service:

  pipelines:

    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
```
