### ISSUE TITLE
opentelemetry-collector did not work well in K8s

### ISSUE THREAD

**Issue by yiyu0x** [open-telemetry/opentelemetry-collector#1904]
I followed [exporter-collector](https://www.npmjs.com/package/@opentelemetry/exporter-collector) to development my web app, and build envirement by docker-compose:

```yaml
version: '3'
services:
  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/conf/collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "55681:55681"
    depends_on:
      - jaeger
```

But now, I want to deploy `opentelemetry-collector` to k8s. I saw the [example](https://github.com/open-telemetry/opentelemetry-collector/blob/master/examples/k8s/otel-config.yaml), it did not open the 55681 port. 
Is it any spec to explain what is different between 55680 and 55681 port?  And what is different between image `opentelemetry-collector` and image `opentelemetry-collector-dev`?
