### ISSUE TITLE
zPages report wrong trace and span ids

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-collector#1988]
**Describe the bug**
zPages `/tracez` reports different traceId and spanId as compared to logging exporter on the console.

**Steps to reproduce**
Run Collector with configured zPages and logging exporter. Send a trace data to the Collector.

**What did you expect to see?**
traceId as reported by logging exporter on the console should be the same as traceId as reported by `/debug/tracez?zspanname=exporter%2flogging%2fTraceDataExported&ztype=1&zsubtype=2` zPage

**What did you see instead?**
Logging exporter:
`Trace ID       : dbe2df6af303c154763801d85e0495ca`
zPage for logging exporter:
`trace_id: 0eafbbf37b7a61e6527bd6ef66d9d4ad`
zPage for OTLP receiver:
`trace_id: be34cf862f3afb74332c810ce495af99`

**What version did you use?**
"Version":"latest","GitHash":"1f4a1946"

**What config did you use?**
```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  zipkin:
  otlp:
    protocols:
      grpc:

processors:
  batch:
  queued_retry:

  attributes/newenvironment:
    actions:
      - key: environment
        value: nikem
        action: insert

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    traces:
      receivers: [ zipkin, otlp ]
      processors: [ attributes/newenvironment, batch, queued_retry ]
      exporters: [ logging, sapm ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]

  extensions: [ health_check, pprof, zpages ]
```

**Environment**
OS: Ran as docker container from `otel/opentelemetry-collector-contrib-dev:latest` image
