### ISSUE TITLE
PrometheusReceiver Incorrectly Unmarshals Replacement Relabel Configs

### ISSUE THREAD

**Issue by JasonXZLiu** [open-telemetry/opentelemetry-collector#1999]
## Describe the bug

The PrometheusReceiver is unable to handle the *replacement* label of relabel_configs in the [Prometheus configurations](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config). The unmarshaller is not able to parse the `${1}${2}` that we use in the replacement value. Instead, it immediately drops the sequence after `$`.

This limits certain relabelling capabilities.

## Steps to reproduce

In the PrometheusReceiver code, we unmarshal, then marshal, and then unmarshal the configurations (to extract the actual Prometheus configurations). So, we can just print out the marshalled configurations out ([here](https://github.com/open-o11y/opentelemetry-collector/blob/master/receiver/prometheusreceiver/factory.go#L71)) to verify what our configurations turn into.

1. Edit the OpenTelemetry Collector code to print the unmarshalled configurations here: https://github.com/open-o11y/opentelemetry-collector/blob/master/receiver/prometheusreceiver/factory.go#L71
    1. Just add fmt.Println(string(out)) as out is a byte array
2. Run an instance of the collector with the configurations below
3. View the logs to find the printed out YAML configurations

## What did you expect to see?

I expected to see the exact PrometheusReceiver configurations that I set.

<pre>
global:
  scrape_interval: 15s
scrape_configs:
- job_name: kubernetes-ingresses
  kubernetes_sd_configs:
  - role: ingress
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - regex: (.+);(.+);(.+)
    <b>replacement: ${1}://${2}${3}</b>
    source_labels:
    - __meta_kubernetes_ingress_scheme
    - __address__
    - __meta_kubernetes_ingress_path
    target_label: __param_target
  ...
</pre>

## What did you see instead?

<pre>
global:
  scrape_interval: 15s
scrape_configs:
- job_name: kubernetes-ingresses
  kubernetes_sd_configs:
  - role: ingress
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - regex: (.+);(.+);(.+)
    <b>replacement: ://</b>
    source_labels:
    - __meta_kubernetes_ingress_scheme
    - __address__
    - __meta_kubernetes_ingress_path
    target_label: __param_target
  ...
</pre>

## What version did you use?

Master branch

## What config did you use?

```
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kubernetes-ingresses'

        metrics_path: /probe
        params:
          module: [http_2xx]

        kubernetes_sd_configs:
        - role: ingress

        relabel_configs:
        # Example relabel to probe only some ingresses that have "example.io/should_be_probed = true" annotation
        #  - source_labels: [__meta_kubernetes_ingress_annotation_example_io_should_be_probed]
        #    action: keep
        #    regex: true
        - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
          regex: (.+);(.+);(.+)
          replacement: ${1}://${2}${3}
          target_label: __param_target
        - target_label: __address__
          replacement: blackbox-exporter-service:9115
        - source_labels: [__param_target]
          target_label: instance
        - action: labelmap
          regex: __meta_kubernetes_ingress_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_ingress_name]
          target_label: kubernetes_name
```

## Environment
OS: Linux
Kubernetes: 1.17

cc - @alolita
