### ISSUE TITLE
Issue: Prometheus Remote Write Histograms not showing as expected

### ISSUE THREAD

**Issue by amanbrar1999** [open-telemetry/opentelemetry-collector#2040]
**Description of Bug**
In order to verify functionality of the Prometheus pipeline within the OTel Collector (ie. Prometheus Receiver + Prometheus Remote Write Exporter) I set up a sample app called “rpc” and attempted scraping metrics and visualizing them in Grafana using both the OTel Collector and a regular Prometheus server. Here are the results:

Output in Grafana from OTel Collector with Prometheus receiver + Prometheus remote write exporter:
![image](https://user-images.githubusercontent.com/24356083/97745134-c370f380-1abe-11eb-9b96-876855ec08a0.png)

Output in Grafana from helm Prometheus server:
![image](https://user-images.githubusercontent.com/24356083/97745184-d97eb400-1abe-11eb-8640-7868b84ecc37.png)

From my understanding these metrics should be pretty much identical, with some slight differences caused by different time stamps, however it is clear here that these are not minor differences, so something is not right in the OTel Collector Prometheus pipeline. 

**Steps to Reproduce:**

* Set up an instance of Grafana and Cortex, add the Cortex endpoint as a Datasource in Grafana
* Setup a Prometheus Server in a k8s cluster to scrape metrics and remote write them to the Cortex endpoint
* Deploy an instance of the Otel Collector with the same scraping configuration as the Prometheus Server setup in the Prometheus Receiver, and same Cortex endpoint specified in the Prometheus Remote Write Exporter. 
* You should see significant differences in the Histogram metrics

**What config did you use?**

OTel Collector Config: 

```
   receivers:
      prometheus:
        config:
          global:
            scrape_interval: 1m
            scrape_timeout: 10s
          scrape_configs:
          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
            - role: pod
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels: [__meta_kubernetes_namespace]
              target_label: Namespace
            - action: replace
              source_labels: [__meta_kubernetes_pod_name]
              target_label: pod_name
            - action: replace
              source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container_name
            - action: replace
              source_labels: [__meta_kubernetes_pod_controller_name]
              target_label: pod_controller_name
            - action: replace
              source_labels: [__meta_kubernetes_pod_controller_kind]
              target_label: pod_controller_kind
            - action: replace
              source_labels: [__meta_kubernetes_pod_phase]
              target_label: pod_phase           
            metric_relabel_configs:
            - action: drop
              source_labels: [__name__]
              regex: 'go_gc_duration_seconds.*'
          - job_name: 'kubernetes-service-endpoints'
            kubernetes_sd_configs:
            - role: endpoints
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: true
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)      
            - action: replace
              source_labels: [__meta_kubernetes_namespace]
              target_label: Namespace
            - action: replace
              source_labels: [__meta_kubernetes_service_name]
              target_label: Service
            - action: replace
              source_labels: [__meta_kubernetes_pod_node_name]
              target_label: kubernetes_node
            - action: replace
              source_labels: [__meta_kubernetes_pod_name]
              target_label: pod_name
            - action: replace
              source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container_name
          
    processors:
    
    exporters:
      prometheusremotewrite:
        endpoint: "cortex endpoint"
        namespace: "namespace"
        timeout: 10s
      logging:
        loglevel: debug

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: []
          exporters: [prometheusremotewrite, logging]
```

I used `make docker-otelcol` to get the docker image and deployed it using the example k8s config in the repo

Prometheus Server Config:

Identical to config within Prometheus receiver. I used the community helm charts so I set it up with these commands:

`helm install prometheus prometheus-community/prometheus —namespace NAMESPACE `
`helm upgrade --install prometheus prometheus-community/prometheus --namespace NAMESPACE -f ./override_values.yaml`

override_values.yaml:

```
serviceAccounts:
  create: false
  name: default

server:
    remoteWrite:
        - url: same cortex endpoint

serverFiles:
  prometheus.yml: // identical to prometheus receiver 
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          source_labels: [__meta_kubernetes_namespace]
          target_label: Namespace
        - action: replace
          source_labels: [__meta_kubernetes_pod_name]
          target_label: pod_name
        - action: replace
          source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container_name
        - action: replace
          source_labels: [__meta_kubernetes_pod_controller_name]
          target_label: pod_controller_name
        - action: replace
          source_labels: [__meta_kubernetes_pod_controller_kind]
          target_label: pod_controller_kind
        - action: replace
          source_labels: [__meta_kubernetes_pod_phase]
          target_label: pod_phase 
        metric_relabel_configs:
        - action: drop
          source_labels: [__name__]
          regex: 'go_gc_duration_seconds.*'
      - job_name: 'kubernetes-service-endpoints'
        kubernetes_sd_configs:
        - role: endpoints
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)      
        - action: replace
          source_labels: [__meta_kubernetes_namespace]
          target_label: Namespace
        - action: replace
          source_labels: [__meta_kubernetes_service_name]
          target_label: Service
        - action: replace
          source_labels: [__meta_kubernetes_pod_node_name]
          target_label: kubernetes_node
        - action: replace
          source_labels: [__meta_kubernetes_pod_name]
          target_label: pod_name
        - action: replace
          source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container_name
```

For the specific metrics in question, I deployed a sample app which the above config scrapes metrics from under the name “rpc”

```
---
# create rpc-app namespace
apiVersion: v1
kind: Namespace
metadata:
  name: rpc-app
  labels:
    name: rpc-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-app-deployment
  namespace: rpc-app
  labels:
    app: rpc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rpc-app
  template:
    metadata:
      labels:
        app: rpc-app
    spec:
      containers:
      - name: rpc-app-cont
        image: supergiantkir/prometheus-test-app
        ports:
        - name: web
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  namespace: rpc-app
  labels:
    app: rpc-app
  annotations:
    prometheus.io/probe: "true"
spec:
  ports:
  - name: web
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: rpc-app
  type: NodePort
---
```

**Environment**
Docker & Kubernetes

**What version did you use?**
latest, 0.13.0

For next steps, I will be investigating this issue, however I wanted it documented here on Github for awareness.
