### ISSUE TITLE
[filterprocessor] filter metrics using resource attributes

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector#2050]
Current `filter` processor can include/exclude metrics based on metric_name field. However, It would be good if we can filter metrics using metric_name and resource attributes together. For example, we have `container.cpu.utilized` metrics and it comes from three different containers. Customer cares about metrics from only one container and want to exclude other two. All the metrics have a resource attribute `container.id` and we want to filter the metrics using this field.

**Describe the solution you'd like**
Planning to introduce a new filter property `resource_attributes`.
```yaml
include:
        match_type: strict
        metric_names:
        - container.cpu.utilized
        - container.memory.utilized
        resource_attributes:
        - container.id: app_container_1_09809888
       
```
