### ISSUE TITLE
OTLP exporter doesn't load custom CA certs

### ISSUE THREAD

**Issue by kowshikn** [open-telemetry/opentelemetry-collector#2054]
**Describe the bug**
OTLP exporter doesn't load custom CA certs. This is happening only in v0.12.0 onwards. The 

**Steps to reproduce**
[tls.zip](https://github.com/open-telemetry/opentelemetry-collector/files/5478916/tls.zip) Attached zip uses Jaeger-Hotrod example app to otel-collector-1 `v0.12.0` exports data to secure-otelcol `v0.13.0.`  The communication between the two otel collectors is secured by a custom CA.

**What did you expect to see?**
Both otel-collector-1 and secure-otelcol have logging exporter, I expect to see traces logged in both.

**What did you see instead?**
No data flows to secure-otelcol

**What version did you use?**
Version: `v0.12.0` and `v0.13.0`

**What config did you use?**
Config: 

```
receivers:
  jaeger:
    protocols:
      grpc:

exporters:
  otlp/2:
    endpoint: secure-otelcol:55680
    ca_file: /etc/demo-otelcol.crt
  logging:

service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logging, otlp/2]
```

```
receivers:
  otlp:
    protocols:
      grpc:
        tls_settings:
          key_file: /etc/demo-otelcol.key
          cert_file: /etc/demo-otelcol.crt

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]

```

**Environment**
docker images

**Additional context**

* certificates were generated using openssl `openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout demo-otelcol.key -out demo-otelcol.crt -subj /CN=secure-otelcol` (they are also inside the zip)
