### ISSUE TITLE
nginx ingress traces using jaeger collector and exporter show as errors, in jaeger ui.

### ISSUE THREAD

**Issue by ovidiubuligan** [open-telemetry/opentelemetry-collector#2166]
**Describe the bug**
nginx ingress traces using jaeger collector and exporter show as errors, in jaeger ui.

**Steps to reproduce**
Collector config:
```yaml
# ############################
# Receivers
# ############################
receivers:
  # Data sources: traces, metrics, logs
  otlp:
    protocols:
      grpc:
      http:

  # Data sources: traces
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  # Data sources: traces
  zipkin:
# ########################################################
# Processors
# ########################################################
processors:
  batch:

# #########################
# Exporters
# #########################

exporters:
  # Data sources: traces, metrics, logs
  azuremonitor:
    instrumentation_key: "<redacted out>"
  # Data sources: traces, metrics, logs
  file:
    path: ./filename.json

  # Data sources: traces
  jaeger:
    endpoint: "jaeger-all-in-one-service:14250"
    insecure: true

# ####################################
# Service
# ####################################
service:
  pipelines:
    traces:
      receivers: [zipkin,otlp,jaeger]
      #processors: [batch]
      exporters: [file,azuremonitor,jaeger]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp,azuremonitor]
    #logs:
    #  receivers: [otlp]
    #  processors: [batch]
    #  exporters: [otlp]
```

I used the following ngnix ingress config to export traces
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovi-ingres-ingress-nginx-controller
  #namespace: nginx-ingress
data:
  enable-opentracing: "true"
  #zipkin-collector-host: otel-collector-service.default.svc.cluster.local
  jaeger-collector-host: otel-collector-service.default.svc.cluster.local
```

**What did you expect to see?**
I did not expect to see traces as errors when status code is `200` :
![image](https://user-images.githubusercontent.com/4757459/99395302-e38b1a00-28e8-11eb-9284-967282728b53.png)

**Environment**
k3d environment  created 1 day ago 

I don't think this is a nginx-ingress issue since it is said to be tested..
