### ISSUE TITLE
[attributeprocessor] introduce "rename" action 

### ISSUE THREAD

**Issue by hossain-rayhan** [open-telemetry/opentelemetry-collector#2184]
**Is your feature request related to a problem? Please describe.**
We need a way to rename our metric labels. But the problem is, we cannot get these metric labels until data comes to the exporter. In the exporter, resource attributes are converted to metric labels using the `WithResourceToTelemetryConversion()` option from `exporterhelper` module. So, technically, we need a way to rename our resource attributes which will be used as metric labels.

**Describe the solution you'd like**
As we cannot get benefits from the `metricstransformprocessor`, I think extending the `attributeprocessor` would be an ideal decision. Now, we can rename a resource attribute using two actions like the following-

```yaml
processors:
  attributes/example:
    actions:
      - key: new_attribute_key
        from_attribute: key_original
        action: update
      - key: key_original
        action: delete
```

I was thinking to introduce a new `action` to rename the attribute key directly like the folloing-

```yaml
processors:
  attributes/example:
    actions:
      - key: old_attribute_key
        value: new_attribute_key
        action: rename
```
