### ISSUE TITLE
Jaeger thrift to OTLP translation removes error tag without setting a proper status code.

### ISSUE THREAD

**Issue by ZFLloyd** [open-telemetry/opentelemetry-collector#2304]
**Describe the bug**
We are using opencensus jaeger exporter so far and I have been trying to use the otel-collector to send trace data to an otel speaking service as well as still exporting to a local jaeger instance.

Currently when an error happened in the span, we were setting `error=true` in the span attributes (as the [opentracing spec](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table) had us do for jaeger), but it seems to be removed from the span attributes and when reexported to jaeger or a otlp speaking service, it is not marked as a error anymore.

If we set the status code to 2, it is properly marked as an error in both jaeger and otlp, even without setting the `error=true` in the original span. I've tried a few other codes, and only 2 seems to result in an error out of the few I've tried out.

**Steps to reproduce**
```go
package main

import (
	"context"
	"errors"
	"fmt"
	"github.com/fewlinesco/go-pkg/platform/tracing"
	"go.opencensus.io/trace"
	"time"
)

func main() {
	config := tracing.Config{
		LocalEndpoint: "0.0.0.0:8080",
		ReporterURI:   "http://localhost:20001/api/traces",
		ServiceName:   "tracing-test",
		Probability:   1,
	}

	err := tracing.Start(config)
	if err != nil {
		fmt.Printf("can't start tracing: %v", err)
	}

	parent()
	time.Sleep(time.Second * 5)
}

func parent() {
	ctx, span := tracing.StartSpan(context.Background(), "parent-span")
	defer span.End()
	tracing.AddAttributeWithDisclosedData(span, "test-attribute-1", "1")
	child(ctx)
}

func child(ctx context.Context) {
	ctx, span := tracing.StartSpan(ctx, "child-span")
	defer span.End()
	tracing.AddAttributeWithDisclosedData(span, "test-attribute-2", "2")
	err := errors.New("something bad has happened")
	span.AddAttributes(
		trace.BoolAttribute("error", true),
		trace.StringAttribute("message", err.Error()),
	)
}
```

**What did you expect to see?**
The resulting trace should have the `error=true` tag for the jaeger exporter, and the proper error status code for the otlp exporter.

**What did you see instead?**
Jaeger exporter logs:
```
Resource labels:

-> service.name: STRING(tracing-test)

InstrumentationLibrarySpans #0

Span #0

Trace ID : 557e0a73dda02ee4258b99c6c242a4d7

Parent ID : 891c221a31267f27

ID : c0da924f840e5ff8

Name : child-span

Kind : SPAN_KIND_UNSPECIFIED

Start time : 2020-12-18 14:19:39.430372 +0000 UTC

End time : 2020-12-18 14:19:39.430375 +0000 UTC

Status code : STATUS_CODE_OK

Status message :

Attributes:

-> test-attribute-2: STRING(2)

-> message: STRING(something bad has happened)

Span #1

Trace ID : 557e0a73dda02ee4258b99c6c242a4d7

Parent ID :

ID : 891c221a31267f27

Name : parent-span

Kind : SPAN_KIND_UNSPECIFIED

Start time : 2020-12-18 14:19:39.430366 +0000 UTC

End time : 2020-12-18 14:19:39.430387 +0000 UTC

Status code : STATUS_CODE_OK

Status message :

Attributes:

-> test-attribute-1: STRING(1)
```

**What version did you use?**
latest

**What config did you use?**
Config:
```yaml
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: localhost:20000
      thrift_http:
        endpoint: localhost:20001
  zipkin:
    endpoint: localhost:20002

processors:
  batch:
  queued_retry:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  otlp:
    insecure: true
    endpoint: lightstep_developer_satellite:8360

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch, queued_retry]
      exporters: [jaeger, logging]
    traces/2:
      receivers: [jaeger]
      processors: [batch, queued_retry]
      exporters: [otlp]

```

**Additional context**
This may be due to me being confused around the different specs and implementation and I'm sorry if that is the case. But the translation seems a bit strange to me. If it is intended behaviour, maybe some more related documentation could help solve the issue for setting errors and have it translated properly.
