### ISSUE TITLE
Filter Processor for Tracing

### ISSUE THREAD

**Issue by cemo** [open-telemetry/opentelemetry-collector#2310]
**Is your feature request related to a problem? Please describe.**
I would like to drop some of our traces such as **health check requests** 

**Describe the solution you'd like**
I see that *filterprocessor* is only supporting metrics.
https://github.com/open-telemetry/opentelemetry-collector/tree/master/processor/filterprocessor
I think using filter processor to drop some requests might be possible. Is it possible?

**Comment by dradetsky** [comment]
I also need this capability. I don't think I can accomplish it via ignore filters in autoinstrumentation plugins, as then I get headless traces from child requests of the parent requests I want to ignore.

**Comment by dradetsky** [comment]
If the way one is supposed to implement it is using [this](https://github.com/open-telemetry/opentelemetry-collector/blob/master/processor/README.md#includeexclude-spans) then it's really unclear how I'm supposed to do it. That config seems to require the use of `name:` and the include/exclude options apply to whether or not the span is included or excluded from having its name modified, not whether the span is or is not dropped entirely.

**Comment by iPaxos** [comment]
Any updates regarding this? I am facing the same issue.

**Comment by morigs** [comment]
Span (not trace) filtering is really what you want to achieve? This can lead to patchy traces
If you want to filter traces, then this is a much more difficult task that cannot be performed by one processor
It called tail based sampling. You can get some background [here](https://github.com/open-telemetry/opentelemetry-collector/issues/407)
In this case you have to use combination of three processors from the contrib repository: [routing](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor), [groupbytrace](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/groupbytraceprocessor) and [tailsampling](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor)

**Comment by cemo** [comment]
@morigs Would you please share a sample :) ?

**Comment by morigs** [comment]
Tbh I didn't experiment with this yet, so you have to try yourself 😞 
Btw I believe it should be better documented, so may be we should comment #407 or create new issue for this case

**Comment by morigs** [comment]
Also I can be wrong about `groupbytrace` requirement

**Comment by albertteoh** [comment]
From this https://github.com/open-telemetry/opentelemetry-collector/issues/560#issuecomment-589655713 it seems there may be some use cases for just filtering on spans and so it's worth exploring.

Agree with @morigs that it can lead to holes in traces and that a tail-based sampling approach would be best for filtering out whole traces. However, it doesn't currently support "sampling out" (i.e. dropping) traces as of now and there are plans to [deprecate it](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/1797).

**Comment by jpkrohling** [comment]
We talked about this during the SIG from yesterday: https://docs.google.com/document/d/1r2JC5MB7GupCE7N32EwGEXs9V_YIsPgoFiLP4VWVMkE/edit?ts=5de972a2#heading=h.791inlvyg4dl

I mentioned a few links to requests from users in the Jaeger community, confirming that there's demand for this feature, but there are some questions to be answered.

**Comment by puckpuck** [comment]
I ran into the need for this today, and now have 2 use cases for this.

1. Dropping health checks, which are typically single span traces.
2. Routing traces to different exporters that are received on the same receiver. I should be able to achieve this with multiple pipelines, but I need a way to exclude a set of traces from each pipeline. I can ensure all my spans have an attribute(s) to dictate which pipeline they belong to.

I understand the need to want and keep traces together, but using this processor requires someone to read docs. You could clearly outline in the docs that this can lead to breaking up traces and to use with caution. I would hate we delay trying to implement this because we want to remap parent/child references.

**Comment by jpkrohling** [comment]
> Routing traces to different exporters that are received on the same receiver.

Have you seen the routing processor? 
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor

It might not have the features you need, but should be easy to extend it so that it uses a different source for the `from_attribute` property.

**Comment by miry** [comment]
@jpkrohling Do you have example how can I use contrib processor with main collector?

**Comment by jpkrohling** [comment]
You should use the contrib distribution for that, or build your own distribution based on core + that processor.

https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.24.0

https://github.com/open-telemetry/opentelemetry-collector-builder

**Comment by kradalby** [comment]
Another use case for our organisation is the ability to "enforce" that all traces/spans have an attribute, e.g. an application ID and that we drop everything not adhering to the standard. Yes there might be wholes in the beginning, but when everyone adds it, it should not be an issue.

**Comment by Stocco** [comment]
We also need this feature as well. The spans generated by our LB healthchecks pollutes our vision and it also increases our monitoring tool bill  :'(

**Comment by morigs** [comment]
@Stocco in case you're looking for a workaround: some HTTP instrumentation allows to specify a list of exclusions.
For instance [this parameter](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-instrumentation-http/src/types.ts#L75) in opentelemetry-js

**Comment by gongcon** [comment]
We need this feature as well for dropping spans from envoy which is out of our control. The routing processor looks at http request headers and is very restricted, e.g. does not work with batch. Also, seems it only works on trace level, not span.

**Comment by HuBaX** [comment]
Is anyone working on this? If not I'd like to try to implement that.

**Comment by cemo** [comment]
Not a perfect one but 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060#issuecomment-932369726

**Comment by william-tran** [comment]
>The routing processor looks at http request headers and is very restricted, e.g. does not work with batch

**Comment by william-tran** [comment]
I have a proposal in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7561 that might solve most of these use cases, but generalizes this problem as a routing problem.

**Comment by william-tran** [comment]
@billg-splunk Take a look at https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/7561#issuecomment-1032795704 where we can use attributes -> groupbyattrs -> routing. What's already there works fine for filtering out noisy spans. Re-connecting sub-trees would require a lot more effort though.

**Comment by politician** [comment]
> @Stocco in case you're looking for a workaround: some HTTP instrumentation allows to specify a list of exclusions. For instance [this parameter](https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-instrumentation-http/src/types.ts#L75) in opentelemetry-js

Fix: https://github.com/open-telemetry/opentelemetry-js/blob/21fc8b5280af360a517707ee013a1f37ba38bdc0/experimental/packages/opentelemetry-instrumentation-http/test/functionals/https-enable.test.ts#L195-L197

**Comment by ringerc** [comment]
The opentelemetry-contrib spanprocessor https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/spanprocessor can do this. It's a bit unfortunate that the main filterprocessor can't.

**Comment by AkselAllas** [comment]
Perhaps this [slack Thread](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1619082240073800) can help?

Solution from there by Davy Jones: 

```
receivers:
  otlp:

exporters:
  logging:
    loglevel: info

processors:
  # This processor inspects spans looking for matching attributes.
  # Spans that DONT MATCH this will have a new attribute added named retain-span
  # This is then used by the tail_sampling processor to only export spans that
  # have the retain-span attribute.
  attributes/filter_spans:
    exclude:
      match_type: strict
      attributes:
       - key: http.user_agent
         value: "ELB-HealthChecker/2.0"
    actions:
      - key: retain-span
        action: insert
        value: "true"

  # This Tail Sampling processor works in combination with attributes/filter_spans
  # to remove unwanted spans. This is done by inspecting the attribute that is
  # added to spans that should be retained so that they are pushed to the exporters.
  tail_sampling:
    decision_wait: 10s
    num_traces: 100
    expected_new_traces_per_sec: 10
    policies:
      [
        {
          name: retained_spans,
          type: string_attribute,
          string_attribute: {key: "retain-span", values: ["true"]}
        }
      ]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/filter_spans, tail_sampling]
      exporters: [logging]
```
