### ISSUE TITLE
Clarification on span processor exclusions and relationship to exporter.

### ISSUE THREAD

**Issue by burncycl** [open-telemetry/opentelemetry-collector#2339]
Hello OTEL team, 

If I want to exclude a span received from being exported, is there a means to do that using span processor?

 Example:
```
span/1:
  span:
    exclude:
	match_type: regexp
	span_names:
	  - .*/health
```
