### ISSUE TITLE
Improve error message for prometheus scrape failure

### ISSUE THREAD

**Issue by yyyogev** [open-telemetry/opentelemetry-collector#2364]
If a prometheus receiver, fails to scrape an endpoint, the output shows something like:

```
2021-01-12T21:11:10.496Z	warn	internal/metricsbuilder.go:104	Failed to scrape Prometheus endpoint	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_timestamp": 1610485870495, "target_labels": "map[instance:aks-agentpool-30099824-vmss000002 job:cadvisor]"}
```
The reason for the failure isn't presented here and it's almost impossible to figure out what is wrong

I would suggest enriching the warn message with an actual reason

**Comment by plazma-prizma** [comment]
Hello, I'd like to pick it up as my first contribution to open telemetry 🙂  Though I need some initial guidance, quick search for `metricsbuilder` in this repository didn't help 😬

**Comment by hossain-rayhan** [comment]
Facing similar issue. I have no idea whats going wrong. In my case, it works once when I scrape the `Pods` but never worked when I am trying to scrape `/mectrics/cadvisor`.


`WARN	internal/metricsbuilder.go:104	Failed to scrape Prometheus endpoint	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_timestamp": 1614018163539, "target_labels": "map[alpha_eksctl_io_cluster_name:eks-test-1 alpha_eksctl_io_instance_id:i-0cd2e741621ad97d0 alpha_eksctl_io_nodegroup_name:ng-2-builders beta_kubernetes_io_arch:amd64 beta_kubernetes_io_instance_type:m5.2xlarge beta_kubernetes_io_os:linux failure_domain_beta_kubernetes_io_region:us-east-2 failure_domain_beta_kubernetes_io_zone:us-east-2a instance:ip-192-168-181-249.us-east-2.compute.internal job:kubernetes-cadvisor kubernetes_io_arch:amd64 kubernetes_io_hostname:ip-192-168-181-249.us-east-2.compute.internal kubernetes_io_os:linux node_kubernetes_io_instance_type:m5.2xlarge node_lifecycle:on-demand role:builders topology_kubernetes_io_region:us-east-2 topology_kubernetes_io_zone:us-east-2a]"}`

**Here is the full kubernetes_sd_congig:**
```yaml
kubernetes_sd_configs:
            - role: node
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              insecure_skip_verify: false
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)
                # Only for Kubernetes ^1.7.3.
                # See: https://github.com/prometheus/prometheus/issues/2916
              - target_label: __address__
                replacement: kubernetes.default.svc:443
              - source_labels: [__meta_kubernetes_node_name]
                regex: (.+)
                target_label: __metrics_path__
                replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
            metric_relabel_configs:
              - action: replace
                source_labels: [id]
                regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
                target_label: rkt_container_name
                replacement: '${2}-${1}'
              - action: replace
                source_labels: [id]
                regex: '^/system\.slice/(.+)\.service$'
                target_label: systemd_service_name
                replacement: '${1}'
```

**Comment by dashpole** [comment]
can you try running with the command line flag
`--log-level=DEBUG`?

When I do that with an intentionally misconfigured collector, I see messages like:
```
2021-02-24T18:57:16.040Z	warn	internal/metricsbuilder.go:104	Failed to scrape Prometheus endpoint	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_timestamp": 1614193036037, "target_labels": "map[beta_kubernetes_io_arch:amd64 beta_kubernetes_io_instance_type:e2-medium beta_kubernetes_io_os:linux cloud_google_com_gke_boot_disk:pd-standard cloud_google_com_gke_nodepool:default-pool cloud_google_com_gke_os_distribution:cos cloud_google_com_machine_family:e2 failure_domain_beta_kubernetes_io_region:us-central1 failure_domain_beta_kubernetes_io_zone:us-central1-c instance:gke-cluster-1-default-pool-746cd6d9-mziw job:kubernetes-cadvisor kubernetes_io_arch:amd64 kubernetes_io_hostname:gke-cluster-1-default-pool-746cd6d9-mziw kubernetes_io_os:linux node_kubernetes_io_instance_type:e2-medium topology_kubernetes_io_region:us-central1 topology_kubernetes_io_zone:us-central1-c]"}
2021-02-24T18:57:16.478Z	debug	scrape/scrape.go:1124	Scrape failed	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_pool": "kubernetes-cadvisor", "target": "https://10.128.15.217:10250/metrics/cadvisor/foo", "err": "server returned HTTP status 404 Not Found", "errVerbose": "server returned HTTP status 404 Not Found\ngithub.com/prometheus/prometheus/scrape.(*targetScraper).scrape\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:641\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:1112\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).run\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:1036\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
```

The debug log shows me that my problem was a 404, which is correct for me since I put in an incorrect metrics_path in my prometheus config.

**Comment by hossain-rayhan** [comment]
@dashpole thanks, it gives more insights. 

I am getting `403 Forbidden`. Not sure which permission I missed. 
```
2021-02-24T19:18:01.859Z	warn	internal/metricsbuilder.go:104	Failed to scrape Prometheus endpoint	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_timestamp": 1614194281848, "target_labels": "map[alpha_eksctl_io_cluster_name:eks-test-1 alpha_eksctl_io_instance_id:i-09892500d4bf9388b alpha_eksctl_io_nodegroup_name:ng-1-workers beta_kubernetes_io_arch:amd64 beta_kubernetes_io_instance_type:m5.xlarge beta_kubernetes_io_os:linux failure_domain_beta_kubernetes_io_region:us-east-2 failure_domain_beta_kubernetes_io_zone:us-east-2a instance:ip-192-168-173-241.us-east-2.compute.internal job:kubernetes-cadvisor kubernetes_io_arch:amd64 kubernetes_io_hostname:ip-192-168-173-241.us-east-2.compute.internal kubernetes_io_os:linux node_kubernetes_io_instance_type:m5.xlarge node_lifecycle:on-demand role:workers topology_kubernetes_io_region:us-east-2 topology_kubernetes_io_zone:us-east-2a]"}
2021-02-24T19:18:02.105Z	debug	scrape/scrape.go:1124	Scrape failed	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_pool": "kubernetes-cadvisor", "target": "https://192.168.125.115:10250/metrics/cadvisor", "err": "server returned HTTP status 403 Forbidden", "errVerbose": "server returned HTTP status 403 Forbidden\ngithub.com/prometheus/prometheus/scrape.(*targetScraper).scrape\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:641\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:1112\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).run\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:1036\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"}
```

**Comment by hossain-rayhan** [comment]
I resolved my issue. I was missing permission for `- node/metrics`. After adding this in my `ClusterRole` it worked for me. 

One thing, maybe we can upgrade the label from `debug` to `warn` for detailed failing reason.

**Comment by dashpole** [comment]
The line in question: in scrape/scrape.go is in the prometheus server, so without forking it we can't modify the level.  The same question was raised in upstream prometheus here: https://github.com/prometheus/prometheus/issues/2820#issuecomment-307064716, and it wasn't deemed appropriate to raise the verbosity

**Comment by glaenen** [comment]
> node/metrics



> I resolved my issue. I was missing permission for `- node/metrics`. After adding this in my `ClusterRole` it worked for me.
> 
> One thing, maybe we can upgrade the label from `debug` to `warn` for detailed failing reason.

Thanks pointing me in the right direction.
Small correction, the mission permission is "nodes/metrics"

**Comment by naseemkullah** [comment]
@nilebox I see you've worked on the prometheus receiver logging, would you have any idea how to wait for the subsequent debug log (coming from prometheus server) and put its `err` field into `AddDataPoint`'s `warn` log?

**Comment by nilebox** [comment]
> any idea how to wait for the subsequent debug log

@naseemkullah in https://github.com/open-telemetry/opentelemetry-collector/blob/68871bdd7db82d0d495f886c558f8ea6005ef2d0/receiver/prometheusreceiver/internal/logger.go#L46, we get key-value pairs from go-kit (used by Prometheus) for each log message, which gets parsed and forwarded to zap logger.

You may change the code to catch specific errors there (e.g. based on known error message), and convert it to warn log message in zap.

P.S. I'm no longer working on this project, so won't be able to help you beyond this advice unfortunately.

**Comment by odeke-em** [comment]
I've mailed out a fix for it in https://github.com/open-telemetry/opentelemetry-collector/pull/2906

**Comment by anuraaga** [comment]
AFAIK logging detailed information at debug level is consistent with the rest of the collector so not sure this change is a good idea. Could be wrong though. @bogdandrutu @tigrannajaryan could you clarify any best practices for logging in collector and whether it makes sense to use a different default than prometheus here?

**Comment by odeke-em** [comment]
Yeah from discussions in the Prometheus Working Group and other discussions, we came to the conclusion that we shouldn't do this. @alolita @Aneurysm9 could you please help perhaps mark as this a "Won't Fix" and then we can close it? Thank you.

**Comment by ringerc** [comment]
This unhelpful error is emitted if the metric set is scraped successfully but the metrics returned do not contain the `up` metric.

**Comment by stoerig** [comment]
> This error also appears to be emitted when the endpoint gets scraped successfully, but does not emit a metric named `up`. Or (possibly) if it's excluded by label filters.

Is there any solution to his? I have tried filtering with params to the scrape request to the metrics endpoint and filtering by ignoring the up metric, but nothing has solved the issue. 

Does anyone know what can be done to fix this issue? 

Don't know if it's relevant but I am attempting to scrape an eventstore db node.

My attempted configs:

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'my-job'
          static_configs:
            - targets: ['localhost:9090']  # Replace with your actual target
          params:
            match[]:
              - '{__name__!~"up"}'  # Exclude metrics with the name "up"
```
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'my-job'
          static_configs:
            - targets: ['localhost:9090']  # Replace with your actual target
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: 'up'
              action: drop
```
