### ISSUE TITLE
Remote Configuration Proposal [Draft]

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#2374]
# Goal

Allow remote configuration of Collectors by feeding the configuration to the Collectors from a remote configuration source. The source of the remote configuration must be possible to specify in the Collector's local config file via a pluggable component that can be implemented by the Collector core team or independently by third-party developers in the contrib repo.

# Summary

Remote configuration implementation should be plugable at runtime (it should be possible for the end user to choose at runtime from a set of implementations defined at compile time).

We need to define a remote configuration interface (internal API) between Collector core config and remote configuration implementations. The interface should preferably have a "watcher" style, where the implementation notifies the Collector core about the availability of a new configuration (as opposed to Collector core periodically polling the implementation and asking for a new configuration).

The remote configuration interface may be defined on top of the current `extension` concept or may be completely separated from it (try and see which approach feels better). The exact internal API to be defined.

Note that this proposal does not define the behavior of an actual implementation that performs the fetching of the remote config. We specify an internal remote configuration API in this proposal and the corresponding code that uses this API in the Collector core to be implemented. Where and how exactly the config is fetched from is a concern of a particular implementation (and there be many such implementations in the core or contrib repos).

Remote configuration capability should be enabled via a command line switch (e.g. --remote-config=<filename.yaml>) that points to a local config file that contains the remote configuration setting (e.g. the implementation type, the endpoint to fetch the config from, etc). Note that if we choose top-level keys in this yaml file carefully we may allow this to be the same file as the current local config file (which has potential future uses such as fallback to local config without requiring 2 config files).

# Operation

The Collector core will initialize the Remote configuration implementation and will provide attributes that identify the Collector, then will wait to be notified about the availability of a new config. The implementation may use these identifying attributes to fetch the configuration that is applicable to this particular Collector.

The Collector core will identify itself using the following attributes:
- Static attributes defined at build time, such as Collector version, version of OS it is built for, commit hash, etc.
- Dynamic attributes that the Collector will auto-detect at runtime, such as the OS version it runs on, the machine id it runs on (if available), etc.
- User-defined attributes that are specified manually by the end user in the local config file used by the Collector (such as for example "environment=production").
- Collector's unique instance id, specified in "service.instance.id" attribute. The Collector will attempt to obtain this from a persistent ID source (such as machine UUID), falling back to an ephemeral generated UID.

On startup the Collector with an enabled remote configuration option should wait for the remote configuration to arrive before the Collector's regular operation begins. This behavior may be configurable locally (e.g. how long to wait for).

After the Collector core receives a remote config it will attempt to reconfigure itself. If the reconfiguration fails the Collector will revert to the last known good config. 

The reconfiguration requires graceful shutdown, reconfiguration and restart of the Collector so https://github.com/open-telemetry/opentelemetry-collector/issues/483 and https://github.com/open-telemetry/opentelemetry-collector/issues/1007 are a pre-requisite.

# Local Config File Format that Specifies Remote Config Settings

Possible format for local file to be read via --remote-config option:
```yaml
 remote_config:
   # The name of the extension that implements fetching of the
   # remote config.
   config_source: remote_config_source   
   # How long to wait for the config server to respond during
   # startup.
   # Setting to 0 will disable the waiting and will let the Collector
   # start immediately. In that case the Collector may work with only
   # the local config for a while and the remote config may be
   # applied some time after the startup is finished.
   wait_for_config: 30s
   # User defined identity attributes which identify this Collector
   # to the config server. A map of key-value pairs. Valid characters for
   # keys are: alphanumeric, underscore, dot.
   identify_self_attributes:
     environment: production
     service.namespace: onlineshop
     service.name: checkout
   # List of directories from which it is allowed to run external
   # executables. All components must honor this setting.
   allow_executable_dirs:
     - /usr/lib
     - ./
   # List of directories from which it is allowed to read data
   # All components must honor this setting.
   allow_read_dirs:
     - /var/log
   # A set of options that enable proxying of configuration requests.
```

# Collector Identity Auto-Detection

We will reuse detectors from the resourcedetection processor. It currently detects GCP and AWS attributes and populates attributes such as "cloud.account.id", "host.id", etc.

# Collector Unique Instance ID

We will try to fetch persistent machine id when it is available using a library like this. When persistent machine id is not available the Collector will generate random ephemeral UUID for its UID. Ephemeral UID is not very useful for remote long-term config purposes but is still useful for uniquely identifying the Collector at least during one session. This allows to tie status reports with the particular Collector instance and show reported effective config or config errors in the UI. 

In the future we may add an ability for the Collector to inform the backend the UID is ephemeral so that the UI warns the user not to use it to create a partial config.

We may also add an ability to detect duplicate UIDs in the future, if we are not confident that the persistent or ephemeral UIDs are unique enough.

# Security

Remotely controlled configuration is a security risk. Via remote configuration the Collector may be compelled to collect data and send to a destination. Collector today is capable of collecting data both passively by accepting it and actively by scraping metrics from locally and remotely running systems. In the future we also plan to introduce log collection capability that will allow to read local files.

In order to reduce this risk we make remote configuration capability disabled by default. It has to be explicitly enabled by the user using a setting in a local configuration file.

In the future we may have more dangerous capabilities, such as planned file log collection or ability to execute external processes for metric collection.

To reduce the risks all components should be limited to executing programs only in directories specified via allow_executable_dirs setting (any external program execution is prohibited if this setting is unspecified). All components are limited to read files only from directories specified via allow_read_dirs setting (any file read is prohibited if this setting is unspecified).

Component interfaces must be modified to include allow_executable_dirs and allow_read_dirs in the `Start()` function or in the factory creation. All existing components must be reviewed to ensure they honour this settings.

In addition we may want to consider jailing the process to certain directory so that we do not rely on component's honouring the security settings.

# Risks

If the remote config source is unavailable then remote configuration capability can bring down the entire collection. There are ways to mitigate this (e.g. persist last known good configuration) but it is not foolproof and is additional work to do.

# Tradeoff, Alternates and Future Possibilities

## Persisting Effective Config

This is not included in the design because we do not always have a persistent filesystem available to the Collector. Instead we opted to always fetch the config on startup. This may delay the startup but removes the need to rely on the filesystem which may not be present.

## Config Pipeline

Instead of specifying remote config functionality as a first-class concept, I considered making the configuration a pipeline data type (similar to how traces and metrics are a data type), and then have a receiver for this data type and an exporter for the data type and possibly processors that can modify the remote config. 

While this may be a viable idea it is not clear at this stage if the flexibility that pipelines bring is necessary for the remote configs. It may be an overkill and unnecessary complication for the end user.

This idea is discarded for now, but we may return to it in the future if we see the need for more flexibility in remote configuration processing.

## Push vs Pull

This proposal suggests the Collector to be notified when a new config is available. We could instead design the Internal Remote Config API in a way that requires Collector to poll the remote source for config changes.

This can simplify implementation but increase the time that the configuration changes become effective.

## Proxying Config Requests

Collector can serve as a gateway for fetching the remote config for another Collector. It would require the Collector to forward the requests (possibly batching first) then wait for the config source response and return it to the requestor.

This is possible to do and is a reasonable architecture for Agents+Collector deployment scenario. It can be designed and implemented in the future but it is out of the scope for now.

## Merging Local and Remote Partial Configs

Allow to merge locally-specified and remotely-received configurations to form an effective configuration. Requires specifying merging rules and complicates the implementation.
