### ISSUE TITLE
'fetch_endpoint' is an invalid key for 'remote_sampling'

### ISSUE THREAD

**Issue by DanTulovsky** [open-telemetry/opentelemetry-collector#2440]
**Describe the bug**

Using the suggested config below, I receive an error message from the collector when it comes up.

```
'remote_sampling' has invalid keys: fetch_endpoint
```

```
receivers:
  jaeger:
    protocols:
      grpc:
    remote_sampling:
      fetch_endpoint: "jaeger-collector:1234"
```

**Steps to reproduce**
Start a collector with the above config.

**What did you expect to see?**
A working collector.

**What did you see instead?**
crash loop with error:

```
'remote_sampling' has invalid keys: fetch_endpoint
```

**What version did you use?**

```
Starting OpenTelemetry Contrib Collector... {"Version": "latest", "GitHash": "bb44b79b", "NumCPU": 2}
```

**What config did you use?**
```
receivers:
  jaeger:
    protocols:
      grpc:
    remote_sampling:
      fetch_endpoint: "jaeger-collector:1234"
```

**Environment**
OS: kubernetes

**Additional context**
