### ISSUE TITLE
FileExporter file separation

### ISSUE THREAD

**Issue by EliyaCohen** [open-telemetry/opentelemetry-collector#2450]
I want to use the FileExporter to transfer files from places where I don't have direct network access to the main collector. For example, when using a DMZ that only allows file transfers. 
The current exporter only allows writing to a single file, so it can't be used reliably to send the file through the DMZ (The file will always be locked under large workloads)

I'd like that the FileExporter will have the option to write data to a directory and separate each trace/metric to a single file.

Alternatively, it can be split based on time interval or file size.

**Comment by Andrey1337** [comment]
I got the same Issue

**Comment by bogdandrutu** [comment]
(Not sure if this was a question) Just to write in different files based on the signal type (trace and metrics), here is a config you can do:

```
exporters:
  file_traces:
    path: ./filename_traces.json
  file_metrics:
    path: ./filename_metrics.json

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file_traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file_metrics]
```

> I'd like that the FileExporter will have the option to write data to a directory and separate each trace/metric to a single file.

By each, you mean each "batch" that the exporter receives probably. I think this is not that useful if we offer a file rotation option correct?

> Alternatively, it can be split based on time interval or file size.

I would go with this option if I were to add it.
