### ISSUE TITLE
prometheusexporter droping the OTEL resource lables

### ISSUE THREAD

**Issue by yorikya** [open-telemetry/opentelemetry-collector#2498]
**Describe the bug**
In our company, we are using opentelemetry-sdk-go to export the metrics from a service, then collector-agent which is running on the same host receives the metrics through the OTLP receiver and exports the metrics via the Prometheus exporter.
When we are adding some custom Lable to OTEL Resource via  `opentelemetry-sdk-go` those Labels are dropped by Prometheus exporter, but Labels created within the metric are shown without any issue. 

**Steps to reproduce**
1. (Collector) Run otelcollector with the next configuration (config.yaml):
```
receivers:
  otlp/notls:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"

  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [prometheus]
    
    traces:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [logging]    
```
2. (Service) Setup opentelemetry-sdk-go to export metrics/traces via otlp (I am using this example: https://github.com/open-telemetry/opentelemetry-go/tree/9524ac095466565e01746600da3d83f27220a5da/example/prom-collector)
```
ctx := context.Background()

	res, err := resource.New(
		ctx,
		resource.WithAttributes(label.String("R", "V")),
	)
	if err != nil {
		log.Fatal("could not initialize resource:", err)
	}

	driver := otlpgrpc.NewDriver(
		otlpgrpc.WithInsecure(),
		otlpgrpc.WithEndpoint("0.0.0.0:4317"),
	)
	otlpExporter, err := otlp.NewExporter(ctx, driver)

	if err != nil {
		log.Fatal("could not initialize OTLP:", err)
	}

	cont := controller.New(
		processor.New(
			simple.NewWithHistogramDistribution(
				histogram.WithExplicitBoundaries([]float64{
					0.001, 0.01, 0.1, 1, 10, 100, 1000,
				}),
			),
			otlpExporter, // otlpExporter is an ExportKindSelector
			processor.WithMemory(true),
		),
		controller.WithResource(res),
		controller.WithPusher(otlpExporter),
	)

	if err := cont.Start(context.Background()); err != nil {
		log.Fatal("could not start controller:", err)
	}

     otel.SetMeterProvider(cont.MeterProvider())
``` 
3. (Service) Send a metric:
```
observerCallback := func(_ context.Context, result metric.Float64ObserverResult) {
		result.Observe(1, resources.NewLabels(map[string]interface{}{
			"db-instance": "Node",
		})...)
	}
	metric.Must(meterProvider).NewFloat64ValueObserver("create node", observerCallback)
```
4. (Collector) Now query the Prometheus endpoint and check the metric:
```
curl localhost:9090/metrics
# HELP create_node_User
# TYPE create_node_User gauge
create_node_User{db_instance="Node"} 1
```

**What did you expect to see?**
Lable which is added with resources (R="V") should persist in the Prometheus tags 
```
curl localhost:9090/metrics
# HELP create_node_User
# TYPE create_node_User gauge
create_node_User{db_instance="Node", R="V"} 1
```

**What did you see instead?**
The label is not showing in the Prometheus tags
```
curl localhost:9090/metrics
# HELP create_node_User
# TYPE create_node_User gauge
create_node_User{db_instance="Node"} 1
```

**What version did you use?**
Version: `v0.19.0`

**What config did you use?**
Config:
```
receivers:
  otlp/notls:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"

  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [prometheus]
    
    traces:
      receivers: [otlp/notls]
      processors: [batch]
      exporters: [logging]    
```

**Environment**
OS: ("Ubuntu 14.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
I saw that the tags that were added within the metric are showing in the Prometheus tags, so I tried to compile my own version for Prometheus exporter where I am copying the resource Labels to `Timeseries[]` labels.
I just replaced the Prometheus `ExporterMetric` [function](https://github.com/orijtech/prometheus-go-metrics-exporter/blob/master/prometheus.go#L169) with my own: 
```
func (exp *PrometheusContribExporter) ExportMetric(ctx context.Context, node *commonpb.Node, rsc *resourcepb.Resource, metric *metricspb.Metric) error {
	if metric == nil || len(metric.Timeseries) == 0 {
		return nil
	}

	for k, v := range rsc.Labels {
		metric.MetricDescriptor.LabelKeys = append(metric.MetricDescriptor.LabelKeys, &metricspb.LabelKey{
			Key: k,
		})

		metric.Timeseries[0].LabelValues = append(metric.Timeseries[0].LabelValues, &metricspb.LabelValue{
			Value: v,
		})
	}

	return exp.Exporter.ExportMetric(ctx, node, rsc, metric)
}
```
It's working, but I am sure you have the proper way to do that :-)

Full Prometheus exporter with custom tags is here: 
https://github.com/yorikya/otel-custom-prometheus

**Comment by terev** [comment]
Just ran into this issue as well :+1:

**Comment by iror00** [comment]
Me too

**Comment by jrcamp** [comment]
@alolita I think this is probably a pretty high priority Prometheus issue if somebody can take a look at it, number of people have been running into it and results in a lot of missing metadata.

**Comment by weyert** [comment]
I think this problem is a common problem, because when I am using the Javascript SDK and its PrometheusExporter pass a resource to the MeterProvider and then also pass to the meter. The resource labels get lost too

**Comment by seanhoughton** [comment]
I believe the intended solution is to implemented the `resource_to_telemetry_conversion` config flag in the prometheus exporter which is how other projects have solved this problem for exporters that don't have a distinction between resource attributes and metric labels.

I had a quick look at the code and it looks a bit more challenging to implement because prometheus exporter exposes metrics on an http port rather than using the `exporterhelper`.

**Comment by krak3n** [comment]
Just hit this as well, kinda makes the prometheus exporter useless until this gets fixed.

**Comment by terev** [comment]
Until this is fixed I've not been using resource labels and keep a slice of common resource labels. Then merge these with the list of labels for each metric observation.

**Comment by krak3n** [comment]
Yeah @terev I think I'll need to do the same as a temporary solution.

I've been looking around how the `exporthelper` and whether we can it to work with the prometheus exporter, might have a go at a PR but Im new to this code base and Open Telemetry in general but I'll have a go 🤞

**Comment by langecode** [comment]
Isn't this the same with the `prometheusremotewriteexporter` which is also drops/ignores the OTEL attributes (actually there is a comment in the code [exporter.go](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/prometheusremotewriteexporter/exporter.go#L110))? Do you know if this is already being addressed (I see #2412 which may be about this)? Otherwise I'll create a PR for a similar change for the `prometheusremotewriteexporter`.

**Comment by mawenge** [comment]
```
exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    **resource_to_telemetry_conversion:
      enabled: true**
```
this is because otlp format is different with prometheus metric format, so need add above config in otel-collector
