### ISSUE TITLE
[OTLPGRPC Exporter] Enable OAuth2 client credentials configuration in grpc based otlp exporter

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector#2500]
**Is your feature request related to a problem? Please describe.**

 gRPC client from config gRPC module needs to support client credentials (OAuth2) way of handling auth. (exporters). 

Instead of using static token, the client configuration must take in client credentials and implicitly fetch and refresh the token as necessary. gRPC client framework already has module to do this. We just need to enable it l. 

**Describe the solution you'd like**
OTLP grpc exporter should be able to use client credentials to perform OAuth2 flow.  Something like this is desired along the lines of existing "bearer token" based authx

```yaml

exporters:
  otlp:
    endpoint: some-grpc:9090
    per_rpc_auth:
      type: client_credentials
      oauth2:
        client_id: someclientidentifier
        client_secret: someclientsecret
        token_url: https://autz.server.com/oauth2/default/v1/token
        scopes: ["some.resource.read"]

```

**Comment by pavankrish123** [comment]
@jpkrohling kindly let me know if the configuration structure is good. I am happy to add the support.

**Comment by jpkrohling** [comment]
The config implies that the token would be refreshed during a RPC in case it's expired. I can imagine that we'd have a background process that will refresh tokens actively before they expire, outside of the hot-path. On the other hand, the bearer token is appropriately inside the per_rpc_auth node, as it's the same token being added to every RPC call. 

Any suggestions on how we can use a single structure for both cases?

**Comment by pavankrish123** [comment]
Hi @jpkrohling couple of things  

 - As for the proposed OAuth2 client credentials workflow, grpc's OAuth library already has built in mechanism to do the token refresh - we do not have to do anything more other than enabling Oauth as the mechanism in grpc's per rpc auth configuration. The underneath grpc OAuth library handles the token refreshes. 
  
 - As for the static token case,  going by comment from @tigrannajaryan #2508 - the case can be handled directly using headers (which is consistent with what HTTP clients are doing), don't think we need custom bearer mechanism for grpcs per rpc auth - unless you think there is something more to it.  (PS: I could verify static token case  by slapping Bearer: <token> in headers section of grpc exporters) 


This all said, i like the approach happening in #2229. If that gets through,  something like this can be done 

```yaml
receivers:
  somereceiver:
    grpc:
      auth:
        authenticator: oidc
exporters:
   someexporter:
      grpc:
         auth:
           authenticator: oauth2

extensions:
  oidc:
    issuer_url: https://auth.example.com/
    issuer_ca_path: /etc/pki/tls/cert.pem
    audience: my-oidc-client
    username_claim: email
    groups_claim: group
    attribute: authorization

  oauth2:
     client_id: someclientidentifier
     client_secret: someclientsecret
     token_url: https://autz.server.com/oauth2/default/v1/token
     scopes: ["some.resource.read"]

service:
  extensions: [oidc, oauth2]
  pipeline:
    traces/toSomewhere:
      receivers: [somereceiver]
      exporters: [someexporter]
```
