### ISSUE TITLE
zipkin json v2 serialization error

### ISSUE THREAD

**Issue by fletcm** [open-telemetry/opentelemetry-collector#2506]
Probably related to https://github.com/open-telemetry/opentelemetry-collector/issues/954 , which appears to have fixed this issue for zipkin json_v1 spans.

I receive lots of message like this in the opentelemetry-collector logs:
`2021-02-18T18:04:16.840Z        error   exporterhelper/queued_retry.go:239      Exporting failed. The error is not retryable. Dropping data.    {"component_kind": "exporter", "component_type": "zipkin", "component_name": "zipkin", "error": "Permanent error: failed to push trace data via Zipkin exporter: json: error calling MarshalJSON for type *model.SpanModel: valid annotation timestamp required", "dropped_items": 2062}`

I do not expect to see those messages based on the above linked issue which purports to have fixed this edge case.  Reading the code a little, it looks like it is fixed for zipkin json v1 (see [zipkinv1_to_protospan.go](https://github.com/open-telemetry/opentelemetry-collector/blob/81c7cc53b7067fbf3db4e1671b13bbe2796eb56e/translator/trace/zipkin/zipkinv1_to_protospan.go) contains call to `setTimestampsIfUnset(ocSpan)`, but [zipkinv2_to_traces.go](https://github.com/open-telemetry/opentelemetry-collector/blob/81c7cc53b7067fbf3db4e1671b13bbe2796eb56e/translator/trace/zipkin/zipkinv2_to_traces.go) does not.

We are deploying in a k8s cluster via helm chart.
Chart version:
```
- name: opentelemetry-collector
  version: 0.4.2 
  repository: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
```

My helm values.yaml looks like this:
```
opentelemetry-collector:
  agentCollector:
    enabled: false
  autoscaling:
    enabled: false
  standaloneCollector:
    enabled: true
    replicaCount: 2
    configOverride:
      receivers:
        kafka:
          protocol_version: 2.0.0
          brokers: kafka.mydomain.com:9092
          topic: zipkin.traces.v2
          encoding: zipkin_json
          group_id: otel-collector
        otlp:
          # shouldn't need this at all because we aren't using it currently, but some oddity of the helm chart or the underlying application requires that otlp be setup.
          protocols:
            http:
              endpoint: "0.0.0.0:55681"
      processors:
        batch:
          timeout: 1s
      exporters:
        # send data to tempo which accepts zipkin json_v2 list format
        zipkin:
          endpoint: "https://zipkin-ingest.mydomain.com/"

      extensions:
        health_check:

      service:
        extensions: [health_check]
        pipelines:
          metrics:
            exporters:
            - logging
            processors:
            - memory_limiter
            - batch
            receivers:
            - prometheus
          traces:
            receivers: [kafka]
            processors: [batch]
            exporters: [zipkin]
```

Which results in this configmap:
```
apiVersion: v1
data:
  relay: |
    exporters:
      logging: {}
      zipkin:
        endpoint: https://zipkin-ingest.mydomain.com/
    extensions:
      health_check: {}
    processors:
      batch:
        timeout: 1s
      memory_limiter:
        ballast_size_mib: 819
        check_interval: 5s
        limit_mib: 1638
        spike_limit_mib: 512
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
      kafka:
        brokers: kafka.mydomain.com:9092
        encoding: zipkin_json
        group_id: otel-collector
        protocol_version: 2.0.0
        topic: zipkin.traces.v2
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:55681
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888
      zipkin:
        endpoint: 0.0.0.0:9411
    service:
      extensions:
      - health_check
      pipelines:
        metrics:
          exporters:
          - logging
          processors:
          - memory_limiter
          - batch
          receivers:
          - prometheus
        traces:
          exporters:
          - zipkin
          processors:
          - batch
          receivers:
          - kafka
kind: ConfigMap
```
