### ISSUE TITLE
Incorrect receiver label in prometheus receiver observability metrics

### ISSUE THREAD

**Issue by olagacek** [open-telemetry/opentelemetry-collector#2533]
**Describe the bug**

In version 0.20.0 of opentelemetry collector observability metrics coming from prometheus receiver do not contain proper label "receiver" with receiver name - it is set to empty string, instead of "prometheus"

**Steps to reproduce**

Run Open Telemetry app with prometheus receiver enabled, then scrape localhost:8888 metrics and inspect the returned response.

**What did you expect to see?**

otelcol_receiver_accepted_metric_points, otelcol_receiver_refused_metric_points metrics having "receiver" label set to "prometheus" 

**What did you see instead?**

otelcol_receiver_accepted_metric_points, otelcol_receiver_refused_metric_points metrics have "receiver" label set to "" 

**What version did you use?**

Version: v0.20.0

**What config did you use?**

```
    receivers:
      prometheus:
        use_start_time_metric: true
        config:
          scrape_configs:
            - job_name: "kubelet"
              scrape_interval: 60s
              static_configs:
              - targets: ["127.0.0.1:10255"]
              metric_relabel_configs:
              - source_labels: [ __name__ ]
                regex: "kubelet_docker_operations|kubelet_docker_operations_errors"
                action: keep
    exporters:
      stackdriver:
    service:
      pipelines:
        metrics/prom:
          receivers:
            - prometheus
          exporters:
            - stackdriver
```

**Environment**
OS: COS
Compiler(if manually compiled): go 1.14
