### ISSUE TITLE
prometheus receiver can't get  `__meta_kubernetes_node_name`

### ISSUE THREAD

**Issue by wankai123** [open-telemetry/opentelemetry-collector#2556]
**Describe the bug**
In version v0.21.0, when I am trying to scrape `mectrics/cadvisor`,  the debug-log show me this error:
<pre>Scrape failed	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_pool": "kubernetes-cadvisor", "target": "https://kubernetes.default.svc:443/api/v1/nodes//proxy/metrics/cadvisor", "err": "server returned HTTP status 400 Bad Request", "errVerbose": "server returned HTTP status 400 Bad Request\ngithub.com/prometheus/prometheus/scrape.(*targetScraper).scrape\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:641\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:1112\ngithub.com/prometheus/prometheus/scrape.(*scrapeLoop).run\n\t/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20201105135750-00f16d1ac3a4/scrape/scrape.go:1036\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"}
</pre>
The target path obviously missing node name:
`https://kubernetes.default.svc:443/api/v1/nodes//proxy/metrics/cadvisor`

But I did relabeled the path:

``` yaml
receivers:
      prometheus:
        config:
          global:
            scrape_interval: 10s
            evaluation_interval: 10s
          scrape_configs:
            - job_name: 'kubernetes-cadvisor'
              scheme: https
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              kubernetes_sd_configs:
              - role: node
              relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)
              - target_label: __address__
                replacement: kubernetes.default.svc:443
              - source_labels: [__meta_kubernetes_node_name]
                regex: (.+)
                target_label: __metrics_path__
                replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
```
The scrape config works well in Promethues server.
![image](https://user-images.githubusercontent.com/16773043/109277014-b4723600-7851-11eb-91bc-083bb138b092.png)

**What did you expect to see?**
A clear and concise description of what you expected to see.
The target path would be `https://kubernetes.default.svc:443/api/v1/nodes/myNodeName/proxy/metrics/cadvisor`
**What did you see instead?**
`https://kubernetes.default.svc:443/api/v1/nodes//proxy/metrics/cadvisor`
