### ISSUE TITLE
fluentforward: Log body empty with some input plugins, because too arbitrary rule in place in OTEL receiver

### ISSUE THREAD

**Issue by gillg** [open-telemetry/opentelemetry-collector#2588]
**Describe the bug**
FluentForward protocol seems not have a "raw" log body.
It contains only attributes, but an attribute **can** be "message" by convention in some input plugins, and containing the raw log.
OTEL collector take this assumption during the collect : https://github.com/open-telemetry/opentelemetry-collector/blob/73db88faef0a99dfb3317227052fea5299d52ec5/receiver/fluentforwardreceiver/conversion.go#L164

In my case, I use Winlog input (https://github.com/fluent/fluent-bit/tree/master/plugins/in_winlog) and this plugin parse the win eventlog then forward all fields without adding a custom field message.
A serialized view of each entry (in JSON for exemple) should be the real log.

So, I have a questions to discuss.

Do we have to add a full attributes serialized body in this `else` ? https://github.com/open-telemetry/opentelemetry-collector/blob/73db88faef0a99dfb3317227052fea5299d52ec5/receiver/fluentforwardreceiver/conversion.go#L175
Arbitrary in JSON ? What about the case where you have "message" + other attributes ?

**Steps to reproduce**
Use Fluent-Bit with :
```
[INPUT]
    Name         winlog
    Channels     Application,Windows PowerShell
    Interval_Sec 1
    DB           winlog.sqlite

[OUTPUT]
    Name       forward
    Match      *
    Host       otel-collector
    Port       8006
```
It's probably the same case with some other input plugins...

**What did you expect to see?**
The OTEL log body should contains something which is the serialized view of all my fluent attributes

**What did you see instead?**
The body is NULL and all attrubutes are filled

**What version did you use?**
OTEL collector : otel/opentelemetry-collector-contrib:latest
Fluent bit : 1.6.10

**What config did you use?**
```yaml
receivers:
  fluentforward:
    endpoint: 0.0.0.0:8006

exporters:
  logging:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      # Labels works perfectly and thay are pushed to Loki
      # but... there is no "log" pushed on loki because the body is empty
      attributes:
        severity: ""
        Type: "severity"
        EventType: ""
        hostname: "instance"
        instance: ""
        job: ""
        #fluent.tag: "job"

processors:
  batch:

service:
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [batch]
      exporters: [logging, loki]
```

**Environment**
Windows for fluentbit, Amz2 Linux for otel collector image.
