### ISSUE TITLE
Unknown exporters type "splunk_hec" Splunk HEC

### ISSUE THREAD

**Issue by amirulalif** [open-telemetry/opentelemetry-collector#2654]
**Describe the bug**
Unknown exporters type for "splunk_hec" Splunk HEC.

**Steps to reproduce**
```
otelcol --config /path-to-config-file/config.yaml
```

**What did you see instead?**
```
v0.22
DATE_TIME info	service/service.go:411	Starting OpenTelemetry Collector...	{"Version": "v0.22.0", "GitHash": "0345f0d2", "NumCPU": 2}
DATE_TIME info	service/service.go:292	Loading configuration...
Error: cannot load configuration: unknown exporters type "splunk_hec" for splunk_hec
DATE_TIME application run finished with error: cannot load configuration: unknown exporters type "splunk_hec" for splunk_hec
```
```
v0.20
DATE_TIME info	service/service.go:411	Starting OpenTelemetry Collector...	{"Version": "v0.20.0", "GitHash": "a10a1a7a", "NumCPU": 2}
DATE_TIME info	service/service.go:292	Loading configuration...
Error: cannot load configuration: unknown exporters type "splunk_hec" for splunk_hec
DATE_TIME application run finished with error: cannot load configuration: unknown exporters type "splunk_hec" for splunk_hec
```
```
v0.19
DATE_TIME info	service/service.go:411	Starting OpenTelemetry Collector...	{"Version": "v0.19.0", "GitHash": "f47e98ad", "NumCPU": 2}
DATE_TIME info	service/service.go:292	Loading configuration...
Error: cannot load configuration: unknown exporters type "splunk_hec" for splunk_hec
DATE_TIME application run finished with error: cannot load configuration: unknown exporters type "splunk_hec" for splunk_hec
```

**What version did you use?**
0.22 `otel-collector_0.22.0_amd64.deb`
0.20 `otel-collector_0.20.0_amd64.deb`
0.19 `otel-collector_0.19.0_amd64.deb`

**What config did you use?**
```
exporters:
  splunk_hec:
    token: "TOKENID"
    endpoint: "http://IP:8088/services/collector"
    source: "otel"
    sourcetype: "otel"
    index: "metrics"
    max_connections: 200
    disable_compression: false
    timeout: 10s
    insecure_skip_verify: false
service:
  pipelines:
    metrics:
      receivers: [opencensus, prometheus]
      processors: [batch]
      exporters: [splunk_hec]
```

**Environment**
OS: Ubuntu 18.04.5 LTS

**Additional context**
Download from [https://github.com/open-telemetry/opentelemetry-collector/releases](url)
