### ISSUE TITLE
Push metrics to OTLP HTTP receiver with curl and forward to Prometheus Remote Write

### ISSUE THREAD

**Issue by ctolon22** [open-telemetry/opentelemetry-collector#2656]
**Describe the bug**
Hi.

I have a configuration with 3 different receivers: otlp/http, hostmetrics/cpu and prometheus scraping `localhost:8888`. I want to send these metrics to another Prometheus with remote write so I have configured an exporter to `prometheusremotewrite`

I am pushing metrics to OTLP HTTP endpoint using JSON like explained [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp-request).

All my requests are responded with 200 ok. The file I am using as a metric is included below.

Metrics from `hostmetrics/cpu` and `prometheus` are being sent correctly but those I have tried to "push" to the OTLP HTTP endpoint are not.

I am probably missing some configuration or format but I have not found an example for this.

**What did you expect to see?**
I expect to receive my "custom" metric I have pushed to the OTLP HTTP endpoint

**What did you see instead?**
Missing the metric in the Prometheus where I remote write.

**What version did you use?**
otel/opentelemetry-collector-dev:latest

**What config did you use?**
```yaml
apiVersion: v1
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          http:
      hostmetrics:
        scrapers:
          cpu:
      prometheus:
        config:
          scrape_configs:
            - job_name: "otel-collector"
              scrape_interval: 5s
              static_configs:
                - targets: ["localhost:8888"]
    processors:
      batch:
    extensions:
      health_check: {}
    exporters:
      prometheusremotewrite:
        endpoint: "http://prometheus-server.prometheus.svc.cluster.local/api/v1/write"
        insecure: true
        external_labels:
          server: otel
      logging:
        loglevel: debug
    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [hostmetrics,prometheus]
          processors: [batch]
          exporters: [prometheusremotewrite]
        metrics/2:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
kind: ConfigMap
metadata:
  labels:
    app: opentelemetry
    component: otel-collector-conf
  name: otel-collector-conf
```

**Environment**
Installed everythin in Kubernetes

**Additional context**
Metric for the query sent with `curl -H "Content-Type: application/json" -XPOST <url to otel>:55681/v1/metrics --data '@query-body-example.json'`
```json
{
    "node": {
      "identifier": {
        "host_name": "hostname",
        "pid": 123,
        "start_timestamp": "2021-03-10T08:16:43.333Z"
      },
      "library_info": {
        "language": "LANGUAGE_UNSPECIFIED",
        "exporter_version": "1.0",
        "core_library_version": "1.0"
      },
      "service_info": {
        "name": "nameoftheservice"
      },
      "attributes": {
        "additionalProp1": "one",
        "additionalProp2": "two",
        "additionalProp3": "three"
      }
    },
    "metrics": [
      {
        "metric_descriptor": {
          "name": "nameofthemetrics",
          "description": "Description of the metric",
          "unit": "string",
          "type": "GAUGE_INT64",
          "label_keys": [
            {
              "key": "label1",
              "description": "Label one"
            }
          ]
        },
        "timeseries": [
          {
            "start_timestamp": "2021-03-10T08:16:43.333Z",
            "label_values": [
              {
                "value": "value1",
                "has_value": true
              }
            ],
            "points": [
              {
                "timestamp": "2021-03-10T08:16:43.333Z",
                "int64_value": "12345"
              }
            ]
          }
        ],
        "resource": {
          "type": "metric",
          "labels": {
            "property1": "example1"
          }
        }
      }
    ],
    "resource": {
      "type": "metric",
      "labels": {
        "property": "example1"
      }
    }
  }
```

Thanks a lot for your help
