### ISSUE TITLE
Prometheusreceiver throws SIGSEGV in MetricsAdjuster

### ISSUE THREAD

**Issue by akirn** [open-telemetry/opentelemetry-collector#2818]
**Describe the bug**
Prometheusreceiver segfaults and forces a restart of the Collector when `initial.GetSummaryValue().Count.GetValue()` returns nil.

**Steps to reproduce**
I'm not sure of the exact steps to reproduce the issue, other than having `initial.GetSummaryValue().Count.GetValue()` return nil.

**What did you expect to see?**
A graceful recovery (drop the current metric) without a forced restart.

**What did you see instead?**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x265a32c]

goroutine 488 [running]:
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustPoint(0xc00f683990, 0x7, 0xc00ed4d640, 0xc00f62de80, 0xc00f62de80, 0xc00f683568)
	/home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:339 +0x40c
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustPoints(0xc00f683990, 0x7, 0xc00f9c4948, 0x1, 0x1, 0xc00e241fe8, 0x1, 0x1, 0xc00e241fe8, 0x1, ...)
	/home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:292 +0x465
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustTimeseries(0xc00f683990, 0xc000000007, 0xc01773b620, 0xc00f62f0e0, 0xc00f62f0e0, 0xc00f99cf80)
	/home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:277 +0xbb
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetricTimeseries(0xc00f683990, 0xc01cc10e60, 0xc012951200, 0x1)
	/home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:257 +0x1e5
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).adjustMetric(0xc00f683990, 0xc01cc10e60, 0x0, 0x1)
	/home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:239 +0x5c
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*MetricsAdjuster).AdjustMetrics(0xc00f683990, 0xc01ccf5000, 0x97, 0x100, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/receiver/prometheusreceiver/internal/metrics_adjuster.go:214 +0x149
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*transaction).Commit(0xc0008f0580, 0xc00f799597faf131, 0x1d694d3120)
	/home/circleci/project/receiver/prometheusreceiver/internal/transaction.go:173 +0x4a5
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xc00f683c18, 0xc00f683c28, 0xc00f6158c0)
	/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1086 +0x49
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc00f6158c0, 0x1bf08eb000, 0x37e11d600, 0xc00f797797fb0f46, 0x178be9ed1, 0x47f6d20, 0xc00f799597faf131, 0x1d694d3120, 0x47f6d20, 0x0, ...)
	/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1153 +0xb45
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc00f6158c0, 0x1bf08eb000, 0x37e11d600, 0x0)
	/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:1039 +0x39e
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	/home/circleci/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210217141258-a6be548dbc17/scrape/scrape.go:510 +0x9ce
```

**What version did you use?**
`v0.22.0`

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
AKS and Kubernetes 1.18.10

**Additional context**
Installed via opentelemetry-helm-charts, running as an agent (Daemonset with 3 pods).

**Comment by akirn** [comment]
This is related to https://github.com/open-telemetry/opentelemetry-collector/issues/2297#issue-769271531.

Consuming metrics with empty descriptors and type of "none" triggers the above-described error.

In our case, the specific relabel configs that cause the issue are those in the following jobs:

```
        - job_name: 'kubernetes-service-endpoints'
          scrape_interval: 2m
          scrape_timeout: 15s
          kubernetes_sd_configs:
          - role: endpoints
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name

        - job_name: 'kubernetes-pods'
          scrape_interval: 2m
          scrape_timeout: 15s
          kubernetes_sd_configs:
          - role: pod
          relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
```
