### ISSUE TITLE
Attributesprocessor does not delete `process.command_line` tag

### ISSUE THREAD

**Issue by ozoz03** [open-telemetry/opentelemetry-collector#2830]
**Describe the bug**
Unable to delete `process.command_line` tag on Collector which contains sensitive data.

**Steps to reproduce**
```
    processors:
      attributes/delete:
        actions:
        - key: process.command_line
          action: delete
        ...  
    service:
      pipelines:
        traces:
          processors: [attributes/delete, memory_limiter, batch]
          ...         
  ```
          
**What did you expect to see?**
The tag should not be visible.

**What did you see instead?**
```
process.command_line | /Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home/jre:bin:java...

```

**What version did you use?**
Version: (`v0.23.0`)

**Comment by bogdandrutu** [comment]
I think that is a resource not an attribute on the Span. So give a try to the "resource" processor which should do what you expect. Config is very similar to the attributes processor.

**Comment by bogdandrutu** [comment]
I know the current design of processors is very confusing, so I am sorry about that, we will fix things in the near future.

**Comment by bogdandrutu** [comment]
Already answered and resolved in the java. The problem here was indeed the wrong processor used

**Comment by freshgeek** [comment]
hi~ can your tell me how to fix this question ? Unfortunately, I have also encountered this problem, but I cannot find a solution @bogdandrutu

**Comment by atoulme** [comment]
The problem is that the wrong processor is used, as Bogdan explained, and the resource processor should be used instead.

The snippet becomes:
```
processors:
      resource/delete:
        actions:
        - key: process.command_line
          action: delete
        ...  
    service:
      pipelines:
        traces:
          processors: [resource/delete, memory_limiter, batch]
          ...         
```
