### ISSUE TITLE
How would I go about getting internal traces for a collector itself?

### ISSUE THREAD

**Issue by jcleal** [open-telemetry/opentelemetry-collector#2831]
My team and I are looking to monitor some collectors we have running for a project, and was wondering how to pull the internal traces to send "somewhere" (eg. could be Jaeger, could be AWS X-Ray, etc). 

I'm thinking that I'd need to instrument a collector with an SDK to forward the traces to somewhere, but I noticed there are some traces returned from the [zpages extension](https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/zpagesextension). Just wondering how I'd forward those, if that's possible at the moment.

I previously asked this question over in https://cloud-native.slack.com/archives/C01N6P7KR6W, and was told to create an issue here 👍🏻

**Comment by alolita** [comment]
@bogdandrutu this issue does not seem to be a GA must-have issue? Can we move this to a post-GA phase 3 backlog?

**Comment by bogdandrutu** [comment]
I think we need to extend the ["config.Service"](https://github.com/open-telemetry/opentelemetry-collector/blob/0bbb1b7f3d886c4ba7a03b36ce4b57c538a727c5/config/config.go#L168) and allow to configure telemetry support:
1. Exporters for traces/metrics
2. Telemetry level (see that in the code).

So users should do this via configuration of the service (here is an example but somebody needs to really think if this is the right config):
```
service:
  telemetry:
    - defaultlevel: normal
    - metrics:
      - exporter: 
        - name: prometheus
        - port: 123
    - traces: 
      - exporter: 
        - name: x-ray
        - endpoint: localhost:123
  extensions: [exampleextension/0, exampleextension/1]
  pipelines:
    traces:
      receivers: [examplereceiver]
      processors: [exampleprocessor]
      exporters: [exampleexporter]
```
