### ISSUE TITLE
Prometheus receiver not working when `prometheus.io/port` added to annotations

### ISSUE THREAD

**Issue by golthitarun** [open-telemetry/opentelemetry-collector#2859]
**Describe the bug**
When I try to add 'prometheus.io/port' to pod annotations, collector with Prometheus receiver and Kubernetes pod scrape config, fails to scrape metrics from that pod. Debug loglevel is not showing any clear error messages, if I remove `prometheus.io/port` it's able to collect metrics.

log msg:
```2021-03-31T15:39:19.088Z	warn	internal/metricsbuilder.go:104	Failed to scrape Prometheus endpoint	{"component_kind": "receiver", "component_type": "prometheus", "component_name": "prometheus", "scrape_timestamp": 1617205159088, "target_labels": "map[app:hello-world-service instance:: istio_io_rev:default job:kubernetes-pods kubernetes_namespace:demo kubernetes_pod_name:hello-world-service-6c9854f69c-bcgk7 pod_template_hash:6c9854f69c security_istio_io_tlsMode:istio service_istio_io_canonical_name:hello-world-service service_istio_io_canonical_revision:1.0.0 version:1.0.0]"}```

If I use a Prometheus server, it's able to detect the 'prometheus.io/port' annotation as expected to scrape metrics with the same config as used in the collector.

**Steps to reproduce**
It can be reproduced in any Kubernetes environment by running a pod with metrics enabled and `prometheus.io/port` set in annotations

**What did you expect to see?**
I am expecting the port set to be used for scraping metrics from the pod containers.

**What did you see instead?**
collector is failing to scrape metrics

**What version did you use?**
Version: 0.20.0

**What config did you use?**
```
    exporters:
      logging:
        loglevel: debug
    extensions:
      health_check: {}
    processors:
      batch: {}
      memory_limiter:
        ballast_size_mib: 819
        check_interval: 5s
        limit_mib: 1638
        spike_limit_mib: 512
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:55681
      prometheus:
        config:
          scrape_configs:
          - job_name: kubernetes-pods
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (https?)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scheme
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: kubernetes_pod_name
            - action: drop
              regex: Pending|Succeeded|Failed
              replacement: $1
              separator: ;
              source_labels:
              - __meta_kubernetes_pod_phase
          - job_name: kubernetes-pods-slow
            kubernetes_sd_configs:
            - role: pod
            relabel_configs:
            - action: keep
              regex: true
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
            - action: replace
              regex: (https?)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_scheme
              target_label: __scheme__
            - action: replace
              regex: (.+)
              source_labels:
              - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: ([^:]+)(?::\d+)?;(\d+)
              replacement: $1:$2
              source_labels:
              - __address__
              - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: kubernetes_namespace
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: kubernetes_pod_name
            - action: drop
              regex: Pending|Succeeded|Failed
              source_labels:
              - __meta_kubernetes_pod_phase
            scrape_interval: 5m
            scrape_timeout: 30s
      zipkin:
        endpoint: 0.0.0.0:9411
    service:
      extensions:
      - health_check
      pipelines:
        metrics:
          exporters:
          - logging
          processors: []
          receivers:
          - prometheus
        traces:
          exporters:
          - logging
          processors:
          - batch
          receivers:
          - zipkin
 ```

**Environment**

RKE2 

**Additional context**
