### ISSUE TITLE
Jaeger thrift receiver requires parentID to be set

### ISSUE THREAD

**Issue by rmfitzpatrick** [open-telemetry/opentelemetry-collector#2884]
**Describe the bug**
The otel-java jaeger thrift exporter doesn't currently set the parentId field on its destination span, but instead creates a child_of reference.  This will cause a link to be created by the Collector's jaeger thrift to pdata translator so that the resulting* reference is a "follows_from" on jaeger exporting.

**Steps to reproduce**
Send a trace from the otel-java-sdk w/ jaeger thrift exporter to the collector's jaeger thrift receiver in a pipeline with a jaeger exporter.

**What did you expect to see?**
The parentId/child_of reference persisted

**What did you see instead?**
Follows from references in all child spans.

**What version did you use?**
`v0.23.1-0.20210329172532-38e57614135f`

**What config did you use?**
```yaml
receivers:
  jaeger:
    protocols:
      grpc:
      thrift_http:

exporters:
  jaeger:
    insecure: true

service:
  pipelines:
    traces:
      receivers: [jaeger]
      processors: []
      exporters: [jaeger]
```

**Additional context**
I'm happy to address this, but would like confirmation that we should be setting a parentID field if not explicitly set in the incoming thrift span: https://github.com/open-telemetry/opentelemetry-collector/blob/08a18d5b9f1b8ee001f8e16e6f6b9daf45b4d42e/translator/trace/jaeger/jaegerthrift_to_traces.go#L175
