### ISSUE TITLE
Ability to SHA data in span

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector#289]
Today we have the ability to redact tags in spans. Another use-case is to mask data in a consistent way so it can be seen, but not easily reverse engineered into its actual value. The specific ask we have heard is to support this for the IP address in the span. In theory, this should be an enhancement to the redaction processor.

**Comment by tigrannajaryan** [comment]
Existing `attributes` processor can be easily extended to allow this. Something like this in the config:
```
 attributes:
    actions:
      - key: "secret"
        from_attribute: "secret"
        transform: SHA256 # this is a new option
        action: update
```
This would update the attribute "secret" by its own SHA (or if needed SHA of another attribute). The `transform` option would specify what transformation to perform on the attribute value (default action would be `copy` or `noop - which is the current behavior).

@ccaraman, other suggestions to achieve this functionality are welcome.
