### ISSUE TITLE
Prometheus receiver throws error on parsing metrics with multiple similar summary values

### ISSUE THREAD

**Issue by marcdejonge** [open-telemetry/opentelemetry-collector#2928]
**Describe the bug**
We're using micrometer with Ktor for our services and by default it creates a prometheus summary type output for each endpoint with several quantiles. Parsing this gives us the error: "given metricType has no BucketLabel or QuantileLabel" in the output.

**Steps to reproduce**
We have an output like this:

```
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/health",status="200",throwable="n/a",quantile="0.5",} 0.027262976
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/health",status="200",throwable="n/a",quantile="0.9",} 0.042991616
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/health",status="200",throwable="n/a",quantile="0.95",} 0.070254592
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/health",status="200",throwable="n/a",quantile="0.99",} 0.070254592
ktor_http_server_requests_seconds_count{address="10.1.0.56:8080",method="GET",route="/health",status="200",throwable="n/a",} 156.0
ktor_http_server_requests_seconds_sum{address="10.1.0.56:8080",method="GET",route="/health",status="200",throwable="n/a",} 9.193772815
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/metrics",status="200",throwable="n/a",quantile="0.5",} 0.067108864
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/metrics",status="200",throwable="n/a",quantile="0.9",} 0.067108864
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/metrics",status="200",throwable="n/a",quantile="0.95",} 0.067108864
ktor_http_server_requests_seconds{address="10.1.0.56:8080",method="GET",route="/metrics",status="200",throwable="n/a",quantile="0.99",} 0.067108864
ktor_http_server_requests_seconds_count{address="10.1.0.56:8080",method="GET",route="/metrics",status="200",throwable="n/a",} 13.0
ktor_http_server_requests_seconds_sum{address="10.1.0.56:8080",method="GET",route="/metrics",status="200",throwable="n/a",} 2.248212394
```

**What did you expect to see?**
I expected this to parse correctly.

**What did you see instead?**
The error in the logging: "given metricType has no BucketLabel or QuantileLabel"

**What version did you use?**
Version: 0.22.0

**What config did you use?**
This is the relevant config for prometheus, nothing speciaal
```
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kubernetes-pods'
              scrape_interval: 10s
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
                  action: keep
                  regex: true
```

**Environment**
Using the Helm chart:
```
  - name: opentelemetry-collector
    version: ~0.5.3
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
```
