### ISSUE TITLE
data race between batch processor and kafkareceiver

### ISSUE THREAD

**Issue by hanjm** [open-telemetry/opentelemetry-collector#2956]
**Describe the bug**
data race in batch processor and kafkareceiver

```
==================
WARNING: DATA RACE
Write at 0x00c0001108d0 by goroutine 115:
  go.opentelemetry.io/collector/consumer/pdata.ResourceSpansSlice.MoveAndAppendTo()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/consumer/pdata/generated_trace.go:75 +0x237
  go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).add()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/processor/batchprocessor/batch_processor.go:269 +0xe5
  go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).processItem()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/processor/batchprocessor/batch_processor.go:187 +0x138
  go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/processor/batchprocessor/batch_processor.go:143 +0x284

Previous read at 0x00c0001108d0 by goroutine 123:
  go.opentelemetry.io/collector/consumer/pdata.ResourceSpansSlice.Len()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/consumer/pdata/generated_trace.go:52 +0x113
  go.opentelemetry.io/collector/consumer/pdata.Traces.SpanCount()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/consumer/pdata/trace.go:79 +0x3a
  go.opentelemetry.io/collector/receiver/kafkareceiver.(*consumerGroupHandler).ConsumeClaim()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/receiver/kafkareceiver/kafka_receiver.go:175 +0xd0b
  github.com/Shopify/sarama.(*consumerGroupSession).consume()
      /Users/jimmiehan/go/pkg/mod/github.com/!shopify/sarama@v1.28.0/consumer_group.go:690 +0x3a8
  github.com/Shopify/sarama.newConsumerGroupSession.func2()
      /Users/jimmiehan/go/pkg/mod/github.com/!shopify/sarama@v1.28.0/consumer_group.go:615 +0x104

Goroutine 115 (running) created at:
  go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).Start()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/processor/batchprocessor/batch_processor.go:103 +0x4c
  go.opentelemetry.io/collector/service/internal/builder.BuiltPipelines.StartProcessors()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/service/internal/builder/pipelines_builder.go:58 +0x154
  go.opentelemetry.io/collector/service.(*service).startPipelines()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/service/service.go:206 +0x264
  go.opentelemetry.io/collector/service.(*service).Start()
      /Users/jimmiehan/github.com/hanjm/opentelemetry-collector/service/service.go:90 +0x169

```

**Steps to reproduce**
1. modify examples/local/otel-config.yaml, add kafka receiver and kafka exporter.

```yaml
receivers:
  kafka:

exporters:
  logging:
    logLevel: debug
  kafka:

service:
  pipelines:
    traces/producer:
      receivers: [otlp, opencensus, jaeger, zipkin]
      exporters: [kafka]
    traces/consumer:
      receivers: [kafka]
      processors: [batch]
      exporters: [logging]
```

2. make run

go run --race ./cmd/otelcol/... --config examples/local/otel-config.yaml 

3. client send some trace  span data. 
4. collector log data race

**What did you expect to see?**
no data race

**What did you see instead?**
data race

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

master  90b2dec708129eeb21d705dc4bee36e4a8d043d3 

**What config did you use?**
Config: (e.g. the yaml config file)

```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  opencensus:
  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:
  zipkin:
  kafka:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

processors:
  batch:

exporters:
  logging:
    logLevel: debug
  kafka:
service:
  pipelines:
    traces/producer:
      receivers: [otlp, opencensus, jaeger, zipkin]
      exporters: [kafka]
    traces/consumer:
      receivers: [kafka]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp, opencensus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]

```

**Environment**
OS: Macos 10.15.7 
Compiler(if manually compiled):  go version go1.16.3 darwin/amd64

**Additional context**
