### ISSUE TITLE
Add gRPC health check

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector#3040]
**Is your feature request related to a problem? Please describe.**
If you want to deploy the OpenTelemetry Collector in gateway-mode behind an AWS Application Load Balancer (ALB) to support gRPC (e.g. OTLP) then ALB requires a gRPC health check. Today, we have a health check extension, however it only support HTTP.

**Describe the solution you'd like**
Either extend the health check extension or add health check endpoints to gRPC receivers.

**Describe alternatives you've considered**
Switch from gRPC to HTTP for receiving data

**Comment by rakyll** [comment]
Might be related to https://github.com/open-telemetry/opentelemetry-collector/issues/3002.

**Comment by ligeogeorge** [comment]
+1 

Unable to set up ALB->(gRPC)->ECS because there is no support for gRPC health checks as is required by AWS ALB. This would be a common use case, IMO.

#3002 is only talking about enhancing HTTP health checks.

**Comment by obitech** [comment]
You can specify the allowed return codes on the ALB, as a workaround just set them to `0-99` and leave the health check path as default.

**Comment by g3kr** [comment]
@flands @obitech can you share your collector config? I am running into problems using the ALB as the otlp exporter endpoint.  or could you throw some light on #5246 ? Much appreciated. Thank you

**Comment by jangaraj** [comment]
I use this config for ALB for OTLP/GRPC, which works like a charm:
```
 TargetGroupGRPC:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 4317
      Protocol: HTTP
      ProtocolVersion: GRPC
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Matcher:
        GrpcCode: 0-99
      HealthCheckTimeoutSeconds: 4
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetType: ip
```
Unfortunately, I have a problem with OTLP/HTTP. It works fine with JSON payload, but it has problem with protobuf payloads sometimes (SSL handshake timeout, client headers timeout):
```
 TargetGroupHTTP:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 4318
      Protocol: HTTP
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckPort: 13133
      HealthCheckTimeoutSeconds: 4
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetType: ip
 ```
 Any idea how to configure AWS ALB to work with OTLP HTTP Protobuf?
