### ISSUE TITLE
Support for Custom Exporter Authenticators as Extensions 

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector#3115]
**Is your feature request related to a problem? Please describe.**
We recently added framework to add server (receiver) side authentication via extensions.  This is very convenient to extend and add custom authentication seamlessly.  In similar fashion clients (exporters) should be able to utilize any custom authentication defined as extension. 

**Describe the solution you'd like**

something like this (similar to [extension/authoidcextension)](https://github.com/open-telemetry/opentelemetry-collector/tree/main/extension/authoidcextension) for receivers

```
extensions:
  oauth2:
      client_id: someclientidentifier
      client_secret: someclientsecret
      token_url: https://autz.server/oauth2/default/v1/token
      scopes: ["some.resource.read"]

exporter:
  otlphttp/withauth:
    authentication:
      authenticator: oauth2

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [oltphttp/withoauth]
```

**Describe alternatives you've considered**
Implemented PR #2464 where ConfigHttp client directly implements one form of Auth (Oauth2)
