### ISSUE TITLE
Inconsistent results between prometheusexporter and prometheusremotewrite

### ISSUE THREAD

**Issue by albertteoh** [open-telemetry/opentelemetry-collector#3131]
**Describe the bug**
When using prometheusremotewrite to export metrics to M3, I'm getting latencies that are over 200 years when queried from M3.

However, when scraping these metrics from prometheus, the latencies look correct.

Am I configuring something incorrectly?

**Steps to reproduce**
1. Run opentelemetry-collector-contrib with the config attached in this issue.
2. Send spans to the collector using omnition/synthetic-load-generator, and with the spanmetrics processor sending metrics to a prometheus exporter. 
3. Have a prometheus server running to scrape metrics from the prometheus exporter.
4. Within opentelemetry collector, a prometheus receiver will also scrape metrics from the same prometheus exporter above and send it to the configured prometheusremotewrite exporter that will write to an M3 instance.
5. Setup grafana to query both data sources (prometheus server and M3) and graph both timeseries with the same query.

**What did you expect to see?**
Identical 95th percentile latencies, or at least close enough to one another.

**What did you see instead?**
Latencies from M3 were over 200 years, whereas from Prometheus, they were a more sensible ~200ms.

Here are two screenshots of the same query executed against Prometheus and M3 data sources respectively:

**Prometheus**
<img width="1266" alt="Screen Shot 2021-05-08 at 10 30 09 pm" src="https://user-images.githubusercontent.com/26584478/117539216-04892800-b04d-11eb-90a4-9386fdc8f42d.png">

**M3**
<img width="1266" alt="Screen Shot 2021-05-08 at 10 29 54 pm" src="https://user-images.githubusercontent.com/26584478/117539218-06eb8200-b04d-11eb-996e-24df8d9ccba7.png">

To reduce the search space by ruling out M3 and spanmetrics processor as possible causes, I also checked the logs (these are from an earlier run):

Here, I log the total latency_count as well as the latency_bucket counts within spanmetrics processor. I've taken logs from two different times, 10 seconds apart and as you can see, the count is consistent with the sum of bucket_counts:
```
2021-05-08T18:54:20.947+1000    debug   spanmetricsprocessor@v0.0.0-00010101000000-000000000000/processor.go:258        Latency metrics {"kind": "processor", "name": "spanmetrics", "key": "frontend\u0000/checkout\u0000SPAN_KIND_CLIENT\u0000STATUS_CODE_UNSET", "count": 2, "bucket_count": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]}

2021-05-08T18:54:30.958+1000    debug   spanmetricsprocessor@v0.0.0-00010101000000-000000000000/processor.go:258        Latency metrics {"kind": "processor", "name": "spanmetrics", "key": "frontend\u0000/checkout\u0000SPAN_KIND_CLIENT\u0000STATUS_CODE_UNSET", "count": 3, "bucket_count": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0]}
```

However, this is the log output from the last metrics pipeline in the config below, i.e.:
```
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite, logging]
```

As you can see the total count is `1` but the bucket count total is `2 + 1 = 3`, and so I believe the `+Inf` tries to account for this discrepancy, resulting in `-2` represented as the uint64 equivalent of `18446744073709551614`. I have also seen versions in logs where the total count > sum of bucket counts, leading to a "positive" spillover `+Inf` count.
```
HistogramDataPoints #12
Data point labels:
     -> operation: /checkout
     -> service_name: frontend
     -> span_kind: SPAN_KIND_CLIENT
     -> status_code: STATUS_CODE_UNSET
StartTimestamp: 2021-05-08 08:54:22.433 +0000 UTC
Timestamp: 2021-05-08 08:54:32.437 +0000 UTC
Count: 1
Sum: 1708.000000
ExplicitBounds #0: 2.000000
ExplicitBounds #1: 6.000000
ExplicitBounds #2: 10.000000
ExplicitBounds #3: 100.000000
ExplicitBounds #4: 250.000000
ExplicitBounds #5: 300.000000
ExplicitBounds #6: 400.000000
ExplicitBounds #7: 800.000000
ExplicitBounds #8: 1000.000000
ExplicitBounds #9: 1400.000000
ExplicitBounds #10: 2000.000000
ExplicitBounds #11: 5000.000000
ExplicitBounds #12: 15000.000000
ExplicitBounds #13: 30000.000000
ExplicitBounds #14: 120000.000000
ExplicitBounds #15: 9223372036854.000000
Buckets #0, Count: 0
Buckets #1, Count: 0
Buckets #2, Count: 0
Buckets #3, Count: 0
Buckets #4, Count: 0
Buckets #5, Count: 0
Buckets #6, Count: 0
Buckets #7, Count: 0
Buckets #8, Count: 0
Buckets #9, Count: 0
Buckets #10, Count: 2
Buckets #11, Count: 1
Buckets #12, Count: 0
Buckets #13, Count: 0
Buckets #14, Count: 0
Buckets #15, Count: 0
Buckets #16, Count: 18446744073709551614
```

**What version did you use?**
Version: opentelemetry-collector-contrib@master

**What config did you use?**
Config: (e.g. the yaml config file)

```
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'atm'
        scrape_interval: 10s
        static_configs:
        - targets: [ "0.0.0.0:8889" ]

  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14278"

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:65535"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  logging:
    loglevel: debug

  jaeger:
    endpoint: "localhost:14250"
    insecure: true

  prometheusremotewrite:
    endpoint: "http://localhost:7201/api/v1/prom/remote/write"
    insecure: true

  otlp/spanmetrics:
    endpoint: "localhost:55677"
    insecure: true


processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus
    # default (in ms): [2, 4, 6, 8, 10, 50, 100, 200, 400, 800, 1000, 1400, 2000, 5000, 10_000, 15_000]
    latency_histogram_buckets: [2ms, 6ms, 10ms, 100ms, 250ms, 300ms, 400ms, 800ms, 1s, 1.4s, 2s, 5s, 15s, 30s, 120s]

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [spanmetrics]
      exporters: [jaeger]
    # The exporter name must match the metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [prometheus, logging]
    metrics:
      receivers: [prometheus]
      exporters: [prometheusremotewrite, logging]
```

**Environment**
OS: MacOS
Compiler(if manually compiled): go 1.16

**Additional context**
cc @bogdandrutu
