### ISSUE TITLE
Kafka receiver metrics abnormal behavior

### ISSUE THREAD

**Issue by hyde404** [open-telemetry/opentelemetry-collector#3149]
Hello,

We are currently facing an issue with metrics consumption from kafka receiver running on kubernetes.

Here's what we are trying to achieve:

Metrics from app ---->(receiver: otlp) OTLP Collector 1 (exporter: kafka)---> KAFKA <--- (receiver: kafka) OTLP Collector 2(exporter: prometheus)

but we get this error message : 
```
Error: cannot build pipelines: cannot build receivers: receiver kafka/metrics does not support metrics but it was used in a metrics pipeline
2021/05/12 20:03:10 application run finished with error: cannot build pipelines: cannot build receivers: receiver kafka/metrics does not support metrics but it was used in a metrics pipeline
```

Here's a sample of my configuration:

### OTLP Collector 1:
```
receivers:
  # Self monitor to have some metrics to test things up
  otlp:
    protocols:
      grpc:
      http:

...

exporters:
  kafka/metrics:
    brokers:
      - kafka-otelcol-bootstrap.<NAMESPACE>.svc.cluster.local:9092
    topic: otlp-metrics-receivers

service:
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [kafka/metrics]
```

### OTLP Collector 2 : 

```
receivers:
  kafka/metrics:
    topic: otlp-metrics-receivers
    brokers:
      - kafka-otelcol-bootstrap.<NAMESPACE>.svc.cluster.local:9092
...

service:
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [kafka/metrics]
      processors: []
      exporters: [prometheus]
```

We already noticed `"Supported pipeline types: traces, logs"` on the kafka receiver front page but is it possible to use kafka for metrics another way ? 
Is it an incoming feature ?

Thank you !
