### ISSUE TITLE
Collector return "invalid length for ID" for trace reporting 

### ISSUE THREAD

**Issue by jacky15** [open-telemetry/opentelemetry-collector#3195]
**Describe the bug**
I am using  opentelemetry-collector with otlphttp exporter. But when data report to the collector, it return HTTP status code 400 with the message "invalid length for ID"

**Steps to reproduce**
Here is the tcp traffic

```
POST /v1/traces HTTP/1.1
Host: 10.0.1.21:4317
User-Agent: Go-http-client/1.1
Content-Length: 20316
Content-Type: application/json
Accept-Encoding: gzip

{"resourceSpans":[{"resource":{"attributes":[{"key":"service.name","value":{"stringValue":"unknown_service:unify-query"}},{"key":"telemetry.sdk.language","value":{"stringValue":"go"}},{"key":"telemetry.sdk.name","value":{"stringValue":"opentelemetry"}},{"key":"telemetry.sdk.version","value":{"stringValue":"0.19.0"}}]},"instrumentationLibrarySpans":[{"instrumentationLibrary":{"name":"bk-monitorv3/unify-query"},"spans":[{"traceId":"cgXI6uihz643E6Zqq7Nl4w==","spanId":"+iPdFTeJDX8=","name":"/metrics","kind":"SPAN_KIND_INTERNAL","startTimeUnixNano":"1621253293188761633","endTimeUnixNano":"1621253293190601010","status":{"code":"STATUS_CODE_OK"}},{"traceId":"tXrmFgvi148s6EsroJ1S1A==","spanId":"zIqhNylUXuk=","name":"/metrics","kind":"SPAN_KIND_INTERNAL","startTimeUnixNano":"1621254568188753964","endTimeUnixNano":"1621254568189747171","status":{"code":"STATUS_CODE_OK"}},{"traceId":"Q2sKzOrO09THC8n5rb8V5Q==","spanId":"x6GjCl4l8t8=","name":"/metrics","kind":"SPAN_KIND_INTERNAL","startTimeUnixNano":"1621254583188746771","endTimeUnixNano":"1621254583189715582","status":{"code":"STATUS_CODE_OK"}}]}]}]}

HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Mon, 17 May 2021 12:29:56 GMT
Content-Length: 73

{
  "code": 3,
  "message": "invalid length for ID",
  "details": [
  ]
}

```

**What did you expect to see?**
Report success.

**What did you see instead?**
Report failed with 400 status code

**What version did you use?**
Version: c1e3d479ca759284a08b2570d6ececc58980813e

**What config did you use?**

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4317"
processors:
  batch:
extensions:
  health_check: {}
exporters:
  zipkin:
    endpoint: "http://10.0.0.1:9411/api/v2/spans"
    format: proto
  logging:
    loglevel: debug
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]
```

**Environment**
OS: centos-release-7-8.2003.0.el7.centos.x86_64
Compiler(if manually compiled): go version go1.14 linux/amd64
