### ISSUE TITLE
Add processor: convert to lowercase

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector#322]
As a user, I want a processor that will convert a service name or attribute to lowercase.

**Comment by ccaraman** [comment]
For Spans, the configuration could look like
```
span/transform:
  name:
    action: transform
    transform: {lower/upper}

span/rename:
 name:
   action: rename
   separator: <string>
   from_attributes: [ <key0>,...]
```
With attributes processor looking like
```
attributes/transform:
  actions:
    - key: "some key"
       action: transform
       transform: {lower, upper}
```
