### ISSUE TITLE
fileexporter panics when marshaling data

### ISSUE THREAD

**Issue by loomis-relativity** [open-telemetry/opentelemetry-collector#3248]
**Describe the bug**
The fileexporter panics when it processes data and causes the Collector to fail.

**Steps to reproduce**
Run the given Kubernetes manifest with `k apply -f .`.

[collector-egress-file.txt](https://github.com/open-telemetry/opentelemetry-collector/files/6522939/collector-egress-file.txt)

**What did you expect to see?**
The Collector starting and then writing metric data to the configured file in the container. 

**What did you see instead?**
The Collector starts but fails as soon as the Prometheus metric data is processed by the fileexporter. 

**What version did you use?**
Version: v0.27.0

**What config did you use?**
Config:

```yaml
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'collector-metrics'
              scrape_interval: 10s
              static_configs:
                - targets:
                    - 'localhost:8888'

    exporters:
      logging:
      file:
        path: /metrics.json

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          # Works if only the logging exporter is configured.
          #exporters: [logging]
          # Panics if any data sent to file exporter. This configuration
          # tests only the metrics, but also fails with logs or traces.
          exporters: [logging, file]
```

**Environment**
OS: Microsoft Windows 10 Enterprise (Version 10.0.18363 Build 18363)

**Additional context**
Although the example only reproduces the problem for metrics, in our environment we see the same behavior for logs and traces as well.

The stack trace of the panic follows:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcf8878]

goroutine 146 [running]:
github.com/gogo/protobuf/jsonpb.(*errWriter).write(...)
        github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb.go:1272
github.com/gogo/protobuf/jsonpb.(*Marshaler).marshalObject(0x4b98600, 0xc0003dae80, 0x36cb5b0, 0xc0003488a0, 0x0, 0x0, 0x0, 0x0, 0x2d1c640, 0x9360200ae101)
        github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb.go:281 +0x14f8
github.com/gogo/protobuf/jsonpb.(*Marshaler).Marshal(0x4b98600, 0x0, 0x0, 0x36cb5b0, 0xc0003488a0, 0xc00061e420, 0x36de718)
        github.com/gogo/protobuf@v1.3.2/jsonpb/jsonpb.go:138 +0x1b0
go.opentelemetry.io/collector/exporter/fileexporter.exportMessageAsLine(0xc000b16f90, 0x36cb5b0, 0xc0003488a0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/fileexporter/file_exporter.go:63 +0xc9
go.opentelemetry.io/collector/exporter/fileexporter.(*fileExporter).ConsumeMetrics(...)
        go.opentelemetry.io/collector/exporter/fileexporter/file_exporter.go:52
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsRequest).export(0xc000b11dc0, 0x36de6e0, 0xc00061e420, 0x36de6e0, 0xc00061e420)
        go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:55 +0x47
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000059c08, 0x36f16f8, 0xc000b11dc0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/common.go:222 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc0009bff80, 0x36f16f8, 0xc000b11dc0, 0x31a4d05, 0x8)
go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send(0xc00063adb0, 0x36f16f8, 0xc000b11dc0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:119 +0xb1
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send(0xc0000dc690, 0x36f16f8, 0xc000b11dc0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/queued_retry.go:171 +0x3dc
go.opentelemetry.io/collector/exporter/exporterhelper.NewMetricsExporter.func2(0x36de718, 0xc000810f00, 0xc0003488a0, 0x0, 0x0)
        go.opentelemetry.io/collector/exporter/exporterhelper/metrics.go:103 +0xbe
go.opentelemetry.io/collector/consumer/consumerhelper.ConsumeMetricsFunc.ConsumeMetrics(0xc000b11280, 0x36de718, 0xc000810f00, 0xc0003488a0, 0x0, 0x0)
        go.opentelemetry.io/collector/consumer/consumerhelper/metrics.go:29 +0x44
go.opentelemetry.io/collector/service/internal/fanoutconsumer.metricsConsumer.ConsumeMetrics(0xc000b112e0, 0x2, 0x2, 0x36de718, 0xc000810f00, 0xc0003488a0, 0xc0003488a0, 0xc000aa7040)
        go.opentelemetry.io/collector/service/internal/fanoutconsumer/consumer.go:51 +0xa4
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*transaction).Commit(0xc000122b60, 0x314c3638, 0xed839af41)
        go.opentelemetry.io/collector/receiver/prometheusreceiver/internal/transaction.go:202 +0x2e9
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xc0003dbce8, 0xc00068bcf8, 0xc00002a2c0)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1096 +0x49
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc00002a2c0, 0x2540be400, 0x2540be400, 0x0, 0x0, 0x0, 0x314c3638, 0xed839af41, 0x4b991a0, 0x0, ...)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1163 +0xb4d
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc00002a2c0, 0x2540be400, 0x2540be400, 0x0)
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:1049 +0x365
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
        github.com/prometheus/prometheus@v1.8.2-0.20210430082741-2a4b8e12bbf2/scrape/scrape.go:518 +0x9ce
```
