### ISSUE TITLE
Attributes processor is not identified when regex does not match

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-collector#3300]
**Describe the bug**
When a regular expression doesn't match a log line, it fails, but is not identified in the error message, making it hard for the developer to understand which processor entry is failing.

**Steps to reproduce**
Define a pipeline with two different processors such as:
```
attributes/quorum_log_file:
    actions:
      - key: "file_name"
        pattern: ^geth-(?P<host>.*)\.log
        action: extract
  attributes/tessera_log_file:
    actions:
      - key: "file_name"
        pattern: ^tessera-(?P<host>.*)\.log
        action: extract
```
Add those 2 processors to the same pipeline.

Run the pipeline.

**What did you expect to see?**
I expect to see no errors, or a warning that one of the regular expression has not matched, at most.

**What did you see instead?**
I see this error:
```
2021-05-25T17:47:17.107Z	ERROR	Failed to process entry	{"kind": "receiver", "name": "filelog/quorum", "operator_id": "$.regex_parser", "operator_type": "regex_parser", "error": "regex pattern does not match", "action": "send", "entry": {"timestamp":"2021-05-25T17:47:17.107868766Z","severity":0,"attributes":{"file_name":"geth-5b637c3a018d.log"},"body":"DEBUG[05-25|17:47:16.943] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s"}}
```
Neither `attributes/quorum_log_file` nor `attributes/tessera_log_file` are named.

**What version did you use?**
Latest

**Environment**
OS: Ubuntu 20.04

**Additional context**
Additionally, I don't think this should error out at all :)
