### ISSUE TITLE
Add in ability to specify tls version (min and max)

### ISSUE THREAD

**Issue by bputt-e** [open-telemetry/opentelemetry-collector#3396]
**Is your feature request related to a problem? Please describe.**
We have requirements where we have to require TLSv1.2+ and the OTLP receiver does not seem to have a way to configure a specific TLS version to adhere to

**Describe the solution you'd like**
Add config options to configtls.go where we can configure the MinVersion & MaxVersion per https://pkg.go.dev/crypto/tls#Config

**Describe alternatives you've considered**
We *can* setup a proxy in front of OTLP to terminate SSL to adhere to our requirements, but figured it might be best to remove the additional layer

**Additional context**
Example config for tls_settings:
```
receivers:
  otlp:
    protocols:
      grpc:
        tls_settings:
          min_version: 1.2
          max_version: 1.3
```
