### ISSUE TITLE
OTLP receiver seems to support deprecated fields only

### ISSUE THREAD

**Issue by akiross** [open-telemetry/opentelemetry-collector#3451]
**Describe the bug**
It seems that the collector is [still using](https://github.com/open-telemetry/opentelemetry-collector/blob/main/cmd/pdatagen/internal/metrics_structs.go) deprecated metric fields _only_ (e.g. `IntSum`, `IntGauge`) and apparently it's unable to receive data that is conformant to the protocol, but not using deprecated fields. This emerged a [couple of weeks back](https://gitter.im/open-telemetry/opentelemetry-rust?at=60b60915d0f55b33ba1e4411) when trying to use OTLP exporter using opentelemetry-rust and the latest collector (0.27, but this did not change with 0.28).

**Steps to reproduce**
1. Use `opentelemetry-rust` 0.14.0 and `opentelemetry-otlp` 0.7 to export metrics gauges;
2. Use collector to receive the data;
3. Send valid data to collector;
4. Collector receives only 0 values.

**What did you expect to see?**
Collector should be able to receive correct data, even if the protocol version is more recent.

**What did you see instead?**
I see data being sent correctly via OTLP, but only 0 were received.

**What version did you use?**
Version: `v0.27.0` but this seems to affect `v0.28.0` as well

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging
```

**Environment**
OS: Docker container with Ubuntu 20.04.

**Additional context**

Not an otel/otlp expert, but it seems the collector is using only some of the possible fields that are coming via otlp - in particular, deprecated ones. I'm aware that there's a plan to remove deprecated fields and that this is not really a bug (depending on the PoV), but I was unable to find an issue on this and, as a user of (patched) rust crates, I would like to have an issue to know when this problem will be addressed and bump my stack.

Please, disregard this if a tracking issue is present already.
