### ISSUE TITLE
Refactor service "config"

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-collector#346]
Currently service contains only "extensions". I suggest that service should contain extensions and pipelines:

**Current:**
```
receivers:
  examplereceiver:
  examplereceiver/myreceiver:
    endpoint: "127.0.0.1:12345"
    extra: "some string"
  examplereceiver/disabled:
    disabled: true

processors:
  exampleprocessor:
  exampleprocessor/disabled:
    disabled: true

exporters:
  exampleexporter/myexporter:
    extra: "some export string 2"
  exampleexporter/disabled:
    disabled: true
  exampleexporter:

pipelines:
  traces:
    receivers: [examplereceiver, examplereceiver/disabled]
    processors: [exampleprocessor, exampleprocessor/disabled]
    exporters: [exampleexporter/disabled, exampleexporter]

extensions:
  exampleextension/0:
  exampleextension/disabled:
    disabled: true
  exampleextension/1:
    extra: "some string"

service:
  extensions: [exampleextension/0, exampleextension/disabled, exampleextension/1]
```

**Proposed:**
```
receivers:
  examplereceiver:
  examplereceiver/myreceiver:
    endpoint: "127.0.0.1:12345"
    extra: "some string"
  examplereceiver/disabled:
    disabled: true

processors:
  exampleprocessor:
  exampleprocessor/disabled:
    disabled: true

exporters:
  exampleexporter/myexporter:
    extra: "some export string 2"
  exampleexporter/disabled:
    disabled: true
  exampleexporter:

extensions:
  exampleextension/0:
  exampleextension/disabled:
    disabled: true
  exampleextension/1:
    extra: "some string"

service:
  extensions:
    - exampleextension/0
    - exampleextension/disabled
    - exampleextension/1
  pipelines:
    traces:
      receivers:
        - examplereceiver
        - examplereceiver/disabled
      processors:
        - exampleprocessor
        - exampleprocessor/disabled
      exporters:
        - exampleexporter/disabled
        - exampleexporter
```
