### ISSUE TITLE
kubectl exec -it  otel-collector-589ffff9c8-8lrch    -n default    -- /bin/bash - Error

### ISSUE THREAD

**Issue by anishmarokeyGitHub** [open-telemetry/opentelemetry-collector#3481]
when I am trying to -it in kubectl geting below error.

### **command:**
kubectl exec -it  otel-collector-589ffff9c8-8lrch    -n default    -- /bin/bash

Error:
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
command terminated with exit code 126

**Comment by jrcamp** [comment]
Unfortunately the image doesn't ship with any shell. You can try using [k8s debug container](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/) if enabled for your environment. Otherwise you'll have to build your own image (could do `FROM <otel image>` to extend it).

**Comment by anishmarokeyGitHub** [comment]
@jrcamp  thanks for info.

where I can find the **./filename.json** I used in exporter.

My Config:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
    ....................
  exporters:
      file:
        path: ./filename.json
```

I have to check open-telemetry is configured properly
