### ISSUE TITLE
Enviroment Variable Expansion in Configuration doesn't work as expected

### ISSUE THREAD

**Issue by pquerna** [open-telemetry/opentelemetry-collector#3584]
**Describe the bug**
- I tried to use an evnrioment variable expansion, per the documentation here: https://opentelemetry.io/docs/collector/configuration/#configuration-environment-variables
- I'm storing my honeycomb API key in a k8s secret.
- I set the secret to the environment variable `HONEYCOMB_WRITE_KEY`
- I used the following otelcol configuration:

```
---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls_settings:
          client_ca_file: /mnt/pki/service-ca.crt
          cert_file: /mnt/pki/service.crt
          key_file: /mnt/pki/service.key

extensions:
  health_check:

processors:
  batch:

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${HONEYCOMB_WRITE_KEY}"
      "x-honeycomb-dataset": "sandbox-usw2"
  logging:
    # change to debug log level to see all traces logged
    # logLevel: debug
    logLevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
  extensions: [health_check]
```

**Steps to reproduce**
- Use environment variable as a oltp gRPC Header Value 

**What did you expect to see?**
- Environment variable was not expanded.  When I hard coded the API key instead of trying to use the Enviroment Variable expansion, it immediately worked. 

**What did you see instead?**

**What version did you use?**
Version: v0.29.0

**Environment**
OS: debian/10
Compiler: go 1.16.5
