### ISSUE TITLE
OTLP  Collector does not support auth with http protocol

### ISSUE THREAD

**Issue by Renaud009** [open-telemetry/opentelemetry-collector#3680]
**Describe the bug**
I'm trying to send web application traces to otel collector http api. Currently working, but when adding oidc authentication extension, it looks like protocol http does not support that.

Following the collector documentation, "Most receivers exposing an HTTP or gRPC port are able to be protected using the collector’s authentication mechanism, and most exporters using HTTP or gRPC clients are able to add authentication data to the outgoing requests.".

**Steps to reproduce**
- Using docker image otel/opentelemetry-collector:0.28.0
- Targetting a config file that contain receiver http auth:
```
extensions:
  oidc:
    issuer_url: http://localhost:8080/auth/realms/opentelemetry
    audience: collector
receivers:
  otlp/auth:
    protocols:
      http:
        endpoint: '0.0.0.0:55681'
        cors_allowed_origins:
          - http://*
          - https://*
        auth:
          authenticator: oidc
```

**What did you expect to see?**
Collector validating token with provided Identity Server

**What did you see instead?**
Console error:
```
2021-07-20T15:09:12.303Z     info    service/application.go:262      Starting otelcol...     {"Version": "v0.28.0", "NumCPU": 8}
otel-collector_1         | 2021-07-20T15:09:12.303Z     info    service/application.go:170      Setting up own telemetry...
otel-collector_1         | 2021-07-20T15:09:12.304Z     info    service/telemetry.go:99 Serving Prometheus metrics      {"address": ":8888", "level": 0, "service.instance.id": "1c724a06-cc04-42bc-85d7-f27b066849e6"}
otel-collector_1         | 2021-07-20T15:09:12.304Z     info    service/application.go:205      Loading configuration...
otel-collector_1         | Error: cannot load configuration: error reading receivers configuration for otlp/auth: 1 error(s) decoding:
otel-collector_1         | 
otel-collector_1         | * 'protocols.http' has invalid keys: auth
otel-collector_1         | 2021/07/20 15:09:12 application run finished with error: cannot load configuration: error reading receivers configuration for otlp/auth: 1 error(s) decoding:
otel-collector_1         | 
otel-collector_1         | * 'protocols.http' has invalid keys: auth
otel-collector_1         | 2021-07-20T15:14:52.407Z     info    service/application.go:262      Starting otelcol...     {"Version": "v0.28.0", "NumCPU": 8}
otel-collector_1         | 2021-07-20T15:14:52.408Z     info    service/application.go:170      Setting up own telemetry...
otel-collector_1         | 2021-07-20T15:14:52.409Z     info    service/telemetry.go:99 Serving Prometheus metrics      {"address": ":8888", "level": 0, "service.instance.id": "bd6467e0-41de-4018-829b-c3005c936731"}
otel-collector_1         | 2021-07-20T15:14:52.409Z     info    service/application.go:205      Loading configuration...
otel-collector_1         | Error: cannot load configuration: error reading receivers configuration for otlp/auth: 1 error(s) decoding:
otel-collector_1         | 
otel-collector_1         | * 'protocols.http' has invalid keys: auth
otel-collector_1         | 2021/07/20 15:14:52 application run finished with error: cannot load configuration: error reading receivers configuration for otlp/auth: 1 error(s) decoding:
```

**What version did you use?**
docker image otel/opentelemetry-collector:0.28.0

**What config did you use?**
```
receivers:
  otlp/auth:
    protocols:
      http:
        endpoint: '0.0.0.0:55681'
        cors_allowed_origins:
          - http://*
          - https://*
        auth:
          authenticator: oidc
exporters:
  logging: # traces, metrics, logs
    loglevel: debug
processors:
  batch:
    send_batch_size: 1
extensions:
  oidc:
    issuer_url: http://localhost:8080/auth/realms/opentelemetry
    audience: collector
service:
  extensions: [oidc]
  pipelines:
    traces:
      receivers: [otlp/auth]
      processors: [batch]
      exporters: [logging]
```

**Environment**
Docker WSL2

Am I doing something wrong or auth really not supported for http protocol?
