### ISSUE TITLE
Collector not working on localhost

### ISSUE THREAD

**Issue by dickiebowuk** [open-telemetry/opentelemetry-collector#3713]
First off apologies is this is not the right place as I feel I am asking for help more than reporting a bug, but the stackoverflow community for opentelemetry is non existent with most questions unanswered.

I have applied opentelemetry to a .Net Core 5 API using the following nuget packages:

OpenTelemetry 1.1.0-rc1
OpenTelemetry.Exporter.Console 1.1.0-beta-1
OpenTelemetry.Exporter.Jaeger 1.1.0-rc1
OpenTelemetry.Exporter.OpeneTelemetryProtocol 1.1.0-beta1
OpenTelemetry.Exporter.Zipkin 1.1.0-beta1
OpenTelemetry.Extensions.Hosting 1.0.0-rc6
OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc6
OpenTelemetry.Instrumentation.Http 1.0.0-rc6
OpenTelemetry.Instrumentation.SqlClient 1.0.0-rc6

I have successfully had trace and log data being exported out of the API to both Jaeger and Zipkin locally and to my New Relic account using their own NuGet package.

The problem arises when I try and export data from my API to the collector running in a docker container on my laptop. I first tried to export to Zipkin and have the Collector batch process the data and export it to Jaeger. I can see the spans have been received by Zipkin, but nothing appears in Jaeger. I have also tried the OTLP exporter to the collector with it batch processing data and exporting it to Jaeger and Zipkin and it produces no output. I can see some metrics in Prometheus.

I based my docker and config files for the collector based on the example files that use the synthetics packages to produce trace, log and metric data.

docker-compose file:
```
version: "3.9"
services:

  # Jaeger
  jaeger-all-in-one:
    container_name:  jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    container_name: zipkin-all-in-one
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

 # Collector
  otel-collector:
    container_name: otel-collector
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "--log-level=DEBUG"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one
 
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
 ```

otel-collector-config.yaml file:
```
receivers:
  otlp:
    protocols:
      grpc:
  zipkin:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
    
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [zipkin]
      processors: [batch]
      exporters: [logging, prometheus]
`

prometheus.yaml:
`
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
```
Here is the instrumentation code in C# from the API:

```
services
                .AddOpenTelemetryTracing(builder =>
                {
                    

                    builder.Configure((serviceProvider, builder) => 
                    {
                        // Make the logger factory available to the dependency injection
                        // container so that it may be injected into the OpenTelemetry Tracer.
                        var loggerFactory = serviceProvider.GetRequiredService<ILoggerFactory>();
                    });
                    
                    builder
                        .SetResourceBuilder(ResourceBuilder
                            .CreateDefault()
                            .AddService(environment.ApplicationName + "." + environment.EnvironmentName))
                        .AddSource("AppName", "Logs")
                        // Captures incoming HTTP requests
                        // https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.AspNetCore
                        .AddAspNetCoreInstrumentation(options =>
                        {
                            options.RecordException = true;
                            options.Enrich = EnrichTelemetry();
                        })
                        // Captures outgoing HTTP requests through System.Net.Http.HttpClient
                        // https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http
                        .AddHttpClientInstrumentation(options =>
                        {
                            options.Filter = message =>
                                message is not null &&
                                message.RequestUri is not null &&
                                !message.RequestUri.Host.Contains("visualstudio");
                        })
                        // Instruments Microsoft.Data.SQLClient and System.Data.SQLClient and collects telemetry about database operations
                        // https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.SqlClient
                        .AddSqlClientInstrumentation(options =>
                        {
                            // Captures server and instance as net.peer.name or net.peer.ip and db.mssql.instance_name (default = false)
                            options.EnableConnectionLevelAttributes = true;
                            // Captures CommandType.StoredProcedure (default = true)
                            options.SetDbStatementForStoredProcedure = true;
                            // Captures CommandType.Text (default = false)
                            options.SetDbStatementForText = true;
                            // Records SQLExecptions as activity events (default = false and only available on Core)
                            options.RecordException = true;
                            // Add additional attributes to the span including TimeOut and SP Parameters
                            options.Enrich = EnrichSQLTelemetry();
                        })
                        // Sample selects what data from the SPANS collected will be sampled.
                        // https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#sampler
                        .SetSampler(new AlwaysOnSampler());

                        /*builder
                            .AddJaegerExporter();*/
                        /*builder.AddOtlpExporter(options =>
                        {
                            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

                            options.Endpoint = new Uri("http://localhost:4317");
                        });*/

                        builder.AddZipkinExporter(options => {
                            options.Endpoint = new Uri("http://localhost:9411/api/v2/spans");
                        })
                        // Push outgoing spans to your Output Debug window.
                        .AddConsoleExporter(options => options.Targets = ConsoleExporterOutputTargets.Debug);                  
                    }
                });
```

Problems: 

1. The logging output in debug mode is only reporting Prometheus doing something, nothing in regard to Jaeger output.
2. Jaeger receives no trace data and has nothing to search for.
3. The zpages address on localhost is not available. Get a security error in Chrome on http://localhost:55679 suggesting it is blocked by the firewall.

Any advice on why the collector is not processing data would be greatly received?

**Comment by bogdandrutu** [comment]
You can use the "logging" exporter to log all data received by the collector and check if there are data received, also you can look at collector:55670/debug/tracez (not sure why you map that to 55679) to see spans for the exporters and check if there are marked as errors and see the error there.

**Comment by pellared** [comment]
I guess this issue might be related: https://github.com/open-telemetry/opentelemetry-dotnet/issues/2253

**Comment by pellared** [comment]
@dickiebowuk Do you still have a problem? If so can this issue be closed? Otherwise, could you at least properly format the description? I also can suggest looking at https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/TestOtlpExporter.cs

**Comment by dickiebowuk** [comment]
Looking at the issue today as I haven't had chance due to workload and annual leave over the last few weeks.

**Comment by dickiebowuk** [comment]
@pellared The issue you highlighted with the OTLP collector was the problem. I pulled the latest version of the main branch for the collector and used the following setup:

Docker Compose:
```
version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
```

I had to expose port 4317 on my host Windows machine as the example I took it from uses a synthetic client and server that send spans on the Docker Network as they were running in their own containers. My application is running from Visual Studio on my local machine and was calling the otlp collector on http://localhost:4317

otel-collector-config.yaml
```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: promexample
    const_labels:
      label1: value1
  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
```

It is using the otlp collector to receive trace and metric data, using the batch processor and exporting the trace data to Zipkin and Jaeger (that now both show trace data from my application) and metric data to Prometheus.

Happy that it is finally working, so I can explore the processors within the collector. Thanks for your help.
