### ISSUE TITLE
prometheus missing labels in 0.32.0

### ISSUE THREAD

**Issue by skadefro** [open-telemetry/opentelemetry-collector#3824]
**Describe the bug**
Up til 0.31.0 prometheusremotewrite and prometheus have worked with labels.
But when using the docker image for 0.32.0 ( or latest ) the labels are gone

**Steps to reproduce**
Upgrade to 0.32.0 and with 
```
  prometheus:
   endpoint: "0.0.0.0:9464"
  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"
```
in the config, all metrics are missing labels

**What did you expect to see?**
the labels 
**What did you see instead?**
no labels 

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
        - http://*
        - https://*
processors:
  batch:
extensions:
  health_check: {}
  zpages: {}
exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  logging:
   loglevel: info
  prometheus:
   endpoint: "0.0.0.0:9464"
  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"
service:
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite, logging, prometheus]
      processors: []
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]
     
```

**Environment**
GKE

**Additional context**
