### ISSUE TITLE
move telemetry-related settings to the config file

### ISSUE THREAD

**Issue by kirbyquerby** [open-telemetry/opentelemetry-collector#3843]
context: https://github.com/open-telemetry/opentelemetry-collector/pull/3816#discussion_r686716331

The `metrics-level` and `metrics-backend` configuration for internal metrics are currently configured using command-line flags. Since config is already loaded by the time telemetry collection is set up, we should be able to instead read these values from config instead, eg:
```yaml
...
service:
  telemetry:
    metrics-level: basic
    metrics-backend: opencensus
  pipelines:  
...
```

/cc @tigrannajaryan @bogdandrutu @odeke-em
