### ISSUE TITLE
In kubernetes 1.21.x cannot load configuration

### ISSUE THREAD

**Issue by jinxin-fu** [open-telemetry/opentelemetry-collector#3845]
When I use collertor.yaml provide by Knative_doc to create collector for knative, I meet some error as follow :

Error: cannot load configuration: error reading top level configuration sections: 1 error(s) decoding:
* 'service.extensions[0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[health_check:<nil> pprof:<nil> zpages:<nil>]'
2021/08/17 06:10:57 collector server run finished with error: cannot load configuration: error reading top level configuration sections: 1 error(s) decoding:
* 'service.extensions[0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[health_check:<nil> pprof:<nil> zpages:<nil>]'

the cofiguration is list here:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: metrics
data:
  collector.yaml: |
    receivers:
      opencensus:
        endpoint: "0.0.0.0:55678"

    exporters:
      logging:
      prometheus:
        endpoint: "0.0.0.0:8889"

    service:
      extensions:
        health_check:
        pprof:
        zpages:
      pipelines:
        metrics:
          receivers: [opencensus]
          processors: []
          exporters: [prometheus]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: metrics
  labels:
    app: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  replicas: 1  # This can be increased for a larger system.
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: collector
        args:
        - --config=/conf/collector.yaml
        image: otel/opentelemetry-collector:latest
        resources:
          requests:  # Note: these are suitable for a small instance, but may need to be increased for a large instance.
            memory: 100Mi
            cpu: 50m
        ports:
        - name: otel
          containerPort: 55678
        - name: prom-export
          containerPort: 8889
        - name: zpages  # A /debug page
          containerPort: 55679
        volumeMounts:
          - mountPath: /conf
            name: config
      volumes:
      - name: config
        configMap:
          name: otel-collector-config
          items:
            - key: collector.yaml
              path: collector.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: metrics
spec:
  selector:
    app: "otel-collector"
  ports:
  - port: 55678
    name: otel
---
apiVersion: v1
kind: Service
metadata:
  name: otel-export
  namespace: metrics
  labels:
    app: otel-export
spec:
  selector:
    app: otel-collector
  ports:
  - port: 8889
    name: prom-export
```

**Comment by bogdandrutu** [comment]
```
  service:
    extensions:
      health_check:
      pprof:
      zpages:
```

this should be
```
  extensions:
    health_check:
    pprof:
    zpages:
  service:
    extensions: [health_check, pprof, zpages]
```
