### ISSUE TITLE
Jaeger receiver UDP transport can not be closed

### ISSUE THREAD

**Issue by Betula-L** [open-telemetry/opentelemetry-collector#3855]
**Describe the bug**
Jaeger receiver UDP transport can not be closed

**Steps to reproduce**
Run otel with below config 
```
receivers:
  jaeger:
    protocols:
      thrift_binary:
        endpoint: 0.0.0.0:6832
        queue_size: 5_000
        max_packet_size: 131_072
        workers: 50
        socket_buffer_size: 8_388_608
exporters:
  jaeger:
    endpoint: ****
service:
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [jaeger]
```

Then give it a signal interrupt.

**What did you expect to see?**
Otel should be closed gracefully.

**What did you see instead?**
Otel was not closed and hang. 

**What version did you use?**
Version: 1e1f24b462e58b141ce967f744aa60efeeb349c7

**Additional context**
I tried to debug this issue, and found it is jaeger UDP transport hang when closing.

![image](https://user-images.githubusercontent.com/6059935/129836903-958be5ca-8678-4bb1-b9c9-7f2082856766.png)
