### ISSUE TITLE
receiver/prometheus: return an error if YAML configuration has valid options not supported by this receiver like rule_files, alert_configs

### ISSUE THREAD

**Issue by odeke-em** [open-telemetry/opentelemetry-collector#3863]
If we have this Prometheus configuration
```yaml
receivers:
  prometheus:
    buffer_period: 234
    buffer_count: 45
    use_start_time_metric: true
    start_time_metric_regex: '^(.+_)*process_start_time_seconds$'
    config:
      scrape_configs: 
        - job_name: 'demo'
          scrape_interval: 5s
      remote_write:
        - url: "https://example.org/write"
                
      remote_read:
        - url: "https://example.org/read"
        
      rule_files: ["a", "b"]
        
      alerting:
        alert_relabel_configs:
          - separator: ","
            target_label: "fix"
                
          - separator: "|"
            target_label: "gotham"
                
        alertmanagers:
          - scheme: "http"
            path_prefix: "/prefix1" 
            timeout: 1s
        
processors:     
  nop:  
        
exporters:      
  nop:          
                
service:
  pipelines:
    traces: 
      receivers: [prometheus]
      processors: [nop] 
      exporters: [nop]
```

Unfortunately it won't return an error despite the Prometheus receiver not having support for values like:
* alerting/*
* alertmanagers
* remote_read
* remote_write
* rule_files

This issue is a follow-up of the Prometheus Working Group SIG discussion from https://github.com/open-telemetry/wg-prometheus/issues/3. PR coming up shortly.
