### ISSUE TITLE
Fix jaeger receiver collector remote sampling strategies in gRPC endpoint

### ISSUE THREAD

**Issue by Betula-L** [open-telemetry/opentelemetry-collector#3866]
**Describe the bug**
We are trying to replace jaeger agent to opentelemetry-collector now as following described.
![image](https://user-images.githubusercontent.com/6059935/130052721-ff847875-b3a6-4bf4-81e8-be31bc0de463.png)

However, we encountered some troubles for java programs. As recent PR https://github.com/open-telemetry/opentelemetry-java/pull/3368, java SDK only supports request remote sampling strategies by gRPC client rather than http client. Jaeger collector supports gRPC server for remote sampling now, but remote endpoint do not work for it.
https://github.com/open-telemetry/opentelemetry-collector/blob/6fe699e417256e8e20d782f849382971f64be00a/receiver/jaegerreceiver/trace_receiver.go#L480

Thus, java program can not get remote sampling strategies now.
 
**Steps to reproduce**
Run otel as following configs, and request gRPC endpoint, for example
```
	conn, err := grpc.Dial("127.0.0.1:14250", grpc.WithInsecure())
	if err != nil {
		return err
	}
	m := jSamplingConfig.NewConfigManager(conn)
	strategy, err := m.GetSamplingStrategy(context.Background(), "service")
```

**What did you expect to see?**
Thus, java program should be able to get remote sampling strategies now.

**What version did you use?**
Version: 1e1f24b462e58b141ce967f744aa60efeeb349c7

**What config did you use?**
```
receivers:
  jaeger/udp:
    protocols:
      thrift_binary:
        endpoint: 0.0.0.0:5774
        queue_size: 5_000
        max_packet_size: 131_072
        workers: 50
        socket_buffer_size: 8_388_608
  jaeger/grpc:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
    remote_sampling:
      host_endpoint: "0.0.0.0:5778"
      endpoint: "remote-jaeger-collector:14250"
      insecure: true
```
