### ISSUE TITLE
panic when shipping metrics via http/otlp

### ISSUE THREAD

**Issue by mjpowersjr** [open-telemetry/opentelemetry-collector#3978]
**Describe the bug**
I'm using opentelemetry-js to ship metrics to an otel-collector over http / otlp. The collector logs the following error constantly:

```

2021/09/06 19:05:44 http: panic serving 10.42.0.121:55594: runtime error: invalid memory address or nil pointer dereference
goroutine 187373 [running]:
net/http.(*conn).serve.func1(0xc000144be0)
        net/http/server.go:1804 +0x153
panic(0x2d15ac0, 0x4cf60a0)
        runtime/panic.go:971 +0x499
go.opentelemetry.io/otel/sdk/trace.(*span).End(0xc000fc7b00, 0x0, 0x0, 0x0)
        go.opentelemetry.io/otel/sdk@v1.0.0-RC2/trace/span.go:274 +0x325
panic(0x2d15ac0, 0x4cf60a0)
        runtime/panic.go:965 +0x1b9
go.opentelemetry.io/collector/model/internal.MetricsCompatibilityChanges(0xc000bf50f8)
        go.opentelemetry.io/collector/model@v0.33.0/internal/otlp_wrapper.go:53 +0x81
go.opentelemetry.io/collector/model/internal.MetricsFromOtlp(...)
        go.opentelemetry.io/collector/model@v0.33.0/internal/otlp_wrapper.go:40
go.opentelemetry.io/collector/model/otlp.(*jsonUnmarshaler).UnmarshalMetrics(0xc0001601f8, 0xc0007d7600, 0x805, 0x900, 0x10, 0xc0007d7600, 0x805)
        go.opentelemetry.io/collector/model@v0.33.0/otlp/json_unmarshaler.go:61 +0x11a
go.opentelemetry.io/collector/receiver/otlpreceiver.handleMetrics(0x37f1b80, 0xc000d0aa20, 0xc000b8b300, 0x32aae42, 0x10, 0xc000161b30, 0x37a59a0, 0xc0001601f8)
        go.opentelemetry.io/collector/receiver/otlpreceiver/otlphttp.go:74 +0x9a
go.opentelemetry.io/collector/receiver/otlpreceiver.(*otlpReceiver).registerMetricsConsumer.func2(0x37f1b80, 0xc000d0aa20, 0xc000b8b300)
        go.opentelemetry.io/collector/receiver/otlpreceiver/otlp.go:237 +0x79
net/http.HandlerFunc.ServeHTTP(0xc00007c3b0, 0x37f1b80, 0xc000d0aa20, 0xc000b8b300)
        net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000816900, 0x37f1b80, 0xc000d0aa20, 0xc000b8b100)
        github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
go.opentelemetry.io/collector/internal/middleware.(*decompressor).wrap.func1(0x37f1b80, 0xc000d0aa20, 0xc000b8b100)
        go.opentelemetry.io/collector/internal/middleware/compression.go:127 +0xcf
net/http.HandlerFunc.ServeHTTP(0xc00014d840, 0x37f1b80, 0xc000d0aa20, 0xc000b8b100)
        net/http/server.go:2049 +0x44
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc0008169c0, 0x37f0770, 0xc000d0aa20, 0xc000b8ad00)
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.22.0/handler.go:179 +0x957
net/http.serverHandler.ServeHTTP(0xc0003062a0, 0x37f0770, 0xc000a86380, 0xc000b8ad00)
        net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000144be0, 0x37f9258, 0xc000aa3740)
        net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
        net/http/server.go:2993 +0x39b
```

**Steps to reproduce**
The error seems to occur almost immediately after starting a js service that ships metrics to the collector. Disabling metrics and only shipping traces seems to be working correctly.

**Otel Collector Version**
```
          image: otel/opentelemetry-collector:0.33.0
```

**JS Libs**
```
  "dependencies": {
    "@opentelemetry/api": "^1.0.3",
    "@opentelemetry/core": "^0.24.0",
    "@opentelemetry/exporter-collector": "^0.24.0",
    "@opentelemetry/id-generator-aws-xray": "^0.24.0",
    "@opentelemetry/instrumentation": "^0.24.0",
    "@opentelemetry/instrumentation-dns": "^0.24.0",
    "@opentelemetry/instrumentation-express": "^0.24.0",
    "@opentelemetry/instrumentation-graphql": "^0.24.0",
    "@opentelemetry/instrumentation-http": "^0.24.0",
    "@opentelemetry/instrumentation-pg": "^0.24.0",
    "@opentelemetry/instrumentation-redis": "^0.24.0",
    "@opentelemetry/metrics": "^0.24.0",
    "@opentelemetry/node": "^0.24.0",
    "@opentelemetry/propagator-aws-xray": "^0.24.0",
    "@opentelemetry/resource-detector-aws": "^0.24.0",
    "@opentelemetry/resources": "^0.24.0",
    "@opentelemetry/semantic-conventions": "^0.24.0",
    "@opentelemetry/tracing": "^0.24.0",
    "opentelemetry-instrumentation-aws-sdk": "^0.24.2"
  },
```

**Collector Config**
```yaml
extensions:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50
  batch/metrics:
    timeout: 60s

exporters:
  logging:
    logLevel: debug
    
  otlp:
    endpoint: tempo:55680
    insecure: true
    
  prometheus:
    endpoint: "0.0.0.0:9464"
    namespace: default
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [otlp]
    
    metrics:
      receivers: [otlp]
      processors: [batch/metrics]
      exporters: [logging]
  extensions: [health_check]
```

**Environment**
Kubernetest hosting environment.
Node v14

**Additional context**
I've tried switching between prometheus and logging exporters, but neither seems to impact the error.
