### ISSUE TITLE
Changing `insecure` per READMEs no longer works

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-collector#4092]
**Describe the bug**
Many components (e.g. exporters) default to `insecure: false`. Changing this setting now requires nesting it under `tls:`

**Steps to reproduce**

```
exporters:
  otlp:
    endpoint: 1.2.3.4:4317
    insecure: true
```

**What did you expect to see?**
No error

**What did you see instead?**
Collector will not start as config is invalid

**What version did you use?**
Main

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

Fix:

```
exporters:
  otlp:
    endpoint: 1.2.3.4:4317
    tls:
      insecure: true
```

FYI this needs to be fixed in contrib as well.
