### ISSUE TITLE
HTTP receiver doesn't work

### ISSUE THREAD

**Issue by IvanVan** [open-telemetry/opentelemetry-collector#4094]
**Describe the bug**
Got the following message error when use http receiver
```
Sep 22, 2021 5:21:28 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export spans. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found
```

**Steps to reproduce**
Run docker compose with the following docker-compose.yaml
```
version: "2"
services:

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=otel-local-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ${PWD}/config.yaml:/otel-local-config.yaml
    ports:
      - "4318:4318"
```

and config.yaml

```
receivers:
  otlp:
    protocols:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  logging:

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin]
```

Run simple Java app:

```
import io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration;
import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.api.trace.Tracer;
import java.util.Scanner;

public class Main
{
  public static void main(String[] args)
  {
    System.setProperty("otel.service.name", "Simple server");
    System.setProperty("otel.experimental.exporter.otlp.protocol", "http/protobuf");
    System.setProperty("otel.exporter.otlp.endpoint", "http://localhost:4318");

    OpenTelemetrySdkAutoConfiguration.initialize();

    while (true) {
      Scanner scanner = new Scanner(System.in);
      String in = scanner.nextLine();
      if (in.equals("exit")) {
        break;
      }
      Tracer tracer = GlobalOpenTelemetry.getTracer("Simple server");
      Span outGoing = tracer.spanBuilder("Simple server").setSpanKind(SpanKind.CLIENT).startSpan();
      outGoing.end();
    }
  }
}
```

**What did you expect to see?**
Expect to see spans in zipkin

**What did you see instead?**
Error message

**What version did you use?**
opentelemetry - 1.6.0
com.google.protobuf - protobuf-java - 3.17.3
