### ISSUE TITLE
unable to use filelog

### ISSUE THREAD

**Issue by navneet1075** [open-telemetry/opentelemetry-collector#4142]
**Describe the bug**
Unable to load filelog configuration

**Steps to reproduce**
1. installed opentelemetry from documentation 
2. created configuration  like this 

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: test-sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      filelog:
        include: [ /var/log/myservice/*.json ]
        operators:
          - type: json_parser
            parse_from: message

    processors:

    exporters:
      logging:

    service:
      pipelines:
        logs:
          receivers: [filelog]
          processors: []
          exporters: [logging]
``` 

3. created a deployment with some image

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.opentelemetry.io/inject: "true"
    spec:
      serviceAccountName: pod-lister
      containers:
        - name: resource-reader
          image: ***
          resources:
            limits:
              memory: "400Mi"
              cpu: "1000m"
```

4. 
**What did you expect to see?**

Pods created properly and otc container able to get the log files from the shared path

**What did you see instead?**

saw the errors in the otc container 
```
2021-09-29T00:18:53.823Z	info	service/collector.go:303	Starting otelcol...	{"Version": "0.34.0", "NumCPU": 8}
2021-09-29T00:18:53.824Z	info	service/collector.go:242	Loading configuration...
Error: cannot load configuration: unknown receivers type "filelog" for filelog
```

**What version did you use?**
Version: 

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
