### ISSUE TITLE
Prometheus capture group not recognized

### ISSUE THREAD

**Issue by etiennejournet** [open-telemetry/opentelemetry-collector#4145]
Hello !

I'm using opentelemetry 0.22.0 and this configuration doesn't work:
```
       - action: replace
          regex: (\d+\.\d+\.\d+\.\d+);(\d+)
          replacement: $1:$2
          source_labels:
          - __meta_kubernetes_pod_host_ip
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          target_label: test
```

I expect this to provision a label being something like `test: "1.2.3.4:1234"` but for some reason it doesn't seem to recognize the capture group... Resulting in `test: ":"`

I know I could do it with a separator but the use case at first was to use `__address__`, in which case separator is not sufficient.

Is it something I missed in the documentation ?
