### ISSUE TITLE
stream terminated by RST_STREAM with error code: FRAME_SIZE_ERROR

### ISSUE THREAD

**Issue by trjate** [open-telemetry/opentelemetry-collector#4173]
I have not found any other publicly discussed occurrences of this `FRAME_SIZE_ERROR` error code in the context of OTEL.

**Describe the bug**
`stream terminated by RST_STREAM with error code: FRAME_SIZE_ERROR"` error when attempting to use Jaeger exporter in Ruby application.

Here is my `opentelemtry.rb` initializer:
```
require 'opentelemetry/sdk'
require 'opentelemetry/exporter/otlp'
ENV['OTEL_EXPORTER_OTLP_ENDPOINT'] = 'http://otel-collector.sales:4318'
OpenTelemetry::SDK.configure do |c|
  c.use_all
end
```

**What did you see instead?**
```
go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/internal/bounded_queue.go:82
2021-10-04T22:10:01.765Z        info    exporterhelper/queued_retry.go:231      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "name": "jaeger", "error": "failed to push trace data via Jaeger exporter: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: FRAME_SIZE_ERROR", "interval": "9.47506418s"}
2021-10-04T22:10:12.408Z        info    exporterhelper/queued_retry.go:231      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "name": "jaeger", "error": "failed to push trace data via Jaeger exporter: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: FRAME_SIZE_ERROR", "interval": "13.996005988s"}
2021-10-04T22:10:18.226Z        error   exporterhelper/queued_retry_inmemory.go:93      Exporting failed. No more retries left. Dropping data.  {"kind": "exporter", "name": "jaeger", "error": "max elapsed time expired failed to push trace data via Jaeger exporter: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: FRAME_SIZE_ERROR", "dropped_items": 46}
go.opentelemetry.io/collector/exporter/exporterhelper.onTemporaryFailure
        go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/queued_retry_inmemory.go:93
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/queued_retry.go:215
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
        go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/traces.go:134
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).start.func1
        go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/queued_retry_inmemory.go:105
go.opentelemetry.io/collector/exporter/exporterhelper/internal.ConsumerFunc.Consume
        go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/internal/bounded_queue.go:103
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BoundedQueue).StartConsumersWithFactory.func1
        go.opentelemetry.io/collector@v0.36.0/exporter/exporterhelper/internal/bounded_queue.go:82
```

**What version did you use?**
Version: `v0.36.0`

**What config did you use?**
Config: 
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - command:
          - "/otelcontribcol"
          - "--config=/conf/otel-collector-config.yaml"
#           Memory Ballast size should be max 1/3 to 1/2 of memory.
 #- "--mem-ballast-size-mib=683"
        image: otel/opentelemetry-collector-contrib:0.36.0
        name: otel-collector
        ports:
        - containerPort: 55679 # ZPages
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 4318 # Default endpoint for OpenTelemetry receiver.
          #- containerPort: 14250 # Default endpoint for jaeger HTTP receiver.
          #- containerPort: 14268 # Default endpoint for jaeger HTTP receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
... etc
```
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318 
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 683
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      zpages: {}
    exporters:
      jaeger:
        endpoint: "collector.linkerd-jaeger:14268"
        tls:
          insecure: true
    service:
      # extensions: [zpages]
      pipelines:
        traces/1:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          #exporters: [otlp]
          exporters: [jaeger]
---

```
**Environment**
Basic RoR application running on Minikube
