### ISSUE TITLE
Dropping and Filtering Spans from Within a Trace

### ISSUE THREAD

**Issue by mjallday** [open-telemetry/opentelemetry-collector#4174]
**Is your feature request related to a problem? Please describe.**

We need a feature to allow for dropping/filtering spans from third party services which are out of our control. 

**Describe the solution you'd like**

Being able to use a syntax similar to the [logs and metrics filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/57a2ef2644c55fbfd43437afceeebb66939ed80b/processor/filterprocessor) would be useful. 

```yaml
processors:
  filter/remove_hello_world_spans:
    spans:
      exclude:
        match_type: strict
        attributes:
          - key: some_attribute
             values: [hello_world]
```

I would like to be able to use this type of filter like so that i may be able to route all spans/traces to one exporter but for another exporter only receive a subset of the spans within a trace

```yaml
service:
  pipelines:
    traces/all:
      receivers: [otlp]
      processors:
        - batch
      exporters: [jaeger/all]
    traces/clean:
      receivers: [otlp]
      processors:
        - filter/remove_hello_world_spans
        - batch
      exporters: [jaeger/clean]
```

**Describe alternatives you've considered**

I've looked through the various suggestions proposed in #2310 and did not find anything relevant. Everything is related to filtering at the trace level, not at the span level.

I did read that at a SIG this was discussed and resulted in [some additional work being identified](https://github.com/open-telemetry/opentelemetry-collector/issues/2310#issuecomment-777370664). 

![image](https://user-images.githubusercontent.com/252280/136087170-592f07aa-e8f3-4cbc-a429-c2a2c36f3835.png)

I understand this may result in incomplete traces but believe that this is something we can live with initially even if we cannot cover remapping spans in a first implementation to help control scope of the change.
