### ISSUE TITLE
Send traces from Jaeger to OpenTelemetry collector

### ISSUE THREAD

**Issue by markvdlaan93** [open-telemetry/opentelemetry-collector#4186]
Currently, I'm trying to connect a PHP Laravel application to Honeycomb.io through Jaeger and the OpenTelemetry collector. It seems like the otel collector doesn't receive any traces from Jaeger. I'm using docker-compose and I've verified that traces are received in Jaeger.

docker-compose.yaml
```
version: '3.0'

services:
 web:
  build:
    context: .
    dockerfile: DockerfileLocal
  ports:
  - "8000:80"
  restart: always
  depends_on:
    - mysqldb
    - jaeger-agent
  volumes:
    - "./source:/var/www/html"
  deploy:
    resources:
        limits:
          memory: 3g
        reservations:
          memory: 1g
myadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  deploy:
    resources:
        limits:
          memory: 500m
        reservations:
          memory: 100m
  ports:
    - "8080:80"
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=${MYSQL_HOST}
  restart: always
  depends_on:
    - mysqldb
mysqldb:
  image: mysql:${MYSQL_VERSION}
  container_name: ${MYSQL_HOST}
  deploy:
    resources:
      limits:
        memory: 1g
      reservations:
        memory: 200m
  restart: always
  env_file:
    - ".env"
  environment:
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  ports:
    - "8990:3306"
  volumes:
    - "./local/data/db/mysql:/var/lib/mysql"
jaeger-agent:
  container_name: ${JAEGER_HOST} # value is jaeger
  image: jaegertracing/all-in-one:1.27.0
  ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  environment:
      - LOG_LEVEL=debug
  labels:
      NAME: "jaeger-agent"
otel-collector:
  image: otel/opentelemetry-collector:v0.36.0
  command: ["--config=/etc/otel-collector-config.yaml"]
  depends_on:
    - jaeger-agent
    - web
  volumes:
    - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  ports:
    - "1888:1888"   # pprof extension
    - "8888:8888"   # Prometheus metrics exposed by the collector
    - "8889:8889"   # Prometheus exporter metrics
    - "13133:13133" # health_check extension
    - "4317"        # OTLP gRPC receiver
    - "55670:55679" # zpages extension
  depends_on:
    - jaeger-all-in-one
    - web
```

otel-collector-config.yaml
```
receivers:
  jaeger:
    protocols:
      thrift_http:
        endpoint: "0.0.0.0:14268"

processors:
  batch:

exporters:
  logging:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "...."
      "x-honeycomb-dataset": "..."

extensions:
  health_check:
  pprof:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [jaeger]
      processors: [batch]
      exporters: [otlp, logging]
```
The otel collector logs don't indicate that something is wrong. I was wondering what the thrift_http endpoint should be. I tried jaeger:14268 because in the PHP application I'm also using jaeger:6831 for sending the traces to Jaeger. However, when I try that I'm getting a 'cannot assign requested address'-error.

Does anyone know what I'm doing wrong?
