### ISSUE TITLE
Config sources to support full remote config and individual config value substitution

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#4190]
@bogdandrutu @Aneurysm9 and I discussed how the Collector configuration can be extended to support the remote [configuration needs](https://github.com/open-telemetry/opentelemetry-collector/issues/2374).

One possible approach is to extend the concept of config sources that were proposed earlier in https://github.com/open-telemetry/opentelemetry-collector/pull/3687 to allow the config sources to supply the full configuration and value sources to provided individual values to substitute in the configuration (see examples below).

The following proposal shows what it will look like from the end user perspective. Please review and comment. At this stage we would like to validate that this approach covers the use cases that the community is interested it. Once we agree on the end-user perspective, we will discuss what the internal API should look like.

# Proposal

The config sources / value sources concepts enhance Collector configuration capabilities while keeping full backwards compatibility.

The following are examples of how the end user will specify the configuration, assuming the new concept of config sources is implemented.

## Example 1. Single Local Config File.

This is the old (current) way. It is still fully supported and will continue to be supported. It is not obsolete and is the preferable way when there is a single local config file.

Command line: `./otelcol --config=local.yaml`

local.yaml content:
```yaml
receivers:
  otlp:
    grpc:

exporters:
  otlp:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
```

## Example 2. Config Sources, Single Local Config File.

This uses a new `--config_sources` command line flag.

Command line: `./otelcol --config_sources=sources.yaml`

sources.yaml content:
```yaml
config_sources:
  - files: local.yaml
```

local.yaml content:
```yaml
receivers:
  otlp:
    grpc:

exporters:
  otlp:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
```

This example results in a config that is completely equivalent to the config in Example 1.

## Example 3. Config Sources from Command Line

This uses a shorthand for specifying a single config source on the command line.

Command line: `./otelcol --config_sources=files:local.yaml`

local.yaml content:
```yaml
receivers:
  otlp:
    grpc:

exporters:
  otlp:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
```

## Example 4. Multiple Local Config Files

Command line: `./otelcol --config_sources=sources.yaml`

sources.yaml content:
```yaml
config_sources:
  # Merge all files that match the specified glob into one file and use that as a config
  - files: /var/lib/otelcol/config/**/*.yaml
```

/var/lib/otelcol/config/local.yaml content:
```yaml
receivers:
  otlp:
    grpc:

exporters:
  otlp:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
```

/var/lib/otelcol/config/local2.yaml content:
```yaml
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlp]
```

This results in the following effective configuration:

```yaml
receivers:
  otlp:
    grpc:

exporters:
  otlp:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
```

## Example 5. From HTTP Server

Command line: `./otelcol --config_sources=sources.yaml`

source.yaml content:
```yaml
config_sources:
  - http:
      url: http://example.com/path/file.yaml
```

This will do a HTTP GET request to https://example.com/path/file.yaml, will download the content and will use the content as the config file.

The equivalent result can be achieved using only the command line:

`./otelcol --config_sources=http:http://example.com/path/file.yaml`

or 

`./otelcol --config_sources=http://example.com/path/file.yaml`

(Note that http config_source automatically prepends "http" to the url if not already present).

## Example 6. Multiple Sources

Command line: `./otelcol --config_sources=sources.yaml`

source.yaml content:
```yaml
config_sources:
  - files: local.yaml
  - s3: 
      bucket: mybucket
      region: us-east-1
```

This will merge a local.yaml file with the content of an S3 bucket and will use the content as the config file.

## Example 7. Value Sources

Value sources are almost exactly what the the experimental [ConfigSources](https://github.com/open-telemetry/opentelemetry-collector/blob/a298b1047fe38793372d11c172676e2cf6bbcfd6/config/experimental/configsource/component.go#L49) were proposed to be, i.e. allow individual values in the config file to be substituted.

Command line: `./otelcol --config_sources=sources.yaml`

source.yaml content:
```yaml
config_sources:
  - files: local.yaml

value_sources:
  # define a value source of "vault" type
  # that can be referenced later.
  vault:
    # endpoint is the Vault server address.
    endpoint: http://localhost:8200
    # path is the Vault path to the secret location.
    path: secret/data/kv
    auth:
      token: foo
```

local.yaml content:
```yaml
receivers:
  otlp:
    grpc:

exporters:
  signalfx:
    # this will read the access_token value from "vault" config source.
    realm: us0
    access_token: $vault:data.access_token

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [signalfx]
```

## Alternative Command Line Approach

Note that this proposal suggest that we add a new `--config_sources` flag and keep the existing `--config` for single-file case. An alternate approach is to only have `--config` flag and auto-detect the provided file format and either enable the current single-file config logic or enable the newly proposed "config sources" approach.

**Comment by bogdandrutu** [comment]
@PettitWesley your request is pretty simple right now (but you need to create the flag yourself), let's assume you have already a `[]string` of files:

```
files := getFiles()
var fileProviders []configmapprovider.Provider
for _, file : range files {
  fileProviders = append(fileProviders, configmapprovider.NewFile(file))
}
// Set this to the service.CollectorSettings { ConfigMapProvider :   configmapprovider.NewMerge(fileProviders...) }

```

**Comment by vjsamuel** [comment]
One of the things worth considering is that, rather than building a consolidated service each time a config source is added/modified we should only be rebuilding a portion of it, i.e pipelines that were affected. 

My proposal would be in this case to, keep both `--config` and `--config-source` as two parameters. The config would provide the core service related configuration and config-source would only container pipeline definitions. 

The benefit would be that, when ever a new config-source file is added in, we create its pipelines. when it is removed, we delete only those pipelines. 

A pipeline from a config source can only refer to `receivers`, `exporters` and `processors` that are either defined on the same config source or on the main config file. 

All pipelines need to be refreshed only if the core config changes as there might be references to the components defined on it. 

thoughts?

**Comment by tigrannajaryan** [comment]
> One of the things worth considering is that, rather than building a consolidated service each time a config source is added/modified we should only be rebuilding a portion of it, i.e pipelines that were affected.

We want to do this in the future. We can detect the config deltas and only rebuild affected pipelines.


> My proposal would be in this case is to keep both `--config` and `--config-source` as two parameters. The config would provide the core service related configuration and config-source would only contain pipeline definitions.

This does not seems to be necessary for the above goal. We can keep the current approach and still only rebuild affected pipelines.

**Comment by tigrannajaryan** [comment]
Heads up: I am also looking at a slightly different config file structure, while maintaining the functionality described in the above examples. We can do this:

```yaml
# Define all config sources (including vaule sources)
config_sources:
  files/local: local.yaml

  # define a value source of "vault" type
  # that can be referenced later.
  vault:
    # endpoint is the Vault server address.
    endpoint: http://localhost:8200
    # path is the Vault path to the secret location.
    path: secret/data/kv
    auth:
      token: foo

merge_configs:
  - files/local
```

In local.yaml:
```yaml
exporters:
  signalfx:
    # this will read the access_token value from "vault" config source.
    realm: us0
    access_token: $vault:data.access_token
```

Conceptually it is no different than the original proposal at the top of this thread. However this is more uniform with other configuration settings, where we first define the component with its setting (e.g. a receiver) and then have a list of components used somewhere (e.g. receivers list in the pipeline definition).

**Comment by tigrannajaryan** [comment]
Chatted with @bogdandrutu and decided that [the PR](https://github.com/open-telemetry/opentelemetry-collector/pull/4468) that implements this looks more complicated than we would like. Bogdan is going to see if he can come up with a simpler alternate. I am un-assigning this from myself for now.

**Comment by alolita** [comment]
@bogdandrutu will you be proposing a simpler alternative?

**Comment by ttomsu** [comment]
Happy New Year everyone! Just checking in on this... specifically interested in pattern 4 (Multiple Local Config Files)

**Comment by bogdandrutu** [comment]
@ttomsu are you interested to support "blob/regexp" or just multiple local files in general?

**Comment by ttomsu** [comment]
@bogdandrutu - Apologies for the delay. I'm interested in both - using the blob/regexp to specify a directory such as `/etc/otel-collector/*.yaml` to pick up any custom config files my client teams may to add.

**Comment by bogdandrutu** [comment]
@ttomsu look at https://github.com/open-telemetry/opentelemetry-collector/pull/4727, we can extend later with blobs, but it has a problem that, because you need to tell me the order, otherwise I cannot guarantee stable final config.

**Comment by ttomsu** [comment]
Hey @bogdandrutu - I finally got some time to update and test drive the changes in the codebase. It looks like you're using the `https://github.com/knadh/koanf` library under the hood. How am I supposed to merge together files that provide, lets say, logs receivers? For example:

Config 1:

```
service:
  pipelines:
    logs:
      receivers:
        - tcplog/tcp-json
```

Config 2:
```
service:
  pipelines:
    logs:
      receivers:
        - filelog/apache-access
        - filelog/apache-error
        - filelog/apache-startup
 ```

According to [this issue](https://github.com/knadh/koanf/issues/125#issuecomment-1002386233):

> The merge is on the keys recursively ... until a key is traversed to the end to a static non-map value, when the values are overwritten.

So my second config clobbers the list of receivers, which is what I observe in practice.
