### ISSUE TITLE
change in behaviour for otlp grpc exporter

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#4191]
**Describe the bug**
The following change causes the default for the grpc exporter transport to change from secure to insecure. https://github.com/open-telemetry/opentelemetry-collector/commit/ebb0fbd6f23e9ecc17ddc64edd54bb2a84ea9ce1#diff-2eb38d27ab53ca22abef502c1b39e68f28165a4eb3aa92e2c1d2314ab8991a59R194-R199

I reproduced the change in behaviour by using the same configuration both before and after this change.
This was the config:
```
exporters:
  logging:
      loglevel: debug
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
        "lightstep-access-token": "redacted"
```

The fix was to set the following options:
```
exporters:
  logging:
      loglevel: debug
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
        "lightstep-access-token": "redacted"
    tls:
      insecure: false
```

Two things I'm looking for with this issue:
1. ensure the change in behaviour was intentional
2. if so, ensure we have this documented in the changelog/release notes
