### ISSUE TITLE
Collector cannot forward to another collector using the otlphttp exporter

### ISSUE THREAD

**Issue by timcosta** [open-telemetry/opentelemetry-collector#4221]
**Describe the bug**
The collector is unable to forward traces to another collector using the otlphttp exporter and otlp receiver. The data exits the original collector with trace/span IDs base64 encoded instead of hex encoded, which causes the secondary receiver to 400 with an `{"code":3,"message":"invalid length for ID"}` response.

Related: 
https://github.com/open-telemetry/opentelemetry-collector/issues/3195
https://github.com/open-telemetry/opentelemetry-go/pull/1990

**Steps to reproduce**
Just point a collector using the otlphttp exporter at another collector, and all trace requests will fail

**What did you expect to see?**
I expected trace requests coming out of the otlphttp exporter to have properly formatted trace and span IDs

**What did you see instead?**
Trace and span IDs were base64 encoded. For example, the otlphttp exporter outputs `QwOFPwhvT4yGzxmLZVHfhA==` as the trace id when it received `4303853f086f4f8c86cf198b6551df84`.

**What version did you use?**
Version: 0.36.0

**What config did you use?**
Config: Here's the secondary receiver config
```yaml
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:${port}

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: jaeger-collector.${namespace}.svc.cluster.local:14250
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging,jaeger]
```

**Environment**
OS: otel/opentelemetry-collector-contrib:0.36.0
Compiler(if manually compiled): provided in docker image

**Additional context**
This seems to be due to an issue in the Go SDK, but the SIG meeting elected to drop JSON exporting support instead of fixing the issue. Is this fixable in the collector? If not, should the `otlphttp` exporter be removed from the collector as it exports data that isnt spec-compliant?
