### ISSUE TITLE
Add documentation to update opentelemetry collector image as part of OpenTelemetryCollector Definition

### ISSUE THREAD

**Issue by bharathiram** [open-telemetry/opentelemetry-collector#4282]
**Describe the bug**

There is no mention in the documentation about the feature that we can pass `image` as part of the OpenTelemetryCollector configuration

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "service.fullname" .}}
  namespace: {{ .Release.Namespace }}
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:0.37.1
  config: |
 {{ .Files.Get (printf "config/otlp-config-%s.yaml" .Values.environment) | indent 4 }}
```
It would be helpful to list this feature in the documentation
