### ISSUE TITLE
Update jaeger exporter in the docs

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-collector#4377]
in the official documentation at https://opentelemetry.io/docs/collector/configuration/#exporters in the example:
```yaml
...
  jaeger:
    endpoint: "http://jaeger-all-in-one:14250"
    tls:
      insecure: true
...
```
the protocol is part of the endpoint url resulting in `address http://jaeger-all-in-one:14250: too many colons in address` errors. Could you please update the documentation.

_Originally posted by @Legion2 in https://github.com/open-telemetry/opentelemetry-collector/issues/4179#issuecomment-962153627_
