### ISSUE TITLE
Expose custom round tripper in confighttp.ClientSettings as an extension

### ISSUE THREAD

**Issue by pavankrish123** [open-telemetry/opentelemetry-collector#4438]
**Is your feature request related to a problem? Please describe.**

We already have defined  custom round tripper as a part of [HTTPClientSettings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/confighttp.go#L57) in confighttp.go. This has been done to provide some help with testing. However, It is not exposed as a configuration/plugin.

We are running into variety of use cases where we are ending up with requirement to "plug in" a custom round tripper/interceptor of export requests/responses around 1) auditing 2) logging 3) capturing some business specific metrics. 

If the custom round tripper is exposed as an extension (akin to how we are doing auth class extensions) - Users can plugin their own custom interceptors extensions on http exporters without need to modifying new exporters/modifying core similar to how we plug in auth.  

**Describe the solution you'd like**
something like 

```yaml 

extensions:
  mycustomroundtripper:

exporters:
  otlphttp/withroundtripper:
    endpoint: http://localhost:9000
    inteceptors:
      roundtrippers:  [mycustomroundtripper, ....]
```

cc: @pureklkl @svrnm
