### ISSUE TITLE
promethues exporter not working as expected, metrics is empty

### ISSUE THREAD

**Issue by offSwitch** [open-telemetry/opentelemetry-collector#4453]
**Describe the bug**
metrics is empty

**Steps to reproduce**
after run opentelemetry-go\example\otel-collector\main.go
![image](https://user-images.githubusercontent.com/11695496/142350475-074522a8-815f-464f-ab16-f85a7e5e2563.png)

curl http://192.168.137.15:32664/metrics is empty
![image](https://user-images.githubusercontent.com/11695496/142350553-06fb21a2-4979-4805-af24-79e9ba294217.png)

but jaeger exporter working correctly
![image](https://user-images.githubusercontent.com/11695496/142350225-22a142d6-506f-439b-9889-084fbc035d29.png)

**What did you expect to see?**

**What did you see instead?**

**What version did you use?**
otel/opentelemetry-collector:0.38.0

**What config did you use?**
otel-collector-config:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  batch:
extensions:
  zpages: {}
  memory_ballast:
    # Memory Ballast size should be max 1/3 to 1/2 of memory.
    size_mib: 683
exporters:
  jaeger:
    endpoint: "jaeger.default.svc.cluster.local:14250" # Replace with a real endpoint.
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
service:
  pipelines:
    traces/1:
      receivers: [otlp]
      exporters: [jaeger]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
```
otel-collector-service.yaml
```yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opentelemetry
    component: otel-collector
  name: otel-collector
  namespace: default
spec:
  ports:
    - name: otlp-grpc
      nodePort: 30247
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http
      nodePort: 32712
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metrics
      nodePort: 30514
      port: 8888
      protocol: TCP
      targetPort: 8888
    - name: metrics2
      nodePort: 32664
      port: 8889
      protocol: TCP
      targetPort: 8889
  selector:
    component: otel-collector
  type: NodePort
```

**Environment**
OS: Ubuntu 20.04

**Additional context**
