### ISSUE TITLE
Batch processor failed with error: unsupported metric otelcol_processor_batch_batch_send_size (Histogram)

### ISSUE THREAD

**Issue by FuyuanChu** [open-telemetry/opentelemetry-collector#4456]
**Describe the bug**

There are errors in otel-collector's log

```
2021-11-18T08:48:25.399Z	warn	batchprocessor/batch_processor.go:185	Sender failed	{"kind": "processor", "name": "batch", "error": "Permanent error: unsupported metric otelcol_processor_batch_batch_send_size (Histogram)"}
```
What happened when this error occurs？Does the error cause data losses?

**Steps to reproduce**

Using configuration below to setup a otel-colletor deployment:

```
exporters:
  logging: null
  newrelic:
    apiKey: xxxxxxxxxxxxxx
extensions:
  health_check: {}
  memory_ballast: {}
processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 1638
    spike_limit_mib: 512
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
      - honor_timestamps: true
        job_name: k8s
        kubernetes_sd_configs:
        - follow_redirects: true
          kubeconfig_file: ""
          namespaces:
            names:
            - otel-system
          role: endpoints
        metrics_path: /metrics
        relabel_configs:
        - action: keep
          regex: otel-collector-gateway
          replacement: $1
          separator: ;
          source_labels:
          - __meta_kubernetes_service_label_app
        - action: keep
          regex: metrics
          replacement: $1
          separator: ;
          source_labels:
          - __meta_kubernetes_endpoint_port_name
        - action: replace
          regex: Pod;(.*)
          replacement: ${1}
          separator: ;
          source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
          target_label: pod
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          source_labels:
          - __meta_kubernetes_service_name
          target_label: service
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          regex: (.*)
          replacement: $1
          separator: ;
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - action: replace
          regex: (.*)
          replacement: metrics
          separator: ;
          target_label: endpoint
        scheme: http
        scrape_interval: 15s
        scrape_timeout: 5s
  zipkin:
    endpoint: 0.0.0.0:9411
service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    metrics:
      exporters:
      - newrelic
      processors:
      - memory_limiter
      - batch
      receivers:
      - prometheus
```
