### ISSUE TITLE
Trouble adding observability to an exporter

### ISSUE THREAD

**Issue by rarick** [open-telemetry/opentelemetry-collector#4472]
# Problem
I have been using the opentelemetry-contrib repo to build a custom exporter. A requirement of my project is to add observability of the exporter itself. Specifically, I have a need for publishing health metrics ABOUT the exporter. Below is an outline of my config for reference.

# Current Approach
I am currently using the following otel collector config:

```
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          metrics_path: /metrics
          scrape_interval: 5s
          static_configs:
            - targets: ["localhost:8888"]

  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
  
processors:
  batch:
    timeout: 30s
    send_batch_size: 131072

exporters:
  custom_exporter:
    my_custom_exporter_options:
  file:
    path: /export/export.json
  logging:

service:
  pipelines:
    # Main data pipeline
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [custom_exporter, logging]

    # Health pipeline
    metrics/2:
      receivers: [prometheus]
      processors: []
      exporters: [file]                                                                                                                                                                                     
```

I've attempted to use the `obsreport` module in the following way in order to access health metrics out of the prometheus endpoint at `localhost:8888`. I only know about this option from the CNCF slack channel, so I can't point to this in documentation anywhere, and I could be wrong about the connection between what's being published on `localhost:8888` and the hooks in `obsreport`.

Here is an example on how I hooked my exporter in with the `obsreport` package:

I added the exporter helper to my exporter structure:
```
// ... constructor for exporter
    obsexp: obsreport.NewExporter(obsreport.ExporterSettings{
      ExporterID: cfg.ID(),
      ExporterCreateSettings: params,
    }),
// ...
```

And I added `obsexp.StartMetricsOp` and `obsexp.EndMetricsOp` calls to my exporter's consumption function:

```
ctx = e.obsexp.StartMetricsOp(ctx)
// ...
// do work
// ...
e.obsexp.EndMetricsOp(ctx, numMetricPoints, err)
```

However, when I scrape the `localhost:8888/metrics` data, I do not see **any** information about my `custom_exporter` component. I see information on the batch processor, the fileexporter, the receivers, and even the logging exporter. But nothing related to my `custom_exporter` ever appears in the `/export/export.json` file.

# Other considerations
Am I going about this the right way? I don't see any other exporter components making these calls. Should I instead be using the opentelemetry client module to gather metrics in my component, and send them to a new health pipeline which uses the otlp GRPC receiver, for example?

This seems like it would be a fairly common problem to have, so I hope that I'm just going about it the wrong way and just need a bit of guidance. I was really having trouble finding documentation on the usage of these modules, and couldn't find another component to serve as an example, so any information like that would also be very helpful.

Thanks in advance for any help and suggestions!
