### ISSUE TITLE
Exporting from otelcol to data-prepper

### ISSUE THREAD

**Issue by ghaithTK** [open-telemetry/opentelemetry-collector#4515]
I am trying to export data from otel-collector to data-prepper. I am using otelcol v 0.40.0 (otelcol_0.40.0_linux_amd64.deb)
I got this Error:
 error        exporterhelper/queued_retry.go:183        Exporting failed. The error is not retryable. Dropping data.        {"kind": "exporter", "name": "otlp/data-prepper", "error": "Permanent error: rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type \"text/plain; charset=utf-8\"", "dropped_items": 4163}

I am running data-prepper in docker container in the same machine with otel-collector.
my otel-collector config file :
![image](https://user-images.githubusercontent.com/82761415/144820705-f44bc9fe-950e-4df6-9e56-88db7bd99642.png)

**Comment by ghaithTK** [comment]
> The destination that the Collector is sending to is not receiving OTLP/gRPC data correctly (or not responding correctly). Check your destination settings, port numbers, etc.

Thanks very much for your reply. May I will share the destination with you to check if there is some misconfiguration!
The destination is data-prepper running in docker container in the same machine with otel-collector with compose file:
```
version: '3'

services:
  data-prepper:
    container_name: "data-prepper"
    image: 'opensearchproject/data-prepper:latest'
    ports:
      - 4900:4900
      - 21890:21890
    volumes:
      - /home/support/data-prepper/pipelines.yaml:/usr/share/data-prepper/pipelines.yaml
      - /home/support/data-prepper/data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml
```
and that is my pipeline.yaml
```
entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  prepper:
    - otel_trace_raw_prepper:
  sink:
    - opensearch:
        hosts: ["https://xxx.xx.xx.xx:9200"]
        insecure: true
        username: "xxxx"
        password: "xxxx"
        trace_analytics_raw: true
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  prepper:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["https://xxx.xx.xx.xx:9200"]
        insecure: true
        username: "xxxx"
        password: "xxxx"
        trace_analytics_service_map: true
```
