### ISSUE TITLE
Have a way to disable the legacy HTTP endpoint

### ISSUE THREAD

**Issue by rgl** [open-telemetry/opentelemetry-collector#4565]
**Describe the bug**

There is no way to disable the legacy HTTP endpoint.

This behavior [seems to be hardcoded without a way to disable](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/otlp.go#L146-L157).

**Steps to reproduce**

When using this library from Tempo, I've explicitly set the HTTP endpoint as:

```yaml
distributor:
  receivers:
    # see https://github.com/grafana/tempo/blob/v1.2.1/modules/distributor/config.go#L33
    # see https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
```

**What did you expect to see?**

Only port 4318 listening.

**What did you see instead?**

It also opens the legacy HTTP listener at port 55681.

**What version did you use?**

I'm using it tru Tempo 1.2.1. I think its using v0.21.0:

* https://github.com/grafana/tempo/blob/v1.2.1/go.mod#L57
* https://github.com/grafana/tempo/blob/v1.2.1/go.sum#L2065-L2066

Also note that the latest collector version (v0.41.0) also uses the same code, so I guess it also has the same behavior.

**What config did you use?**

See the description.

**Environment**

OS: Ubuntu 20.04
Compiler(if manually compiled): N/A.

**Additional context**

Originally asked for help at https://github.com/grafana/tempo/discussions/1181
