### ISSUE TITLE
`exporterhelper` should reject a queue size of `0`

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#4584]
**Describe the bug**

`exporterhelper` allows for a `QueueSize` of `0`, which results in a permanently blocked exporter that drops all data (see https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6718#issuecomment-994715344).

**Steps to reproduce**

Create a pipeline with an exporter that exposes the `QueueSettings` struct and set the queue size to 0.

**What did you expect to see?**

The Collector would fail to start and provide a descriptive error.

**What did you see instead?**

The Collector fails each time a payload gets to the exporter with a message similar to:

```
exporterhelper/queued_retry.go:99       Dropping data because sending_queue is full. Try increasing queue_size.   {"kind": "exporter", "name": "otlp", "dropped_items": 3}
```

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)

Latest commit reproduces 81ab024486f067433d025fe0b25f8b532520ebe0

**What config did you use?**
Config: (e.g. the yaml config file)

<details>

<summary>Example config with contrib distro</summary>

```yaml
receivers:
  hostmetrics:
    scrapers:
      load:
    collection_interval: 2s

exporters:
  otlp:
    endpoint: 0.0.0.0:4317
    sending_queue:
      queue_size: 0

  
service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [otlp]
```

</details>

**Environment**

not relevant
