### ISSUE TITLE
otlptext support for ExponentialHistogram

### ISSUE THREAD

**Issue by jmacd** [open-telemetry/opentelemetry-collector#4641]
**Describe the bug**
The `otlptext` package does not recognize ExponentialHistogram data types.

**Steps to reproduce**
Demonstrated in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/6666 using a logging exporter and a statsd receiver configured to produce exponential histograms.

**What did you expect to see?**
The data type should print its buckets in a human readable way.

**What did you see instead?**
Nothing prints.

**What version did you use?**
60823e2

**What config did you use?**

```
receivers:
  statsd:
    endpoint: :8127
    aggregation_interval: 10s
    is_monotonic_counter: true
    timer_histogram_mapping:
    - statsd_type: histogram
      observer_type: histogram
      histogram:
        max_size: 16
    - statsd_type: timing
      observer_type: histogram
      histogram:
        max_size: 128

exporters:
  logging:
    loglevel: debug
   
service:
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [logging]
```
