### ISSUE TITLE
Health checks against the gRPC ports cause annoying log entries

### ISSUE THREAD

**Issue by mplachter** [open-telemetry/opentelemetry-collector#4747]
**Describe the bug**

When upgrading from 0.37.0 to 0.42.0 getting spammed with the below log messages over and over.

```2022-01-25T16:40:11.352Z	warn	zapgrpc/zapgrpc.go:191	[core] grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: read tcp 192.168.2.184:14250->192.168.1.94:2793: read: connection reset by peer"	{"grpc_log": true}```

**Steps to reproduce**
~~Otel Collector Exporting OTLP to another Otel Collector Receiving OTLP with TLS insecure enabled.~~
Place the collector behind a load balancer doing periodical health checks, such as AKS'

**What did you expect to see?**
Not a bunch of warn log messages over and over again.

**What did you see instead?**
All the initialization up till `Everything is ready. Begin running and processing data.` was fine with only `info` messages until the `warn` messages started. 

**What version did you use?**
Version: v0.42.0

**What config did you use?**
```
config:
  exporters:
    otlp:
      endpoint: collector:4317
      tls:
        insecure: true
  extensions:
    health_check: {}
    memory_ballast: {}
  processors:
    attributes:
      actions:
        - key: deployment.environment
          value: dev
          action: upsert
        - key: env
          value: dev
          action: upsert
    resourcedetection:
      detectors: [env, azure]
      timeout: 5s
      override: false
    k8sattributes:
      passthrough: true
      extract:
        metadata:
          # extract the following well-known metadata fields from pods and namespaces
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.cluster.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
    batch: {}
    memory_limiter: null
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
        thrift_compact:
          endpoint: 0.0.0.0:6831
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets: ["${MY_POD_IP}:8888"]
                labels:
                  env: dev
    zipkin:
      endpoint: 0.0.0.0:9411
  service:
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs:
        exporters:
          - otlp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics:
        exporters:
          - otlp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
      traces:
        exporters:
          - otlp
        processors:
          - memory_limiter
          - batch
          - resourcedetection
          - attributes
          - k8sattributes
        receivers:
          - otlp
          - jaeger
          - zipkin
```

**Environment**
Running in k8s.

**Additional context**
Using a older version of the otel collector (v0.40.0) exporting to the newer otel-collector (0.42.0) receiving otlp does not have this behavior. This makes me believe it just has to do with `exporting` OTLP to another collector on `0.42.0`.
