### ISSUE TITLE
Resource Limiter Processor as a more generic replacement to Memory Limiter Processor

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-collector#4911]
**Is your feature request related to a problem? Please describe.**

[Memory Limiter Processor](https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor) can be used to prevent out of memory situations by not accepting data when limits are exceeded. In such case, the preceding component (which normally is a receiver) receives an error from ConsumeX function, which allows to handle such case gracefully.

A similar approach could be used in case of high CPU usage and possibly other resource-related limits.

**Describe the solution you'd like**

To avoid creating additional processors, `memorylimiterprocessor` could be renamed to `resourcelimiterprocessor` and additional options related to dealing with CPU limits could be added. For example:

```yaml
processors:
  resource_limiter:
    check_interval: 1s
    mem:
      limit_mib: 4000
    cpu:
      limit_perc: 200
```
