### ISSUE TITLE
add the option to enable server reflection on otlp grpc receiver

### ISSUE THREAD

**Issue by tvaintrob** [open-telemetry/opentelemetry-collector#4951]
**Describe the solution you'd like**
a configuration to enable server reflection on the grpc otlp receiver something like the following:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        enable_reflection: true
```

**Describe alternatives you've considered**
thought about adding a new receiver plugin but seems like the better solution is to add the functionality to the default one

id be happy to implement this one myself and submit a PR
