### ISSUE TITLE
Degenerate collector performance when exporter has problems

### ISSUE THREAD

**Issue by kvcache** [open-telemetry/opentelemetry-collector#4981]
**Describe the bug**
Our collector running on our server has an OTLP `exporter`. That downstream target crashed. The otel collector running on the server batched up in the memorylimiter as configured, then descended into this permanently broken state where all it does is force GC in a loop & take up over 70% of a 16 core server's CPU. It never recovered, even after we fixed the downstream service. The application server was broken until I ssh'd into the machine by hand and manually ran `sudo systemctl restart otelCollector`

**Steps to reproduce**
* Configure a receiver, a batcher, a memory limiter and an OTLP exporter in a metrics & tracing pipeline.
* Set up a constant rate of 300 traces per second and a few score metrics per second.
* Blackhole the target of your OTLP sender.
* Wait for a while.

**What did you expect to see?**
OpenTelemetry Collector never uses excessive CPU or memory when a memory limiter is configured. This is a tool to prevent back-pressure from ailing downstream servers.

**What did you see instead?**
OpenTelemetry Collector consumed nearly all of the server's resources continually while the back-pressure was there. It did not recover when the downstream service was repaired either. It was permanently broken, causing severe performance problems for our application server.

**What version did you use?**
Version: `otelcontribcol version v0.36.0`

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
        # Agent is only receiving metrics on local loopback. We can set max msg size very high. Default value is 4.
        max_recv_msg_size_mib: 512

  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:

processors:
  memory_limiter/metrics:
    check_interval: 1s
    limit_mib: 256
  memory_limiter/traces:
    check_interval: 1s
    limit_mib: 256
  batch:
    timeout: 10s
    send_batch_size: 8192
    send_batch_max_size: 16384

  metricstransform:
    transforms:
    # Should match all otel system metrics https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md#metric-instruments
    - include: ^system\.
      match_type: regexp
      action: update
      operations:
        - action: add_label
          new_label: cloud_region
          new_value: us-west-2

exporters:
  otlp/central_collector:
    endpoint: "our-downstream-otel-endpoint:4317"
  logging:
    loglevel: info
    sampling_initial: 5
    sampling_thereafter: 1000

service:
  pipelines:
    metrics/system:
      receivers: [hostmetrics]
      processors: [memory_limiter/metrics, metricstransform, batch]
      exporters: [logging, otlp/central_collector]
    metrics/application:
      receivers: [otlp]
      processors: [memory_limiter/metrics, batch]
      exporters: [logging, otlp/central_collector]
    traces/central_relay:
      receivers: [otlp]
      processors: [memory_limiter/traces, batch]
      exporters: [otlp/central_collector]
```

**Environment**
OS: AmazonLinux2 5.10 x86_64
Compiler(if manually compiled): Not manually compiled

**Additional context**
The logs just spew this continuously with little variation:
```
memorylimiterprocessor/memorylimiter.go:263        Memory usage after GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9593}
memorylimiterprocessor/memorylimiter.go:273        Memory usage is above hard limit. Forcing a GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9593}
loggingexporter/logging_exporter.go:56        MetricsExporter        {"#metrics": 4}
loggingexporter/logging_exporter.go:56        MetricsExporter        {"#metrics": 32}
memorylimiterprocessor/memorylimiter.go:263        Memory usage after GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9633}
memorylimiterprocessor/memorylimiter.go:273        Memory usage is above hard limit. Forcing a GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9633}
memorylimiterprocessor/memorylimiter.go:263        Memory usage after GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9560}
memorylimiterprocessor/memorylimiter.go:273        Memory usage is above hard limit. Forcing a GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9560}
exporterhelper/queued_retry.go:231        Exporting failed. Will retry the request after interval.        {"kind": "exporter", "name": "otlp/central_collector", "error": "failed to push metrics data via OTLP exporter: rpc error: code = DeadlineExceeded desc = context deadline exceeded", "interval": "43.144164884s"}
memorylimiterprocessor/memorylimiter.go:263        Memory usage after GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9558}
memorylimiterprocessor/memorylimiter.go:273        Memory usage is above hard limit. Forcing a GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9558}
memorylimiterprocessor/memorylimiter.go:263        Memory usage after GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9512}
memorylimiterprocessor/memorylimiter.go:273        Memory usage is above hard limit. Forcing a GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9512}
memorylimiterprocessor/memorylimiter.go:263        Memory usage after GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9509}
memorylimiterprocessor/memorylimiter.go:273        Memory usage is above hard limit. Forcing a GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9509}
memorylimiterprocessor/memorylimiter.go:263        Memory usage after GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9522}
memorylimiterprocessor/memorylimiter.go:273        Memory usage is above hard limit. Forcing a GC.        {"kind": "processor", "name": "memory_limiter/traces", "cur_mem_mib": 9522}
```
