### ISSUE TITLE
OTLP HTTP receiver with OIDC : always getting 401 Unauthorized

### ISSUE THREAD

**Issue by trudyq** [open-telemetry/opentelemetry-collector#4982]
**Describe the bug**
What's working : In the collector i can setup an OTLP GRPC receiver with OIDC auth.
From a Java OLTP GRPC exporter everything is fine : I set my jwt token with a `io.grpc.ClientInterceptor` through a `ManagedChannel` object. The collector grpc endpoint works as expected.

What's not working : I can't setup an OTLP HTTP receiver with an OIDC auth. I always get a 401 Unauthorized response.
I'm pretty sure i'm doing something wrong but i don't find out where. 

**Steps to reproduce**

From a Java OTEL GRPC exporter everything works
```java
    public Tracer opentelemetryTracer() {

        Tracer tracer;
        TracerProvider tracerProvider = GlobalOpenTelemetry.getTracerProvider();

        URI endpoint = new URI("http://localhost:5317");

        ManagedChannelBuilder<?> managedChannelBuilder = ManagedChannelBuilder.forTarget(endpoint.getAuthority());
        managedChannelBuilder.usePlaintext();

        // this.otelJwtToken.getMetadata() return <"Authorization", "Bearer <token>"
        managedChannelBuilder.intercept(new ClientInterceptor[]{MetadataUtils.newAttachHeadersInterceptor(this.otelJwtToken.getMetadata())});

        OtlpGrpcSpanExporter otlpGrpcSpanExporter = OtlpGrpcSpanExporter.builder()
            .setChannel(managedChannelBuilder.build())
            .build();

        OpenTelemetrySdk openTelemetrySdk =
            OpenTelemetrySdk.builder()
                .setTracerProvider(
                    SdkTracerProvider.builder()
                        .addSpanProcessor(SimpleSpanProcessor.create(LoggingSpanExporter.create()))
                        .addSpanProcessor(
                            BatchSpanProcessor
                                .builder(
                                        otlpGrpcSpanExporter
                                ).build()
                        ).build()
                ).build();

        tracer = openTelemetrySdk.getTracer("otl-mytracer-provider");

        return tracer;
    }
```

With a Java OTEL HTTP exporter it fails
```java
    public Tracer opentelemetryTracer2() {

        Tracer tracer;
        TracerProvider tracerProvider = GlobalOpenTelemetry.getTracerProvider();

        String token = "<token>";

        OtlpHttpSpanExporter otlpHttpSpanExporter = OtlpHttpSpanExporter.builder()
            .setEndpoint("http://localhost:5318/v1/traces")
            .addHeader("authorization", "Bearer " + token)
            .build();

        OpenTelemetrySdk openTelemetrySdk =
            OpenTelemetrySdk.builder()
                .setTracerProvider(
                    SdkTracerProvider.builder()
                        .addSpanProcessor(SimpleSpanProcessor.create(LoggingSpanExporter.create()))
                        .addSpanProcessor(
                            BatchSpanProcessor
                                .builder(
                                    otlpHttpSpanExporter
                                ).build()
                        ).build()
                ).build();

        tracer = openTelemetrySdk.getTracer("otl-mytracer-provider");

        return tracer;
    }
```

With curl i also get a 401 wheter my token is valid or not
```shell
curl -v -XPOST "localhost:5318/v1/traces" -H "Authorization: Bearer ${TOKEN}"

*   Trying 127.0.0.1:5318...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5318 (#0)
> POST /v1/traces HTTP/1.1
> Host: localhost:5318
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization: Bearer <Token>
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 11 Mar 2022 13:57:05 GMT
< Content-Length: 13
< 
Unauthorized
* Connection #0 to host localhost left intact
```

**What did you expect to see?**
An authorized response if my token is valid.

**What did you see instead?**
An Unauthorized response

**What version did you use?**
Version: 0.44, 0.45, 0.46

**What config did you use?**
```yaml
receivers:
  otlp/jwt:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5317
        auth:
          authenticator: oidc/jwt
      http:
        endpoint: 0.0.0.0:5318
        auth:
          authenticator: oidc/jwt

exporters:
  logging:
    logLevel: debug

processors:
  batch:
    send_batch_size: 32768
  memory_limiter:
    check_interval: 5s
    limit_mib: 1000
    spike_limit_mib: 250
  resource:
    attributes:
    - key: otel-dc
      value: "local"
      action: insert

extensions:
  oidc/jwt:
    issuer_url: https://my-oidc-server
    audience: my-audience

service:
  telemetry:
    logs:
      level: debug
      encoding: console
      development: false
  extensions: [oidc/jwt]
  pipelines:
    traces:
      receivers: [otlp/jwt]
      processors: [memory_limiter, batch, resource]
      exporters: [logging]
```

**Environment**
OS: Ubuntu 20.04

**Additional context**
N/A

**Comment by jpkrohling** [comment]
Just a hunch, but can you try overriding the "attribute" parameter to "Authorization" (vs. "authorization")?

**Comment by trudyq** [comment]
It's the same 401 response.

I tried "authorization", "Authorization" and i also set a custom attribute name in oidc extension.

It works with OLTP GRPC exporter not with OTLP HTTP exporter.

Looking at the history i saw there were changes for HTTP in this [commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/b354a8edef9b6380d083583b4e259ea1ed6b0605#diff-5b7b297bc782ee576fd04f83ca039f3c5fad5d5ec6e3f123053d89f7153e2b33)

and they disapeared in this [commit](https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/bc723350687233d47067e6a08961066f30ed8490#diff-5b7b297bc782ee576fd04f83ca039f3c5fad5d5ec6e3f123053d89f7153e2b33)

Don't know if it's related.

**Comment by jpkrohling** [comment]
I'm adding this to my queue and will take a look soon.

**Comment by jpkrohling** [comment]
@pavankrish123, do you have free cycles to look into this?

**Comment by umarkhan17** [comment]
changing from "authorization" to "Authorization" solved it for me.

**Comment by pavankrish123** [comment]
I can take a look into it.

**Comment by pavankrish123** [comment]
Sure @jpkrohling. I will run tests and verify last time I played with it collector (oauth2) -> collector(oidc) was working fine. 

Not sure if it is a problem in the Java SDK. But since curl is throwing error as well. I will re-run the tests.

**Comment by jpkrohling** [comment]
I believe @gouthamve also tried this scenario recently, using HTTP auth against a Prometheus Remote Write endpoint.

**Comment by pavankrish123** [comment]
I can confirm I am seeing the same issue as well on my end while using HTTP exports to OTLP HTTP receiver with OIDC. I have also tested with our [standard example ](https://medium.com/opentelemetry/securing-your-opentelemetry-collector-1a4f9fa5bd6f) but with a slight modification

`tracegen` --grpc->  `OTEL Collector (Agent) export via http OAuth2` -> `OIDC enabled http receiver` 

agent-config.yaml 

```yaml
extensions:
  oauth2client:
    client_id: agent
    client_secret: joGTMxKWiGhWTE3dDQaJYoWzDrmGe34b
    token_url: http://localhost:8080/auth/realms/opentelemetry/protocol/openid-connect/token

receivers:
  otlp:
    protocols:
      grpc:

processors:

exporters:
  otlphttp:
    endpoint: https://localhost:4318
    tls:
      ca_file: /tmp/certs/ca.pem
    auth:
      authenticator: oauth2client

service:
  telemetry:
    logs:
      level: debug
    metrics:
      address: :8988
  extensions: [oauth2client]
  pipelines:
    traces/agent:
      receivers: [otlp]
      processors: []
      exporters: [otlphttp]
```
and gateway.yaml

```yaml
receivers:
  otlp/withauth:
    protocols:
      http:
        tls:
          cert_file: /tmp/certs/cert.pem
          key_file:  /tmp/certs/cert-key.pem
        auth:
          authenticator: oidc 
   
processors:

exporters:
  logging:
    logLevel: debug

service:
  extensions: [oidc]
  pipelines:
    traces/collector:
      receivers: [otlp/withauth]
      processors: []
      exporters: [logging]
```

The Agent Collector With Client OAuth2 -> Gateway collector with OIDC is failing with error consistent with the bug 

```bash
2022-03-16T01:26:50.961-0700	debug	otlphttpexporter/otlp.go:127	Preparing to make HTTP request	{"kind": "exporter", "name": "otlphttp", "url": "https://localhost:4318/v1/traces"}
2022-03-16T01:26:50.966-0700	info	exporterhelper/queued_retry.go:218	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "name": "otlphttp", "error": "error exporting items, request to https://localhost:4318/v1/traces responded with HTTP Status Code 401", "interval": "21.16479875s"}
2022-03-16T01:27:12.133-0700	debug	otlphttpexporter/otlp.go:127	Preparing to make HTTP request	{"kind": "exporter", "name": "otlphttp", "url": "https://localhost:4318/v1/traces"}
2022-03-16T01:27:12.136-0700	info	exporterhelper/queued_retry.go:218	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "name": "otlphttp", "error": "error exporting items, request to https://localhost:4318/v1/traces responded with HTTP Status Code 401", "interval": "39.748023572s"}
```

and grpc works fine 

I will have to look into http implementation of oidc extension - will get back to you soon. Thanks!

**Comment by jpkrohling** [comment]
Thank you for the investigation, @pavankrish123!

**Comment by pavankrish123** [comment]
Hi @jpkrohling, I see that there is a new instruction added in our [standard example](https://medium.com/opentelemetry/securing-your-opentelemetry-collector-1a4f9fa5bd6f) about adding the collector (gateway) client as the audience for the tokens issued for agent clients. (unless I missed it while I did my previous test)

Starting the setup of keycloak server  with the mapper step produces no 401 error and I could see traces reach gateway collector without any issue now. 

Here is my test setup 

-  Setup key cloak server as [mentioned here ](https://medium.com/opentelemetry/securing-your-opentelemetry-collector-1a4f9fa5bd6f)
- . Start Agent collector with Client OAuth2  with below configuration 
```yaml
extensions:
  oauth2client:
    client_id: agent
    client_secret: IjPe8UfH7cmQGxUrwPx3q5CPocnO2GLL
    token_url: http://localhost:8080/auth/realms/opentelemetry/protocol/openid-connect/token

receivers:
  otlp:
    protocols:
      grpc:

processors:

exporters:
  logging:
    loglevel: debug
  otlphttp:
    endpoint: https://localhost:4318
    tls:
      ca_file: /tmp/certs/ca.pem
    auth:
      authenticator: oauth2client

service:
  telemetry:
    logs:
      level: debug
    metrics:
      address: :8988
  extensions: [oauth2client]
  pipelines:
    traces/agent:
      receivers: [otlp]
      processors: []
      exporters: [logging, otlphttp]
```
-  Setup gateway collector with OIDC with the below configuration 
```yaml
extensions:
  oidc:
    issuer_url: http://localhost:8080/auth/realms/opentelemetry
    audience: collector
    attribute: Authorization  # (A)uthorization - note the A

receivers:
  otlp/withauth:
    protocols:
      http:
        tls:
          cert_file: /tmp/certs/cert.pem
          key_file:  /tmp/certs/cert-key.pem
        auth:
          authenticator: oidc

processors:

exporters:
  logging:
    logLevel: debug

service:
  extensions: [oidc]
  pipelines:
    traces/collector:
      receivers: [otlp/withauth]
      processors: []
      exporters: [logging]
``` 

- use tracegen to send traces into agent collector 
```bash 
tracegen -traces 1 -otlp-insecure
```

- Traces on Gateway collector observed 

```bash
2022-03-30T22:37:35.011-0700    INFO    loggingexporter/logging_exporter.go:40  TracesExporter  {"#spans": 2}
2022-03-30T22:37:35.011-0700    DEBUG   loggingexporter/logging_exporter.go:49  ResourceSpans #0
Resource SchemaURL: https://opentelemetry.io/schemas/v1.4.0
Resource labels:
     -> service.name: STRING(tracegen)
ScopeSpans #0
ScopeSpans SchemaURL: 
InstrumentationScope tracegen 
Span #0
    Trace ID       : 30f0508c42650a9b46c4acff79e9341f
    Parent ID      : 81f50b52ba5cbd32
    ID             : 6d5466ba0f80f46e
    Name           : okey-dokey
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2022-03-31 05:37:35.00853 +0000 UTC
    End time       : 2022-03-31 05:37:35.008654 +0000 UTC
    Status code    : STATUS_CODE_UNSET
    Status message : 
Attributes:
     -> span.kind: STRING(server)
     -> net.peer.ip: STRING(1.2.3.4)
     -> peer.service: STRING(tracegen-client)
Span #1
    Trace ID       : 30f0508c42650a9b46c4acff79e9341f
    Parent ID      : 
    ID             : 81f50b52ba5cbd32
    Name           : lets-go
    Kind           : SPAN_KIND_INTERNAL
    Start time     : 2022-03-31 05:37:35.00851 +0000 UTC
    End time       : 2022-03-31 05:37:35.008654 +0000 UTC
    Status code    : STATUS_CODE_UNSET
    Status message : 
Attributes:
     -> span.kind: STRING(client)
     -> net.peer.ip: STRING(1.2.3.4)
     -> peer.service: STRING(tracegen-server)
```
Not sure what the mapping step in keycloak does but I am not seeing the issue anymore? I wonder if something has changed since.  cc: @jpkrohling
