### ISSUE TITLE
Enable Authentication between agent collector and Standalone collector via Zipkin Exporter not working

### ISSUE THREAD

**Issue by umarkhan17** [open-telemetry/opentelemetry-collector#4994]
I am trying to enable authentication between agent and standalone collector. I have deployed Collecter and Operator.
I am deploying agent collector as a sidecar. which is sending trace data to the standalone collector. But every time i enable Authentication. It gives me 

`2022-03-14T11:14:41.801Z        info    exporterhelper/queued_retry.go:215      Exporting failed. Will retry the request after interval.        {"kind": "exporter", "name": "zipkin", "error": "failed the request with status code 401", "interval": "30.021009004s"}`

My standalone collector config looks like : 

```
config:
  exporters:
    logging:
      loglevel: info
    jaeger:
      endpoint: "jaeger-collector.central-observability.svc.cluster.local:14250"
      tls:
        insecure: true

  extensions:
    oidc:
      issuer_url: http://auth-server:8080/auth/realms/opentelemetry
      audience: collector
      attribute: authorization
    health_check: {}
    memory_ballast: {}
  processors:
    batch: {}
    # If set to null, will be overridden with values based on k8s resource limits
    memory_limiter: null
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
        thrift_compact:
          endpoint: 0.0.0.0:6831
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
          auth:
            authenticator: oidc

    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${MY_POD_IP}:8888
    zipkin:
      endpoint: 0.0.0.0:9411
      auth:
        authenticator: oidc
  service:
    extensions:
      - oidc
      - health_check
      - memory_ballast
    pipelines:
      logs:
        exporters:
          - logging
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
#      metrics:
#        exporters:
#          - logging
#        processors:
#          - memory_limiter
#          - batch
#        receivers:
#          - otlp
#          - prometheus
      traces:
        exporters:
          - logging
          - jaeger
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
          - zipkin

```

My agent collector config looks like this :

```
config: |
   extensions:
           oauth2client:
             client_id: agent
             client_secret: 3oBVLQYDAkpCDP039ORy8Iv3dtyki3CH
             token_url: http://auth-server:8080/auth/realms/opentelemetry/protocol/openid-connect/token
   receivers:
         jaeger:
           protocols:
             grpc:
         otlp:
           protocols:
             grpc:
             http:
         zipkin:
           endpoint: 0.0.0.0:9411

   exporters:
     logging:
     zipkin:
       endpoint: http://standalone.url/api/v2/spans
       auth:
         authenticator: oauth2client
   service:
     telemetry:
       logs:
         level: "info"
     extensions: [oauth2client]
     pipelines:
       traces/agent:
         receivers: [jaeger,otlp,zipkin]
         processors: []
         exporters: [logging,zipkin]

```
P.S: when trying to do with OTLP, it wants me to enable TLS. i want to do it without TLS for a POC.Is it possible to do it with zipkin exporter. Pls assist.

**Comment by jpkrohling** [comment]
This might be related to #4982

**Comment by umarkhan17** [comment]
```
exporters:
     logging:
     zipkin:
       endpoint: http://standalone.url/api/v2/spans
       auth:
         authenticator: oauth2client
```

is this correct? can we use oauth2client extension with Zipkin exporter?
