### ISSUE TITLE
[receiver/otlp] data not processed when using the old instrumentation library fields

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#5188]
**Describe the bug**
Using the v0.15.0 protos with the current Python SDK/OTLP over gRPC exporter (which still uses instrumentation library fields) results in no data being processed by the collector.

The receiver isn't translating InstrumentationLibrary* fields to Scope*, resulting in the traces being discarded.

**Steps to reproduce**
Run the following code using the Python SDK/Exporter in `main`:

```
from opentelemetry import trace
from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import (
    OTLPSpanExporter,
)
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor

span_exporter = OTLPSpanExporter(
    # optional
    insecure=True,
    endpoint="127.0.0.1:4317",
    # credentials=ChannelCredentials(credentials),
    # headers=(("metadata", "metadata")),
)
tracer_provider = TracerProvider()
trace.set_tracer_provider(tracer_provider)
span_processor = BatchSpanProcessor(span_exporter)
tracer_provider.add_span_processor(span_processor)

# Configure the tracer to use the collector exporter
tracer = trace.get_tracer_provider().get_tracer(__name__)

with tracer.start_as_current_span("foo"):
    print("Hello world!")
```

**What did you expect to see?**
Data is processed as it was before.

**What did you see instead?**
No data is processed.

**What version did you use?**
Version: `main`

**What config did you use?**
```
receivers:
    otlp:
        protocols:
            http:
exporters:
    logging:
        loglevel: debug

service:
    pipelines:
        traces:
            exporters: [logging]
            receivers: [otlp]
        metrics:
            exporters: [logging]
            receivers: [otlp]
        logs:
            exporters: [logging]
            receivers: [otlp]
```
