### ISSUE TITLE
How to troubleshoot prometheus metrics data anomalies?

### ISSUE THREAD

**Issue by 1046102779** [open-telemetry/opentelemetry-collector#5238]
I use Opentelemetry-Go SDK metrics v0.27.0 to report metrics via http. The real traffic of the business is 0.3w~1.7w req/sec. The metrics data collected by prometheus is occasionally exceptional, as shown in the following figure. This is difficult to locate. I tried to use the vendor mechanism to print the collector service log, and found that Opentelemetry-go sdk reported and received by the collector, and there was nothing exceptional.

<img width="769" alt="image" src="https://user-images.githubusercontent.com/20457624/164360936-419f8545-6922-47df-9517-7b68c9ecc5ff.png">
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/20457624/164362779-8c90e25b-369f-4349-834b-d3b41f1bb931.png">

microservice go.mod
```golang
        go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.29.0
        go.opentelemetry.io/otel v1.6.3
        go.opentelemetry.io/otel/exporters/otlp/otlpmetric v0.27.0
        go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v0.27.0
        go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.5.0
        go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.5.0
        go.opentelemetry.io/otel/metric v0.27.0
        go.opentelemetry.io/otel/sdk v1.5.0
        go.opentelemetry.io/otel/sdk/metric v0.27.0
        go.opentelemetry.io/otel/trace v1.6.3
```

microservice(opentelemetry-go sdk)
```golang
func (m *MetricClient) init() error {
        var err error
        ctx := context.Background()
        client := otlpmetrichttp.NewClient(
                otlpmetrichttp.WithInsecure(),
                otlpmetrichttp.WithEndpoint(m.Address))
        m.exporter, err = otlpmetric.New(ctx, client)
        if err != nil {
                return errors.Errorf("Failed to create the collector exporter: %v", err)
        }
        res, _ := resource.New(ctx,
                resource.WithAttributes(
                        semconv.ServiceNameKey.String(m.AppID),
                        semconv.ServiceNamespaceKey.String(m.Namespace),
                ),
        )
        // ::TODO https://github.com/open-telemetry/opentelemetry-go/issues/2678
        // fake boundary
        bounds := []float64{10, 50, 100, 150, 200, 250, 300, 350, 400}         
        m.pusher = controller.New(
                processor.NewFactory(
                        simple.NewWithHistogramDistribution(
                                histogram.WithExplicitBoundaries(
                                        bounds)),
                        m.exporter,
                ),
                controller.WithExporter(m.exporter),
                controller.WithCollectPeriod(DefaultReportingPeriod),
                controller.WithCollectTimeout(30*time.Second),                         
                controller.WithPushTimeout(30*time.Second),
                controller.WithResource(res))
        global.SetMeterProvider(m.pusher)
        // only global one meter, not multiple meters.
        strictMeter := metric.Must(
                global.Meter("mecha",
                        metric.WithInstrumentationVersion("v0.27.0"),
                        metric.WithSchemaURL("go.opentelemetry.io/otel/metric")),                                                                     )
        m.meter = &strictMeter

        if err := m.pusher.Start(ctx); err != nil {
                return errors.Errorf("could not start metric controller: %v", err)
        }
        return nil
}
```

collector server go.mod
```golang
    github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.44.0
    github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.44.0
    github.com/stretchr/testify v1.7.0
    go.opentelemetry.io/collector v0.44.0
    golang.org/x/sys v0.0.0-20220114195835-da31bd327af9
```

collector server log:
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/20457624/164362714-e95154fa-b745-4273-a155-697f3f5d05af.png">

otel.yaml 
```yaml
extensions:
  zpages:

receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    send_batch_size: 10000
    timeout: "10s"
  memory_limiter:
    check_interval: "1s"
    limit_mib: 4000
    spike_limit_mib: 800

exporters:
  prometheus:
    endpoint: "0.0.0.0:9091"
    send_timestamps: true
    metric_expiration: "180m"
    resource_to_telemetry_conversion:
      enabled: true
  jaeger:
    endpoint: "xx.xx.xx.xx:14250"
    tls:
      insecure: true

service:
  extensions: [zpages]
  pipelines:
    traces/1:
      receivers:
        - otlp
      processors:
        - batch
        - memory_limiter
      exporters:
        - jaeger
    metrics/1:
      receivers:
        - otlp
      processors:
        - batch
        - memory_limiter
      exporters:
        - prometheus
```

<img width="785" alt="image" src="https://user-images.githubusercontent.com/20457624/164363240-f1d89560-5952-4a1d-ab98-07d550cce047.png">

**Comment by bogdandrutu** [comment]
Hi @1046102779 

Prometheus "exporter" (the pull based version) is not very well designed in my opinion. I recommend to use either prometheus remote write exporter in the collector, or to simply expose directly prometheus format from your app and let the prometheus server scrape directly your app (avoid using the collector).

**Comment by dashpole** [comment]
Memory usage aside, the prometheus exporter should work ~mostly correctly.  This seems like an issue with data correctness if i'm understanding correctly.  @1046102779 can you share your prometheus scrape config?

cc @gouthamve, who might've seen something like this before.

**Comment by 1046102779** [comment]
> Memory usage aside, the prometheus exporter should work ~mostly correctly. This seems like an issue with data correctness if i'm understanding correctly. @1046102779 can you share your prometheus scrape config?
> 
> cc @gouthamve, who might've seen something like this before.

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "otlp"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["0.0.0.0:9091"]
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["0.0.0.0:9090"]
```
