### ISSUE TITLE
Collector gives 404 for http/protobuf traces

### ISSUE THREAD

**Issue by rohanagarwal36** [open-telemetry/opentelemetry-collector#5241]
**Describe the bug**
I have configured the collector on Kubernetes, the collector receiver server starts successfully at 0.0.0.0:4318. I am using otlp http receiver. But the opentelemetry java agent is unable to send data to the collector. I have tried many combinations but all of them return 404.
Logs from collector:
`
2022-04-21T05:53:21.156Z	info	service/collector.go:303	Starting otelcol...	{"Version": "0.35.0", "NumCPU": 8}
2022-04-21T05:53:21.156Z	info	service/collector.go:242	Loading configuration...
2022-04-21T05:53:21.157Z	info	service/collector.go:258	Applying configuration...
2022-04-21T05:53:21.157Z	info	builder/exporters_builder.go:266	Exporter was built.	{"kind": "exporter", "name": "otlphttp/2"}
2022-04-21T05:53:21.157Z	info	builder/exporters_builder.go:266	Exporter was built.	{"kind": "exporter", "name": "otlphttp"}
2022-04-21T05:53:21.157Z	info	builder/pipelines_builder.go:216	Pipeline was built.	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2022-04-21T05:53:21.157Z	info	builder/receivers_builder.go:229	Receiver was built.	{"kind": "receiver", "name": "otlp", "datatype": "traces"}
2022-04-21T05:53:21.157Z	info	service/service.go:143	Starting extensions...
2022-04-21T05:53:21.157Z	info	service/service.go:188	Starting exporters...
2022-04-21T05:53:21.157Z	info	builder/exporters_builder.go:93	Exporter is starting...	{"kind": "exporter", "name": "otlphttp/2"}
2022-04-21T05:53:21.157Z	info	builder/exporters_builder.go:98	Exporter started.	{"kind": "exporter", "name": "otlphttp/2"}
2022-04-21T05:53:21.157Z	info	builder/exporters_builder.go:93	Exporter is starting...	{"kind": "exporter", "name": "otlphttp"}
2022-04-21T05:53:21.158Z	info	builder/exporters_builder.go:98	Exporter started.	{"kind": "exporter", "name": "otlphttp"}
2022-04-21T05:53:21.158Z	info	service/service.go:193	Starting processors...
2022-04-21T05:53:21.158Z	info	builder/pipelines_builder.go:52	Pipeline is starting...	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2022-04-21T05:53:21.158Z	info	builder/pipelines_builder.go:63	Pipeline is started.	{"pipeline_name": "traces", "pipeline_datatype": "traces"}
2022-04-21T05:53:21.158Z	info	service/service.go:198	Starting receivers...
2022-04-21T05:53:21.158Z	info	builder/receivers_builder.go:71	Receiver is starting...	{"kind": "receiver", "name": "otlp"}
2022-04-21T05:53:21.158Z	info	otlpreceiver/otlp.go:93	Starting HTTP server on endpoint 0.0.0.0:4318	{"kind": "receiver", "name": "otlp"}
2022-04-21T05:53:21.158Z	info	otlpreceiver/otlp.go:147	Setting up a second HTTP listener on legacy endpoint 0.0.0.0:55681	{"kind": "receiver", "name": "otlp"}
2022-04-21T05:53:21.158Z	info	otlpreceiver/otlp.go:93	Starting HTTP server on endpoint 0.0.0.0:55681	{"kind": "receiver", "name": "otlp"}
2022-04-21T05:53:21.158Z	info	builder/receivers_builder.go:76	Receiver started.	{"kind": "receiver", "name": "otlp"}
2022-04-21T05:53:21.158Z	info	service/collector.go:206	Setting up own telemetry...
2022-04-21T05:53:21.160Z	info	service/telemetry.go:105	Serving Prometheus metrics	{"address": ":8888", "level": 0, "service.instance.id": "e0991cad-fb45-41b0-89cd-cd9f5a63b4a0"}
2022-04-21T05:53:21.160Z	info	service/collector.go:218	Everything is ready. Begin running and processing data.`

**Steps to reproduce**
Run the collector using the yaml below.
Run the agent using the following command:
`java -javaagent:otw2.jar -Dotel.exporter.otlp.protocol=http/protobuf -Dotel.exporter.otlp.traces.endpoint=http://url-where-collector-service-is-exposed/v1/traces -Dotel.service.name=sample-service -Dotel.bsp.schedule.delay=1000 -Dotel.bsp.max.export.batch.size=256  -Dotel.javaagent.debug=true -Dotel.exporter.otlp.headers=Content-Type=application/json  -jar target/service1-1.0.jar`
For -Dotel.exporter.otlp.traces.endpoint, I have tried, and none works, error is same for all
1) http://url-where-collector-service-is-exposed/v1/traces
2) http://url-where-collector-service-is-exposed:4318/v1/traces
3) http://url-where-collector-service-is-exposed:4318
4) http://url-where-collector-service-is-exposed

**What did you expect to see?**
Successful export of spans to the collector.

**What did you see instead?**
404 error when exporting spans to the collector.
`
io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export spans. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found
`

**What version did you use?**
latest collector image - otel/opentelemetry-collector

**What config did you use?**
Config yaml:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-conf
  labels:
    app: opentelemetry-collector
    component: otel-agent-conf
data:
  otel-agent-config: |
    receivers:
      otlp:
        protocols:
          http:
            cors_allowed_origins:
            - "*"
    processors:
      batch:
    exporters:
      logging:
      otlphttp:
        traces_endpoint: "http://some-internal-url-xxxxxx-1"
      otlphttp/2:
        traces_endpoint: "http://some-internal-url-xxxxxx-2"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp, otlphttp/2]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
  labels:
    service: opentelemetry-collector
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 5%
  selector:
    matchLabels:
      service: opentelemetry-collector
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
      labels:
        service: opentelemetry-collector
        version: v1
        app: opentelemetry-collector
        id: opentelemetry-collector
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - opentelemetry-collector
              topologyKey: "kubernetes.io/hostname"
            weight: 100
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
            weight: 100
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
        name: opentelemetry-collector
        image: otel/opentelemetry-collector
        imagePullPolicy: Always
        ports:
          - name: http-plainport
            containerPort: 4318
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
        resources:
          limits:
            memory: 4Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"]
        terminationMessagePath: /termination-log
        terminationMessagePolicy: File
      terminationGracePeriodSeconds: 35
      volumes:
        - configMap:
            name: otel-agent-conf
            items:
              - key: otel-agent-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
---
kind: Service
apiVersion: v1
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  selector:
    service: opentelemetry-collector
    version: v1
  ports:
    - name: http-otlp
      port: 4318
      targetPort: 4318
      protocol: TCP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: opentelemetry-collector
  targetCPUUtilizationPercentage: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-collector
spec:
  ingressClassName: nginx-internal
  rules:
  - host: some-url-where-collector-service-is-exposed
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: opentelemetry-collector
            port:
              number: 4318
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
MacOS, Kubernetes
