### ISSUE TITLE
Access headers in OTLP exporter

### ISSUE THREAD

**Issue by tonychoe** [open-telemetry/opentelemetry-collector#5264]
**Is your feature request related to a problem? Please describe.**

The otlp exporter supports the headers option so we can specify the header value we want to send to the downstream.
```
  exporters:
    otlp/archlab:
      endpoint: distributor.tempo:4317
        headers:
          X-Scope-OrgID: archlab
```
However, in the multi-tenant scenario, passing different headers mean we need to create a pipeline of multiple exporters and each exporter has the hard-coded header.

**Describe the solution you'd like**
Enable accessing headers passed from the upstream. So, the exporter simply use the passed one.
```
  exporters:
    otlp/archlab:
      endpoint: distributor.tempo:4317
        headers:
          key: X-Scope-OrgID
          from_context: X-Scope-OrgID
```

**Describe alternatives you've considered**
Tried this pipeline
- Have multiple exporters, each with the different header value hard-coded.
- Have the routing processor that determines which exporter will be used by the header value passed from the upstream.
Cons is the more tenant we have, the more exporter we must create.
