### ISSUE TITLE
Failed to export spans to OpenTelemetry Collector

### ISSUE THREAD

**Issue by tejeswar-komma** [open-telemetry/opentelemetry-collector#5309]
VM Arguments:
-javaagent:/Users/user-name/Downloads/Eclipse-projects/opentelemetry-javaagent.jar
-Dotel.exporter.otlp.traces.protocol=http/protobuf
-Dotel.traces.exporter=otlp
-Dotel.exporter.otlp.traces.endpoint=http://localhost:4318/v1/traces
-Dotel.resource.attributes=service.name="serviceName"
-Dotel.metrics.exporter=prometheus
-Dotel.exporter.prometheus.port=9472

[otel.javaagent 2022-05-04 10:07:07:433 +0530] [OkHttp http://localhost:4318/...] ERROR io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/0:0:0:0:0:0:0:1:4318

I am trying to export the traces to the AppDynamics. "https://docs.appdynamics.com/22.5/en/application-monitoring/appdynamics-for-opentelemetry". I have few queries.

1. I am using OpenTelemetry Java agent for the basic traces and metrics of my services. As per my knowledge, OpenTelemetry Collector can be deployed either as an agent or as a Gateway. So Is the OpenTelemetry Collector present inside this Java agent to Collect the traces and metrics?
2. If it is present in the Java agent, how should I configure the yaml file i.e., How should I use the yaml file to configure the OpenTelemetry Collector? How should I use the yaml file in VM Arguments in Eclipse? Should I keep it somewhere in the local and use --config path??
3. After running my application with above VM arguments, when I hit the "http://localhost:4318/v1/traces" on the browser, it is not working. How to know that our Collector is collecting the traces and how to see these traces? 
4. I want to use both Jaeger and AppDynamics to collect the traces. How to achieve that?

**Comment by bogdandrutu** [comment]
@arminru @dyladan can you help, sorry I missed this issue before

**Comment by arminru** [comment]
@bogdandrutu That's AppDynamics, not us 🙂 
@mhosabettu @scheler can you take a look?

**Comment by bogdandrutu** [comment]
Sorry, this is what happens when you wake up too early :))

**Comment by pavankrish123** [comment]
>>>   I am using OpenTelemetry Java agent for the basic traces and metrics of my services. As per my knowledge, OpenTelemetry Collector can be deployed either as an agent or as a Gateway. So Is the OpenTelemetry Collector present inside this Java agent to Collect the traces and metrics?

No, Otel collector is a separate process next to the Java Agent (either as an agent or gateway). Please refer to https://opentelemetry.io/docs/ for more information on the architecture. 


 >>>   If it is present in the Java agent, how should I configure the yaml file i.e., How should I use the yaml file to configure the OpenTelemetry Collector? How should I use the yaml file in VM Arguments in Eclipse? Should I keep it somewhere in the local and use --config path??

Nope, since otel collector is a separate process you [need to download otel collector ](https://github.com/open-telemetry/opentelemetry-collector-releases/releases) (suggest using contrib in case  if we want to use Jaeger) and start the collector with --config option. Please refer to [installation instructions ](https://opentelemetry.io/docs/collector/getting-started/) and [configuration instructions](https://opentelemetry.io/docs/collector/configuration/) 

>>>    After running my application with above VM arguments, when I hit the "http://localhost:4318/v1/traces" on the browser, it is not working. How to know that our Collector is collecting the traces and how to see these traces?

Simplest way is to start collector and see the logs of the collector process :) . In addition to that you can enable health_check extension which exposes an endpoint to see the health of collector. I believe :4318 is the receiver (ingestion) enpoint for collector to receive traces. The url you are trying to access in browser is REST url. You won't be able to see anything.

>>>   I want to use both Jaeger and AppDynamics to collect the traces. How to achieve that?
Absolutely, this is precisely one of the key benefits of using Otel collector. You can "fan out" the data received by collector from Java Agent to multiple destinations, including but not limited to OTLP (AppDynamics) , Jaeger, Zipkin. All that is needed to enable exporters the choice. 

Here is a sample configuration. 

```yaml
# to receive otlp data 
receivers:
  # for additional configuration see https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver/otlpreceiver
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

# to export data 
exporters:
  # for additional configuration https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlpexporter
  otlp:
    endpoint: otelcol:4317
 # for additional configuration https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/jaegerexporter
  jaeger:
     endpoint: <>

extensions:
  # exposes http://localhost:13133 by default which we can use to query the health status of collector. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, jaeger]

```
https://opentelemetry.io/docs/  has excellent documentation every thing from getting started to advanced. Hope this helps.
