### ISSUE TITLE
Enable or disable pipelines with env-vars

### ISSUE THREAD

**Issue by ringerc** [open-telemetry/opentelemetry-collector#5325]
# Feature: Enable/disable pipelines via an env-subst-able key

When deploying a collector configuration via tools like the opentelemetry-operator and Kustomize, it's difficult to dynamically mangle the yaml blob of the otel collector's main config payload to adjust it for different environments or configurations.

For example, a deployment may need to enable the `tracing/our-inhouse-jaeger` pipeline only when deployed in a dev-env, while on a production env traces may be shipped on a `tracing/grafana-cloud` pipeline.

This is presently very difficult to accomplish without duplicating the whole config file for each environment.

**Describe the solution you'd like**

I would like to have an `enabled:` or `disabled:` key for `services.pipelines` children, so they can be toggled via env-var value substitution, e.g the following *imaginary and unsupported* syntax:

```
        traces/datadog:
          # This next line is the suggestion
          enabled: "${DATADOG_ENABLED}"
          receivers:
            - zipkin
            - otlp
          processors:
            - memory_limiter
            - resource
            - resourcedetection
            - batch
          exporters:
            - datadog
```

**Describe alternatives you've considered**

**Replacing the exporter name using an env-var**

e.g.

```
exporters:
  - "${DATADOG_EXPORTER}"
```

does not work - the empty string is not ignored as an exporter name, a pipeline must have at least one exporter, and the `nop` exporter is not exposed in release builds per https://github.com/open-telemetry/opentelemetry-collector/issues/5324 so I cannot set `DATADOG_EXPORTER=nop`

**Using the `filter` processor**

The `filter` processor does not support trace spans, so it cannot be used to match on an env-var and discard spans. Additionally, the exporter is still started and initialized.

**Using the `probabilistic_sampler` to discard traces**

This is what I'm doing now, but it has many downsides:

* The pipeline is still created, but does nothing useful
* The exporter is still initialized, so its configuration must be valid in this environment or it will spew errors
* It's a bit clumsy to understand in the configuration

**Using span routing**

It may be possible to accomplish this using the contrib span routing extension but the same issues will apply as for the sampler, if not worse, and it's more complex.

**Additional context**

Not that comes to mind

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-collector/pull/5507

**Comment by ringerc** [comment]
Thankyou very much @bogdandrutu and @mx-psi 

I think that would probably satisfy the use case. Using env-var based config snippets defined in a separate k8s `ConfigMap` would make it feasible to handle under the control of the `opentelemetry-operator`, too.

I'll report back, but I'll close this now as I think it's likely that your suggestions would be sufficient. I'll see about adding a note to the operator docs with hints on how to compose layered configuration if it works out.

**Comment by sirianni** [comment]
@ringerc Thanks for the great writeup.  We have exactly the same use case.  Your proposed syntax would work very well for us

```yaml
        traces/datadog:
          # This next line is the suggestion
          enabled: "${DATADOG_ENABLED}"
```

We rely heavily on YAML merging/layering (via Helm and a homegrown tool) and the ability to unset default values is fragile and doesn't work well with our setup.  Being able to set an `enabled: false` flag would merge well.  Which approach did you end up using?
