### ISSUE TITLE
Deploying as a daemonset

### ISSUE THREAD

**Issue by dudicoco** [open-telemetry/opentelemetry-collector#5370]
Hi,

I don't see anywhere in the docs on how the client/exporter should be configured when the collector is deployed as a daemonset.
It seems to me that in order to make a daemonset useful you MUST set `hostNetwork: true` and then set the clients to export the traces to the node IP: https://stackoverflow.com/questions/50216813/exposing-a-daemonset-service-for-consumption-by-pods-on-the-same-node.
Without this configuration the daemonset is useless as client won't send traces to the daemonset pod within the same node.

Can someone please elaborate how this should be configured with opentelemetry and as to why it's not documented?

Thanks

**Comment by dmitryax** [comment]
@dudicoco this repo is for core collector functionality. Which distribution, helm chart or operator are you using?

**Comment by dudicoco** [comment]
@dmitryax i'm referring here to the documentation on how to run the collector as a daemonset: https://opentelemetry.io/docs/collector/getting-started/#kubernetes
After fishing into the code in the operator repo and discussing with @TylerHelmuth on slack, these are my conclusions:
1. The daemonset ports need to be exposed within the host:
```yaml
ports:
- name: otlp
  hostPort: 4317
  containerPort: 4317
  protocol: TCP
```
2. The client configuration need to use the k8s downwards API to get the host IP and connect to the daemonset pod on the same node:
```yaml
env:
  - name: HOST_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
- name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
  value: http://$(HOST_IP):4317
```
