### ISSUE TITLE
Allow specifying Collector's own Resource in the config

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#5398]
In order to allow external Supervisor to control the Collector we want to the Supervisor to be able to tell the Collector to use a specific `service.instance.id` instead of auto-generating one.

One of the ways to allow this is to add a sub-section in the `service.telemetry` config section where any Resource attributes can be specified. This allow to specify not only `service.instance.id`, but also `service.namespace` (to .g. specify the team this Collector belongs too) or `deployment.environment` or even the `service.name` (defaults to current "io.opentelemetry.collector").

For example we can have the following in the config:
```yaml
service:
  telemetry:
    resource:
      service.instance.id: 01G3EN4NW306AFVGQT5ZYC0GEK
      service.namespace: onlineshop
      deployment.environment: production
```
