### ISSUE TITLE
Extend configuration syntax so received metadata or span attributes can be used as dynamic values to set on processors or exporters

### ISSUE THREAD

**Issue by dixanms** [open-telemetry/opentelemetry-collector#5460]
**Is your feature request related to a problem? Please describe.**

- Need to pass through metadata from a grpc receiver, into an otlp exporter header

**Describe the solution you'd like**

```yaml
exporters:
  otlp:
      endpoint: "http://some-endpoint:4317/"
      headers:
        my-data1: ":metadata.data1"
```

or

```yaml
exporters:
  otlp:
      endpoint: "http://some-endpoint:4317/"
      headers:
        my-data1: ":attributes.data1"
```
