### ISSUE TITLE
Need help in collecting server metrics - Disk/CPU #6197

### ISSUE THREAD

**Issue by Godwinmoses93** [open-telemetry/opentelemetry-collector#5568]
Hi All,

I am new to open-telemtry, I am trying to collect a Linux machines metrics such as CPU/Disk/Memory to display in cloudwatch.
I have installed open-telemetry collector in my Linux AWS instance and tried to run the docker container provided in the example. I was able to see application metrics pulled in, someone please help me how to collect the Infrastructure metrics, if there is any example config.yaml that would be helpful. Or is there any API commands for open-telemetry like AWS command line, where I can create custom metrics using putmetricdata ! Thanks in advance.

**Comment by fatsheep9146** [comment]
The target you want to collect cpu metric is linux AWS machine or the container running on the machine?

**Comment by Godwinmoses93** [comment]
@fatsheep9146 , In the linux machine. Can I use open-telemetry as a agent to collect these metrics !
If I get some example Yaml or API command, I will create for others.

**Comment by Godwinmoses93** [comment]
Post creating the Yaml, do we need to create any script to trigger the yaml ? or once the config.yaml edited we will be able to see in cloudwatch ?

**Comment by fatsheep9146** [comment]
@Godwinmoses93 I think you should use hostmetrics receiver in your collector configuration, and [awscloudwatch exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awsemfexporter) to export metric to cloudwatch. something like 
```
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
exporters:
    awsemf:
        region: 'us-west-2'
        resource_to_telemetry_conversion:
            enabled: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [awsemf]
      
```
