### ISSUE TITLE
[QUESTION] Possibility to use duration as policy for tail-based sampling

### ISSUE THREAD

**Issue by tsologub** [open-telemetry/opentelemetry-collector#558]
Does Otel collector provide a possibility to use `duration` as a policy? 
I am using the following collector configuration:
```yaml
...
processors:
  batch:
  queued_retry:
  tail_sampling:
    decision_wait: 10s
    policies:
      - name: sample-long-running-requests
        type: numeric_attribute
        numeric_attribute: {key: duration, min_value: 1000, max_value: 10000}
...
```
