### ISSUE TITLE
[loggingexporter] Does not print anything on the logs pipeline

### ISSUE THREAD

**Issue by carlosjgp** [open-telemetry/opentelemetry-collector#5583]
**Describe the bug**
`logging` exporter does not print anything when used on the `logs` pipeline

**Steps to reproduce**
`my-values.yaml`
```
clusterRole:
  create: true
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    - pods
    - nodes
    verbs:
    - get
    - list
    - watch
config:
  exporters:
    logging/debug:
      loglevel: debug
    logging:
      loglevel: warn
    otlp:
      endpoint: endpoint.company.com:4317
      tls:
        ca_file: /certificates/otel_tls_ca_crt
        cert_file: /certificates/otel_tls_client_crt
        insecure: false
        key_file: /certificates/otel_tls_client_key
  processors:
    k8sattributes:
      auth_type: kubeConfig
      extract:
        labels:
        - from: pod
          key: app.kubernetes.io/version
          tag_name: version
        - from: pod
          key: oaknorth.com/team
          tag_name: team
        metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.pod.start_time
      passthrough: false
      pod_association:
      - from: resource_attribute
        name: ip
      - from: resource_attribute
        name: k8s.pod.ip
      - from: resource_attribute
        name: host.name
      - from: connection
        name: ip
      - from: resource_attribute
        name: k8s.pod.uid
    resource:
      attributes:
      - action: upsert
        key: datadog.organisation
        value: ddorg
      - action: upsert
        key: cluster
        value: cluster-name
      - action: upsert
        key: account_name
        value: name
      - action: upsert
        key: account_id
        value: "111111111111"
    resourcedetection:
      detectors:
      - eks
      - ec2
      - env
      - system
      override: false
      timeout: 5s
  service:
    pipelines:
      logs:
        exporters:
        - otlp
        - logging/debug
        processors:
        - resourcedetection
        - k8sattributes
        - resource
        - memory_limiter
        - batch
        receivers:
        - otlp
      metrics:
        exporters:
        - logging
        processors:
        - resourcedetection
        - k8sattributes
        - resource
        - memory_limiter
        - batch
        receivers:
        - otlp
        - prometheus
      traces:
        exporters:
        - logging
        - otlp
        processors:
        - resourcedetection
        - k8sattributes
        - resource
        - memory_limiter
        - batch
        receivers:
        - otlp
        - jaeger
        - zipkin
    telemetry:
      logs:
        level: warn
containerLogs:
  enabled: true
dnsPolicy: ClusterFirstWithHostNet
extraEnvs: []
extraVolumeMounts:
- mountPath: /certificates
  name: certificates
  readOnly: true
extraVolumes:
- csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: opentelemetry-collector
  name: certificates
fullnameOverride: opentelemetry-collector
hostNetwork: true
mode: daemonset
ports:
  metrics:
    enabled: true
priorityClassName: system-node-critical
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi
securityContext:
  readOnlyRootFilesystem: true
serviceMonitor:
  enabled: true
```
```
helm upgrade --install open-telemetry/opentelemetry-collector --version 0.20.0 -f my-values.yaml
```

**What did you expect to see?**
LogEntries printed including all the attributes and resources. I'm trying to configure Loki exporter correctly

```
(Cluster A              )                 (Cluster B                                             )
OTEL collector Daemonset --> TLS auth --> OTEL collector (receiver) Deployment --> Loki
```

**What did you see instead?**
Nothing printed

**What version did you use?**
`otel/opentelemetry-collector-contrib:0.53.0`

**What config did you use?**
ConfigMap
```
apiVersion: v1
data:
  relay: |
    exporters:
      logging/debug:
        loglevel: debug
      logging:
        loglevel: warn
      otlp:
        endpoint: endpoint.company.com:4317
        tls:
          ca_file: /certificates/otel_tls_ca_crt
          cert_file: /certificates/otel_tls_client_crt
          insecure: false
          key_file: /certificates/otel_tls_client_key
    extensions:
      health_check: {}
      memory_ballast:
        size_mib: "204"
    processors:
      batch: {}
      k8sattributes:
        auth_type: kubeConfig
        extract:
          labels:
          - from: pod
            key: app.kubernetes.io/version
            tag_name: version
          - from: pod
            key: oaknorth.com/team
            tag_name: team
          metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time
        passthrough: false
        pod_association:
        - from: resource_attribute
          name: ip
        - from: resource_attribute
          name: k8s.pod.ip
        - from: resource_attribute
          name: host.name
        - from: connection
          name: ip
        - from: resource_attribute
          name: k8s.pod.uid
      memory_limiter:
        check_interval: 5s
        limit_mib: 409
        spike_limit_mib: 128
      resource:
        attributes:
        - action: upsert
          key: datadog.organisation
          value: ddorg
        - action: upsert
          key: cluster
          value: cluster-name
        - action: upsert
          key: account_name
          value: name
        - action: upsert
          key: account_id
          value: "111111111111"
      resourcedetection:
        detectors:
        - eks
        - ec2
        - env
        - system
        override: false
        timeout: 5s
    receivers:
      filelog:
        exclude:
        - /var/log/pods/observability_opentelemetry-collector*_*/opentelemetry-collector/*.log
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
        - id: get-format
          routes:
          - expr: body matches "^\\{"
            output: parser-docker
          - expr: body matches "^[^ Z]+ "
            output: parser-crio
          - expr: body matches "^[^ Z]+Z"
            output: parser-containerd
          type: router
        - id: parser-crio
          output: extract_metadata_from_filepath
          regex: ^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
          timestamp:
            layout: "2006-01-02T15:04:05.000000000-07:00"
            layout_type: gotime
            parse_from: attributes.time
          type: regex_parser
        - id: parser-containerd
          output: extract_metadata_from_filepath
          regex: ^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) ?(?P<log>.*)$
          timestamp:
            layout: '%Y-%m-%dT%H:%M:%S.%LZ'
            parse_from: attributes.time
          type: regex_parser
        - id: parser-docker
          output: extract_metadata_from_filepath
          timestamp:
            layout: '%Y-%m-%dT%H:%M:%S.%LZ'
            parse_from: attributes.time
          type: json_parser
        - id: extract_metadata_from_filepath
          parse_from: attributes["log.file.path"]
          regex: ^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]{36})\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$
          type: regex_parser
        - from: attributes.stream
          to: attributes["log.iostream"]
          type: move
        - from: attributes.container_name
          to: attributes["k8s.container.name"]
          type: move
        - from: attributes.namespace
          to: attributes["k8s.namespace.name"]
          type: move
        - from: attributes.pod_name
          to: attributes["k8s.pod.name"]
          type: move
        - from: attributes.restart_count
          to: attributes["k8s.container.restart_count"]
          type: move
        - from: attributes.uid
          to: attributes["k8s.pod.uid"]
          type: move
        - from: attributes.log
          to: body
          type: move
        start_at: beginning
      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14268
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888
      zipkin:
        endpoint: 0.0.0.0:9411
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        logs:
          exporters:
          - otlp
          - logging/debug
          processors:
          - resourcedetection
          - k8sattributes
          - resource
          - memory_limiter
          - batch
          receivers:
          - otlp
        metrics:
          exporters:
          - logging
          processors:
          - resourcedetection
          - k8sattributes
          - resource
          - memory_limiter
          - batch
          receivers:
          - otlp
          - prometheus
        traces:
          exporters:
          - otlp
          - logging
          processors:
          - resourcedetection
          - k8sattributes
          - resource
          - memory_limiter
          - batch
          receivers:
          - otlp
          - jaeger
          - zipkin
      telemetry:
        logs:
          level: warn
        metrics:
          address: 0.0.0.0:8888
```

**Environment**
OS: [BottleRocket 1.8.0](https://github.com/bottlerocket-os/bottlerocket)
Cloud: AWS
Flavour: EKS

**Additional context**

**Comment by fatsheep9146** [comment]
You mean 'Nothing printed' is that nothing is printed in stdout of otel-collector?

**Comment by carlosjgp** [comment]
> You mean 'Nothing printed' is that nothing is printed in stdout of otel-collector?

Correct. I wondered if the receiver was not detecting the files correctly so I fiddled around with the path expressions
```
    receivers:
      filelog:
        exclude:
        - /var/log/pods/observability_opentelemetry-collector*_*/opentelemetry-collector/*.log
        include:
        - /var/log/pods/*/*/*.log
```
to `/var/log/containers/*.log` which is the path Fluentbit is currently using, although this is a set of symbolic links to `/var/log/pods` and `telemetry.logs.level: debug` then I get "No files match expression" such error is not shown with the default path `/var/log/pods/*/*/*.log`

Something to note is that FluentBit is running as a privileged container
```
securityContext:
  allowPrivilegeEscalation: true
  privileged: true
  readOnlyRootFilesystem: false
  runAsNonRoot: false
```
whereas OTEL collector is only
```
securityContext:
  readOnlyRootFilesystem: false
```
otherwise, I get "Access denied/File not found errors"

**Comment by djaglowski** [comment]
@carlosjgp, are you sure the `filelog` receiver is in the appropriate pipeline? It is not in the example you provided.

```
    pipelines:
      logs:
        exporters:
        - otlp
        - logging/debug
        processors:
        - resourcedetection
        - k8sattributes
        - resource
        - memory_limiter
        - batch
        receivers:
        - otlp
```
