### ISSUE TITLE
[exporter/logging] Logging exporter logger does not honor telemetry logs configuration

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#5652]
**Describe the bug**

The logging exporter does not honor telemetry logs configuration, since a new logger is created at startup which is completely independent from the Collector's logger.

https://github.com/open-telemetry/opentelemetry-collector/blob/feab9491538a882737a5bceb8757b4458a86edd3/exporter/loggingexporter/factory.go#L87

I am not sure if this was intentional, but it is confusing to me :)

**Steps to reproduce**

Run the Collector with the following configuration:

```
receivers:
  hostmetrics:
    scrapers:
      load:
    collection_interval: 3s

exporters:
  logging:
    loglevel: debug

service:
  telemetry:
    logs:
      output_paths: [example.log]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [logging]
```

**What did you expect to see?**

I expected logging exporter logs to be logged to the `example.log` file, as this is where the rest of components will log.

**What did you see instead?**

All logs but the logging exporter's are logged to `example.log`. The logging exporter logs are logged to stderr.

**What version did you use?**
Version: v0.55.0

**Additional context**

This also makes this exporter less useful on context where the Collector is used as a library, since you effectively can't control where the logging exporter outputs.
 
This can be easily fixed if we take the core from the main logger and build a new core with sampling options to it, using [`zapcore.NewSamplingWithOptions`](https://pkg.go.dev/go.uber.org/zap/zapcore#NewSamplerWithOptions). The level can also be managed with `zapcore.NewIncreaseLevelCore`, although in this case we lose the possibility of having a lower log level on the logging exporter than in the global one (IMO that's fine so long as we have a descriptive error).
