### ISSUE TITLE
[Telemetry] Collector telemetry not including opencensus metrics along with internal metrics when feature flag useOtelForInternalMetrics is true

### ISSUE THREAD

**Issue by timannguyen** [open-telemetry/opentelemetry-collector#5687]
**Describe the bug**
using flag --feature-gates=telemetry.useOtelForInternalMetrics using [demo](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo) or through 

```go
featuregate.Apply(map[string]bool{
	"telemetry.useOtelForInternalMetrics": true,
})
```

, calling http://localhost:8888/metrics does not displays the metrics mentioned in[ monitoring documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/monitoring.md).

**Steps to reproduce**

1. set config yaml with below or through code, set the config map service::telemetry::metrics::address: ":8888"

```yaml
service:
  telemetry:
    metrics:
      address: ":8888"
```

3. set flag with --feature-gates=telemetry.useOtelForInternalMetrics or in code set telemetry.useOtelForInternalMetrics  to true in featuregate.
4.  go to http://localhost:8888/metrics
5. it will return empty 200 or if any metrics was set through featuregate, only those are shown. Ones from [ monitoring documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/monitoring.md) does not appear.

**What did you expect to see?**

I expected metrics from [ monitoring documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/monitoring.md) and any internal metrics added using otel metrics sdk.

EXAMPLE: 

```txt
# HELP otelcol_exporter_enqueue_failed_log_records Number of log records failed to be added to the sending queue.
# TYPE otelcol_exporter_enqueue_failed_log_records counter
otelcol_exporter_enqueue_failed_log_records{exporter="jaeger",service_instance_id="71249946-a6bd-4e88-86e3-6c310b093c54",service_version="latest"} 0
otelcol_exporter_enqueue_failed_log_records{exporter="logging",service_instance_id="71249946-a6bd-4e88-86e3-6c310b093c54",service_version="latest"} 0
otelcol_exporter_enqueue_failed_log_records{exporter="prometheus",service_instance_id="71249946-a6bd-4e88-86e3-6c310b093c54",service_version="latest"} 0
otelcol_exporter_enqueue_failed_log_records{exporter="zipkin",service_instance_id="71249946-a6bd-4e88-86e3-6c310b093c54",service_version="latest"} 0
...
...
# TYPE my_metrics counter
my_metrics(tags="foo",tags="bar") 0
...
...
```

**What did you see instead?**

empty 200 response 

OR 

```
# TYPE my_metrics counter
my_metrics(tags="foo",tags="bar") 0
...
```

**What version did you use?**
demo: docker image : (`fb056cba11cd`)
code: Version: (`v0.48.0`)

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  logging:

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  telemetry:
    metrics:
      address: ":8888"
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]

```

**Environment**
OS: (e.g., "M1 MAC")
Docker

Edit: define featuregate calls
Edit2: formatting
