### ISSUE TITLE
prometheus translator: multiple target metric might be emitted if gropubyattrs processor is involved

### ISSUE THREAD

**Issue by newly12** [open-telemetry/opentelemetry-collector#5688]
**Describe the bug**
Given a metrics pipeline like `prometheus` receiver -> `groupbyattrs` processor -> `prometheusremotewrite` exporter, since groupbyattrs sort of splits the `pmetric.Metrics` to multiple `pmetric.Metrics` and in `prometheusremotewrite` exporter, the translator [adds](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/pkg/translator/prometheusremotewrite/metrics_to_prw.go#L103) resource target info(the `target` metric) for every `pmetric.Metrics`, which turns out eventually we got multiple `target` metric, see additional context part for more details for our use case.

**Steps to reproduce**
give a simple metrics like
```
# HELP m
# TYPE m gauge
m{a="a", n="1"} 0
m{a="a", n="2"} 0 
m{a="b", n="1"} 0
m{a="b", n="2"} 0
```
and a config
```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: kubernetes-cadvisor-metrics
          metrics_path: /metrics.txt
          static_configs:
            - targets:
                - localhost:8000

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:8428/api/v1/write

processors:
  batch:

  groupbyattrs:
    keys:
      - a

service:
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      address: 127.0.0.1:8888
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, groupbyattrs]
      exporters: [ prometheusremotewrite ]
```

![image](https://user-images.githubusercontent.com/14903757/179158892-d18988f4-633b-41ce-a2aa-aabd446e9133.png)

**What did you expect to see?**
Just one target metric for a scrape target.

**What did you see instead?**
Multiple target metrics.

**What version did you use?**
Version: v0.55.0

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
The reason we need groupbyattrs is that we are collecting cadvisor metrics and enrich them with additional pod info, to do so we group metrics by `namespace` and `pod` name, then follow by a `k8sattributes` processor as it only supports enrichment based on resources, not metric attributes currently, and probably more efficient as enrich multiple metrics multiple times seems to be more expensive than group multiple metrics by 2 attributes.

```yaml
      resource/copy:
        attributes:
          - key: k8s.namespace.name
            from_attribute: namespace
            action: insert
          - key: k8s.pod.name
            from_attribute: pod
            action: insert

      k8sattributes:
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.namespace.name
              - from: resource_attribute
                name: k8s.pod.name

```
