### ISSUE TITLE
Add config correctness validation

### ISSUE THREAD

**Issue by olagacek** [open-telemetry/opentelemetry-collector#583]
Recently I discovered that it is possible to misconfigure prometheus receiver and there will be no runtime errors. Sample incorrect configuration:

```yaml
receivers:
   prometheus:
    config:
      use_start_time_metric: true
      scrape_configs:
```

There was no error when loading configuration indicating that use_start_time_metric was in incorrect place, I think that there should be some error saying that `config` field had some extra, unused arguments.
