### ISSUE TITLE
Collector metrics OpenCensus receiver question

### ISSUE THREAD

**Issue by hectorhdzg** [open-telemetry/opentelemetry-collector#586]
I'm working on Python exporter for Collector Metrics, I'm using grpc and getting following error when trying to send data, currently hitting localhost:55678 do I need to use a different URL?

details:'unknown service opencensus.proto.agent.metrics.v1.MetricsService'

Collector config

receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  logging: {}

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [opencensus]
      exporters: [logging]
      processors: [batch, queued_retry]

**Comment by pjanotti** [comment]
hi @hectorhdzg - you need to create a metrics pipeline, (warning hand compiled):
```yaml
receivers:
  opencensus:
    endpoint: "0.0.0.0:55678"

exporters:
  logging: {}
  # suggestion use prometheus too since you are testing metrics
  prometheus:
    endpoint: "0.0.0.0:8890"

service:
  pipelines:
    metrics:
      receivers: [opencensus]
      exporters: [logging, prometheus]
```
