### ISSUE TITLE
[pdata.Map] InsertStringValue causes high memory usage

### ISSUE THREAD

**Issue by MovieStoreGuy** [open-telemetry/opentelemetry-collector#5958]
**Describe the bug**
Configuring a custom distro of the open collector contrib, we have seen a high amount of memory usage with `value.setStringValue` which has caused our migration from our previous telemetry agent (The SignalFx smart agent) to stall.

**What did we see**
[heap.txt](https://github.com/open-telemetry/opentelemetry-collector/files/9411600/heap.txt)

I've attached a heap profile from our running distro of the collector and roughly experience 3x the amount of memory compared to what the smart agent would consume.

**What version did you use?**
We were using the v0.56.0 of the collector contrib which I believe imports the same version of the collector.

**What config did you use?**
Config:

```yaml
exporters:
  promethues:
   ...
processes:
  metricstransformer:
   ...

exporters:
  signalfx:
   ...
```

**Environment**
OS: Debian like docker container
Compiler(if manually compiled): go1.18.4

**Additional context**
Looking through the profile, i believe it is a problem that strings are considered immutable and cause a copy on each stack created thus seeing an increase in memory usage compared to what we are expecting.

You should be able to examine the heap profile using the provided go tools:
`go tool pprof --http=:8080 heap.txt`

**Comment by MovieStoreGuy** [comment]
@bogdandrutu let me find more information for, in the case I am more a middleman so I will get all those details for you.

Our previous agent was the SignalFx smart agent in a near like for like configuration.
The memory being consumed from the smart agent was ~50MiB with the collector reaching ~260MiB, we are simply reading the memory used from the docker stats for this running within k8s. I believe this was running on one of our test clusters so the expected throughput is fairly small and static which is where I believe the heap profile was taken from.

```yaml
 receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'prom-local'
            scrape_interval: 30s
            static_configs:
            - targets:
              - redacted
              labels:
                redacted
          - job_name: 'prom-aggregator'
            scrape_interval: 30s
            metrics_path: '/federate'
            params:
              'match[]':
              - redacted
            static_configs:
            - targets:
              - redacted
              labels:
                metric_source: prometheus
            relabel_configs:
            - action: keep
              source_labels: [ __name__ ]
              regex: 'redacted'

    processors:
      metricstransform:
        # 7x calls to add additional labels to all metrics

    exporters:
      signalfx:
    extensions:
      pprof:

    service:
      extensions: ['pprof']
      pipelines:
        metrics:
          receivers:
          - prometheus
          processors:
          - metricstransform
          exporters:
          - signalfx
```
