### ISSUE TITLE
[request help]some questions about collector performance test

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-collector#5961]
I read the doc about performance from [this link](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/performance.md), and i tried to reproduce the result. So i start a collector in k8s with 1c 2gi, and start the load test.

I used a simple config:
```
receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      logging:
        loglevel: info

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [logging]
        logs:
          receivers: [otlp]
          exporters: [logging]
```

and set the submission rate to 100000 spans per second.

When the test starts, i tried to observe the metrics from localhost:8888.I found the number of the `otelcol_receiver_accepted_spans` grows too fast. (About 50000 spans per second , larger than 12k) And when the usage of the cpu and memory is also strange:
```
[root@vm5 load-test]# kubectl top pod -n otel otel-collector-7b6f65ffcd-jhbk9
NAME                              CPU(cores)   MEMORY(bytes)
otel-collector-7b6f65ffcd-jhbk9   112m          54Mi
```

The uasge seems too low!

Did i make some mistake? Or the load test is not starting in a correct way?
