### ISSUE TITLE
OpenTelemetry HTTP Exporter unequal traffic to backend

### ISSUE THREAD

**Issue by LeonD9** [open-telemetry/opentelemetry-collector#5964]
I am connecting via OTLPHTTP Exporter to grafana tempo cluster service that contains 5 pods:
```
exporters:
  otlphttp:
    endpoint: http://tempo.kube-system.svc.cluster.local:4318
    tls:
      insecure: true
      insecure_skip_verify: true
    timeout: 10s
```
It seems that some backend pods get more traffic than the others which causes them to get OOM.
Is there a way to split traffic more equally between the backend endpoints? to avoid traffic overloading specific pods

**Comment by jpkrohling** [comment]
When using a regular Kubernetes service as the host, the HTTP client will resolve the IPs and typically use the first from the DNS query. Only upon failure will another IP be selected. One solution is to use Kubernetes' load balancing alternatives. When using gRPC, it's possible to use client-side load balancing when the endpoint is set to something like `dns:///tempo.kube-system.svc.cluster.local:4317`, but I'm not sure Tempo supports gRPC (cc @mapno, @kvrhdn ).

**Comment by LeonD9** [comment]
> When using a regular Kubernetes service as the host, the HTTP client will resolve the IPs and typically use the first from the DNS query. Only upon failure will another IP be selected. One solution is to use Kubernetes' load balancing alternatives. When using gRPC, it's possible to use client-side load balancing when the endpoint is set to something like `dns:///tempo.kube-system.svc.cluster.local:4317`, but I'm not sure Tempo supports gRPC (cc @mapno, @kvrhdn ).

As far as i know tempo does support gRPC, 
I tried using the following configuration:
```
exporters:
  otlp/tempo:
    endpoint: tempo.kube-system.svc.cluster.local:4317
    tls:
      insecure: true
      insecure_skip_verify: true
  logging:
    loglevel: debug
```
and had the same issue with traffic balancing, @jpkrohling can i use this `dns:///tempo.kube-system.svc.cluster.local:4317` as endpoint with gRPC service and it will balance the traffic?

**Comment by jpkrohling** [comment]
Yes, it should.

**Comment by LeonD9** [comment]
Hey @jpkrohling ,
I changed to `dns:///tempo-headless.kube-system.svc.cluster.local:4317` and i see it detects all pods but the lb policy is still:
`2022-08-28T07:38:57.423Z	info	zapgrpc/zapgrpc.go:174	[core] [Channel #1] Channel switches to new LB policy "pick_first"	{"grpc_log": true}`
how can i change it to `round_robin`?

**Comment by LeonD9** [comment]
When using the following config:
```
exporters:
  otlp/tempo:
    endpoint: dns:///tempo-headless.kube-system.svc.cluster.local:4317
    tls:
      insecure: true
      insecure_skip_verify: true
    balancer_name: "round_robin"
 ```
 The traffic still seems to be unequal:
 
![image](https://user-images.githubusercontent.com/86968998/187069213-54957482-5a84-4c94-a59c-cb64cb1d8cc7.png)

two pods receive more traffic then the others for some reason.
