### ISSUE TITLE
regex_parser: resource cannot be referenced without subfield

### ISSUE THREAD

**Issue by shushenghong** [open-telemetry/opentelemetry-collector#6028]
**Describe the bug**
regex_parser: resource cannot be referenced without subfield

**Steps to reproduce**
```
operators:
      - type: regex_parser
        parse_from: attributes["log.file.path"]
        parse_to: resource
        regex: 'vcslogs/(?P<service>.+?)/'
```

**What did you expect to see?**
set resource.service

**What did you see instead?**
regex_parser: resource cannot be referenced without subfield

I have to set `parse_to: resource.xxx`, and the `service` will be a property of `xxx`, and i want the `service` be a property of `resource`
