### ISSUE TITLE
Regex is not matching with utf-16le

### ISSUE THREAD

**Issue by saikalyan-bhagavathula** [open-telemetry/opentelemetry-collector#6211]
**Describe the bug**
When I give the **utf16-le** encoded files to **ocb** all the log statements from the file are appending to a single line even I gave the multiline option.

**Steps to reproduce**
By just giving the **utf16-le** encoded files to **ocb** .

**What did you expect to see?**
Every Log Statement is splitting as the new one.

**What did you see instead?**
All the log statements from the file are appending to a single line even I gave the multiline option.

**What version did you use?**
Version: 0.61.0

**What config did you use?**
Config: 
```
receivers:
  filelog:
    include:
      - "E:\\mssql\\MSSQL15.SQLEXPRESS\\MSSQL\\Log\\ERRORLOG"
    start_at: beginning
    multiline:
      line_start_pattern: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{2})'
    operators:
      - type: regex_parser
        regex: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{2})\s*(?P<server>\w*)\s*(?P<message>.*)$'
        timestamp:
          parse_from: attributes.timestamp
          layout_type: gotime
          layout: "2006-01-02 15:04:05.00"
processors:
exporters:
  otlp:
    endpoint: "localhost:50052"
    tls:
      insecure: true
      insecure_skip_verify: true
    compression: none
    headers:
      - collector: "otlp-collector"
      - authorization: ""
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: []
      exporters: [otlp]

```
**Environment**
OS: Windows 10
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
