### ISSUE TITLE
Prometheus exporter failing with 'tls' has invalid keys: insecure

### ISSUE THREAD

**Issue by gabrielgiussi** [open-telemetry/opentelemetry-collector#6229]
**Describe the bug**
I'm getting an error trying to disable tls in prometheus metrics exporter
```
2022-10-04 12:55:55.652865 I | collector server run finished with error: failed to get config: cannot unmarshal the configuration: error reading exporters configuration for "prometheus": 1 error(s) decoding:

* 'tls' has invalid keys: insecure
```

I've also tested putting insecure in the root of the prometheus configuration but was failing with `'' has invalid keys: insecure`.

**What version did you use?**
Both opentelemetry-collector-contrib and opentelemetry-collector images in version 0.61.0

**What config did you use?**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
    exporters:
      prometheus:
        endpoint: "0.0.0.0:4318"
        tls:
          insecure: true
        namespace: test-space
        const_labels:
          label1: value1
          "another label": spaced value
        send_timestamps: true
        metric_expiration: 180m
        enable_open_metrics: true
        resource_to_telemetry_conversion:
          enabled: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [prometheus]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetrycollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetrycollector
    spec:
      containers:
        - name: otelcol
          args:
            - --config=/conf/collector.yaml
          image: otel/opentelemetry-collector:0.61.0
          volumeMounts:
            - mountPath: /conf
              name: collector-config
      volumes:
        - configMap:
            items:
              - key: collector.yaml
                path: collector.yaml
            name: collector-config
          name: collector-config          
```

**Additional context**
Related issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5377
