### ISSUE TITLE
Allow components access to config

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opentelemetry-collector#6254]
Using slightly different variations of the same exporter in two pipelines results in having to duplicate config between them if consistent behaviour is desired. It would be nice if it would be possible to either a) have a shared configuration section or b) allow one exporter to access the configuration of the other, perhaps only the ones of the same type. Alternatively, one idea would be to give components access to the full config.

For example, let's assume that the `my_exporter` exporter is set up to export traces to a certain endpoint with a given API key, and additionally add two tags, all of which is set via configuration. Then, a separate pipeline, for all traces, should do the same thing except also filter out some traces based on a criteria. This results in the following configuration:

```yaml
receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
  probabilistic_sampler:
    sampling_percentage: 10

exporters:
  my_exporter:
    add_tags:
      - a:b
      - c:d
    api:
      key: c8ecxasd1b783b123rd87a96431da

  my_exporter/filter:
    filter_metrics:
      - containing: *.grpc.*
    # duplicate my_exporter here for consistent behaviour
    add_tags:
      - a:b
      - c:d
    api:
      key: c8ecxasd1b783b123rd87a96431da

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, probabilistic_sampler]
      exporters: [my_exporter]
    traces/stats:
      receivers: [otlp]
      processors: [batch]
      exporters: [my_exporter/filter]
```
This is a dumb example which obviously could result in duplicate traces, but i hope it illustrates the problem.

This results in duplicating the configuration in the latter exporter. Could we maybe have a centralised exporter configuration, or add API into the components that allow the latter exporter to read the config from the former under the hood?

Is this something that has been looked into? Is there interest in such a feature? I am happy to provide proposals to resolve this if so, and even contribute it myself.

**Comment by bogdandrutu** [comment]
Can you please write the config that you have in mind? I am a bit confused, since right now you can definitely use one exporter in multiple pipelines (but is the same instance correct). Is your request to have multiple instances of the same exporter with same config?

**Comment by bogdandrutu** [comment]
So please write the current situation "with the duplicate code" to understand what is the "duplication" there, thanks a lot for the report.

**Comment by gbbr** [comment]
Thanks for the prompt reply Bogdan. Apologies if I was too ambiguous of vague. I guess I had the context in my mind and thought it was going to be obvious. I updated the description. I wonder if it makes more sense now.

**Comment by bogdandrutu** [comment]
can you look into this new feature https://github.com/open-telemetry/opentelemetry-collector/pull/6276, maybe something can be used here, by having a separate file with the common config and embed that?

**Comment by gbbr** [comment]
That's a really nice feature! I just tried it out and it works, but unfortunately not for this use case because it is bound to being a value. For my use case it would only work if the feature would be allowed in this form:
```yaml
...
exporters:
  my_exporter:
    ${file:/path/to/file}
    api:
      key: c8ecxasd1b783b123rd87a96431da
...
```
The current implementation is cool, but it doesn't allow slight modifications and overriding. I do realise it's a much more complicated implementation, but happy to help if others find value in this proposal.

**Comment by bogdandrutu** [comment]
@gbbr let's continue the discussion here, so what do you want to have in the `/path/to/my_exporter/shared/settings.yaml`? Can you put both yaml files here so I can understand a bit more. The indentation you have there suggests that the result is merged into "my_exporter", is that the case?

**Comment by gbbr** [comment]
Absolutely!

Given the configuration file:
```yaml
# ...
exporters:
  my_exporter:
    ${file:/path/to/my_exporter/shared/settings.yaml}

  my_exporter/filter:
    filter_metrics:
      - containing: *.grpc.*
    ${file:/path/to/my_exporter/shared/settings.yaml}
# ...
```
Where `/path/to/my_exporter/shared/settings.yaml` contains:
```yaml
add_tags:
  - a:b
  - c:d
api:
  key: c8ecxasd1b783b123rd87a96431da
```
The compilation result becomes:
```yaml
# ...
exporters:
  my_exporter:
    add_tags:
      - a:b
      - c:d
    api:
      key: c8ecxasd1b783b123rd87a96431da

  my_exporter/filter:
    filter_metrics:
      - containing: *.grpc.*
    add_tags:
      - a:b
      - c:d
    api:
      key: c8ecxasd1b783b123rd87a96431da
# ...
```
Technically the indentation of the "file import statement" (`${file:/path/to/my_exporter/shared/settings.yaml}`) is applied to the embedded content.

This style allows for more complex embedding. The current implementation only works if the full contents of a YAML property need to be replaced. It does not allow varying adjacent properties.

**Comment by bogdandrutu** [comment]
One of my main rule of thumb was to keep the syntax "yaml" compliant, a.k.a to ensure that the result is yaml compliant to allow editors to highlight the configuration, etc.

Unfortunately I think this is not yaml compliant, the `my_exporter/filter` part:
```yaml
# ...
exporters:
  my_exporter:
    ${file:/path/to/my_exporter/shared/settings.yaml}

  my_exporter/filter:
    filter_metrics:
      - containing: "*.grpc.*"
    ${file:/path/to/my_exporter/shared/settings.yaml}
# ...
```

An option is to have a "reserved" key `__from__` (and idea is that everything in that map overrides the `__from__`), that we can use:
```yaml
# ...
exporters:
  my_exporter:
    __from__: ${file:/path/to/my_exporter/shared/settings.yaml}

  my_exporter/filter:
    __from__: ${file:/path/to/my_exporter/shared/settings.yaml}
    filter_metrics:
      - containing: "*.grpc.*"
# ...
```

**Comment by gbbr** [comment]
> One of my main rule of thumb was to keep the syntax "yaml" compliant, a.k.a to ensure that the result is yaml compliant to allow editors to highlight the configuration, etc.

True, I did not consider that. It will also allow `gopkg.in/yaml.v3` to unmarshal it.

> An option is to have a "reserved" key __from__ (and idea is that everything in that map overrides the __from__), that we can use [...]

I think that's a good idea. I have another proposal which is also YAML compliant:
```yaml
# ...
exporters:
  my_exporter:
    ${file:/path/to/my_exporter/shared/settings.yaml}:

  my_exporter/filter:
    ${file:/path/to/my_exporter/shared/settings.yaml}:
    filter_metrics:
      - containing: "*.grpc.*"
# ...
```
By simply adding a colon at the end, it becomes valid yaml. It avoids the need for a new reserved key and is arguably more intuitive because it lives at the level where it expands.

Although, I'm not sure how this plays out rationally in conjunction with the other usage that we currently have as a key.

I'd be ok with any of the two.

**Comment by bogdandrutu** [comment]
Or we make it a programming language 🥇 

```yaml
  ${extend:${/path/to/my_exporter/shared/settings.yaml}:my_exporter/filter}:
    filter_metrics:
      - containing: "*.grpc.*"
```
