### ISSUE TITLE
Proto mismatch errors not obvious when posting traces

### ISSUE THREAD

**Issue by Pitta** [open-telemetry/opentelemetry-collector#6320]
**Describe the bug**
When sending test traces via `otlp-http`, if the format of the trace is mismatched the server still returns a 200 with no indication of a problem.

```bash
$ curl -i http://localhost:4318/v1/traces -X POST -H "Content-Type: application/json" -d @trace.json

HTTP/1.1 200 OK
Content-Type: application/json
Date: Sat, 15 Oct 2022 00:30:09 GMT
Content-Length: 2

{}
```

**Steps to reproduce**
config: _BELOW_

docker-compose.yaml:
```yaml
version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.60.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "13133:13133" # Health Check
```

trace.json ([from this example](https://docs.lightstep.com/otel/send-otlp-over-http-to-lightstep))
```
{
  "resourceSpans": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "curl-test-otel-pipeline"
            }
          }
        ]
      },
      "instrumentationLibrarySpans": [
        {
          "spans": [
            {
              "traceId": "71699b6fe85982c7c8995ea3d9c95df2",
              "spanId": "3c191d03fa8be065",
              "name": "test-span",
              "kind": 1,
              "droppedAttributesCount": 0,
              "events": [],
              "droppedEventsCount": 0,
              "status": {
                "code": 1
              }
            }
          ],
          "instrumentationLibrary": {
            "name": "local-curl-example"
          }
        }
      ]
    }
  ]
 }
```

1. `docker compose up`
2. from another terminal `curl -i http://localhost:4318/v1/traces -X POST -H "Content-Type: application/json" -d @trace.json`

**What did you expect to see?**
A 200 response if the trace data was 👍
Anything else with a message mentioning the proto mistmatch

**What did you see instead?**
```bash
$ curl -i http://localhost:4318/v1/traces -X POST -H "Content-Type: application/json" -d @trace.json

HTTP/1.1 200 OK
Content-Type: application/json
Date: Sat, 15 Oct 2022 00:30:09 GMT
Content-Length: 2

{}
```

**What version did you use?**
Version: `0.60.0`

**What config did you use?**
```yaml
exporters:
  logging:

extensions:
  health_check: {}
  memory_ballast: {}

processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_mib: 409
    spike_limit_mib: 128

receivers:
  otlp:
    protocols:
      grpc:
      http:

service:
  extensions:
  - health_check
  - memory_ballast
  pipelines:
    traces:
      exporters:
      - logging
      - otlp
      processors:
      - memory_limiter
      - batch
      receivers:
      - otlp
  telemetry:
    logs:
      level: "debug"
```
