### ISSUE TITLE
OTEL_RESOURCE_ATTRIBUTES not adding tags

### ISSUE THREAD

**Issue by pseymournutanix** [open-telemetry/opentelemetry-collector#6478]
I am trying to add tags to each span via the collector (istio via zipkin)before sending upstream to jaeger/tempo etc.

I am setting this in my collector:-
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry
spec:
...
  env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: cluster=services
```

I can see the environment vars in the pod created via the operator but the tags never show up. Have I done something wrong or misinterpreted use ? Just trying to get unique identifiers per collector before sending to central UI.

Images used are:
`opentelemetry-operator:v0.61.0` & `otel/opentelemetry-collector-contrib:0.62.1`

Thanks.
