### ISSUE TITLE
otelcol_exporter_send_failed_spans metric does not get exposed

### ISSUE THREAD

**Issue by Allex1** [open-telemetry/opentelemetry-collector#6509]
**Describe the bug**
`otelcol_exporter_send_failed_spans` metric is not reported even when spans fail to be sent to the backend (Jaeger), even though it's referenced in the [docs](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/monitoring.md#data-loss)  and in https://github.com/open-telemetry/opentelemetry-collector/issues/6162

**Steps to reproduce**
messed up the dns intentionally : 
```2022-11-09T07:45:27.171Z	info	exporterhelper/queued_retry.go:427	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "error": "failed to push trace data via Jaeger exporter: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup xxx.xxx.xxx on 192.168.0.2:53: no such host\"", "interval": "32.615183573s"}```
and then messed up auth :
```2022-11-09T08:02:52.678Z	info	exporterhelper/queued_retry.go:427	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "error": "failed to push trace data via Jaeger exporter: rpc error: code = Unknown desc = authentication failed", "interval": "4.821630717s"}```
**What did you expect to see?**
the metric `otelcol_exporter_send_failed_spans` being created and increasing as no spans are being exported
<img width="1777" alt="Screenshot 2022-11-09 at 10 05 30" src="https://user-images.githubusercontent.com/8087146/200773641-cbf71355-75bf-44a1-ac5c-db7f91ca0dfb.png">

In contrast for the same testing `otelcol_exporter_send_failed_metric_points` does show up and increasing
<img width="1393" alt="Screenshot 2022-11-09 at 10 07 15" src="https://user-images.githubusercontent.com/8087146/200773923-eb86faf3-da4a-4d18-91e4-61ea4277d9fe.png">

**What did you see instead?**
no `otelcol_exporter_send_failed_spans` exposed on the monitoring endpoint:8888 

**What version did you use?**
Version: 0.62.1

**What config did you use?**
```
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"
    extensions:
      health_check: {}
    processors:
      batch: {}
      memory_limiter: {}
    exporters:
      jaeger:
        endpoint: "xxx.xxx.xxx"
        headers:
          Authorization: "Bearer JaegerID:SuperSecret" 
        timeout: "30s"
      logging:
        loglevel: "info"
    service:
      extensions:
        - "health_check"
      pipelines:
        traces:
          receivers:
            - "otlp"
          processors:
            - "memory_limiter"
            - "batch"
          exporters:
            - "logging"
            - "jaeger"
      telemetry:
        metrics:
          address: 0.0.0.0:8888
```

**Environment**
Kubernetes 1.22

**Additional context**
