### ISSUE TITLE
more than 2 config files not supported

### ISSUE THREAD

**Issue by BenWa67** [open-telemetry/opentelemetry-collector#6515]
**Describe the bug**
I would like to have multiples config files ( more than 2 )  for my open telemetry collector 

**Steps to reproduce**
i tried to launch my open telemetry like this
`otelcol-contrib.exe --config=file:C:/Install/Observability/otel/base.yml --config=file:C:/Install/Observability/otel/config2.yml --config=file:C:/GE_Install/Observability/otel/config3.yml`

**What did you expect to see?**
The 3 configurations files been merged 

**What did you see instead?**
base and config3 merged but config2 not take into account

**What version did you use?**
Version: v0.62.1 of open telemetry contrib

**What config did you use?**
base.yml
```yaml
receivers:
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
      processes:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true
service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: []
      exporters: [prometheus]
```
config2.yml
```yaml
receivers:
  prometheus/2:
    config:
      scrape_configs:
 (...)
service:
  pipelines:
    metrics:
      receivers: [prometheus/2]
      processors: []
      exporters: [prometheus]
```

config3.yml
```yaml
receivers:
  prometheus/3:
    config:
      scrape_configs:
 (...)
service:
  pipelines:
    metrics:
      receivers: [prometheus/3]
      processors: []
      exporters: [prometheus]
```

**Environment**
OS: Windows Server 2022

**Comment by bogdandrutu** [comment]
Working as intended since in all files you defined the same "pipeline" ("metrics") which by the merge rule will overwrite the previous config, so the final result will be:

```yaml
service:
  pipelines:
    metrics:
      receivers: [prometheus/3]
      processors: []
      exporters: [prometheus]
```

If you want them to be independent pipelines and not overwrite pipelines, give them different names:

base.yaml:
```yaml
service:
  pipelines:
    metrics/base:
      receivers: [hostmetrics]
      processors: []
      exporters: [prometheus]
```

config2.yml
```yaml
service:
  pipelines:
    metrics/2:
      receivers: [hostmetrics/2]
      processors: []
      exporters: [prometheus]
```

config3.yml
```yaml
service:
  pipelines:
    metrics/3:
      receivers: [hostmetrics/3]
      processors: []
      exporters: [prometheus]
```
