### ISSUE TITLE
When using the `daemonset` mode, the services that are created by the controller should use `internalTrafficPolicy: Local`

### ISSUE THREAD

**Issue by dlydiard** [open-telemetry/opentelemetry-collector#6573]
When using the `daemonset` mode, the services that are created by the controller should use `internalTrafficPolicy: Local` so that network traffic routing is optimal.

Using 
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  ...
spec:
  mode: daemonset
  hostNetwork: false
```

Results in a `Service`
```
kind: Service
apiVersion: v1
metadata:
  ...
spec:
  ...
  internalTrafficPolicy: Cluster
```

`internalTrafficPolicy: Cluster` should be `internalTrafficPolicy: Local` when in the `daemonset` mode.
