### ISSUE TITLE
V0.62.0+ breaks environment variables in config file

### ISSUE THREAD

**Issue by HaroonSaid** [open-telemetry/opentelemetry-collector#6580]
**Describe the bug**
We have the following in the yaml config file 

```
exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: :8889
  jaeger:
    endpoint: ${JAEGER_ENDPOINT}:${JAEGER_PORT}
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: ${PROMETHEUSREMOTEWRITE}
```

and pass in the values thru environment variables 

**Steps to reproduce**
Starting with `0.62.0` that no longer works

```
Error: failed to get config: cannot resolve the configuration: invalid uri: "JAEGER_ENDPOINT}:${JAEGER_PORT"
2022/11/19 19:12:22 collector server run finished with error: failed to get config: cannot resolve the configuration: invalid uri: "JAEGER_ENDPOINT}:${JAEGER_PORT"
```

**What did you expect to see?**
Should continue work.

**What did you see instead?**

**What version did you use?**
Version: 0.62+

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
