### ISSUE TITLE
v0.64.1 builder fails with errors related to deprecations in v0.65.0 release

### ISSUE THREAD

**Issue by samanthawalter** [open-telemetry/opentelemetry-collector#6621]
**Describe the bug**
Without any changes to configuration or custom components, the v0.64.1 builder started failing after the v0.65.0 release with errors related to deprecations in the v0.65.0 release. I would expect that new releases do not affect previous releases.

**Steps to reproduce**
Attempt to run v0.64.1 of the builder with the following config.yaml.
```yaml
dist:
  module: github.com/my-organization/opentelemetry-collector-custom
  otelcol_version: "0.64.1"
  output_path: bin
exporters:
  - import: "go.opentelemetry.io/collector/exporter/loggingexporter"
    gomod: "go.opentelemetry.io/collector v0.64.1"
  - import: "go.opentelemetry.io/collector/exporter/otlpexporter"
    gomod: "go.opentelemetry.io/collector v0.64.1"
  - import: "go.opentelemetry.io/collector/exporter/otlphttpexporter"
    gomod: "go.opentelemetry.io/collector v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/zipkinexporter v0.64.0"
extensions:
  - import: "go.opentelemetry.io/collector/extension/ballastextension"
    gomod: "go.opentelemetry.io/collector/extension/ballastextension v0.64.1"
  - import: "go.opentelemetry.io/collector/extension/zpagesextension"
    gomod: "go.opentelemetry.io/collector/extension/zpagesextension v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.64.0"
processors:
  - import: "go.opentelemetry.io/collector/processor/batchprocessor"
    gomod: "go.opentelemetry.io/collector/processor/batchprocessor v0.64.1"
  - import: "go.opentelemetry.io/collector/processor/memorylimiterprocessor"
    gomod: "go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.64.0"
receivers:
  - import: "go.opentelemetry.io/collector/receiver/otlpreceiver"
    gomod: "go.opentelemetry.io/collector/receiver/otlpreceiver v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureeventhubreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.64.0"
```

**What did you expect to see?**
Successful build

**What did you see instead?**
Replaced `\n` with newlines for readability
```
Error: failed to compile the OpenTelemetry Collector distribution: exit status 2. Output: "
# github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_label.go:25:2: unknown field 'ID' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_label.go:26:2: unknown field 'Enabled' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_label.go:27:2: unknown field 'Description' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_label.go:31:28: featuregate.GetRegistry().MustRegister undefined (type *featuregate.Registry has no field or method MustRegister)
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_name.go:86:2: unknown field 'ID' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_name.go:87:2: unknown field 'Enabled' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_name.go:88:2: unknown field 'Description' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/pkg/translator/prometheus@v0.64.0/normalize_name.go:93:28: featuregate.GetRegistry().MustRegister undefined (type *featuregate.Registry has no field or method MustRegister)
# github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor@v0.64.0/processor.go:32:2: unknown field 'ID' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor@v0.64.0/processor.go:33:2: unknown field 'Enabled' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor@v0.64.0/processor.go:34:2: unknown field 'Description' in struct literal of type featuregate.Gate
/home/samantha/go/pkg/mod/github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor@v0.64.0/processor.go:38:28: featuregate.GetRegistry().MustRegister undefined (type *featuregate.Registry has no field or method MustRegister)
# github.com/jaegertracing/jaeger/cmd/collector/app/handler
/home/samantha/go/pkg/mod/github.com/jaegertracing/jaeger@v1.39.0/cmd/collector/app/handler/otlp_receiver.go:69:14: undefined: config.Receiver
/home/samantha/go/pkg/mod/github.com/jaegertracing/jaeger@v1.39.0/cmd/collector/app/handler/otlp_receiver.go:184:56: undefined: config.Type
/home/samantha/go/pkg/mod/github.com/jaegertracing/jaeger@v1.39.0/cmd/collector/app/handler/otlp_receiver.go:188:45: undefined: config.ComponentID
/home/samantha/go/pkg/mod/github.com/jaegertracing/jaeger@v1.39.0/cmd/collector/app/handler/otlp_receiver.go:192:44: undefined: config.DataType
/home/samantha/go/pkg/mod/github.com/jaegertracing/jaeger@v1.39.0/cmd/collector/app/handler/otlp_receiver.go:192:64: undefined: config.ComponentID
"
```

**What version did you use?**
Version: `v0.64.1`

**What config did you use?**
See steps to reproduce section above

**Environment**
linux amd64

**Additional context**
I believe this is related to or the same issue as https://github.com/open-telemetry/opentelemetry-collector/issues/6604. I'm opening this specifically for v0.64.1 and since I'm skeptical that a new release will fix the breakdown of isolation between releases.

**Comment by codeboten** [comment]
A few of the modules have been pulled out of go.opentelemetry.io/collector and must be referenced directly. I updated the config you supplied as per the following and was able to compile the collector:

```
dist:
  module: github.com/my-organization/opentelemetry-collector-custom
  otelcol_version: "0.64.1"
  output_path: bin
exporters:
  - gomod: "go.opentelemetry.io/collector/exporter/loggingexporter v0.64.1"
  - gomod: "go.opentelemetry.io/collector/exporter/otlpexporter v0.64.1"
  - gomod: "go.opentelemetry.io/collector/exporter/otlphttpexporter v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/zipkinexporter v0.64.0"
extensions:
  - gomod: "go.opentelemetry.io/collector/extension/ballastextension v0.64.1"
  - gomod: "go.opentelemetry.io/collector/extension/zpagesextension v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.64.0"
processors:
  - gomod: "go.opentelemetry.io/collector/processor/batchprocessor v0.64.1"
  - gomod: "go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/cumulativetodeltaprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/metricstransformprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourceprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.64.0"
receivers:
  - gomod: "go.opentelemetry.io/collector/receiver/otlpreceiver v0.64.1"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/azureeventhubreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/fluentforwardreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunkhecreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver v0.64.0"
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/zipkinreceiver v0.64.0"
```
