### ISSUE TITLE
Allow Exporting of the Collector's internal spans

### ISSUE THREAD

**Issue by TylerHelmuth** [open-telemetry/opentelemetry-collector#6629]
**Is your feature request related to a problem? Please describe.**
Currently the collector can be made to emit metric and log telemetry, but not spans.  The collector does have the capability to generate its own spans, but they can only be viewed with the zpages extension.  It would be best if the spans could also be emitted like the collector's metrics and logs  

**Describe the solution you'd like**
The collector's telemetry settings allow for configuring a "output" for spans that result in the spans being sent through a collector pipeline.  

I think it would be best if the data could be sent to a pipeline directly without needing to go over the network.  If that isn't possible then maybe we restrict exporting of spans to the OTLP format and require a OTLP receiver to collect the collector's spans?

The configuration could look something like:

```go
// TracesConfig exposes the common Telemetry configuration for collector's internal spans.
// Experimental: *NOTE* this structure is subject to change or removal in the future.
type TracesConfig struct {
	// Propagators is a list of TextMapPropagators from the supported propagators list. Currently,
	// tracecontext and  b3 are supported. By default, the value is set to empty list and
	// context propagation is disabled.
	Propagators []string `mapstructure:"propagators"`

	// Outputs is a list of pipeline names that should receive the collector's spans.
	// If no outputs are specified then spans are not exported from the collector.
	Outputs []string `mapstructure:"outputs"`
}
```

```yaml
service:
  telemetry:
    traces:
      outputs:
        - "pipeline"
```

Maybe we could use the default pipeline if no outputs are specific, essentially making span exporting the default behavior, and include some other config option to disable span exporting?

**Comment by TylerHelmuth** [comment]
@jpkrohling maybe the solution is being able to define in the telemetry settings a pipeline specific to the collector's internal telemetry and this pipeline doesn't instrument itself (somehow)? Could look like:

```yaml
service:
  telemetry:
    pipeline:
      traces:
        processors: []
        exporters: []
      metrics:
        processors: []
        exporters: []
      logs:
        processors: []
        exporters: []
```

**Comment by jpkrohling** [comment]
I have a bad feeling about this one. The common practice I've been seeing is to have the monitors being external to the process being monitored, and I think this applies here as well ("who monitors the monitor" type of question). In that sense, I would recommend our users use an external OTLP endpoint whenever possible to receive the collector's telemetry data and would not have this enabled by default.

**Comment by TylerHelmuth** [comment]
@jpkrohling an external endpoint is ok as well, although we lose potential processing.  As long as we can get the spans out I'll be happy.

**Comment by TylerHelmuth** [comment]
Based on the SIG discussion today I will move forward with a config proposal to allow configuring exporters in the OpenTelemetry Go SDK.

**Comment by TylerHelmuth** [comment]
@bogdandrutu @jpkrohling @codeboten @Aneurysm9 was the idea of using ENV VARs to configure the exporter completely rejected?  If they are allowed, which takes precedence, env vars or the explicit configuration in TelemetrySettings?

**Comment by bogdandrutu** [comment]
I think we should not support that for the moment, idea being that these kind of decisions should be made by the config SIG and by not supporting I believe that we are postponing that decision.

**Comment by TylerHelmuth** [comment]
## Current Requirements:

1. The configuration must be generic enough to apply to any type of exporter (even if we only support OTLP at the start)
2. Should be able to be extended to include metrics and logs in the future.
3. ENV VARs should not be used to do the configuring (for now).

## SDK Exporter Configuration

* The Go SDK exporters all use the Go pattern of Options to configure the exporter.  
* These Options vary by exporter type.  
* Each option can have different parameters

To be able to configure the SDK we will need to be able to identify which options should be used and the parameters

## Collector TelemetrySettings Configuration Proposal

I think we can handle mapping from configuration to Option via a map.  A combination of the exporter’s name and the option name will map to a Go SDK option.

```yaml
service:
  telemetry:
    traces:
      exporters:
        - name: "exporter name"
          options: 
            - name: "option name"
              parameters: 
                - "string"
                - "string"
            - name: "option name"
              parameters: 
                - "string"
                - "string"
        - name: "exporter name"
          options: 
            - name: "option name"
              parameters: 
                - "string"
                - "string"
            - name: "option name"
              parameters: 
                - "string"
                - "string"
```

### Downsides:

* User must know the Go SDK in order to configure the collector’s use of the Go SDK. If the user doesn’t know what exporters/options are available (and no using Intelisense here to help) it will be difficult to configure.
* Maybe doesn’t extend to other languages, won’t fit in with the Configuration SIG’s goals?

### Upsides:

* Generic enough to handle any type of exporter, as long as it uses options.
* Explicit; all options are available and configurable.
* Scalable; as more options/exporters are added the configuration doesn’t have to change

**Comment by jpkrohling** [comment]
Are we allowing users to configure other settings, like samplers, tracer names, and custom resource attributes? I think it would also be good to have a property to enable tracing, like:

```yaml
service:
  telemetry:
    traces:
      enabled: true
```

**Comment by TylerHelmuth** [comment]
@jpkrohling we don't currently have an `enable` switch for metrics or logs or the traces that are created today.  If we add one for tracing then I think it should be consistent and we should add some for metric and log telemetry as well.  The lack of any exporter configuration could also be used to signify logs should not be exported but should continue to be created and exposed via zpages.

I think we will need to be able to configure samplers and tracer name (although I think we should supply defaults for both).  Custom resource attributes should reuse the telemetry setting's existing `Resource` field I think.

**Comment by codeboten** [comment]
@TylerHelmuth adding the current example configuration from the configuration working group since we're essentially configuring the OTel Go SDK, I would lean towards supporting the same configuration:

```yaml
  tracer_provider:
    # Span exporters. Each exporter key refers to the type of the exporter. Values configure the exporter. Exporters must be associated with a span processor.
    exporters:
      # Configure the zipkin exporter.
      zipkin:
        # Sets the endpoint.
        #
        # Environment variable: OTEL_EXPORTER_ZIPKIN_ENDPOINT
        endpoint: http://localhost:9411/api/v2/spans
        # Sets the max time to wait for each export.
        #
        # Environment variable: OTEL_EXPORTER_ZIPKIN_TIMEOUT
        timeout: 10000
    # List of span processors. Each span processor has a name and args used to configure it.
    span_processors:
      # Add a batch span processor.
      #
      # Environment variable: OTEL_BSP_*, OTEL_TRACES_EXPORTER
      - name: batch
        # Configure the batch span processor.
        args:
          # Sets the delay interval between two consecutive exports.
          #
          # Environment variable: OTEL_BSP_SCHEDULE_DELAY
          schedule_delay: 5000
          # Sets the maximum allowed time to export data.
          #
          # Environment variable: OTEL_BSP_EXPORT_TIMEOUT
          export_timeout: 30000
          # Sets the maximum queue size.
          #
          # Environment variable: OTEL_BSP_MAX_QUEUE_SIZE
          max_queue_size: 2048
          # Sets the maximum batch size.
          #
          # Environment variable: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
          max_export_batch_size: 512
          # Sets the exporter. Exporter must refer to a key in sdk.tracer_provider.exporters.
          #
          # Environment variable: OTEL_TRACES_EXPORTER
          exporter: zipkin
```
See https://github.com/MrAlias/otel-schema/blob/332987fc1980b2631122771c8d721fa3e7ab32d4/config.yaml#L35-L77 for additional configuration
