### ISSUE TITLE
otlpreceiver's `receiver_accepted_spans` metric have same transport label for grpc and http

### ISSUE THREAD

**Issue by Frefreak** [open-telemetry/opentelemetry-collector#6695]
**Describe the bug**
The metrics for otlpreceiver have the following metrics
- receiver_accepted_spans
- receiver_refused_spans

They have a **transport** label. Currently for both grpc and http endpoint it uses "grpc" as label value.

**Steps to reproduce**
Run collector with this minimal config

report 2 spans to the grpc (4317) and http (4318) endpoint respectively, then inspect metrics  `receiver_accepted_spans`

**What did you expect to see?**
Two lines for `receiver_accepted_spans`, one with transport = grpc, the other with transport = http (or tcp or something else, but not grpc)

**What did you see instead?**
grpc and http endpoint both uses "grpc" as transport label value

```
otelcol_receiver_accepted_spans{receiver="otlp",service_instance_id="...",service_name="otelcorecol",service_version="0.66.0-dev",transport="grpc"} 2
```

**What version did you use?**
Version: current main (8d11723a046363bd5bd3ce89ea16ad8f93e55f79)

**What config did you use?**
Config: 
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
```

**Environment**
OS: archlinux
Compiler(if manually compiled): go version go1.19.3 linux/amd64
