### ISSUE TITLE
Document ability to use config providers inside config

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#6748]
I think the Collector does not document anywhere directly that the config providers can be used inside the config. I am referring to the ability to do this:

```yaml
exporters:
  logging:

receivers: ${file:receivers.yaml}

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
```
Where `receivers.yaml` is another file:
```yaml
otlp:
  protocols:
    grpc:
    http:
```
