### ISSUE TITLE
Opentelemetry does not discover target with service monitor

### ISSUE THREAD

**Issue by vivekcusat** [open-telemetry/opentelemetry-collector#6831]
**What are you trying to achieve?**
I have configured prometheus receiver to scrap the metrics the service discovery start collecting the metrics and sending to my exporter but all the metrics coming having no-namespace tag. It is not able to identify the app from where it is coming. I have define the service monitor to label it but it does not work .
  
What did you expect to see?
Metrics should come with label public-web-api-dev. 
**Additional context.**

Add any other context about the problem here. If you followed an existing documentation, please share the link to it.
Please find my config and service monitor configuration.
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: my-collector
spec:
  mode: deployment # This configuration is omittable.
  config: |
    exporters:
      datadog:
        api:
          key: ""
          site: "datadoghq.eu"

    extensions:
      health_check: {}
      memory_ballast: {}
      zpages: {}
    processors:
      batch: 
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s
    
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317

      prometheus:
        config:
          scrape_configs:
            - job_name: public-web-api-dev
              scrape_interval: 60s
              kubernetes_sd_configs:
                - role: endpoints
              relabel_configs:
                - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
                  action: keep
                  regex: default;public-web-api-dev;web

              
      hostmetrics:
        collection_interval: 10s
        scrapers:
          paging:
            metrics:
              system.paging.utilization:
                enabled: true
          cpu:
            metrics:
              system.cpu.utilization:
                enabled: true
          disk:
          filesystem:
            metrics:
              system.filesystem.utilization:
                enabled: true
          load:
          memory:
          network:
          processes:

    service:
      extensions:
        - health_check
        - memory_ballast
        - zpages
      pipelines:
        metrics: 
          receivers: [prometheus, hostmetrics]
          processors: [batch]
          exporters: [datadog]
        traces:
          receivers: 
            - otlp
          processors: 
            - batch
          exporters: 
            - datadog
      telemetry:
        logs:
          level: "debug"
```
```
---
apiVersion: monitoring.coreos.com/v1                                                                                                                                                                                                                                   
kind: ServiceMonitor                                                                                                                                                                                                                                                   
metadata:                                                                                                                                                                                                                                                              
  labels:                                                                                                                                                                                                                                                              
    app: public-web-api-dev
    release: opentelemetry-operator                                                                                                                                                                                                                                     
  name: public-web-api-dev                                                                                                                                                                                                                                     
  namespace: default                                                                                                                                                                                                                                                   
spec:                                                                                                                                                                                                                                                                  
  endpoints:                                                                                                                                                                                                                                                           
  - path: /metrics                                                                                                                                                                                                                                                     
    port: web                                                                                                                                                                                                                                                   

                                                                                                                                                                                                                                                         
  selector:                                                                                                                                                                                                                                                            
    matchLabels:
      app: public-web-api-dev                                                                                                                                                                                                                                                       
      release: opentelemetry-operator

```

![Screenshot 2022-12-07 at 12 40 00](https://user-images.githubusercontent.com/50938778/206170487-b87b6aa8-bf51-49b1-bc04-d429198aad7d.png)
