### ISSUE TITLE
otlpreceiver with ocb v0.68.0

### ISSUE THREAD

**Issue by Gauravmeenu** [open-telemetry/opentelemetry-collector#6841]
Whenever I am compling and creating own collector instance with ocb v0.68.0 and mentioning otlpreceiver v0.68.0 in manifest.yaml file then ,
my terminal pop-up with the error like this

Error: failed to compile the OpenTelemetry Collector distribution: exit status 2. Output:
# go.opentelemetry.io/collector/receiver/otlpreceiver/internal/logs
..\..\..\pkg\mod\go.opentelemetry.io\collector\receiver\otlpreceiver@v0.64.1\internal\logs\otlp.go:41:22: undefined: obsreport.MustNewReceiver       
# go.opentelemetry.io/collector/receiver/otlpreceiver/internal/metrics
..\..\..\pkg\mod\go.opentelemetry.io\collector\receiver\otlpreceiver@v0.64.1\internal\metrics\otlp.go:41:22: undefined: obsreport.MustNewReceiver    
# go.opentelemetry.io/collector/receiver/otlpreceiver/internal/trace
..\..\..\pkg\mod\go.opentelemetry.io\collector\receiver\otlpreceiver@v0.64.1\internal\trace\otlp.go:41:22: undefined: obsreport.MustNewReceiver

**Comment by mx-psi** [comment]
@Gauravmeenu can you share a minimal example where this is happening for you?

**Comment by Gauravmeenu** [comment]
Actually When I'm creating a custom collector distribution with ocb 0.68.0 and manifest.yaml file , 
this is my manifest.yaml file ,


dist:
  name: custom-otelcol # the binary name. Optional.
  output_path: ./custom-otelcol # the path to write the output (sources and binary). Optional..
   

exporters:
  - gomod:
      "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter
      v0.68.0"
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.68.0

receivers:
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.68.0

processors:
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.68.0
 


Then I'm getting error which I has mentioned in the above comment section

**Comment by mx-psi** [comment]
This relates to #5992.

As stated in [the changelog](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CHANGELOG.md#0640), since v0.64.0 you need to change the `gomod` for the core components such as the OTLP receiver because they are now served as separate Go modules.

For your manifest, you can fix it as follows:

```yaml
dist:
  name: custom-otelcol # the binary name. Optional.
  output_path: ./custom-otelcol # the path to write the output (sources and binary). Optional..
   

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.68.0
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.68.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.68.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.68.0
```

Does making these changes on your manifest solve the issue for you?
