### ISSUE TITLE
Different Config between opentelemetry-collector and opentelemetry-collector-contrib?

### ISSUE THREAD

**Issue by Liubey** [open-telemetry/opentelemetry-collector#6863]
**Describe the bug**
When I use the same config file , I can got traces in jaeger with opentelemetry-collector.
When I change to  opentelemetry-collector-contrib, I got nothing but only log in console.

the confile is:
```
receivers:
  jaeger:
    protocols:
      thrift_compact:
processors:
 batch:
   timeout: 1s
 resource:
   attributes:
     - key: test.key
       value: "test-value"
       action: insert
exporters:
 logging:
   loglevel: info
 otlp:
   endpoint: 192.168.31.162:4320
   tls:
    insecure: true
extensions:
 health_check:
 pprof:
   endpoint: :1888
 zpages:
   endpoint: :55679
service:
 extensions: [pprof, zpages, health_check]
 pipelines:
   traces:
     receivers: [jaeger]
     processors: [batch, resource]
     exporters: [logging, otlp]
```

the collector docker shell:
```
docker run -v /Users/xinliu/Documents/veeva/apm/tracing/otel-collector-config_6831.yml:/etc/otelcol/config.yaml -p 6831:6831/udp otel/opentelemetry-collector:0.68.0 

```

the collector-contirb docker shell:
```
docker run -v /Users/xinliu/Documents/veeva/apm/tracing/otel-collector-config_6831.yml:/etc/otelcol/config.yaml -p 6831:6831/udp otel/opentelemetry-collector-contrib:0.68.0 

```

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
Is something different betweent them? Cause I want to use loadbalancingexporter, so I tendency to use the "contrib"?

Thank you so much.
**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: (e.g., `v0.4.0`, `1eb551b`, etc)
0.68.0
**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**
