### ISSUE TITLE
how to use Opentelemetry collector's health_check as livenessProbe or readinessProbe

### ISSUE THREAD

**Issue by cdash415** [open-telemetry/opentelemetry-collector#6930]
**Describe the bug**
I'm pretty new to opentelemetry and currently trying to configure livenessProbe for Opentelemetry collector and wanted to verify it in kubernetes cluster.

Issue: 
1. How to use livenessProve here (like we use in kubernetes Deployment)?
2. Unable to modify/add initialDelaySeconds, periodSeconds, failureThreshold etc what are the allowed fields here?

**Added below in config.yaml:**
```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
```
```
config:
      extensions:
        health_check:
          endpoint: 0.0.0.0:8081
          path: healthz
```
```
service:
      extensions:
      - health_check
```
