### ISSUE TITLE
ocb build with 0.69.1 still  have the problem "does not contain package go.opentelemetry.io/collector/config "

### ISSUE THREAD

**Issue by liuqingyang1996** [open-telemetry/opentelemetry-collector#6942]
it seems like the problem of loggingexporter, when i enable it, the error will occur:

2023-01-13T15:55:13.487+0800    INFO    internal/command.go:158 Using config file       {"path": "./config/builder/otel-builder.yaml"}
2023-01-13T15:55:13.487+0800    INFO    builder/config.go:107   Using go        {"go-executable": "/usr/local/go/bin/go"}
2023-01-13T15:55:13.490+0800    INFO    builder/main.go:76      Sources created {"path": "./output"}
Error: failed to update go.mod: exit status 1. Output:
go: finding module for package go.opentelemetry.io/collector/exporter/loggingexporter
go: found go.opentelemetry.io/collector/exporter/loggingexporter in go.opentelemetry.io/collector/exporter/loggingexporter v0.69.1
go: finding module for package go.opentelemetry.io/collector/config
go.opentelemetry.io/collector/cmd/builder imports
        go.opentelemetry.io/collector/processor/batchprocessor imports
        go.opentelemetry.io/collector/config: module go.opentelemetry.io/collector@latest found (v0.69.1), but does not contain package go.opentelemetry.io/collector/config

**Comment by mx-psi** [comment]
Hi @liuqingyang1996 can you share a manifest fail where you get this problem? I have not been able to reproduce, e.g. the following builds fine for me:

```yaml
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.69.1
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.69.1

```

as does this one

```yaml
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.69.1
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.69.1
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.69.1

```
