### ISSUE TITLE
Inject current config file location as a variable

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#7175]
In the Collector config I would like to be able to reference to a file using a path that is relative to the current config file location. 

## What is possible currently

It is currently possible to do for example this (assuming a hypothetical `mapper` processor):

```yaml
processors:
  mapper:
    # The processor will read the mapping.csv file from the current directory 
    mapping_file: mapping.csv 
    from_column: zipcode
    to_column: country 
```

The `mapper` processor will see "mapping.csv" string in its configuration and can read the file. The file will be read from the current directory of the Collector process. But this is not necessarily where the file is located. Often it is more convenient to place additional files in the same directory as the Collector config file, since such files are needed by the configuration.

## What I would like to be able to do

Inject OTELCOL_CFG_LOCATION_BASE variable into the config resolution process automatically. Set its value equal to the base of the URI of the confmap.Provider that was used for loading the **current** config.

### Refer to local file

It would be very useful to be able to specify the path to additional local files like this:

```yaml
processors:
  mapper:
    # The processor will read the mapping.csv file from the directory where the config file is loaded from.
    mapping_file: ${OTELCOL_CFG_LOCATION_BASE}mapping.csv 
    from_column: zipcode
    to_column: country 
```

Here in this example `OTELCOL_CFG_LOCATION_BASE` variable is automatically injected by the Collector and is set to the base of the URI, i.e. to the directory that contains the config file.

This will work correctly for included files too. For example:

```yaml
# this is main config file

# include processors config from another file
processors: ${file:subdir/processors.yaml}
```

```yaml
# this is subdir/processors.yaml

mapper:
  # The processor will read the mapping.csv file from the subdir where the processors.yaml file is
  # loaded from (not where main config file is!). 
  mapping_file: ${OTELCOL_CFG_LOCATION_BASE}mapping.csv 
  from_column: zipcode
  to_column: country
```

### Using with other Providers

OTELCOL_CFG_LOCATION_BASE variable will also work correctly for other confmap.Provider types. For example:

```yaml
# this is main config file.

# Use http provider to get some config:
processors: ${http://example.com/processors.yaml}
```

```yaml
# this file located at http://example.com/processors.yaml and was referenced from main config file.

mapper:
  # OTELCOL_CFG_LOCATION_BASE is now set to http://example.com/ so
  # the processor will correctly read the mapping.csv file from http://example.com/mapping.csv
  mapping_file: ${OTELCOL_CFG_LOCATION_BASE}mapping.csv 
  from_column: zipcode
  to_column: country
```

The variable can be also used for other interesting use cases, for example for [referencing one config file from another](https://github.com/open-telemetry/opentelemetry-collector/issues/7176) (for inclusion using `file` provider).
