### ISSUE TITLE
Extend file confmap.Provider to support globs

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-collector#7177]
**Is your feature request related to a problem? Please describe.**

It is difficult to decompose Collector config and place them in separate files, one per component. For complex configs that use dozens of components which results in very large Collector config or requires multiple ${file} directives to include them, which is also difficult to manage since it requires changes in 2 places when adding new components.

**Describe the solution you'd like**

I would like to be able to use glob patterns for file URIs. When combined with the newly proposed [receivergroup](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/18509) component I can then for example do this:

```yaml
receivers:
  # This will read all *.yaml files from all sub-directories of the "receivers" directory and will merge them into one config
  # and then set the result the config of the receivergroup/all component.
  receivergroup/all: ${file:receivers/*/*.yaml}

service:
  pipelines:
    metrics:
      receivers: receivergroup/all
      exporters: ...
```

The suggestion is that when there are multiple files matching the glob pattern, the content of all those files is merged using the [same merging rules](https://github.com/open-telemetry/opentelemetry-collector/blob/08985c48bb7cdc9a6694d62dde8b711fea9974d8/confmap/resolver.go#L163) logic we already use for confmap.Resolver.

This example allows placing receiver configs each in its own file and when you need to add a new receiver you just create a new yaml file in `receivers` directory.
