### ISSUE TITLE
Unable to receive raw json to otel http collector on /v1/logs

### ISSUE THREAD

**Issue by raghu999** [open-telemetry/opentelemetry-collector#7351]
**Describe the bug**

I am trying to ship a raw JSON to otlp http endpoint and i am recieving a partialSuccess. Don't see the event in the logs or at the destination cluster. The same works when using the splunk hec exporter.

**Steps to reproduce**

1. Start the collector using the below  provided config 

2. Ship a raw json event to otlp HTTP endpoint

```
curl -H'Content-Type: application/json'  http://0.0.0.0:4318/v1/logs -d '{
  "timestamp":1581385157.14429,
  "body":"Incoming request",
  "trace_id":"102981ABCD2901",
  "span_id":"abcdef1010"
}'
{"partialSuccess":{}}%
``` 
 3. Check the stdout debug logs
 
 4. Ship the same event to splunk hec destination 
 
 ```
 curl http://0.0.0.0:8088/services/collector/event -d '{
  "timestamp":1581385157.14429,
  "body":"Incoming request",
  "trace_id":"102981ABCD2901",
  "span_id":"abcdef1010"
}'
"OK"%
```     

The debug log doesn't't show any activity when using otel HTTP endpoint but shows the event making into the otel collector eventually ending up in the destination when using splunk hec receiver.

**What did you expect to see?**

Otel HTTP must accept raw json events to otlp HTTP logs endpoint. 

**What did you see instead?**

Not seeing any event logs in the stdout or activity.

**What version did you use?**
Version: 0.73.0

**What config did you use?**
Config: 
```
extensions:
  memory_ballast:
    size_in_percentage: 33
  health_check:
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  splunk_hec:
  splunk_hec/allsettings:
    # endpoint specifies the network interface and port which will receive
    # Events.
    endpoint: 0.0.0.0:8088
    access_token_passthrough: true
    hec_metadata_to_otel_attrs:
      source: "gateway"
      sourcetype: "ingest"
processors:
  memory_limiter:
    check_interval: 2s
    limit_mib: 2048
  batch:
  resource:
    attributes:
      - key: test.key
        value: "test-value"
        action: insert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  elasticsearch/log:
    endpoints: ["${ELK_URL}"]
    logs_index: "logz-test"
    user: "${ELK_USERNAME}"
    password: "${ELK_PASSWORD}"
    tls:
      insecure_skip_verify: true
  logging:
    verbosity: detailed

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
    logs:
      level: "debug"
  extensions: [memory_ballast, health_check]
  pipelines:
    logs:
      receivers: [otlp, splunk_hec]
      processors: [batch, resource]
      exporters: [elasticsearch/log, logging]

```

**Environment**
OS: K8's using container provided by otel community  `otel/opentelemetry-collector-contrib:0.73.0`
