### ISSUE TITLE
Collector gerenerates invalid output for prometheus

### ISSUE THREAD

**Issue by ImoutoChan** [open-telemetry/opentelemetry-collector#7392]
**Describe the bug**
I have a system with services, collector (latest), and prometheus (2.42.0) for metrics aggregation. 

The collector is up and running and returns metrics on /metrics endpoint. It worked for several hours and Prometheus was successfully receiving data. But then after some point in time it started to display this error:

Url: url:9201/metrics
State: down
Error: expected next entry after timestamp, got "INVALID"

**Steps to reproduce**
I can't reproduce it on small sample, but here is my config for collector:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: ":9201"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
```

and here is for prometheus:

```yaml
- job_name: opentelemetry
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - url:9201
```

If I open url:9201/metrics in new tab it returns metrics, but I suspect something somewhere is wrong

**What did you expect to see?**
Collector should always produce valid output on /metrics endpoint for prometheus

**What did you see instead?**
It produce something, but prometheus unable to parse it and returns 'expected next entry after timestamp, got "INVALID"'

**What version did you use?**
Version: otel/opentelemetry-collector:latest@sha256:69b1cde6062a8ad68fa025fb240b5ec3efbb29205a0538924683471439a73353

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: ":9201"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
```

**Environment**
I used provided image

**Additional context**
If there is any tools to see what is actually wrong with produced output by the collector, please point me to this tool. The output itself is too big to paste it here and I don't know where to look and why Prometheus can't parse it.
Also, maybe there is a way to see more detailed errors on Prometheus side, if you know one, please let me know.

I also suspect that simple /metrics doesn't return metrics in open_metrics format, but I don't know how to request it manually. 

The whole point for me to do this setup was to send exemplars to Prometheus.
