### ISSUE TITLE
Metrics send_failed_requests is inaccurate/abnormal

### ISSUE THREAD

**Issue by mizhexiaoxiao** [open-telemetry/opentelemetry-collector#7456]
**Describe the bug**

I found that regardless of whether in a local or other environment, when attempting to send data, Otel exporter always reports a number greater than 0 for send failed requests. This is puzzling. The number of send failed requests always matches the group of spans sent. For example, based on the information below, 3 group of spans were sent and 3 metric of send failed requests were generated. Would anyone be able to assist in identifying the root cause of this issue? Thank you

**Steps to reproduce**
1. start the collector locally
./otelcol-contrib --config config.yaml
```yaml
receivers:
  otlp/recv-1:
    protocols:
      grpc:
        endpoint: localhost:4317
exporters:
  logging:
processors:
service:
  pipelines:
    traces/agent:
      receivers: [otlp/recv-1]
      processors: []
      exporters: [logging]
```
2. use this [example](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/otel-collector/main.go), modify the endpoint of #L63 to localhost:4317
3. go run main.go

**What did you expect to see?**
otelcol_exporter_send_failed_requests should be 0

**What did you see instead?**
I saw that the exporter sent a total of 11 divided into 3 groups, and there were 3 send failed reqeusts
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/54677442/228812437-29654d1f-d6de-46a8-8ad2-66bd6b9055ba.png">
![image](https://user-images.githubusercontent.com/54677442/228812480-166753a3-5855-4da1-b4ba-2e2fbe7f4201.png)

**What version did you use?**
Version: v0.73.0, version > 0.63.0 has this problem

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: MacOS M1
Compiler(if manually compiled): go1.18 darwin/arm64

**Additional context**
