### ISSUE TITLE
High cardinality metric observed from grpc instrumentation

### ISSUE THREAD

**Issue by jaronoff97** [open-telemetry/opentelemetry-collector#7517]
**Describe the bug**
When the flag `telemetry.useOtelForInternalMetrics` is enabled, metrics for gRPC now come through because of [this line](https://github.com/open-telemetry/opentelemetry-collector/blob/a2f0153679220d5de7b2a2ac79a5bebfca90cf89/config/configgrpc/configgrpc.go#L263). When running a collector with a sufficiently high number of connections, this floods the prometheus exporter with a metric with `net.sock.peer.addr` attributes. This resulted in a prometheus scrape being a 33 MB file.

This issue has been reported and discussed [here](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3071). I'm moving the discussion here because this is going to cause any user enabling this flag to potentially experience this cardinality explosion. Temporarily, it would be ideal if we could disable the line I linked to remediate this problem.

**Steps to reproduce**
Create a collector with the `telemetry.useOtelForInternalMetrics` flag enabled, load test it, curl the metrics endpoint.

**What did you expect to see?**
A stable collector that doesn't constantly OOM.

**What did you see instead?**
Cardinality explosion

**What version did you use?**
v0.74.0

**What config did you use?**
Config:
```
    extensions:
      health_check:
        check_collector_pipeline:
          enabled: false
          exporter_failure_threshold: 5
          interval: 5m
        endpoint: 0.0.0.0:13133
        path: /
      pprof: null
    exporters:
      otlp/selfreport:
        endpoint: XXXXXXXXXXXXXXXXX
        headers:
          lightstep-access-token: ${LS_TOKEN}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            include_metadata: true
      prometheus:
        config:
          scrape_configs:
          - job_name: spaningest
            scrape_interval: 5s
            static_configs:
            - labels:
                collector_name: ${KUBE_POD_NAME}
              targets:
                - 0.0.0.0:8888
    processors:
      batch:
        send_batch_max_size: 1500
        send_batch_size: 1000
        timeout: 1s
      memory_limiter:
        check_interval: 1s
        limit_percentage: 85
        spike_limit_percentage: 10
    service:
      extensions:
      - health_check
      - pprof
      pipelines:
        metrics:
          exporters:
          - otlp/selfreport
          processors:
          - memory_limiter
          - batch
          receivers:
          - prometheus
      telemetry:
        metrics:
          level: detailed
        resource:
          service.name: spaningest
```

**Environment**
OS: Kubernetes
Compiler(if manually compiled): go 1.20

**Additional context**
