### ISSUE TITLE
Memory grows fast, suspected a leak

### ISSUE THREAD

**Issue by bitomaxsp** [open-telemetry/opentelemetry-collector#7622]
After the update to tag v0.76.1 and deployment to production we noticed memory grows up to the set limits.
Grow rate is ~18Mb/min

**Steps to reproduce**
I assume deploying the collector and applying metric point rate at ~350-400 should be enough.

**What did you expect to see?**
Expectation is that memory will grow at least with the same rate as on previously deployed version which is v0.50.0.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
Version: v0.76.1

**What config did you use?**
Config: 
```yaml
  collector.yaml: |
    extensions:
      pprof:

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55680
            read_buffer_size: 4096
            write_buffer_size: 4096
            keepalive:
              server_parameters:
                max_connection_age: 3600s

    processors:
      memory_limiter:
        check_interval: 10s
        limit_mib: 600
        spike_limit_mib: 150
      batch:
        timeout: 10s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9090"
        metric_expiration: 24h0m0s
        send_timestamps: false
        const_labels:
          collector: lambda-opentelemetry-collector
        resource_to_telemetry_conversion:
          enabled: true

    service:
      extensions: [pprof]

      telemetry:
        metrics:
          level: detailed
          address: '0.0.0.0:8888'
        logs:
          level: "info"

      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus]
```

**Environment**
OS: (e.g., "Ubuntu 20.04")
```bash
  nodeInfo:
    architecture: amd64
    bootID: 8fec644d-23e1-41d6-98c7-e8a353405686
    containerRuntimeVersion: docker://20.10.13
    kernelVersion: 5.4.196-108.356.amzn2.x86_64
    kubeProxyVersion: v1.21.12-eks-5308cf7
    kubeletVersion: v1.21.12-eks-5308cf7
    machineID: ec2563e2103fb54ccd7895e788ca1992
    operatingSystem: linux
    osImage: Amazon Linux 2
```
Compiler(if manually compiled): (e.g., "go 1.20.3") compiled for amd64 arch.

K8s memory request: 250Mb
K8s memory limit: 800Mb

Memory consumption on v0.76.1
![v0 76 1](https://user-images.githubusercontent.com/866806/235868512-bfe19edc-783b-488d-b048-368ab0bfee58.png)

Memory consumption on v0.50.0
![v0 50 0](https://user-images.githubusercontent.com/866806/235868599-2a7b98b4-1fcc-4cde-96d0-3f39d5df5ff7.png)
