### ISSUE TITLE
Unable to receive HTTP OTLP on port 4318 using docker container

### ISSUE THREAD

**Issue by quintonn** [open-telemetry/opentelemetry-collector#7692]
**Describe the bug**
I don't seem to be able to receive OTLP logs on port 4318 using HTTP.

**Steps to reproduce**
I run a docker container as follows:  
`docker run --rm -v ./otel-collector/config.yaml:/etc/otel/config.yaml -p 4318:4318 --name otel-collector -it otel/opentelemetry-collector`  

**What did you expect to see?**
The container to run and be able to receive data using the following command:  
`curl -x POST -d '{}' http://localhost:5318/otlp/v1/logs`  

**What did you see instead?**
Unable to start container with port mapping.  
Error:  
`docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:4318 -> 0.0.0.0:0: listen tcp 0.0.0.0:4318: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
time="2023-05-17T16:13:27+01:00" level=error msg="error waiting for container: context canceled"` 

I am able to port forward on port 4317 though, so I don't understand why this is not working.

**What version did you use?**
0.77.0

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  
exporters:
  otlphttp:
    endpoint: http://host.docker.internal:4319/otlp
    compression: none
    tls:
      insecure: true
    
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
```

**Environment**
OS: Windows / Docker
Compiler : n/a

**Additional context**
n/a
