### ISSUE TITLE
Counter Metrics dropping scrapes / Datapoints

### ISSUE THREAD

**Issue by martinrw** [open-telemetry/opentelemetry-collector#7716]
**Describe the bug**
We are using the opentelemetry-collector helm chart to deploy. We have the otel agent running on a number of Java and Python services.

For metrics that are counter based such as http_server_duration_milliseconds_count we are frequently seeing dropped / missing data points.
It is set to scrape every 15 seconds but as you can see from this screenshots we a frequently missing 1 or 2 data points in a row.
![image](https://github.com/open-telemetry/opentelemetry-collector/assets/23168921/66e7e027-9af5-47c8-9892-393220aab09c)

For our other metrics such as non-counter based Otel ones we see a data point every 15 seconds with nothing being dropped, same for metrics coming from Kube-state-metrics etc

**Steps to reproduce**
Otel agent installed on docker image pushing metrics to the otel collector (See config below) - which is scraped by prometheus.
We see the same thing when looking at the metric in both prometheus or grafana.

Looking at the Scrape config in prometheus, this is what we end up with:
```
- job_name: serviceMonitor/opentelemetry-collector/opentelemetry-collector-apps-monitor/0
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
```  

**What did you expect to see?**
I would expect to see a data point every 15 seconds

**What did you see instead?**
When looking at the values over time for one of these metrics we occasionally have no data for 15 or 30 seconds (See screenshot above)

**What version did you use?**
0.77.0

**What config did you use?**
Here is our otel-collector config
```
config:
  exporters:
    prometheus:
      endpoint: "0.0.0.0:9464"
      resource_to_telemetry_conversion:
        enabled: true
      enable_open_metrics: true
      metric_expiration: 3m
      namespace: prometheus
  extensions:
    health_check: {}
    zpages: {}
    pprof: {}
    memory_ballast:
      size_in_percentage: 30
  processors:

    memory_limiter:
      check_interval: 1s
      limit_percentage: 50
      spike_limit_percentage: 20
    batch:
      send_batch_size: 10000
      send_batch_max_size: 11000
      timeout: 2s
    resource:
      attributes:
        - key: telemetry.sdk.name
          action: delete
        - key: telemetry.sdk.version
          action: delete
        - key: telemetry.sdk.language
          action: delete
        - key: telemetry.auto.version
          action: delete
        - key: container.id
          action: delete
        - key: process.command.args
          action: delete
    k8sattributes/default:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  service:
    telemetry:
      #logs for the collector itself
      logs:
        level: panic
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      traces: null
      logs: null
      metrics:
        exporters:
          - prometheus
        processors:
          - memory_limiter
          - batch
          - resource
          - k8sattributes/default
        receivers:
          - otlp
....
ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP

  app-metrics:
    enabled: true
    containerPort: 9464
    servicePort: 9464
    hostPort: 9464
    protocol: TCP

  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
...
podMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics
      # interval: 15s

  extraLabels:
    prometheus: scrape
    release: prometheus

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: metrics
      interval: 15s
  prometheusMetricsEndpoints:
    - port: app-metrics
      interval: 15s
      honorLabels: true
      relabelings:
        - action: labeldrop
          regex: (container|endpoint|job|namespace|pod|service)
        - action: replace
          regex: (.*)
          replacement: otel-collector
          targetLabel: instance
  extraLabels:
    prometheus: scrape
    release: prometheus
          
```

**Environment**
Kubernetes - Bottlerocket OS 1.13.1 (aws-k8s-1.24)

**Additional context**
This is a Brand new Prometheus + grafana + opentelemetry set-up. We've had this problem right from the beginning
