### ISSUE TITLE
Connection Refused error when using OTLPHTTP Exporter

### ISSUE THREAD

**Issue by ericashi** [open-telemetry/opentelemetry-collector#7811]
**Describe the bug**
I tried to use OTLPHTTP exporter to export my traces from OTLP HTTP receiver. 

**Steps to reproduce**
Configure the .yaml configuration file, then run the .yaml configuration file using the otelcol-contrib binary.
Please refer to the "OpenTelemetry Collector configuration" section for the configurations.

**What did you expect to see?**
I expect to see the traces in the endpoint configured in OTLPHTTP exporter.

**What did you see instead?**
I see error on the log in the Console.
Error message
error   exporterhelper/queued_retry.go:175      Exporting failed. No more retries left. Dropping data.  {"kind": "exporter", "data_type": "traces", "name": "otlphttp", "error": "interrupted due to shutdown failed to make an HTTP request: Post \"http://<host>:<port>/v1/traces\": dial tcp <Link>: connect: connection refused", "dropped_items": 2}

**What version did you use?**
v0.75.0

**What config did you use?**
receivers:
    otlp:
        protocols:
            http:
                endpoint: "<link>:4318"
                cors:
                    allowed_origins:
                        - <Links>
exporters:
    logging:

    otlphttp:
      endpoint: http://<link>:4317

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [logging, otlphttp]

**Environment**
OS: x86-64_linux_4.12_ImageSLES12SP5

**Additional context**
I followed the steps provided in the Github readme file. So, may I know what is the mistake I made and how to solve this error please?

Thank you.

**Comment by frzifus** [comment]
Hi @ericashi, can you confirm that you have been able to see traces printed to your console and that your config looks like this?

```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: ":4318"
        cors:
          allowed_origins:

exporters:
  logging:
  otlphttp:
    endpoint: http://<link>:4317

service:
  pipelines:
    traces:
    receivers: [otlp]
    exporters: [logging, otlphttp]
```

Another question, is it intended that the otlphttp exporter uses the [grpc default port](https://opentelemetry.io/docs/specs/otlp/#:~:text=The%20default%20network%20port%20for%20OTLP%2FgRPC%20is%204317.) as destination?
