### ISSUE TITLE
Memory footprint grows significantly with zstd compression

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-collector#7862]
**Describe the bug**
After some testing of deployments of the collector using zstd compression for grpc. 

**Steps to reproduce**
Enable zstd compression for the otlp exporter and send data through. 

**What did you expect to see?**

Somewhat normal memory usage, see the flamegraph below where the memory is roughly ~11mb in `ensureHist`:
<img width="1589" alt="Screenshot 2023-06-08 at 3 04 59 PM" src="https://github.com/open-telemetry/opentelemetry-collector/assets/223565/187d325d-7dfd-4e9b-a2cb-318bce54d043">

**What did you see instead?**

Memory inside `ensureHist` ballooned up to 160mb:
<img width="1581" alt="Screenshot 2023-06-08 at 3 05 09 PM" src="https://github.com/open-telemetry/opentelemetry-collector/assets/223565/c0573a06-abd8-4197-b1ec-32959894ecb0">

**What config did you use?**

```yaml
receivers:
  otlp:
    protocols:
        grpc:

exporters:
  otlp:
    endpoint: localhost:4389
    tls:
      insecure: true
    compression: zstd
  logging:

connectors:
  forward:

processors:
  batch:
    send_batch_max_size: 2048
    send_batch_size: 512
    timeout: 1s

extensions:
  pprof:

service:
  extensions: [pprof]
  telemetry:
    metrics:
      address: ":8999"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
```
