### ISSUE TITLE
question: how to do client-side load balancing with otlpexporter

### ISSUE THREAD

**Issue by kanata2** [open-telemetry/opentelemetry-collector#8000]
I also asked the question in [CNCF Slack](https://cloud-native.slack.com/archives/C01N6P7KR6W/p1687755769808759), but did not get an answer, so let me ask it here. 🙏 

## Description
I set up an otel-collector with otlpexporter according to [the documentation](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md), but this otel-collector could not do client-side load balancing with gRPC.
I am using the Kubernetes Headless service as the destination, but the gRPC traffic is biased to one pod...

My configuration is here.

```yaml
    exporters:
      otlp:
        endpoint: otelcol-debug-collector-headless.default.svc.cluster.local:4317
        balancer_name: round_robin
```

Is there something we are missing? 🤔
