### ISSUE TITLE
How to view telemetry data using http in postman from default 4318 endpoint for opentelemetry official demo

### ISSUE THREAD

**Issue by hkm-hw** [open-telemetry/opentelemetry-collector#8091]
Demo used: [https://opentelemetry.io/docs/demo/docker-deployment/](https://opentelemetry.io/docs/demo/docker-deployment/)

Expectation: I want to access telemetry data from the existing opentelemetry collectors' endpoint which is 4318(default) using postman.

Note: I am able to see the telemetry data using other exporters like Jaeger, Prometheus, Grafana and Datadog with the below configuration.

otelcol-config.yml:
```
# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        #endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  datadog:
    api:
      site: "my_site"
      key: "my_key"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  otlphttp:
     endpoint: "0.0.0.0:4318"
     compression: none
  logging:
  prometheus:
    endpoint: "otelcol:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, logging, spanmetrics, datadog]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter, batch]
      exporters: [prometheus, logging, datadog]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, datadog]
```

Postman curl:
```
curl --location --request POST 'http://0.0.0.0:4318/v1/traces' \
--header 'Content-Type: application/x-protobuf' \
--data ''
```

Current Response:
![image](https://github.com/open-telemetry/opentelemetry-collector/assets/135842912/811a9f92-059c-43da-a38a-73b1d3b1b251)
