### ISSUE TITLE
Persistent queue fails to delete items from disk in some circumstances

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/opentelemetry-collector#8115]
**Describe the bug**
The persistent queue pulls items from the on-disk database, but fails to delete them after they've been successfully sent. The result is that the db has orphaned data in it that never gets deleted.

**Steps to reproduce**
I haven't been able to reproduce this, but I have had a user send me their DB file, and have confirmed it contained items with indices less than the saved read index.

**What version did you use?**
 0.77.0

**What config did you use?**
The relevant part is:

```yaml
extensions:
  file_storage:
    directory: /var/lib/storage/otc
    timeout: 10s
    compaction:
      on_rebound: true
      directory: /tmp
```

**Environment**
The report I have is from AWS EKS 1.23 with the default storage driver.

**Additional context**
#7396 should technically help address similar problems, but this has happened quite consistently for this specific user in low disk space conditions, and the issue that change addresses should be fairly difficult to trigger.

I'm filing this in the hope that I can get more reports of this behaviour to help verify that it still occurs, and hopefully get to the bottom of the issue.
