### ISSUE TITLE
[otelcol] Improve error message when connectors lead to ambiguous IDs

### ISSUE THREAD

**Issue by mx-psi** [open-telemetry/opentelemetry-collector#8120]
When defining a pipeline, a component ID on the `receivers` or `exporters` section can be ambiguous if there is both a receiver/exporter and a connector with said ID. 

For example, if we were to add a `datadog` connector, with the following configuration:

<details>

<summary> Sample ambiguous configuration (click to expand) </summary>

```yaml
receivers:
  datadog:

exporters:
  datadog:
    api::key: ${env:DD_API_KEY}

connectors:
  datadog:

service:
  pipelines:
    traces:
      receivers: [datadog]
      exporters: [datadog]
    metrics:
      receivers: [datadog]
      exporters: [datadog]
```

</details>

will error out with

```
Error: invalid configuration: connectors::datadog: there's already an exporter named "datadog"
```

A valid way to work around this is to use different IDs for the receiver/exporter and the connector:

<details>

<summary> Sample unambiguous configuration (click to expand) </summary>

```yaml
receivers:
  datadog:

exporters:
  datadog:
    api::key: ${env:DD_API_KEY}

connectors:
  datadog/connector:

service:
  pipelines:
    traces:
      receivers: [datadog]
      exporters: [datadog/connector]
    metrics:
      receivers: [datadog/connector]
      exporters: [datadog]
```

</details>

We should improve the error message given in this case to something closer to the following:

```
Error: invalid configuration: ambiguous ID 'datadog': Found both 'datadog' exporter and 'datadog' connector.
Add a suffix to one of the components' IDs to eliminate ambiguity (e.g. rename 'datadog' connector to 'datadog/connector')
```

The necessary information is available [here](https://github.com/open-telemetry/opentelemetry-collector/blob/a1efc0e7fb148845342b903c8c5945cbbc5f6370/otelcol/config.go#L84-L89).

----

Originally discussed in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/19740#issuecomment-1644141235
