### ISSUE TITLE
otlphttp exporter drops data because memory limiter (of another instance) is considered as non recoverable error

### ISSUE THREAD

**Issue by sumo-drosiek** [open-telemetry/opentelemetry-collector#8132]
**Describe the bug**

Data are being dropped by exporter, because receiver is throttled by memory limiter. This is incorrect in my opinion as receiver may be behind load balancer, so after retry packet may be forwarded to healthy instance. Also memory usage is not constant, and may not be subject of limitation after retry

**Steps to reproduce**

Not sure how to reproduce, we observe it in our environemnt when receiver instance is memory pressured

**What did you expect to see?**

I expect that receiver will try to resend data after some time, or put it back to sending queue

**What did you see instead?**

I see that data is dropped

**What version did you use?**

`v0.81.0`

**What config did you use?**

```
exporters:                                                                                                                                                                                                                                                                                                                                                                                                                            
  otlphttp:                                                                                                                                                                                                                                                                                                                                                                                                                           
    endpoint: ...                                                                                                                                                                                                                                                                                                                                                       
    retry_on_failure:                                                                                                                                                                                                                                                                                                                                                                                                                 
      max_elapsed_time: 600s                                                                                                                                                                                                                                                                                                                                                                                                          
    sending_queue:                                                                                                                                                                                                                                                                                                                                                                                                                    
      queue_size: 1000                                                                                                                                                                                                                                                                                                                                                                                                                
      storage: file_storage
```

**Environment**
N/A

**Additional context**
N/A
