### ISSUE TITLE
[Question] Regarding High Availability

### ISSUE THREAD

**Issue by tpwong** [open-telemetry/opentelemetry-collector#8212]
Hello everyone, I am currently using otel-collector-contri v0.82.0. I have successfully used the loadbalancingexporter that helps me to distribute tracing load balancing. Assuming there are three servers behind me receiving load-balanced tracing. However, I have a question, if one of these three servers goes down, will the loadbalancingexporter be able to distribute all tracings to the other two servers?

Of course, I understand that if one server goes down, the loadbalancingexporter won't know immediately. Is there a heartbeat mechanism behind the loadbalancingexporter? Will it check whether the server is operating normally at intervals (for example, every 30 seconds)? If a server goes down, the tracings entering the loadbalancingexporter will no longer be distributed to the downed server. This can ensure that there will be no loss of tracings.

I hope to implement the above features, but I haven't been successful so far. I would like to ask whether it's a problem with my configuration or if this feature is not currently supported? Here is my configuration, thank you.

otel-collector-contri, config.yaml

```
extensions:
  health_check:
  pprof:
  zpages:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  loadbalancing:
          #routing_key: "service"
    protocol:
      otlp:
        timeout: 1s
        tls:
          insecure: true
    resolver:
      static:
        hostnames:
          - HostnameA:4317
          - HostnameB:4317
          - HostnameC:4317

service:
  extensions: [pprof, zpages,health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [loadbalancing, logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loadbalancing, logging]
```
