### ISSUE TITLE
Password containing `$` doesn't work when passed via `${env:DB_PASSWORD}`

### ISSUE THREAD

**Issue by wand2016** [open-telemetry/opentelemetry-collector#8215]
### Component(s)

receiver/postgresql

### What happened?

Password containing `$` doesn't work when passed via `${env:DB_PASSWORD}`.
When passed directly, it works.

## Steps to Reproduce

1. Prepare PostgreSQL DB:
   - username: `user`
   - password: `p@s$w0rd`
2. Configure postgresql receiver:

```yaml
  postgresql:
    ...
    username: "${env:DB_USERNAME}"
    password: "${env:DB_PASSWORD}"
```

3. Pass environment variables to OpenTelemetry CR:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
...
spec:
  config: <configuration mentioned above>
  env:
    - name: DB_USERNAME
      value: user
    - name: DB_PASSWORD
      value: p@s$w0rd
```

## Expected Result

Authentication passes.

## Actual Result

Authentication fails.

Given password directly, authentication passes.

```yaml
  postgresql:
    ...
    username: "${env:DB_USERNAME}"
    password: "p@s$$w0rd"
```

### Collector version

otel/opentelemetry-collector-contrib:0.81.0

## Environment

contrib Docker Image
