### ISSUE TITLE
Excessively high memory usage when using client-side zstd compression in confighttp

### ISSUE THREAD

**Issue by swiatekm** [open-telemetry/opentelemetry-collector#8216]
**Describe the bug**
We've added zstd support to the server side of confighttp in #7927. I rolled this out for OTLP traffic between an agent and a gateway in a K8s environment and saw very significant increase in memory consumption on the client side.

**Steps to reproduce**
I have some memory profiles saved of this, and I'm planning to create a self-contained reproduction, ideally with just synthetic benchmarks.

**What did you expect to see?**
Memory consumption in the ballpark of what other compression methods use.

**What did you see instead?**
Memory consumption for otlphttp exporter using zstd more than 10x the amount for gzip.

**What version did you use?**
Version: 0.82.0

**What config did you use?**
The relevant part:
```yaml
exporters:
  otlphttp:
    endpoint: ...
    compression: zstd
processors:
   batch:
    send_batch_max_size: 2000
    send_batch_size: 1000
    timeout: 1s
```

**Environment**
Kubernetes 1.24, EKS to be precise.

**Additional context**
 I'm reporting this as is so it doesn't get lost and to consolidate reports in case other users experience this. Will update with more data once I'm able to.
