### ISSUE TITLE
Using Secrets instead of using actual values "username/password"  for exporter authorization

### ISSUE THREAD

**Issue by mbasha86** [open-telemetry/opentelemetry-collector#8354]
**Is your feature request related to a problem? Please describe.**
We are using otel exporter to collect traces and export it to data-prepper instance. For autherization against data-prepper pipeline, otel is using actual values of username and password as per below:

```
config:
  exporters:
    logging:
      loglevel: info
    otlp:
      endpoint: dataprepper:xxxx
      headers:
        authorization: Basic <%= Base64.strict_encode64("#{["data-prepper"].username)}:#{(["data-prepper"].password)}")%>
      tls:
        ca_file: /ssl/ca.crt
```

So, instead we would like to use secrets for autherizations against data-prepper pipeline per below for example:

```
config:
  exporters:
    logging:
      loglevel: info
    otlp:
      endpoint: dataprepper:xxxx
      authorization:
         secret-namespace: xxx
         secret-name: yyy
         secret-key: zzz
      tls:
        ca_file: /ssl/ca.crt
```

**Describe the solution you'd like**
we would like to use secrets instead of actual values for autherizations against data-prepper pipeline per below for example:

```
config:
  exporters:
    logging:
      loglevel: info
    otlp:
      endpoint: dataprepper:xxxx
      authorization:
         secret-namespace: xxx
         secret-name: yyy
         secret-key: zzz
      tls:
        ca_file: /ssl/ca.crt
```
