### ISSUE TITLE
Decompressor is not installed for grpc-encoding "gzip"

### ISSUE THREAD

**Issue by reneweteling** [open-telemetry/opentelemetry-collector#8384]
**Describe the bug**
When starting otelcol it gives me this error:
```
exporterhelper/queued_retry.go:391#011Exporting failed. The error is not retryable. Dropping data.#011{"kind": "exporter", "data_type": "traces", "name": "otlp/elastic", "error": "Permanent error: rpc error: code = Unimplemented desc = grpc: Decompressor is not installed for grpc-encoding \"gzip\"", "dropped_items": 2}
```

**What version did you use?**
otelcol version 0.83.0

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
exporters:
  logging:
    loglevel: warn
  otlp/elastic:
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: xxx.apm.eu-central-1.aws.cloud.es.io:443
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer xxx"
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
```

**Environment**
OS: (e.g., "Ubuntu 20.04") 
Debian 11

**Additional context**
We have an identical server running version 0.54.0 and this one is running smoothly. My guess is that i need some additional packaging.
