### ISSUE TITLE
v0.85.0 fails to unmarshall jaeger exporter

### ISSUE THREAD

**Issue by tbuchaillot** [open-telemetry/opentelemetry-collector#8441]
**Describe the bug**
v0.85.0 fails to decode jaeger exporter. Collector logs:
```
2023-09-14 12:36:20 2023/09/14 10:36:20 collector server run finished with error: failed to get config: cannot unmarshal the configuration: 1 error(s) decoding:
2023-09-14 12:36:20 
2023-09-14 12:36:20 * error decoding 'exporters': unknown type: "jaeger" for id: "jaeger" (valid values: [zipkin logging otlp prometheus opencensus prometheusremotewrite otlphttp file kafka])
```

**Steps to reproduce**
Docker compose:
```
version: "2"
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
  # Collector
  collector-gateway:
    image: otel/opentelemetry-collector:0.85.0
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yml
    command: [ "--config=/etc/otel-collector.yml" ]
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"        # OTLP gRPC receiver
      - "4318:4318"        # OTLP HTTP receiver
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
```
otel-collector.yml:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
```
run: `docker compose up `
**What did you expect to see?**
Collector should work as it was working on 0.84.0

**What did you see instead?**
Collector fails to init.

**What version did you use?**
v0.85.0

**What config did you use?**
Config:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
```

**Environment**
Docker
OS: 
ProductName:		macOS
ProductVersion:		13.2
