### ISSUE TITLE
"Failed to open file" log message is defined as LogLevel Debug

### ISSUE THREAD

**Issue by AndiB42** [open-telemetry/opentelemetry-collector#8442]
Hello together,

**Describe the bug**
The LogMessage is describing an Error-Message, but the message itself is logged by LogLevel `Debug` which is not enabled by default and which leads to long troubleshooting-sessions.

**Steps to reproduce**
- Configure Filelog receiver with defaults
- Change the permission to a logfile in that way, that the opentelemetry collector has no read-permission on it. (That's the original error i was searching for.... i have no idea why these permissions are not correct, but take it as given for this issue)
- Set the LogLevel to `Debug` as described in [this guide](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#logs)

**What did you expect to see?**
I'd have expected to see the ERROR Logs with LogLevel Error - so there should be no need to set the LogLevel to Debug

**What did you see instead?**
This exact error message:
```
2023-09-14T15:13:52.018Z    debug    fileconsumer/file.go:129    Consuming files    {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
2023-09-14T15:13:52.018Z    debug    fileconsumer/file.go:200    Failed to open file%!(EXTRA zapcore.Field={error 26 0  open /var/log/pods/<pod>/<container>/0.log: permission denied})    {"kind": "receiver", "name": "filelog", "data_type": "logs", "component": "fileconsumer"}
```

**What version did you use?**
docker.io/otel/opentelemetry-collector-contrib:0.80.0

**What config did you use?**
There is a pod where the logs should be gathered. 
On the same pod, there is a OpenTelemetryCollector as a sidecar container
The Sidecar Container has a VolumeMount on the Node's /var/log/pods and is configured with this configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  namespace: default
data:
  config.yaml: |
    receivers:
      filelog:
        include:
          - /var/log/pods/<pod>/<container>/*.log
        start_at: beginning
        include_file_path: true
        include_file_name: true
        operators:
          - type: router
            id: get-format
            routes:
              - output: parser-docker
                expr: 'body matches "^\\{"'
              - output: parser-crio
                expr: 'body matches "^[^ Z]+ "'
              - output: parser-containerd
                expr: 'body matches "^[^ Z]+Z"'
          # Parse CRI-O format
          - type: regex_parser
            id: parser-crio
            regex:
              '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*)?(?P<log>.*)$'
            #output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout_type: gotime
              layout: '2006-01-02T15:04:05.999999999Z07:00'
          # Parse CRI-Containerd format
          - type: regex_parser
            id: parser-containerd
            regex:
              '^(?P<time>[^ ^Z]+Z) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*)?(?P<log>.*)$'
            #output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          # Parse Docker format
          - type: json_parser
            id: parser-docker
            #output: extract_metadata_from_filepath
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%dT%H:%M:%S.%LZ'
          - type: move
            from: attributes.log
            to: body
    processors:
    exporters:
      otlp:
        endpoint: my-otelcol.my-otelcol.svc.cluster.local:4317
        tls:
          insecure: true
          insecure_skip_verify: true
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        logs:
          receivers: [filelog]
          processors: []
          exporters: [otlp]
```

**Environment**
The pod is running in a Kubernetes Cluster v1.25.9-eks-0a21954 (EKS in AWS)
