### ISSUE TITLE
Collector does not send pending traces on shutdown

### ISSUE THREAD

**Issue by its-felix** [open-telemetry/opentelemetry-collector#8509]
## DISCLAIMER
I'm not 100% sure if this is a bug in the collector or a configuration issue on my side somewhere in the chain.

**Describe the bug**
I'm using the collector as a AWS Lambda extension as described. My Lambda is providing an HTTP Server via Function URL.
I currently run the API in a low volume scenario. There are only a few invocations per hour.

Even though I configured my application with `sdktrace.WithSampler(sdktrace.AlwaysSample()),`, I don't see any traces in this low-volume scenario. When invoking the API manually multiple times, I see all traces except for the last few appearing.

I suspect this might be due to traces not being sent by the collector on shutdown, but I'm not entirely sure about this.

**Steps to reproduce**
I'm not aware of any specific steps to reproduce - I could simply not get it to work in low-volume scenarios.

**What did you expect to see?**
With the sampling config `sdktrace.WithSampler(sdktrace.AlwaysSample()),` in my application, I expect traces to always appear.

**What did you see instead?**
No traces.

**What version did you use?**
I see this issue since I started to use the collector. The most recent deployment is using https://github.com/open-telemetry/opentelemetry-lambda/tree/08179bd54f386be5736d6260264852e9f31a16b1
(see https://github.com/gw2auth/gw2auth.com-monorepo/tree/566c5a9319490e8f482ef21e7a0ad02e9b916196)

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    verbosity: detailed
  otlphttp:
    endpoint: "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"
    headers:
      authorization: ${env:GRAFANA_CLOUD_AUTH}

service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlphttp]
    logs:
      receivers: [otlp]
      exporters: [logging, otlphttp]
```

**Environment**
Lambda Runtime: `Runtime.PROVIDED_AL2`
GOOS: `linux`
GOVERSION: `^1.20.4`
GOARCH: `amd64`

**Additional context**
- I'm using Grafana Cloud, the traces are sent via otlphttp (see config)
- The application running inside Lambda uses the following otel configuration: https://github.com/gw2auth/gw2auth.com-api/blob/188476d3ba8a7b9a7bc65793ec7a30298b32db92/otel.go
- The Lambda will currently receive a request at most every 15min (if not manually invoked more than that)
