### ISSUE TITLE
Get server response from Collector after sending data to backend

### ISSUE THREAD

**Issue by oulfik** [open-telemetry/opentelemetry-collector#8623]
I have currently configured my Otel Collector to send traces data from the adservice (Otel-demo service) to AppDynamics over a proxy. My problem is that AppDynamics doesn't show any ingested data in the Otel section (No Data available). The collector logs show no errors. Is there maybe an option to log the server response? I tried the zpages extension but it wasn't helpful. Currently I am only getting a generic debug message in the collector logs:

```
2023-10-04T12:39:03.931Z	debug	otlphttpexporter@v0.80.0/otlp.go:116	Preparing to make HTTP request	{"kind": "exporter", "data_type": "traces", "name": "otlphttp", "url": "https://some-agent-api.saas.appdynamics.com/v1/traces"}
```
Here is the complete collector logfile:
[collector-log.txt](https://github.com/open-telemetry/opentelemetry-collector/files/12803473/collector-log.txt)

This is my collector configuration:
```
config: |
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  processors:
      resource:
      attributes:
      - key: appdynamics.controller.account
        action: upsert
        value: "company"
      - key: appdynamics.controller.host
        action: upsert
        value: "company.saas.appdynamics.com"
      - key: appdynamics.controller.port
        action: upsert
        value: 443

    batch:
      send_batch_size: 90
      timeout: 30s

  exporters:
    otlphttp:
      endpoint: "https://some-agent-api.saas.appdynamics.com"
      headers: {"x-api-key": "<some-api-key>"}

     logging:
      verbosity: detailed
      sampling_initial: 10
      sampling_thereafter: 5

  extensions:
    zpages: 
  service:
    telemetry:
      logs:
        level: debug
    extensions: [zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [resource, batch]
        exporters: [logging, otlphttp]

env:
- name: HTTPS_PROXY
  value: proxy.company.com:8080
```
