### ISSUE TITLE
Go install builder installs dev version instead of the specified version

### ISSUE THREAD

**Issue by robinlindberg** [open-telemetry/opentelemetry-collector#8691]
After some further investigating I believe it is not my setup that is causing this issue, so I moved it from Discussions to Issues.
I also split it to 2 separate issues, since they don't seem related.

**Describe the bug**
I can't currently install any specific version of the builder.

**Steps to reproduce**
go install go.opentelemetry. io/collector/cmd/builder@v0.86.0
builder version

**What did you expect to see?**
ocb version 0.86.0

**What did you see instead?**
ocb version dev

**What version did you use?**
Version:  v0.86.0

**What config did you use?**
Config: yaml
```yaml
dist:
  name: otel-collector.exe
  otelcol_version: 0.86.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.86.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.86.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.86.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.86.0

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.86.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.86.0
```

**Environment**
OS: Win 11 Version 10.0.22621
Compiler: go 1.21.3

### Discussed in https://github.com/open-telemetry/opentelemetry-collector/discussions/8668

<div type='discussions-op-text'>

<sup>Originally posted by **robinlindberg** October 11, 2023</sup>
This might be two separate bugs.

I am unable to install a specific version of the builder. I always get "dev" which seems to be the default value the version.go file sets.

![image-2023-10-11-15-59-19-589](https://github.com/open-telemetry/opentelemetry-collector/assets/19304676/b011b82f-3eaa-4ccd-ab61-e5c3cdc1e9b7)

I suspected the builder version being wrong was the cause of the go.mod being filled with both 0.86.0 and 0.87.0 versions. But now I tried using the binaries of the builder directly, instead of doing Go install. I got the same result when building for the non-latest version, e.g. 0.86.0. Building for the latest version works in both scenarios.
![image](https://github.com/open-telemetry/opentelemetry-collector/assets/19304676/848c642b-84f5-49a0-82d6-2550ab5fccf9)
![image](https://github.com/open-telemetry/opentelemetry-collector/assets/19304676/00eeb33f-0867-4c1a-a653-672922f512b1)

Does anyone have any clue what this might be caused by?

What I have tried:
- Uninstalling Go
- Clearing out all files from GOPATH
- If I instead refer to the latest version, it builds just fine
- Running everything as a Github action and try building there, completely separate from my machine. Same behavior.
- Using the builder binary directly instead of using Go install

</div>
