### ISSUE TITLE
x-scope-orgid is not getting fetched dynamically using from_context in headers_setter extension in otel collector while using tempo in multitenant mode?

### ISSUE THREAD

**Issue by SimranCode** [open-telemetry/opentelemetry-collector#8714]
I am trying to setup multi tenant env for Grafana tempo and Loki using Open telemetry Collector , It works fine when I hard code the value of key X-Scope-OrgID in the headers setter , but when I try to fetch the value dynamically through the context , it dosnt work.

I am passing the X-Scope-OrgID value in the request metadata of my dot net application . I also tried Setting the value as an attribute and tag of an activity. But no luck. Could someone please help in figuring out what wrong I am doing. 

  Could you please assist on how to pass the value to the headers_setter extension from application context dynamically. or if there is any other better way to achieve this. ?

Below is the dot net code where I am using a middleware to add the X-Scope-OrgID in the httpcontext for all the incoming and outgoing requests : 
```
 app.Use(async (context, next) =>
        {
            string tenantId = "tenant1"; 
            context.Items["X-Scope-OrgID"] = tenantId;
            context.Request.Headers["X-Scope-OrgID"] = tenantId;
            context.Response.Headers["X-Scope-OrgID"] = tenantId;
            await next();
        });
```
 Below is my Otel Collector config: 
```
version: '3.8'
extensions:
  headers_setter:
    headers:
      - action: upsert
        key: X-Scope-OrgID
        from_context: X-Scope-OrgID
receivers:
  otlp:
    protocols:
      grpc:
        include_metadata: true
        endpoint: 0.0.0.0:5555
      http:
        include_metadata: true        
      
      

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    
   
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true
    auth:
      authenticator: headers_setter  


  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
    format: proto

  file:
    path: /etc/output/logs.json

processors:
    

service:
  extensions: [headers_setter]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, zipkin]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]
```
