### ISSUE TITLE
[confmap] resolver cannot resolve the configuration with ${env:abc} in in-process collector

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-collector#8757]
**Describe the bug**

I included `${env:abc}` in a config yaml file, used it in the config provider, and started a collector binary programmatically in a test. Got an error from resolver:

> failed to resolve config: cannot resolve the configuration: scheme "env" is not supported for uri "env:ENDPOINT"

This is from https://github.com/open-telemetry/opentelemetry-collector/blob/2511161c7d8f94300c775be69c58537a5feba181/confmap/resolver.go#L203

**Steps to reproduce**

A simple reproduce example with a conf.yaml:
```yaml
receivers:
  otlp:
    protocols:
      http:
        endpoint: ${env:ENDPOINT}

processors:
  batch:

exporters:
  logging:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
```

Test function:
```go
func TestConf(t *testing.T) {
	factories := getComponents(t)
	t.Setenv("ENDPOINT", "test")
	fmp := fileprovider.New()
	configProvider, err := otelcol.NewConfigProvider(
		otelcol.ConfigProviderSettings{
			ResolverSettings: confmap.ResolverSettings{
				URIs:      []string{"conf.yaml"},
				Providers: map[string]confmap.Provider{fmp.Scheme(): fmp},
			},
		})
	require.NoError(t, err)

	appSettings := otelcol.CollectorSettings{
		Factories:      factories,
		ConfigProvider: configProvider,
		BuildInfo: component.BuildInfo{
			Command:     "otelcol",
			Description: "OpenTelemetry Collector",
			Version:     "tests",
		},
	}

	app, err := otelcol.NewCollector(appSettings)
	require.NoError(t, err)
	require.NoError(t, app.Run(context.Background()))
	defer app.Shutdown()
}

func getComponents(t *testing.T) otelcol.Factories {
	var (
		factories otelcol.Factories
		err       error
	)
	factories.Receivers, err = receiver.MakeFactoryMap(otlpreceiver.NewFactory())
	require.NoError(t, err)
	factories.Processors, err = processor.MakeFactoryMap(batchprocessor.NewFactory())
	require.NoError(t, err)
	factories.Exporters, err = exporter.MakeFactoryMap(loggingexporter.NewFactory())
	require.NoError(t, err)
	return factories
}
```

Output:
```bash
        	Error:      	Received unexpected error:
        	            	failed to resolve config: cannot resolve the configuration: scheme "env" is not supported for uri "env:ENDPOINT"
        	Test:       	TestConf
```

**What version did you use?**
v0.88.0
