### ISSUE TITLE
Duplicate span.kind tag warnings in Jaeger UI

### ISSUE THREAD

**Issue by sleighzy** [open-telemetry/opentelemetry-collector#878]
Spans containing the "span.kind" tag can be sent to the Jaeger receiver, which are then translated to the associated span kind in the internal protobuf format. These are then sent to the Jaeger Collector when using the Jaeger exporter. Viewing these spans within the Jaeger UI however displays warnings stating that the span.kind tag is duplicated as per the screenshot below. It seems that the span.kind tag is translated and sent to the Jaeger exporter as the span kind, but the original tag is still sent as well?

Screenshot showing expected behaviour, spans sent to the Jaeger agent.

<img width="1689" alt="Using Jaeger agent" src="https://user-images.githubusercontent.com/4580060/80351764-f98eaa00-88c6-11ea-9dd8-1ac7a528d4d5.png">

Screenshot showing actual behaviour, spans sent to the OpenTelemetry Collector.

<img width="1689" alt="Using OTel Collector" src="https://user-images.githubusercontent.com/4580060/80351822-10cd9780-88c7-11ea-8dd1-3cb74cc845ec.png">

This behaviour occurs when sending spans to the OTel collector using either gRPC, thrift http, thrift binary (UDP) based on the clients I've tested with.

***Collector Version*** This does not appear to be an issue in the 0.3.0 release of the OTel collector but the change in behaviour has been introduced recently in the last day or so in the `opentelemetry-collector-dev` Docker container.

**Comment by tigrannajaryan** [comment]
@sleighzy please attach Collector config file. Which Jaeger protocol do you use for receiveing and exporting?

**Comment by sleighzy** [comment]
OTel Collector config below. This is based on the demo example, but just if you need it. I revisited this again and see that I should have been using the `opentracing-shim` from the `opentelemetry-js` repo (there really are a lot of repos) for the Nodejs stuff, see https://github.com/open-telemetry/opentelemetry-js/tree/master/examples/opentracing-shim. The JaegerExporter there should be using thrift_binary on port 6832. I started with the example in that repository (think there is another unrelated bug in there I can raise a PR for) and there is no longer a duplicate span issue for the span kind. What I do experience now is that the `span.kind` value in Jaeger is constantly displayed as `INTERNAL`, even if I explicitly set the tag "`span.kind`" with a value of "`client`" directly within the test code from that `opentracing-shim` repo. Additionally there is now a duplicate tag warning for `status.code`, see the screenshot below.

I'll take my javascript shim questions to another forum re: loss of span.kind tags, but I still have the remaining question for the collector itself around the duplicated `status.code`.

```
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14251
      thrift_http:
        endpoint: 0.0.0.0:14268
      thrift_binary:
        endpoint: "0.0.0.0:6832"
  otlp:
    endpoint: 0.0.0.0:55680

exporters:
  jaeger:
    endpoint: "jaeger-collector:14250"

processors:
  batch:
  queued_retry:

service:
  pipelines: # section that can contain multiple subsections, one per pipeline
    traces: # type of the pipeline
      receivers: [jaeger]
      processors: [batch, queued_retry]
      exporters: [jaeger]
```
