### ISSUE TITLE
Question about memory_limiter in examples/local/otel-config.yaml

### ISSUE THREAD

**Issue by katepangLiu** [open-telemetry/opentelemetry-collector#8837]
examples/local/otel-config.yaml
```
processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
```

In my opinion, `1536 is 25% maximum of  memory up to 4G `, did I misunderstand?

**Comment by astencel-sumo** [comment]
Well spotted. My guess is it was supposed to be `75% of maximum memory up to 2G`:

```yaml
processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 2G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s
```

Would be great if you could raise a pull request for this @katepangLiu, do you think you can do that?
