### ISSUE TITLE
custom build collector panics if it doesn't include extensions

### ISSUE THREAD

**Issue by ymotongpoo** [open-telemetry/opentelemetry-collector#8842]
**Describe the bug**
I built a custom collector without any extensions by running ocb with the following config (`otelcol-builder.yaml`):

```yaml
dist:
  module: github.com/ymotongpoo/opentelemetry-collector-extra/builder
  name: otelcol-custom
  description: Custom OpenTelemetry Collector binary
  output_path: .

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.88.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.88.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.88.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.88.0
```

And I started the custom collector with the following config (`otel-config.yaml`):

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```

Because this is a very simple demo and I don't need extensions, I didn't include extensions in the builder config and collector config.

**Steps to reproduce**

1. Write `otelcol-builder.yaml` as shown above
2. Run ocb (`builder --config=otelcol-builder.yaml`)
3. Run the custom collector (`./otelcol-custom --config=otel-config.yaml`)

**What did you expect to see?**
The custom collector starts without any errors.

**What did you see instead?**
The following stack trace of panic:

```
2023-11-11T21:53:27.650+0900    info    service@v0.88.0/telemetry.go:84 Setting up own telemetry...
2023-11-11T21:53:27.652+0900    info    service@v0.88.0/telemetry.go:201        Serving Prometheus metrics      {"address": ":8888", "level": "Basic"}
2023-11-11T21:53:27.653+0900    info    exporter@v0.88.0/exporter.go:275        Development component. May change in the future.        {"kind": "exporter", "data_type": "metrics", "name": "debug"}
2023-11-11T21:53:27.653+0900    info    service@v0.88.0/service.go:143  Starting otelcol-custom-macos...        {"Version": "1.0.0", "NumCPU": 10}
2023-11-11T21:53:27.653+0900    info    extensions/extensions.go:33     Starting extensions...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x105790ba4]

goroutine 1 [running]:
go.opentelemetry.io/collector/service/internal/graph.(*receiverNode).Start(0x140005f3950?, {0x1086bfe00?, 0x10a1f2fe0?}, {0x1086c00a0?, 0x140005268c0?})
        <autogenerated>:1 +0x34
go.opentelemetry.io/collector/service/internal/graph.(*Graph).StartAll(0x140008f6780, {0x1086bfe00, 0x10a1f2fe0}, {0x1086c00a0, 0x140005268c0})
        go.opentelemetry.io/collector/service@v0.88.0/internal/graph/graph.go:391 +0x178
go.opentelemetry.io/collector/service.(*Service).Start(0x140008e4500, {0x1086bfe00, 0x10a1f2fe0})
        go.opentelemetry.io/collector/service@v0.88.0/service.go:161 +0x24c
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0x14000892000, {0x1086bfe00, 0x10a1f2fe0})
        go.opentelemetry.io/collector/otelcol@v0.88.0/collector.go:186 +0x4d4
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0x14000892000, {0x1086bfe00, 0x10a1f2fe0})
        go.opentelemetry.io/collector/otelcol@v0.88.0/collector.go:221 +0x3c
go.opentelemetry.io/collector/otelcol.NewCommand.func1(0x14000888000, {0x1072d6e09?, 0x7?, 0x1072d2e61?})
        go.opentelemetry.io/collector/otelcol@v0.88.0/command.go:27 +0x70
github.com/spf13/cobra.(*Command).execute(0x14000888000, {0x140001be010, 0x1, 0x1})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x14000888000)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(0x140006ad620?)
        github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.runInteractive({{0x140006ad620, 0x140006ad680, 0x140006ad650, 0x140006ad5f0, 0x140006ad6b0}, {{0x1072f625e, 0x14}, {0x107332e59, 0x25}, {0x1072d3c0d, ...}}, ...})
        github.com/ymotongpoo/opentelemetry-collector-extra/builder/main.go:31 +0x40
main.run(...)
        github.com/ymotongpoo/opentelemetry-collector-extra/builder/main_others.go:11
main.main()
        github.com/ymotongpoo/opentelemetry-collector-extra/builder/main.go:24 +0x134
```

**What version did you use?**
Version: 0.88.0 (Custom build)

**What config did you use?**

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```

**Environment**
OS: macOS 14.1
Compiler(if manually compiled): Go 1.21.4

**Additional context**
N/A
