### ISSUE TITLE
[receiver/otlpreceiver] optional configuration to deny unidentified telemetry

### ISSUE THREAD

**Issue by jwafle** [open-telemetry/opentelemetry-collector#9023]
**Is your feature request related to a problem? Please describe.**
OpenTelemetry collectors can be used to collect metrics from multiple applications at once. In use cases where you are collecting telemetry from services that you may not own, it can be very important to ensure that you are able to identify the services from which you are receiving telemetry signals. Currently, as far as I am aware, [`service.name`](https://opentelemetry.io/docs/specs/semconv/resource/#service) appears to be the best _required_ identifier of what service is sending telemetry to a given collector.

For many use cases, it makes sense to refuse to accept telemetry signals that do not have identifying information (e.g. `service.name`). Currently, the collector can be configured using the [`filterprocessor`](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor) to drop telemetry that does not have a `service.name`. However, there is no way, as far as I am aware, to warn services that are publishing to the collector that their telemetry data is being dropped by the `filterprocessor`, or any other processor.

**Describe the solution you'd like**
I believe that there should be some _optional_ method for configuring OTLP receivers to refuse to accept telemetry data with no identifying information. Essentially, my proposed solution looks something like:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        require_service_name: true
      http:
        require_service_name: false
        endpoint: "localhost:4318"
        cors:
          allowed_origins:
            - http://test.com
            # Origins can have wildcards with *, use * by itself to match any origin.
            - https://*.example.com
          allowed_headers:
            - Example-Header
          max_age: 7200
```

where `require_service_name` is an optional configuration parameter of the HTTP and gRPC OTLP receivers. The expected behavior would be to return a status code indicating bad request if this option is enabled for the given protocol. This would prevent situations where unidentified telemetry signals enter the pipeline and it can become very difficult to assess who sent them.

While I understand that SDKs are supposed to generate `service.name` as it is a required field in the semantic conventions, I believe that some validation of that requirement should be able to be enabled in the processor.
   
**Describe alternatives you've considered**
The `filterprocessor` can achieve part of this functionality by simply dropping telemetry that is missing `service.name`, but this does not do anything to indicate that there is an issue to the publisher(s) of said telemetry. Additionally, IP traffic could be used to attempt to figure out which machines are sending unidentified telemetry, but this solution would be much more robust.

**Additional context**
This is my first time submitting an issue, so please excuse any mistakes I may have made in the process. Also, I would very much be willing to submit a PR related to this issue if a supportive consensus is reached. 

Additionally, as far as I am aware, there is no validation of any semantic convention required fields at the processor level. If there is and I am simply missing it, please let me know. I would like to troubleshoot
