### ISSUE TITLE
Define data flow directly between components

### ISSUE THREAD

**Issue by djaglowski** [open-telemetry/opentelemetry-collector#9077]
## Is your feature request related to a problem? Please describe.

Connectors provide a variety of capabilities within the collector:
- Sequencing of pipelines, including merging and replicating data streams. (e.g. process data, replicate, process more in differing ways)
- Conditional data flow (e.g. routing, failover)
- Deriving new data streams from old (e.g. span metrics)
- Correlated data processing (e.g. sample by resource)

Most importantly, these capabilities respect the collector's pipeline model, which has been used since inception. Prior to connectors, the above problems required novel exceptions to the pipeline model.

While I firmly believe connectors are the correct technical solution for the capabilities above, they clearly introduce a corresponding increase in configuration complexity _in order to respect the pipeline model_.

## Describe the solution you'd like

It should be possible to define data flow directly between components without _explicitly_ managing pipelines. (e.g. Component A sends data to Component B. Component B sends data to Components D and E).

My proposed solution would preserve the pipeline model exactly as it is and build an optional simplified abstraction on top of it. Users could continue using the pre-existing pipelines syntax, or opt into this simplified syntax.

Using an example to illustrate the difference in configuration, consider the following set of connected pipelines:

<img width="1223" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector/assets/5255616/3f4c493f-bea9-4a1f-8bae-fafd8107bc69">

The current way to configure this would be:

```yaml
service:
  pipelines:
    logs/in:
      receivers: [otlp]
      processors: [redact]
      exporters: [routing]
    logs/cold:
      receivers: [routing]
      processors: [batch]
      exporters: [count, cold]
    logs/hot:
      receivers: [routing]
      processors: [label]
      exporters: [hot]
    metrics/hot:
      receivers: [count]
      exporters: [hot]
```

The proposed alternative would look like this:

```yaml
service:
  dataflow:
    logs:
      otlp:    [redact]
      redact:  [routing]
      routing: [label, batch]
      label:   [hot]
      batch:   [count, cold]
    metrics:
      count:   [hot]
```

## How this can be accomplished

Initially, I propose adding a feature gate, which when enabled results in the following:
1. Processors and connectors are merged into a single class of components. Specifically, each processor type would be 
automatically wrapped into an equivalent connector type. e.g. a metrics processor becomes a metrics-to-metrics connector. We may enforce that all processors and connectors be declared under a single section (likely `processors`). Or, we can just automatically merge `processors` and `connectors` for compatibility with the current paradigm.
2. `service::pipelines` may not be specified. Instead, users must specify `service::traces`, `service::metrics`, and `service::logs`. These new sections can be thought of roughly as _sets of edges_ in a component graph.
3. The exact syntax for defining edges should be debated, but importantly, every edge must have both a _direction_ and a _data type_. As a concrete proposal, I suggest `from: [ to1, to2, ... ]` where the key is a component _from_ which data flows and the values are the components _to_ which data flows. In this style, exporters may never be used as keys, and receivers may never be used as values.
4. The set of edges are automatically interpreted into a set of connected pipelines. The data type of the pipeline comes from the type sections in which the edge is listed. The name of the pipeline is autogenerated. In the specific edge format proposed above, the name could be that of the component from which data flows. e.g. `logs/routing` is a pipeline with `receivers: [routing]` and `exporters: [label, batch]`.

The net effect of the above is that we autogenerate a set of pipelines, while allowing the user to reason only about the components and the data types which flow between them. The autogenerated pipelines for the above example look like this:

<img width="1231" alt="image" src="https://github.com/open-telemetry/opentelemetry-collector/assets/5255616/2193a61d-02c6-4599-a518-e4027baf2e84">

## What is actually different between the two?

In short, very very little. The proposed configuration is intended to be as close to syntactic sugar as possible. However, a few nuances should be noted.

### Processor Instancing

In the current model, we treat processors a bit differently than other components. Specifically, processors are _instanced_ per pipeline. This has the effect that a single processor _configuration_ may be used in separate pipelines, while still ensuring that data flowing through each processor _instance_ is kept separate. This is a useful property of processors, but I think it is not widely recognized, and therefore may not be widely used.

In the proposed model, where each processor is wrapped into a connector, instances are _not_ unique to a pipeline. Rather, they are shared by pipelines. This is an artifact of the way receivers and exporters work, which was inherited by connectors. The downside then is that _if_ a user wishes to have separate instances of a processor, they must actually specify multiple configurations, even if they are exactly the same. This can be mitigated by using yaml anchors, for example, or if we adopt templated processors in the future. The upside here is that all components now share the same instancing model.

### Processor ID Collisions w/ Receivers & Exporters

One minor constraint placed on the naming of connectors is that there cannot be ambiguity between connector IDs and either receiver or exporter IDs. e.g. If we had a connector and receiver both called `nop/1`, we would not know which is being used in a pipeline configuration. This is automatically detected and rejected at run time, though in practice it is very unlikely to be a problem, as it would first be necessary to share a common "type".

In the proposed model, since processors are automatically wrapped into connectors, they would adopt this limitation as well.

### Routing Connectors

Routing connectors are those which send data conditionally to downstream pipeline. Currently, these require that pipeline IDs are specified for specific outputs. Fortunately, the data type for a pipeline ID is `component.ID`, so we should be able to accept specific component IDs instead, when using this syntax.

### Data Types

Users must still reason about data types. It is possible that this could lead to some confusion, but I suspect it will be easy to adapt to. Cases which require only a single data type should remain very easy. For those which require multiple types, it is only necessary to understand which data types may be sent to the component, and correspondingly which data types may flow out of it. e.g. I can only send traces to `spanmetrics` and I expect to get metrics out of it.

### Component Class Placement

The relationship between component classes is naturally handled by the automatic conversion to pipelines. Simple rules can be made clear. e.g. in the proposed `from: [ to1, to2, ... ]` style, receivers may only be used as keys, and exporters only as values.

### Graph Considerations

Cycles and fanouts are automatically handled within the existing pipeline system, so no special handling must be introduced. 

### Processor / Connector Type Collisions

Some processors and connectors share the same "type". e.g. `spanmetrics`. For this reason, if we merge the `processors` and `connectors` sections _in configuration_, we could introduce ambiguity. Instead, we may wish to just allow both, and merge them at run time. We would still have to reject ambiguous _IDs_. e.g. Cannot define a processor called `spanmetrics/foo` and also a connector called the same.

### Alternate Edge Definition Models

There are various other ways in which we could define edges. Again, as long as each edge has a clear _direction_ and a _data type_, we can easily autogenerate corresponding pipelines. Other examples:

```yaml
# proposed model - from 1 : to N
service:
  dataflow:
    logs:
      from: [ to1, to2, ...]

# inverse of proposed model - to N : from 1
service:
  dataflow:
    logs:
      to: [ from1, from2, ... ]

# matrix model - from N : to M
service:
  dataflow:
    logs:
      - from: [ from1, from2, ... ]
        to: [ to1, to2, ... ]

# singular edges - from 1 : to 1
service:
  dataflow:
    logs:
      from1: to1
      from2: to2

# mixed model
service:
  dataflow:
    logs:
      from:
        from1: [ to1, to2, ... ]
      to:
        to1: [ from1, from2, ... ]
```

**Comment by djaglowski** [comment]
Also see https://github.com/open-telemetry/opentelemetry-collector/pull/9078 as a working proof of concept.

**Comment by dmitryax** [comment]
Thank you for putting this together. This is interesting. A couple of ideas.

1. It's a bit unclear how the edges between different types are resolved. Let's say I have connectors supporting multiple types on both input and output. If I connect them together with the suggested configuration between particular types, I'd have to define several configurations per type explicitly to avoid ambiguity, right?

2. Having this under `service::[logs||metrics|trace]` is not very intuitive compared to `service::pipelines`. Maybe we can consider having `metrics_consumers`, `traces_consumers` and `logs_consumers` fields right in the configuration interface of all the components except for exporters where applicable? Something like:

```yaml
receivers:
  otlp:
    endpoint: ...
    logs_consumers: [redact]
connectors:
  redact:
    ...
    logs_consumers: [routing]
  routing:
    ...
    logs_consumers: [label, batch]
  label:
    ...
    logs_consumers: [hot]
  batch:
    logs_consumers: [cold, count]
  count:
    metrics_consumers: [hot]
    
exporters:
  hot:
    ...
  cold:
    ...
```

However, it might be hard to follow the data flow in big configuration files.

**Comment by djaglowski** [comment]
> It's a bit unclear how the edges between different types are resolved. Let's say I have connectors supporting multiple types on both input and output. If I connect them together with the suggested configuration between particular types, I'd have to define several configurations per type explicitly to avoid ambiguity, right?

Not sure I understand this but I think it should be fairly intuitive in practice. To use an examples:

Let's say we are using the count connector, which can ingest any data type and generates metrics. However, to match your scenario, let's suppose it also generates logs which describe the counts.

If we want to send traces and logs to the connector, and have it generate both metrics and logs, it would look like this:

```yaml
service:
  traces:
    otlp: [ count ] # I want to send spans to the connector
  logs:
    otlp: [ count ] # I want to send logs to the connector
    count: [ foo ] # I want the connector to generate logs
  metrics:
    count: [ foo ] # I want the connector to generate metrics
```

Is there redundancy here? I would argue no, since each edge has a clear and distinct effect on the behavior. In any case, it's no different than what we have now, except that it doesn't require the user to also reason about pipelines.

```yaml
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ count ]
    logs/in:
      receivers: [ otlp ]
      exporters: [ count ]
    logs/out:
      receivers: [ count ]
      exporters: [ foo ]
    metrics:
      receivers: [ count ]
      exporters: [ foo ]
```
