### ISSUE TITLE
kubeletstats lack labels

### ISSUE THREAD

**Issue by bon77** [open-telemetry/opentelemetry-collector#9111]
**Describe the bug**
I collect the `kubeletstats` following the documentation.
I can see them in the logs and  find them in Grafana (explore), but they do not have any labels attached to them.
For the node related metrics, I would expect to have the label `node_name` attached.

**Steps to reproduce**
Install the collector helm chart with the values below:
(I use kind, but I don't think that is of relevance)

```sh
helm install otel --namespace otel -f collector-values.yaml open-telemetry/opentelemetry-collector
```

**What did you expect to see?**
I expect to see a label containing the k8s.node.name, so that I can match the metrics in dash-boards etc.

```
2023-12-14T05:21:42.217Z    info    ResourceMetrics #0
Resource SchemaURL:
Resource attributes:
     -> k8s.node.name: Str(unkind-control-plane)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope otelcol/kubeletstatsreceiver 0.91.0
Metric #0
Descriptor:
     -> Name: k8s.node.cpu.time
     -> Description: Node CPU time
     -> Unit: s
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
**Data point attributes:
    -> node_name: Str(unkind-control-plane)**
StartTimestamp: 2023-12-14 01:30:48 +0000 UTC
Timestamp: 2023-12-14 05:21:42.012037899 +0000 UTC
Value: 3047.665864
Metric #1
Descriptor:
     -> Name: k8s.node.cpu.utilization
     -> Description: Node CPU utilization
[..]
```

**What did you see instead?**
```
2023-12-14T05:21:42.217Z    info    ResourceMetrics #0
Resource SchemaURL:
Resource attributes:
     -> k8s.node.name: Str(unkind-control-plane)
ScopeMetrics #0
ScopeMetrics SchemaURL:
InstrumentationScope otelcol/kubeletstatsreceiver 0.91.0
Metric #0
Descriptor:
     -> Name: k8s.node.cpu.time
     -> Description: Node CPU time
     -> Unit: s
     -> DataType: Sum
     -> IsMonotonic: true
     -> AggregationTemporality: Cumulative
NumberDataPoints #0
[..]
```

**What version did you use?**
v0.91.0
Helm chart version: opentelemetry-collector-0.77.0

**What config did you use?**
Config: (e.g. the yaml config file)
`collector-values.yaml`:

```yaml
nameOverride: ""
fullnameOverride: ""
mode: "deployment"
namespaceOverride: "otel"
presets:
  logsCollection:
    enabled: false
    includeCollectorLogs: false
    storeCheckpoints: false
    maxRecombineLogSize: 102400
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: false
    extractAllPodAnnotations: false
  kubeletMetrics:
    enabled: false
  kubernetesEvents:
    enabled: true
  clusterMetrics:
    enabled: true
configMap:
  create: true
config:
  exporters:
    debug/basic:
      verbosity: basic
    debug/normal:
      verbosity: normal
    debug/detailed:
      verbosity: detailed
  extensions:
    health_check: {}
    memory_ballast: {}
  processors:
    batch: {}
    memory_limiter: null
    k8sattributes: null
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:14250
        thrift_http:
          endpoint: ${env:MY_POD_IP}:14268
        thrift_compact:
          endpoint: ${env:MY_POD_IP}:6831
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    hostmetrics:
      collection_interval: 20s
      root_path: /hostfs
    kubeletstats:
      auth_type: 'serviceAccount'
      collection_interval: 20s
      endpoint: '${env:K8S_NODE_NAME}:10250'
      insecure_skip_verify: true
      metric_groups:
        - node
        - pod
        - container
    k8s_cluster:
    prometheus:
      config:
        scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
              - targets:
                  - ${env:MY_POD_IP}:8888
    zipkin:
      endpoint: ${env:MY_POD_IP}:9411
  service:
    telemetry:
      metrics:
        address: ${env:MY_POD_IP}:8888
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      metrics:
        exporters:
          - debug/detailed
        processors:
          - memory_limiter
          - batch
          - k8sattributes
        receivers:
          - otlp
          - prometheus
          - k8s_cluster
          - hostmetrics
          - kubeletstats
image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: ""
  digest: ""
imagePullSecrets: []
command:
  name: otelcol-contrib
  extraArgs: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
clusterRole:
  create: true
  annotations: {}
  name: ""
  rules:
    - apiGroups:
      - ''
      resources:
      - 'pods'
      - 'nodes'
      - 'nodes/stats'
      verbs:
      - 'get'
      - 'list'
      - 'watch'
  clusterRoleBinding:
    annotations: {}
    name: ""
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
priorityClassName: ""
extraEnvs:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.podIP
  - name: K8S_NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
extraEnvsFrom: []
extraVolumes: []
extraVolumeMounts: []
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  jaeger-compact:
    enabled: true
    containerPort: 6831
    servicePort: 6831
    hostPort: 6831
    protocol: UDP
  jaeger-thrift:
    enabled: true
    containerPort: 14268
    servicePort: 14268
    hostPort: 14268
    protocol: TCP
  jaeger-grpc:
    enabled: true
    containerPort: 14250
    servicePort: 14250
    hostPort: 14250
    protocol: TCP
  zipkin:
    enabled: true
    containerPort: 9411
    servicePort: 9411
    hostPort: 9411
    protocol: TCP
  metrics:
    enabled: false
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
resources:
  limits:
    cpu: 250m
    memory: 512Mi
podAnnotations: {}
podLabels: {}
additionalLabels: {}
hostNetwork: false
dnsPolicy: ""
dnsConfig: {}
replicaCount: 1
revisionHistoryLimit: 10
annotations: {}
extraContainers: []
initContainers: []
lifecycleHooks: {}
livenessProbe:
  httpGet:
    port: 13133
    path: /
readinessProbe:
  httpGet:
    port: 13133
    path: /
service:
  type: ClusterIP
  annotations: {}
ingress:
  enabled: false
  additionalIngresses: []
podMonitor:
  enabled: false
  metricsEndpoints:
    - port: metrics
  extraLabels: {}
serviceMonitor:
  enabled: false
  metricsEndpoints:
    - port: metrics
  extraLabels: {}
podDisruptionBudget:
  enabled: false
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  behavior: {}
  targetCPUUtilizationPercentage: 80
rollout:
  rollingUpdate: {}
  strategy: RollingUpdate
prometheusRule:
  enabled: false
  groups: []
  defaultRules:
    enabled: false
  extraLabels: {}
statefulset:
  volumeClaimTemplates: []
  podManagementPolicy: "Parallel"
networkPolicy:
  enabled: false
  annotations: {}
  allowIngressFrom: []
  extraIngressRules: []
  egressRules: []
useGOMEMLIMIT: true
```

**Environment**
OS: " Ubuntu 22.04.3 LTS"
ARCH: "x86_64"
Helm: "version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.20.10"}"

**Additional context**
What I want to achieve is:

Send these metrics to Mimir and use Grafana to display them.
For that to work, I need to get some relation between the node and the metrics.
