### ISSUE TITLE
Invalid tag value error

### ISSUE THREAD

**Issue by tobervenec** [open-telemetry/opentelemetry-collector#9118]
**Describe the bug**
Invalid tag value error is reported when one of metric attribute values is string that ends with backslash(es).

**Steps to reproduce**
Send metric with string attribute that ends with backslash (e.g. "path" : "C:\Temp\Subfolder\\") to otelcollector.
Error is reported

**What did you expect to see?**
No errors

**What did you see instead?**
An Error is reported about invalid tag value

**What version did you use?**
Version: otelcol-contrib_0.69.0_windows_amd64

**What config did you use?**
Config: yaml config file:

(Edit by @mx-psi  for formatting)

```yaml
receivers:
  otlp:
    protocols:
      http:
      
exporters:
  file:
    path: ./otel.json
    rotation:
        max_megabytes: 10
        
  influxdb:
    endpoint: //http://localhost:${INFLUXDB_PORT}
    timeout: 5s
    org: my-org
    bucket: my-bucket
    token: my-token
    metrics_schema: telegraf-prometheus-v1

    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000

    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 120s

service:
  telemetry:
    metrics:
      address: 0.0.0.0:0
    logs:
      level: info
      output_paths:
        - ./otel.log
        - stdout
      error_output_paths:
        - ./otel.err
        - stderr
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
    metrics:
      receivers: [otlp]
      exporters: [file]
    logs:
      receivers: [otlp]
      exporters: [file]
```

**Environment**
OS: Windows Server 2022 Datacenter

**Additional context**
Could not find similar issue in a list of already reported issues
