### ISSUE TITLE
otlp: balancer_name: round_robin doesn't make it round_robin

### ISSUE THREAD

**Issue by sokoide** [open-telemetry/opentelemetry-collector#9129]
**Describe the bug**
In the following network,

```
OTELCOL --(gRPC)--> foo.com ---> receiver1.com
                            |--> receiver2.com
```

When the OTELCOL sends to foo.com who has 2 DNS A records for reciver1.com and receier2.com, the following configuration doesn't make the export round-robin. It always export to receiver1.com

```yaml
exporters:
  otlp:
    endpoint: "foo.com:4317"
    tls:
      insecure: true
    balancer_name: round_robin
```

**Steps to reproduce**

1. Run OTELCOL with the config above including `balancer_name: round_robin`
2. Run OTLP receivers on receiver1.com and receiver2.com with TLS off (TLS doesn't matter though)
3. Send traces to the OTELCOL over OTLP

**What did you expect to see?**
The first batch of the traces goes to receiver1, second goes to receiver2, the third goes to receiver1... (round_robin)

**What did you see instead?**
All trace buckets go to receiver1.

**What version did you use?**
v0.91.0

**What config did you use?**

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":4317"
exporters:
  otlp:
    endpoint: "foo.com:4317"
    tls:
      insecure: true
    balancer_name: round_robin

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]
```

**Environment**

OS:  Ubuntu 22.04 x64
Compiler: Go 1.21.5

**Additional context**

`balancer_name: round_robin` should be supported according to [the spec](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md#client-configuration)

A question asked as #8000.
