### ISSUE TITLE
[help wanted] pushes metrics to SkyWalking OAP Server failed.

### ISSUE THREAD

**Issue by tanpenggood** [open-telemetry/opentelemetry-collector#9176]
## background

I want used SkyWalking, to monitor infrastructure.

SkyWalking leverages Prometheus node-exporter to collect metrics data from the VMs and leverages OpenTelemetry Collector to transfer the metrics to [OpenTelemetry receiver](https://skywalking.apache.org/docs/main/next/en/setup/backend/opentelemetry-receiver) and into the [Meter System](https://skywalking.apache.org/docs/main/next/en/concepts-and-designs/meter).

https://skywalking.apache.org/docs/main/next/en/setup/backend/backend-vm-monitoring/

---

According to the steps in the document [https://skywalking.apache.org/blog/2021-02-07-infrastructure-monitoring](https://skywalking.apache.org/blog/2021-02-07-infrastructure-monitoring), 

I need to perform the following operations：

1. Prometheus Node Exporter collects metrics data from the VMs.
2. OpenTelemetry Collector fetches metrics from Node Exporters via Prometheus Receiver, and pushes metrics to SkyWalking OAP Server via the OpenCensus GRPC Exporter.
3. The SkyWalking OAP Server parses the expression with [MAL](https://github.com/apache/skywalking/blob/master/docs/en/concepts-and-designs/mal.md) to filter/calculate/aggregate and store the results. The expression rules are in /config/otel-oc-rules/vm.yaml.
4. We can now see the data on the SkyWalking WebUI dashboard.

I have some error messages in step 2. 

Could you kindly please help me to solve it?

## error logs

```
...
otel-collector         | StartTimestamp: 2023-12-22 05:19:23.526 +0000 UTC
otel-collector         | Timestamp: 2023-12-22 05:20:03.526 +0000 UTC
otel-collector         | Value: 1.000000
otel-collector         | NumberDataPoints #15
otel-collector         | Data point attributes:
otel-collector         |      -> device: Str(vethd450de0)
otel-collector         | StartTimestamp: 2023-12-22 05:19:23.526 +0000 UTC
otel-collector         | Timestamp: 2023-12-22 05:20:03.526 +0000 UTC
otel-collector         | Value: 1.000000
otel-collector         | NumberDataPoints #16
otel-collector         | Data point attributes:
otel-collector         |      -> device: Str(vethe12b069)
otel-collector         | StartTimestamp: 2023-12-22 05:19:23.526 +0000 UTC
otel-collector         | Timestamp: 2023-12-22 05:20:03.526 +0000 UTC
otel-collector         | Value: 1.000000
otel-collector         |        {"kind": "exporter", "data_type": "metrics", "name": "logging"}
otel-collector         | 2023-12-22T13:20:05.958+0800   error   exporterhelper/retry_sender.go:126      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = Method not found: opentelemetry.proto.collector.metrics.v1.MetricsService/Export", "dropped_items": 485}
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/retry_sender.go:126
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/metrics.go:170
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).consume
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/queue_sender.go:115
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue[...]).Consume
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/bounded_memory_queue.go:55
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*QueueConsumers[...]).Start.func1
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/consumers.go:43
otel-collector         | 2023-12-22T13:20:06.530+0800   error   exporterhelper/retry_sender.go:126      Exporting failed. The error is not retryable. Dropping data.    {"kind": "exporter", "data_type": "metrics", "name": "otlp", "error": "Permanent error: rpc error: code = Unimplemented desc = Method not found: opentelemetry.proto.collector.metrics.v1.MetricsService/Export", "dropped_items": 485}
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/retry_sender.go:126
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper.(*metricsSenderWithObservability).send
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/metrics.go:170
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper.(*queueSender).consume
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/queue_sender.go:115
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*boundedMemoryQueue[...]).Consume
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/bounded_memory_queue.go:55
otel-collector         | go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*QueueConsumers[...]).Start.func1
otel-collector         |        go.opentelemetry.io/collector/exporter@v0.91.0/exporterhelper/internal/consumers.go:43
skywalking-oap-server  | Dec 22, 2023 1:20:07 PM io.grpc.internal.SerializingExecutor run
skywalking-oap-server  | SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@3941dd04
skywalking-oap-server  | java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed
skywalking-oap-server  |        at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
skywalking-oap-server  |        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:374)
skywalking-oap-server  |        at org.apache.skywalking.oap.server.receiver.event.grpc.EventGrpcServiceHandler$1.onCompleted(EventGrpcServiceHandler.java:101)
skywalking-oap-server  |        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onHalfClose(ServerCalls.java:273)
skywalking-oap-server  |        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:340)
skywalking-oap-server  |        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866)
skywalking-oap-server  |        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
skywalking-oap-server  |        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
skywalking-oap-server  |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
skywalking-oap-server  |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
skywalking-oap-server  |        at java.base/java.lang.Thread.run(Unknown Source)
...
```

## docker-compose.yml

```yaml
version: '3.3'
services:
  skywalking-oap-server:
    image: apache/skywalking-oap-server:9.1.0
    container_name: skywalking-oap-server
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      SW_STORAGE: h2
      TZ: Asia/Shanghai
      JAVA_OPTS: '-Xms1024m -Xmx1024m -Xmn512m'
      SW_OTEL_RECEIVER: default
      SW_OTEL_RECEIVER_ENABLED_OC_RULES: vm
      SW_OTEL_RECEIVER_ENABLED_OTEL_METRICS_RULES: vm
    networks: 
      - sw
    volumes:
      - ./oap/conf/alarm-settings.yml:/skywalking/config/alarm-settings.yml

  skywalking-ui:
    image: apache/skywalking-ui:9.1.0
    container_name: skywalking-ui
    networks:
      - sw
    depends_on:
      - skywalking-oap-server
    links:
      - skywalking-oap-server
    restart: always
    ports:
      - 8080:8080
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap-server:12800
      TZ: Asia/Shanghai
      JAVA_OPTS: '-Xms256m -Xmx256m'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      TZ: Asia/Shanghai
    networks:
      - sw
    expose:
      - 55678
    depends_on:
      - skywalking-oap-server
    links:
      - skywalking-oap-server

networks:
  sw:
```

## otel-collector-config.yaml

> The document I am referring to https://github.com/apache/skywalking-showcase/blob/main/deploy/platform/docker/config/otel-collector-config.yaml

```yaml
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'vm-monitoring'
          scrape_interval: 10s
          static_configs:
            - targets: [ '192.168.31.21:9100', '192.168.31.20:9100', '192.168.31.22:9100' ]

processors:
  batch:

exporters:
  otlp:
    endpoint: "skywalking-oap-server:11800"
    tls:
      insecure: true
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [ prometheus ]
      processors: [ batch ]
      exporters: [ otlp,logging ]
```

## oap/conf/alarm-settings.yml

```yaml
# Sample alarm rules.
rules:
  # Rule unique name, must be ended with `_rule`.
  service_resp_time_rule:
    metrics-name: service_resp_time
    op: ">"
    threshold: 1000
    period: 10
    count: 3
    silence-period: 5
    message: Response time of service {name} is more than 1000ms in 3 minutes of last 10 minutes.
  service_sla_rule:
    # Metrics value need to be long, double or int
    metrics-name: service_sla
    op: "<"
    threshold: 8000
    # The length of time to evaluate the metrics
    period: 10
    # How many times after the metrics match the condition, will trigger alarm
    count: 2
    # How many times of checks, the alarm keeps silence after alarm triggered, default as same as period.
    silence-period: 3
    message: Successful rate of service {name} is lower than 80% in 2 minutes of last 10 minutes
  service_resp_time_percentile_rule:
    # Metrics value need to be long, double or int
    metrics-name: service_percentile
    op: ">"
    threshold: 1000,1000,1000,1000,1000
    period: 10
    count: 3
    silence-period: 5
    message: Percentile response time of service {name} alarm in 3 minutes of last 10 minutes, due to more than one condition of p50 > 1000, p75 > 1000, p90 > 1000, p95 > 1000, p99 > 1000
  service_instance_resp_time_rule:
    metrics-name: service_instance_resp_time
    op: ">"
    threshold: 1000
    period: 10
    count: 2
    silence-period: 5
    message: Response time of service instance {name} is more than 1000ms in 2 minutes of last 10 minutes
  database_access_resp_time_rule:
    metrics-name: database_access_resp_time
    threshold: 1000
    op: ">"
    period: 10
    count: 2
    message: Response time of database access {name} is more than 1000ms in 2 minutes of last 10 minutes
  endpoint_relation_resp_time_rule:
    metrics-name: endpoint_relation_resp_time
    threshold: 1000
    op: ">"
    period: 10
    count: 2
    message: Response time of endpoint relation {name} is more than 1000ms in 2 minutes of last 10 minutes
#  Active endpoint related metrics alarm will cost more memory than service and service instance metrics alarm.
#  Because the number of endpoint is much more than service and instance.
#
#  endpoint_resp_time_rule:
#    metrics-name: endpoint_resp_time
#    op: ">"
#    threshold: 1000
#    period: 10
#    count: 2
#    silence-period: 5
#    message: Response time of endpoint {name} is more than 1000ms in 2 minutes of last 10 minutes

webhooks:
#  - http://127.0.0.1/notify/
#  - http://127.0.0.1/go-wechat/
```
