### ISSUE TITLE
Incorrect warn message when using service::telemetry::metrics::readers config

### ISSUE THREAD

**Issue by petertakacs** [open-telemetry/opentelemetry-collector#9285]
**Describe the bug**
When config `service::telemetry::metrics::readers` contains a prometheus exporter, the collector incorrectly logs a warn message to the console that `address` field is deprecated:

`2024-01-15T13:10:16.667+0100    warn    service@v0.92.0/telemetry.go:124        service::telemetry::metrics::address is being deprecated in favor of service::telemetry::metrics::readers`

**Steps to reproduce**
Run the collector with the following config:

```yaml
service:
  telemetry:
    metrics:
      level: normal
      #address: ""
      readers:
        - pull:
            exporter:
              prometheus:
                host: localhost
                port: 9999
```

**What did you expect to see?**
If I specify the `metrics::readers` fields with `--feature-gates=telemetry.useOtelForInternalMetrics` `--feature-gates=telemetry.useOtelWithSDKConfigurationForInternalTelemetry` flags, I should not see the warning

**What version did you use?**
v0.92 (with ocb)

**Environment**
Go:
go version go1.21.4 darwin/arm64

OS:
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a

**Additional context**
If the address is specified as an empty string I don't get the warning (as expected)
