### ISSUE TITLE
deploymentUpdateStrategy: field not declared in schema when using image

### ISSUE THREAD

**Issue by zs-ko** [open-telemetry/opentelemetry-collector#9313]
**Describe the bug**
when we define an image value for opentelemetrycollector the api throws the following error 
`.spec.deploymentUpdateStrategy: field not declared in schema`

**Steps to reproduce**

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: test
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.92.0
  config: ""
```

**What did you expect to see?**
no error from api

**What did you see instead?**

spec.deploymentUpdateStrategy: field not declared in schema

**What version did you use?**

0.92

**What config did you use?**

**Environment**

v1.27.7+rke2r2

**Additional context**
