### ISSUE TITLE
[exporter/debug] Make output configurable

### ISSUE THREAD

**Issue by astencel-sumo** [open-telemetry/opentelemetry-collector#9372]
It would be awesome if I could (...) choose which metadata I want to see.
Eg. for logs sometimes I might be interested only in logs, sometimes in logs and some metadata and sometimes in metadata only.

_Originally posted by @perk-sumo in https://github.com/open-telemetry/opentelemetry-collector/issues/7806#issuecomment-1571929331_

Things I believe it's worth to configure:

- `output.attributes` whether or not to include records' attributes. They're probably essential for metrics, but for logs - it depends on the nature of the logs. For some users, attributes may be essential; for others, they only obscure the output.
- Whether or not the exporter uses the collector's logger to output data

Other possible configuration options:

- `output.trace_id`, `output.span_id` whether or not to include trace ID, span ID - they are probably essential for traces, but not necessarily for logs.
- `output.timestamp` whether or not to include timestamp - again some users might find them useful, others might want to remove them for clarity

Other configurability option suggestions are welcome.

**Comment by Sanket-0510** [comment]
Hey this is sanket, I would like to express my views over this issue and this CNCF project. 

1. The Issue is the follow up for the issue #7806. Which was regarding the behavior of basic, normal and detailed verbosity levels for the telemetry data such as matrics and logs. The `basic` and the `normal` verbosity level gives same output but the detailed one gives too much verbose output we need too figure out a middle ground for this. 
One way as per proposed by @astencel-sumo  is to make normal level to output in the single like that is to suppress the detailed output. The format for the same is still in the discussion from the design perspective. 

2. while addressing the issue of level and verbosity @perher came with a feature from the user perspective such that it shall be upto user to see what kindda output the person wants to see in form the metrics or the logs data. whether someone wants to see only logs or only metadata, the person shall be able to describe template for the same and shall get the output in that format only. This definitely solves big headache from the user side.


As per suggested by @astencel-sumo  yes we can configure the output for the 
```
1. output.attributes
2. output.trace_id
3. output.span_id
4. output.timestamp
```
we can also configure for the

```
5. output.ip_address
6. output.duration
7. output.message
```


#### This is the what I have understood so far regarding this CNCF mentorship project and the I am looking forward to propose well optimised proposal for the same.

**Comment by ChristianCiach** [comment]
I don't know if I should create a separate issue, but it seems related. I try to debug my **metrics** pipeline and I am surprised that the debug-exporter doesn't log resource-attributes, *at all*, even at `detailed` verbosity. It does so for logs, but not for metrics.

Related config:

```yaml
    receivers:
      receiver_creator/metrics:
        watch_observers: [k8s_observer]
        discovery:
          enabled: true
          default_annotations:
            'io.opentelemetry.discovery.metrics/scraper': 'prometheus_simple'
        receivers:
          prometheus_simple:
            rule: type == "pod" && annotations["prometheus.io/scrape"] == "true"
            config:
              metrics_path: '`annotations["prometheus.io/path"] ?? "/metrics"`'
              endpoint: '`endpoint`:`annotations["prometheus.io/port"] ?? "9090"`'

    exporters:
      debug:
        verbosity: detailed
        use_internal_logger: false

    service:
      extensions:
        - k8s_observer

      pipelines:
        metrics/prometheus:
          receivers: [receiver_creator/metrics]
          processors: []
          exporters:
            - debug
```

My actual pipeline adds a bunch of custom resource attributes, but this example should suffice because the receiver_creator + k8s_observer already adds some `k8s.*` resource attributes.
