### ISSUE TITLE
Sending metrics via HTTP using OTLP JSON not working as expected

### ISSUE THREAD

**Issue by mihneavelinOT** [open-telemetry/opentelemetry-collector#9457]
**Describe the bug**
Assume that I already have the metrics values and timestamps and I want to add them manually in the collector. I did not find any example for my use case, but from what I discovered from the documentation it should be possible to do so. I have followed this [example](https://github.com/open-telemetry/opentelemetry-proto/blob/main/examples/metrics.json) and I reached this format until now:
```json
{
  "resourceMetrics": [
    {
      "resource": {
        "attributes": [
          {
            "key": "service.name",
            "value": {
              "stringValue": "my.service"
            }
          }
        ]
      },
      "scopeMetrics": [
        {
          "scope": {
            "name": "my.library",
            "version": "1.0.0",
            "attributes": [
              {
                "key": "my.scope.attribute",
                "value": {
                  "stringValue": "some scope attribute"
                }
              }
            ]
          },
          "metrics": [
            {
              "name": "my.gauge",
              "unit": "1",
              "description": "I'm a Gauge",
              "gauge": {
                "dataPoints": [
                  {
                    "asDouble": 321,
                    "timeUnixNano": "1707121647000000000",
                    "attributes": [
                      {
                        "key": "my.gauge.attr",
                        "value": {
                          "stringValue": "some value"
                        }
                      }
                    ]
                  },
                  {
                    "asDouble": 42,
                    "timeUnixNano": "1707121647000000000",
                    "attributes": [
                      {
                        "key": "my.gauge.attr",
                        "value": {
                          "stringValue": "some value"
                        }
                      }
                    ]
                  }
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}
```
But when sending this via a POST request(content type set to application/json), it returns ```{"partialSuccess":{}}``` and only the last value is visible in the Prometheus graph, at the time of the request was sent, not at the time specified in ```timeUnixNano```.

I want to send multiple points with different timestamps at once and see all the values with the correct timestamps.

**Steps to reproduce**
Send a POST request with some metrics to the ```/v1/metrics``` endpoint of the collector.

**What did you expect to see?**
The correct specified values and timestamps in the graph.

**What did you see instead?**
Only the last value, at the time of the request was sent, not at the time specified in "timeUnixNano"

**What config did you use?**
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
  telemetry:
    logs:
      level: "DEBUG"
      development: true
      encoding: "json"
```

**Additional context**
I opened another identical [issue](https://github.com/open-telemetry/opentelemetry-collector/issues/7433) in March 2023, but the feature was postponed and I did not get back to it. Unfortunately, using strings for ```timeUnixNano``` did not fix it.
