### ISSUE TITLE
Zipkin export fails on span without timestamp when used with queued_retry

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [open-telemetry/opentelemetry-collector#954]
Occasionally zipkin spans won't have a timestamp. This works fine normally, but when the `queued_retry` processor is used the spans fail to serialize. 

```
json: error calling MarshalJSON for type *model.SpanModel: valid annotation timestamp required
```

This also results in an infinite retrying for these spans, which seems incorrect. They should permanently fail and not be retried. 

```
otel-collector_1     | {"level":"info","ts":1589295406.122493,"caller":"queuedprocessor/queued_processor.go:214","msg":"Resume processing","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry"}
otel-collector_1     | {"level":"warn","ts":1589295406.1234396,"caller":"queuedprocessor/queued_processor.go:190","msg":"Sender failed","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","error":"json: error calling MarshalJSON for type *model.SpanModel: valid annotation timestamp required"}
otel-collector_1     | {"level":"warn","ts":1589295406.1236405,"caller":"queuedprocessor/queued_processor.go:202","msg":"Failed to process batch, re-enqueued","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","batch-size":1}
otel-collector_1     | {"level":"warn","ts":1589295406.1237097,"caller":"queuedprocessor/queued_processor.go:208","msg":"Backing off before next attempt","component_kind":"processor","component_type":"queued_retry","component_name":"queued_retry","backoff_delay":5}
```

docker-compose.yml
```
version: "2"
services:
  otel-collector:
    image: otelcontribcol:latest
    command: ["--config=/etc/otel-collector-config.yaml", "--mem-ballast-size-mib", "4000"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8080:9411" # zipkin
    depends_on:
      - zipkin-all-in-one

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

```

otel-collector-config.yaml
```
receivers:
  zipkin:
    endpoint: :9411

exporters:
  zipkin:
    url: "http://zipkin-all-in-one:9411/api/v2/spans"

processors:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [zipkin]
      processors: [queued_retry]
      exporters: [zipkin]

```

Sample Data
```
POST http://localhost:8080/api/v2/spans

[
    {
        "traceId": "404059d49fac24fc",
        "id": "404059d49fac24ff",
        "annotations": [
            {
                "timestamp": 1589292979495000,
                "value": "zipkin-js.flush"
            }
        ],
        "tags": {
            "response_size_bytes": "9622"
        }
    }
]
```
