### ISSUE TITLE
Applying memory_limiter extension

### ISSUE THREAD

**Issue by dmitryax** [open-telemetry/opentelemetry-collector#9591]
### Problem

As part of https://github.com/open-telemetry/opentelemetry-collector/issues/8632, we want receivers to be able to reject incoming requests if the collector is running out of memory limits instead of accepting the data transforming to OTLP and get it rejected by the `memory_limiter` processor. Scraping receivers would skip the scraping in that situation.

We introduced a memory_limiter extension in https://github.com/open-telemetry/opentelemetry-collector/pull/8964, but is not been applied yet.

https://github.com/open-telemetry/opentelemetry-collector/pull/9397 proposes a way to configure a `memory_limiter` extension explicitly by receivers using httpconfig. Following this approach would complicate the user configuration interface as they would have to explicitly connect every receiver with a memoery_limiter extension to ensure that it's applied to all of them.

### Proposed solution

We can introduce an option to configure the `memory_limiter` extension in a way that it's applied to every receiver. Particular receivers can override the default memory limiter and connect to a different one.

Configuration example:

```yaml
extensions:
  memory_limiter:
    limit_mib: 800
    apply_to_all_receivers: true
  memory_limiter/internal_metrics:
    limit_mib: 1000

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  prometheus:
    memory_limiter: memory_limiter/internal_metrics
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ["localhost:8888"]

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  extensions: [memory_limiter, memory_limiter/internal_metrics]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [debug]
```

In this configuration, the default `memory_limiter` extension is implicitly applied to `otlp` receiver, and the additional `memory_limiter/internal_metrics` extension is applied to the prometheus receiver.

The user cannot define more than one `memory_limiter` extension with `apply_to_all_receivers: true`; the config validation will fail.

If `memory_limiter` extension with `apply_to_all_receivers: true` is defined, all the receivers used in the pipelines must support the `memory_limiter` extension. Otherwise, the collector won't start.

Proof of concept: https://github.com/open-telemetry/opentelemetry-collector/pull/9590
