### ISSUE TITLE
OTELCollector continues export data although service is down

### ISSUE THREAD

**Issue by StarpTech** [open-telemetry/opentelemetry-collector#9598]
**Describe the bug**

Hi, we've experienced weird behavior with the OTEL collector. We have a single application that reports a asynchronous `runtime.uptime` counter with cumulative temporality. Our dashboard shows the most recent (last one minute) applications that send this metric. For sure, only a single application is running, but we see two. After some investigation, we found out that the OTEL collector still sends data (based on the export interval), which makes that specific instance look like it is up. It feels like that a new metric stream continues the old one. We can eliminate a miss-configuration on the application side because **after a restart of the collectors, the export stopped and the application dissapeared from our dashboard**. Additionally, both metric streams have unique resource attributes. We can't reproduce it all the time.

**What version did you use?**
- OTELCollector: **0.93.0**
- Instrumentation client: v1.23.1 https://github.com/open-telemetry/opentelemetry-go-contrib
- Exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/clickhouseexporter

**What config did you use?**
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
        auth:
          authenticator: jwt
      http:
        endpoint: '0.0.0.0:4318'
        auth:
          authenticator: jwt

processors:
  attributes/from_auth_context:
    actions:
      - key: wg.organization.id
        from_context: auth.organization_id
        action: insert
      - key: wg.federated_graph.id
        from_context: auth.federated_graph_id
        action: insert
  batch:
    send_batch_size: 10000
    timeout: 5s
  memory_limiter:
    # percentage of memory only supported on linux
    limit_percentage: 75
    spike_limit_percentage: 25
    check_interval: 1s

exporters:
  clickhouse:
    endpoint: ${CLICKHOUSE_ENDPOINT}
    timeout: 10s
    database: cosmo
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    ttl_days: 30
    sending_queue:
      queue_size: 5000
      storage: file_storage/clickhouse
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

extensions:
  # When persistent queue is enabled, the batches are being buffered using the provided storage extension - filestorage is a popular and safe choice.
  # If the collector instance is killed while having some items in the persistent queue, on restart the items will be picked and the exporting is continued.
  file_storage/clickhouse:
    directory: /var/lib/otelcol/file_storage/clickhouse
  health_check:
    path: /health
    endpoint: 0.0.0.0:13133
  jwt:
    secret: ${OTEL_INGEST_JWT_SECRET}

service:
  extensions: [health_check, jwt, file_storage/clickhouse]
  pipelines:
    metrics:
      receivers: [otlp]
      # Order is important here. Otherwise, the attributes processor will not be able to read the attributes from the auth context.
      processors: [attributes/from_auth_context, memory_limiter, batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      # Order is important here. Otherwise, the attributes processor will not be able to read the attributes from the auth context.
      processors: [attributes/from_auth_context, memory_limiter, batch]
      exporters: [clickhouse]
```

**Environment**
OS: PopOS
Go: 1.21.1
