### ISSUE TITLE
Pipeline unit test facility

### ISSUE THREAD

**Issue by jmcarp** [open-telemetry/opentelemetry-collector#9709]
**Is your feature request related to a problem? Please describe.**

As far as I can tell, the only way to verify the behavior of an otelcol pipeline is to run the collector, wait for data to pass through the pipeline, and manually verify that telemetry is showing up in the export destinations. This isn't ideal for more complicated pipelines, since we effectively have to manually test every output on every change.

**Describe the solution you'd like**

It would be great to see some kind of unit test functionality that exercises some or all of an otelcol pipeline using synthetic data and making assertions about data that we expect to receive at different points in the pipeline. Other telemetry agents have this capacity. For example, vector has a [unit test feature](https://vector.dev/docs/reference/configuration/unit-tests/) that allows users to make assertions about individual transforms or pipelines, and fluent-bit has an "expect" filter that's meant for [unit-testing pipelines](https://docs.fluentbit.io/manual/local-testing/validating-your-data-and-structure) as well.

Maybe a mock receiver that sends synthetic data and a mock exporter that checks assertions on the data it receives would work here. Do those exist already? I couldn't find them.

**Describe alternatives you've considered**

It's possible to test otelcol pipelines manually, which works, but is slow and fallible. Users could also write end-to-end tests of their system, making assertions that logs arrive in a test environment. This is probably a good idea, but also high-effort; it would still be useful to have some facility for quick pipeline unit tests.

**Comment by TylerHelmuth** [comment]
@jmcarp are you asking for this feature as a user of the collector binary or as a user of the collector libraries? Does [testbed](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/testbed) fit your needs at all?

**Comment by jmcarp** [comment]
@TylerHelmuth the former—I want to write a collector config file and make assertions about its behavior, either with synthetic or real inputs. Is the testbed meant for this use case? From the docs, it seems more focused on developing the collector itself, but maybe I can repurpose it for my use case. Can it load a collector config file, receive data, and make assertions about the outputs of a pipeline?

**Comment by kaarolch** [comment]
@TylerHelmuth 

> user of the collector binary

Collector pipelines could be quite complex. Sometimes when I extend pipeline with a new processors I would like to add config unit tests that could be triggered during config modification as one of PR requirements.  
Like in [Vector.dev](https://vector.dev/docs/reference/configuration/unit-tests/) you can add extra unit test: 

```
- name: metric_processor_name_length
    inputs:
      - insert_at: metrics_remap_naming_standard
        type: metric
        metric:
          name: "ThisIsAVeryLongNameToSeeIfVectorWillCorrectlySendItToTheBlackholeAsItShouldWehaveToExceed200CharactersForThisLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName"
          namespace: "testing"
          kind: "absolute"
          counter:
             value: 1
          tags:
            metrics_processor: "true"
    outputs:
      - extract_from: metrics_route_removal.blackhole_metrics
        conditions:
          - type: vrl
            source: |
              assert!(.name == "ThisIsAVeryLongNameToSeeIfVectorWillCorrectlySendItToTheBlackholeAsItShouldWehaveToExceed200CharactersForThisLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongName")
              assert!(.tags.blackhole == "true")
```
It would be very useful because instead of doing full e2e tests I can choose part of my pipeline like `metricstransform` and check if regex transform there works as expected.
