### ISSUE TITLE
Support for logfmt in collector logs

### ISSUE THREAD

**Issue by Amoolaa** [open-telemetry/opentelemetry-collector#9728]
At the moment we have console and JSON formats for the logs emitted by the collector itself. JSON is easily parsed but not readable enough, and console is readable but not as easily parsed and/or standard as logfmt. 

**Describe the solution you'd like**
Adding logfmt as an option for logging. 

```
service:
  telemetry:
    logs:
      encoding: logfmt
```
