### ISSUE TITLE
Builder hangs on an EC2 instance with Linux AMD64 without completing

### ISSUE THREAD

**Issue by danielfromCL** [open-telemetry/opentelemetry-collector#9754]
**Describe the bug**

When running a EC2 instance on AWS with Linux AMD64, and trying to exec the builder with a configuration, the builder hangs after the compiling step, even though on mac ARM64 the same steps work.

**Steps to reproduce**

1. Instantiate an EC2 on AWS with Linux amd64, then enter said instance.
2. Install go with the following commands:
```
wget https://go.dev/dl/go1.22.1.linux-amd64.tar.gz
sudo tar -C /usr/bin -xzf go1.22.1.linux-amd64.tar.gz
export PATH=$PATH:/usr/bin/go/bin
```
3. Check that Go was correctly installed with `go version`.
4. Get the builder as described on the docs:
```
curl --proto '=https' --tlsv1.2 -fL -o ocb \
https://github.com/open-telemetry/opentelemetry-collector/releases/download/cmd%2Fbuilder%2Fv0.96.0/ocb_0.96.0_linux_amd64
chmod +x ocb
```
5. Move the ocb binary to a folder inside home, in this case `~/otelcol/ `
6. Give said folder all permissions with `chmod -R a+rwx otelcol`.
7. Create the builder-config.yaml inside this `otelcol` folder, which is this:
```
dist:
  name: otelcol
  description: Custom OpenTelemetry Collector
  output_path: ./
  otelcol_version: 0.96.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.96.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.96.0 
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.96.0
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/attributesprocessor v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/redactionprocessor v0.96.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.96.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.96.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.96.0
```
8. Execute the builder as described on the docs, with: `./ocb --config builder-config.yaml` inside the `otelcol` folder.

**What did you expect to see?**

The building process to be completed, with all files and the binary for the collector created, as described in the [docs](https://opentelemetry.io/docs/collector/custom-collector/#step-3---generating-the-code-and-building-your-collectors-distribution).
When executing the same code with the mac amr64 on my local machine, it works as expected.
**What did you see instead?**

The builder hangs at this step:
```
2024-03-13T20:59:28.376Z	INFO	internal/command.go:123	OpenTelemetry Collector Builder	{"version": "0.96.0", "date": "2024-03-04T14:06:34Z"}
2024-03-13T20:59:28.384Z	INFO	internal/command.go:159	Using config file	{"path": "builder-config.yaml"}
2024-03-13T20:59:28.384Z	INFO	builder/config.go:109	Using go	{"go-executable": "/usr/bin/go/bin/go"}
2024-03-13T20:59:28.386Z	INFO	builder/main.go:91	Sources created	{"path": "./"}
2024-03-13T20:59:28.386Z	INFO	builder/main.go:25	Running go subcommand.	{"arguments": ["get", "cloud.google.com/go"]}
2024-03-13T20:59:29.019Z	INFO	builder/main.go:25	Running go subcommand.	{"arguments": ["mod", "tidy", "-compat=1.21"]}
2024-03-13T20:59:34.477Z	INFO	builder/main.go:142	Getting go modules
2024-03-13T20:59:34.477Z	INFO	builder/main.go:25	Running go subcommand.	{"arguments": ["mod", "download"]}
2024-03-13T20:59:34.949Z	INFO	builder/main.go:102	Compiling
2024-03-13T20:59:34.949Z	INFO	builder/main.go:25	Running go subcommand.	{"arguments": ["build", "-trimpath", "-o", "otelcol", "-ldflags=-s -w"]}

```
**What version did you use?**

v0.96.0 of the builder, for linux amd64.
**What config did you use?**

builder-config.yaml shown above.
**Environment**

Linux x86_64, go version go1.22.1 linux/amd64
**Additional context**

When following the same steps on my local machine (mac arm64), the builder works.
