### ISSUE TITLE
Exporting logs

### ISSUE THREAD

**Issue by ba1ajinaidu** [open-telemetry/opentelemetry-collector#9776]
**Describe the bug**
I'm trying to export the host level logs from a kubernetes node to quickwit using otel-collector, using filelog receiver to read `/var/log/messages` file and exporting it. But the logs exporting fails with below error logs

```
2024-03-15T17:10:37.980Z	error	exporterhelper/queue_sender.go:97	Exporting failed. Dropping data.	{"kind": "exporter", "data_type": "logs", "name": "otlp", "error": "not retryable error: Permanent error: rpc error: code = Internal desc = ", "dropped_items": 2}
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.96.0/exporterhelper/queue_sender.go:97
go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.96.0/internal/queue/bounded_memory_queue.go:57
go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.96.0/internal/queue/consumers.go:43
```

**Steps to reproduce**
install otel-collector with the below give helm-values and install quickwit with default helm values

**What did you expect to see?**
Logs should be exported to quickwit

**What did you see instead?**

logs are not being exported and are dropped

**What version did you use?**
`0.96.0`

**What config did you use?**
used helm chart to install collector

helm-values.yml
```
mode: daemonset
presets:
  logsCollection:
    enabled: true
  kubernetesEvents:
    enabled: true

extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
extraVolumeMounts:
  - name: varlog
    readOnly: true
    mountPath: /var/log
initContainers:
  - name: init-fs
    image: busybox:latest
    command:
      - sh
      - "-c"
      - "chown -R 10001: /var/log"
    volumeMounts:
      - name: varlog
        mountPath: /var/log
config:
  receivers:
    filelog/host:
      include:
        - /var/log/messages
  exporters:
    otlp:
      endpoint: quickwit-indexer.quickwit.svc.cluster.local:7281
      tls:
        insecure: true
  service:
    pipelines:
      logs/system:
        receivers: [filelog/host]
        processors: [batch]
        exporters: [otlp]
```

**Environment**

**Additional context**
