### ISSUE TITLE
Components subcommand no longer outputs component names

### ISSUE THREAD

**Issue by FISHMANPET** [open-telemetry/opentelemetry-collector#9855]
**Describe the bug**
The output of the `components` subcommand no longer contain the names of the component, merely `{}`

**Steps to reproduce**
1. Download the latest collector or build your own.
2. Run `collector components`

**What did you expect to see?**
I expected the output to include the names of components, like this (from the 0.96.0 release)
```
    - name: signalfx
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
```
**What did you see instead?**
```
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
```

**What version did you use?**
v0.97.0

**What config did you use?**
N/A

**Environment**
MacOS 13.6.6
For the compiled version, built using ocb 0.97.0, running go 1.22.1

**Additional context**
I'm wondering if this is related to the changes described in #9208 ?

**Comment by TylerHelmuth** [comment]
Tested this with `make otelcontribcol` in Contrib and was able to reproduce:

```
buildinfo:
    command: otelcontribcol
    description: Local OpenTelemetry Collector Contrib binary, testing only.
    version: 0.97.0-dev
receivers:
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Development
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Beta
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Beta
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Stable
        traces: Stable
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Development
        metrics: Undefined
        traces: Development
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Alpha
        traces: Undefined
processors:
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Development
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
exporters:
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Deprecated
    - name: {}
      stability:
        logs: Beta
        metrics: Development
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Alpha
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Development
    - name: {}
      stability:
        logs: Alpha
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Alpha
    - name: {}
      stability:
        logs: Unmaintained
        metrics: Unmaintained
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Development
        metrics: Development
        traces: Development
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Alpha
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Development
        metrics: Undefined
        traces: Alpha
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Stable
        traces: Stable
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Beta
        traces: Undefined
    - name: {}
      stability:
        logs: Alpha
        metrics: Undefined
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Stable
        traces: Stable
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Alpha
        metrics: Alpha
        traces: Alpha
    - name: {}
      stability:
        logs: Undefined
        metrics: Deprecated
        traces: Undefined
    - name: {}
      stability:
        logs: Beta
        metrics: Beta
        traces: Beta
    - name: {}
      stability:
        logs: Undefined
        metrics: Undefined
        traces: Beta
connectors:
    - name: {}
      stability:
        logs-to-logs: Alpha
        logs-to-metrics: Undefined
        logs-to-traces: Undefined
        metrics-to-logs: Undefined
        metrics-to-metrics: Alpha
        metrics-to-traces: Undefined
        traces-to-logs: Undefined
        traces-to-metrics: Undefined
        traces-to-traces: Alpha
    - name: {}
      stability:
        logs-to-logs: Undefined
        logs-to-metrics: Undefined
        logs-to-traces: Undefined
        metrics-to-logs: Undefined
        metrics-to-metrics: Undefined
        metrics-to-traces: Undefined
        traces-to-logs: Undefined
        traces-to-metrics: Alpha
        traces-to-traces: Undefined
    - name: {}
      stability:
        logs-to-logs: Undefined
        logs-to-metrics: Undefined
        logs-to-traces: Undefined
        metrics-to-logs: Undefined
        metrics-to-metrics: Undefined
        metrics-to-traces: Undefined
        traces-to-logs: Undefined
        traces-to-metrics: Alpha
        traces-to-traces: Undefined
    - name: {}
      stability:
        logs-to-logs: Beta
        logs-to-metrics: Undefined
        logs-to-traces: Undefined
        metrics-to-logs: Undefined
        metrics-to-metrics: Beta
        metrics-to-traces: Undefined
        traces-to-logs: Undefined
        traces-to-metrics: Undefined
        traces-to-traces: Beta
    - name: {}
      stability:
        logs-to-logs: Undefined
        logs-to-metrics: Development
        logs-to-traces: Undefined
        metrics-to-logs: Undefined
        metrics-to-metrics: Development
        metrics-to-traces: Undefined
        traces-to-logs: Undefined
        traces-to-metrics: Development
        traces-to-traces: Undefined
    - name: {}
      stability:
        logs-to-logs: Undefined
        logs-to-metrics: Undefined
        logs-to-traces: Undefined
        metrics-to-logs: Undefined
        metrics-to-metrics: Undefined
        metrics-to-traces: Undefined
        traces-to-logs: Undefined
        traces-to-metrics: Beta
        traces-to-traces: Beta
    - name: {}
      stability:
        logs-to-logs: Undefined
        logs-to-metrics: Undefined
        logs-to-traces: Undefined
        metrics-to-logs: Undefined
        metrics-to-metrics: Undefined
        metrics-to-traces: Undefined
        traces-to-logs: Development
        traces-to-metrics: Development
        traces-to-traces: Undefined
extensions:
    - name: {}
      stability:
        extension: Alpha
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Development
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Development
    - name: {}
      stability:
        extension: Alpha
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Development
    - name: {}
      stability:
        extension: Alpha
    - name: {}
      stability:
        extension: Alpha
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Alpha
    - name: {}
      stability:
        extension: Development
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Deprecated
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Development
    - name: {}
      stability:
        extension: Alpha
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Development
    - name: {}
      stability:
        extension: Development
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
    - name: {}
      stability:
        extension: Beta
```
