### ISSUE TITLE
Otel-collector high memory usage / ways to prevent from reaching memory limit

### ISSUE THREAD

**Issue by sati-max** [open-telemetry/opentelemetry-collector#9882]
Hi

We are using open-telemetry collector as a collector + parser in kubernetes cluster (otel-collector installed via helm chart, image used otel/opentelemetry-collector-contrib:0.97.0). It works great for our needs, all docs for config on parser etc. were great.

But we stumbled upon an issue that when we send too much data in very short duration our collector hits the soft memory limit
memorylimiter/memorylimiter.go:222              Memory usage is above soft limit. Forcing a GC.           {"kind": "processor", "name": "memory_limiter", "pipeline": "metrics", "cur_mem_mib": 9018}
and crashes (it goes into an process of Oomkilled -> Terminating -> ContenerCreation -> Running) and continues to hit the memory limit until the data flow will stop. Our k8s workers have 16GBs of RAM each, we have 4 workers. 

Currently our flow is about 1 mln logs each 15 minutes or so and overall it's seems ok. But if we send too much at once - we run into problems - and from what we see when we restart fluentd to switch it to our otel-collector it sends all data from last few hours (might be an issue of fluentd). The above error dropped when otel-collector wanted roughly about 28GBs of RAM. We can add more RAM to our workers (even up to 64GBs) but what if even that won't be enough?

How can we prevent this from happening?

I read about File Storage https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/storage/filestorage - I don't quite get if this will help (I've actually found this info in Splunk article), but the option to buffer data on disk instead of RAM might be good as the excessive data isn't regular (we got it for the first time when we forwarded logs from a large number of hosts and fluentd just send everything to our parser) and we shouldn't have storage issues (we can assign like 500GB or even 1TB for this buffer, on fast disks). How could I configure this, to use disk instead of RAM to buffer incoming data?

We didn't try k8s options on AutoScaling or any limits on the Pod - as if I understand correctly: 
first option (AutoScaling) might just run additional pods on other workers and utilize all ram there (pretty much stopping the whole cluster if stuff goes very bad) 
second option (limiting memory) - we don't know how Fluentd might handle that the endpoint won't take more data and we might lose it. 

Thank you for any help or suggestion.

Our overwite.yaml file: (I've omitted sensitive data like IP or what we are parsing)
```yaml
mode: deployment

config:
  exporters:
    otlp:
      endpoint: xxx.xxx.xxx.xxx
      tls:
        insecure: true
  processors:
    batch: {}
    attributes:
{omitted}
      actions:
{omitted}
    transform:
{omitted}
  receivers:
    fluentforward:
      endpoint: ${env:MY_POD_IP}:24224
  service:
    telemetry:
      metrics: {}
    pipelines:
      logs:
        receivers:
          - fluentforward
        processors:
          - batch
          - attributes
          - transform
        exporters:
          - otlp
      metrics:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp

ports:
  otlp-http:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
  metrics:
    enabled: false
  fluentforward:
    enabled: true
    containerPort: 24224
    servicePort: 24224
    hostPort: 24224
    protocol: TCP
    # nodePort: 24224

replicaCount: 1
    # we tried replicaCount: 3, but it didn't really help

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: xxx.xxx.xxx.xxx
  type: LoadBalancer
```

PS I'm not sure if this it the correct repo/place for this question - if not, please direct me where I can ask :)

**Comment by NickLarsenNZ** [comment]
@sati-max are you able to put your confiugration in a yaml code fence?

~~~
```yaml
config:
  exporters:
   otlp:
    endpoint: xxx.xxx.xxx.xxx
...
```
~~~

It will then render with a monospace font, syntax-highlighting, and preserve the indentation, like so:

```yaml
config:
  exporters:
   otlp:
    endpoint: xxx.xxx.xxx.xxx
...
```

**Comment by sati-max** [comment]
We managed to fix this situation by actually setting batch processor, which we skipped before:

```yaml
    batch:
      send_batch_size: 16384
      send_batch_max_size: 16384
      timeout: 1s
```

We also tried different values but seems this setup works the best for us, higher values were dropping data, lower were again utilizing higher amount of RAM)

This doc helped with realizing what we missed in our configuration: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-around-resource-utilization

@NickLarsenNZ  yes sorry, didn't knew about it, I fixed the initial post for easier reading.
