### ISSUE TITLE
Configuration resolver merge bug upon null component map

### ISSUE THREAD

**Issue by SeanPMiller** [open-telemetry/opentelemetry-collector#9931]
**Describe the bug**
Merge of two or more configurations fails when any component map is `null`. Based on my testing, I think there is a bug in the merge logic behind `confmap.Resolver.Resolve()`. The `null` seems to be "infectious" and wipes the map for that component type.

**Steps to reproduce**
1.  [Install OCB to some working directory](https://opentelemetry.io/docs/collector/custom-collector/#step-1---install-the-builder).
1.  Add the configuration file `builder-config.yaml` from **Additional context** to your working directory.
1.  Build an OpenTelemetry Collector binary using OCB with the following command:
    ```
    ./ocb --config builder-config.yaml 
    ```
1.  Add the two configuration files `alpha.yaml` and `beta.yaml` from **Additional context** to your working directory.
1.  Validate with the following command:
    ```
    ./otelcol/otelcol validate --config=file:$(pwd)/alpha.yaml --config=file:$(pwd)/beta.yaml
    ```

**What did you expect to see?**
Success.

**What did you see instead?**
Failure. Specifically,
```
Error: service::pipelines::metrics/beta: references processor "batch/alpha" which is not configured
```

**What version did you use?**
See `builder-config.yaml`.

**What config did you use?**
See `alpha.yaml` and `beta.yaml`.

**Environment**
```shell
$ go version
go version go1.22.0 linux/amd64
$
```

**Additional context**
builder-config.yaml:
```yaml
---
dist:
    name: otelcol
    description: OTel Collector to demonstrate Resolver bug
    output_path: ./otelcol
    otelcol_version: 0.97.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.97.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.97.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.97.0
...
```

alpha.yaml:
```yaml
---
receivers:
    otlp/alpha:
        protocols:
            http:
                endpoint: localhost:4318

processors:
    batch/alpha:

exporters:
    otlphttp/alpha:
        endpoint: foo.bar.qux.com:4321

service:
    pipelines:
        metrics/alpha:
            receivers:
              - otlp/alpha
            exporters:
              - otlphttp/alpha
...
```

beta.yaml:
```yaml
---
receivers:
    otlp/beta:
        protocols:
            grpc:
                endpoint: localhost:4317

processors:

service:
    pipelines:
        metrics/beta:
            receivers:
              - otlp/beta
            processors:
              - batch/alpha
            exporters:
              - otlphttp/alpha
...
```
