### ISSUE TITLE
Prometheus Receiver Scrape fails to scrape endpoint due to "up" metrics

### ISSUE THREAD

**Issue by stoerig** [open-telemetry/opentelemetry-collector#9962]
**Describe the bug**
The prometheus receiver is logging the following when scraping a /metrics endpoint, in this case the eventstore db provided one.

```log
Apr 14 13:42:39 otelcol-contrib[2315264]: 2024-04-14T13:42:39.155+0200        warn        internal/transaction.go:123        Failed to scrape Prometheus endpoint        {"kind": "receiver", "name": "prometheus", "data_type": "metrics", "scrape_timestamp": 1713094949155, "target_labels": "{__name__=\"up\", instance=\"localhost:2113\", job=\"eventstoredb-metrics\"}"}
```

**Steps to reproduce**
Try scraping a default eventstore db instance on the path :2113/metrics

**What did you expect to see?**
No warnings

**What did you see instead?**
Warning logs

**What version did you use?**
otelcol-contrib version 0.97.0

**What config did you use?**
```yaml
  prometheus:
    config:
      scrape_configs:
      - job_name: otel-collector-metrics # does NOT log the warning
        scrape_interval: 10s
        static_configs:
          - targets:
            - localhost:8888
      - job_name: eventstoredb-metrics # DOES warn the log
        scrape_interval: 10s
        static_configs:
          - targets:
            -  localhost:2113

# Then I tried adding the following parameters to the eventstoredb-metrics job, with no luck
# first relable
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: 'up'
              action: drop
# and then http params 
          params:
            match[]:
              - '{__name__!~"up"}'  # Exclude metrics with the name "up"
```

**Environment**
Rhel 8.9

**Additional context**
If there is anything I can configure to mock the up-metric or something like that. Then I willing to do that. I can live without the up-metric or with a faked always-up metric, as long as this warning log stops.
