### ISSUE TITLE
[cmd/builder] ocb gomod version is ignored when using import

### ISSUE THREAD

**Issue by danelson** [open-telemetry/opentelemetry-collector#9988]
**Describe the bug**

When a version is specified in the builder config for `gomod`, it does not seem to be respected by `import`.

Consider a config that looks something like the following:

A possible breaking config

```yaml
dist:
  name: "otelcol-dev"
  description: "Working example"
  otelcol_version: "0.96.0"
exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/myexporter v0.96.0"
    path: "./exporter/myexporter"
extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage v0.96.0"
    import: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage"
```

vs.

A good config

```yaml
dist:
  name: "otelcol-dev"
  description: "Working example"
  otelcol_version: "0.96.0"
exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/myexporter v0.96.0"
    path: "./exporter/myexporter"
extensions:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/extension/storage/filestorage v0.96.0"

```

**Steps to reproduce**

I wasn't sure I could explain this well so I created a reproduction at https://github.com/danelson/ocb_version_issue.
I think this can break anytime a release is made with a breaking change to an API that you consume in a custom component while still referencing that lower version.

**What did you expect to see?**
I expect both configs to act the same (I am not sure the semantics are the same tho).

**What did you see instead?**
Bad config pulls in latest API version and build fails.

**What version did you use?**
v0.96.0
